import { z } from 'zod';
import { database,bucket } from '@/lib/crm-db';
import { member,AccessError,sameOrigin } from '@/lib/crm-auth';
import {fileOnWork,type CustomerFile} from '@/lib/crm-files';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const spaceOf=(value:unknown)=>z.enum(['demo','live']).parse(value);
const fail=(e:unknown)=>{if(e instanceof AccessError)return reply({error:e.message},e.status);if(e instanceof z.ZodError)return reply({error:e.issues.map(i=>i.message).join(' ')},400);console.error('CRM file failed',e);return reply({error:'Filen kunde inte hanteras. Försök igen.'},503)};
export async function GET(req:Request){try{
 const user=await member(req);const u=new URL(req.url),space=spaceOf(u.searchParams.get('space')),id=u.searchParams.get('id'),customerId=u.searchParams.get('customerId'),orderId=u.searchParams.get('orderId');const db=database();const department=['print','warehouse','production'].includes(user.role);
 const orderRows=(department||orderId)?await db.prepare('SELECT data FROM crm_orders WHERE space=?').bind(space).all<{data:string}>():{results:[]};const orders=orderRows.results.map(r=>JSON.parse(r.data));
 const allowed=(f:CustomerFile)=>orders.some(o=>(!orderId||o.id===orderId)&&fileOnWork(f,o));
 if(id){const row=await db.prepare('SELECT object_key,data FROM crm_files WHERE space=? AND id=?').bind(space,id).first<{object_key:string;data:string}>();if(!row)throw new AccessError('Filen finns inte.',404);const metadata=JSON.parse(row.data) as CustomerFile;if((department||orderId)&&!allowed(metadata))throw new AccessError('Filen hör inte till en arbetsorder.',403);const file=await bucket().get(row.object_key);if(!file)throw new AccessError('Filinnehållet kunde inte hittas.',404);const data=JSON.parse(row.data) as CustomerFile;const ext=data.name.split('.').at(-1)?.toLowerCase(),preview=u.searchParams.get('preview')==='1'&&['png','jpg','jpeg','webp'].includes(ext||'');return new Response(file.body,{headers:{'Content-Type':preview?(ext==='jpg'||ext==='jpeg'?'image/jpeg':'image/'+ext):'application/octet-stream','Content-Disposition':(preview?'inline':'attachment')+"; filename*=UTF-8''"+encodeURIComponent(data.name),'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}});}
 if(!customerId)throw new AccessError('Välj kund.',400);const rows=await db.prepare('SELECT data FROM crm_files WHERE space=? AND customer_id=?').bind(space,customerId).all<{data:string}>();return reply(rows.results.map(r=>JSON.parse(r.data)).filter((f:CustomerFile)=>(!department&&!orderId)||allowed(f)).sort((a:CustomerFile,b:CustomerFile)=>b.at.localeCompare(a.at)));
 }catch(e){return fail(e)}}
export async function POST(req:Request){let objectKey='',savedData:CustomerFile|undefined;try{
 sameOrigin(req);const user=await member(req,true);if(Number(req.headers.get('content-length')||0)>5500000)throw new AccessError('Välj en fil på högst 5 MB.',413);
 // Bound chunked requests too; never buffer an unlimited multipart body.
 const reader=req.body?.getReader();if(!reader)throw new AccessError('Filen saknas.',400);const chunks:Uint8Array[]=[];let size=0;while(true){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>5500000){await reader.cancel();throw new AccessError('Välj en fil på högst 5 MB.',413);}chunks.push(part.value);}
 const bytes=new Uint8Array(size);let pos=0;for(const chunk of chunks){bytes.set(chunk,pos);pos+=chunk.length;}const form=await new Response(bytes,{headers:{'Content-Type':req.headers.get('content-type')||''}}).formData();
 const space=spaceOf(form.get('space')),customerId=z.string().min(1).max(100).parse(form.get('customerId')),version=z.string().trim().min(1,'Ange filens version.').max(100).parse(form.get('version')),kind=z.enum(['logo','proof','document']).parse(form.get('kind')),file=form.get('file');if(!(file instanceof File)||!file.size||file.size>5000000)throw new AccessError('Välj en fil på högst 5 MB.',400);
 if(!/\.(pdf|png|jpe?g|svg|eps|ai|webp|xlsx|docx)$/i.test(file.name))throw new AccessError('Använd PDF, bild, AI/EPS, Word eller Excel.',400);
 const db=database();if(!await db.prepare('SELECT id FROM crm_customers WHERE space=? AND id=?').bind(space,customerId).first())throw new AccessError('Kunden finns inte.',404);
 const photo=form.get('purpose')==='production';let productionOrder:any=null;
 if(photo){const orderId=z.string().min(1).max(100).parse(form.get('orderId')),workId=z.string().min(1).max(100).parse(form.get('workId'));const row=await db.prepare('SELECT data FROM crm_orders WHERE space=? AND id=?').bind(space,orderId).first<{data:string}>();productionOrder=row?JSON.parse(row.data):null;if(!productionOrder||productionOrder.customerId!==customerId||productionOrder.production?.workId!==workId||!['submitted','printed'].includes(productionOrder.production.status))throw new AccessError('Välj en aktiv arbetsorder med aktuellt underlag.',409);
 if(kind!=='document'||!['admin','print','warehouse','production'].includes(user.role))throw new AccessError('Du kan inte lägga till ett arbetsfoto.',403);
 if(!/\.(png|jpe?g|webp)$/i.test(file.name))throw new AccessError('Välj ett foto i JPG, PNG eller WebP.',400);
 const bytes=new Uint8Array(await file.arrayBuffer()),ext=file.name.split('.').at(-1)!.toLowerCase();const valid=ext==='png'?bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10':ext==='webp'?new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP':bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)throw new AccessError('Filen känns inte igen som ett foto.',400);
 }else if(!['admin','seller'].includes(user.role))throw new AccessError('Kundunderlag laddas upp av säljare.',403);
 const count=await db.prepare('SELECT COUNT(*) AS n FROM crm_files WHERE space=? AND customer_id=?').bind(space,customerId).first<{n:number}>();if(count&&count.n>=200)throw new AccessError('Kunden har nått gränsen 200 filer.',400);
 const current=await db.prepare('SELECT version FROM crm_spaces WHERE id=?').bind(space).first<{version:number}>();if(!current)throw new AccessError('Arbetsytan saknas.',404);
 const id=crypto.randomUUID(),at=new Date().toISOString(),data:CustomerFile={id,name:file.name.replace(/[\r\n]/g,'').slice(0,200),kind,version,size:file.size,at,uploadedBy:user.name,...(photo?{purpose:'production' as const,orderId:productionOrder.id,workId:productionOrder.production.workId}:{})};savedData=data;objectKey=space+'/'+customerId+'/'+id;
 await bucket().put(objectKey,file.stream(),{httpMetadata:{contentType:'application/octet-stream'}});
 const token=crypto.randomUUID(),gate='EXISTS(SELECT 1 FROM crm_spaces WHERE id=? AND write_token=?)';const event={id:crypto.randomUUID(),customerId,dealId:productionOrder?.dealId||'',text:(photo?'Arbetsfoto sparat: ':'Fil sparad: ')+data.name+' · version '+version,at,kind:photo?'production':'file',actor:{id:user.user_id!,name:user.name}};
 const r=await db.batch([db.prepare('UPDATE crm_spaces SET version=version+1,write_token=? WHERE id=? AND version=? AND (? IS NULL OR EXISTS(SELECT 1 FROM crm_orders WHERE space=? AND id=? AND data=?))').bind(token,space,current.version,productionOrder?productionOrder.id:null,space,productionOrder?.id||'',productionOrder?JSON.stringify(productionOrder):''),db.prepare('INSERT INTO crm_files(id,space,customer_id,object_key,data) SELECT ?,?,?,?,? WHERE '+gate).bind(id,space,customerId,objectKey,JSON.stringify(data),space,token),db.prepare('INSERT INTO crm_events(id,space,customer_id,data) SELECT ?,?,?,? WHERE '+gate).bind(event.id,space,customerId,JSON.stringify(event),space,token)]);
 if(r[0].meta.changes!==1){await bucket().delete(objectKey);objectKey='';throw new AccessError('En annan ändring hann före. Välj filen igen och försök på nytt.',409);}objectKey='';return reply(data);
 }catch(e){if(objectKey)try{const committed=await database().prepare('SELECT id FROM crm_files WHERE object_key=?').bind(objectKey).first();if(committed&&savedData)return reply(savedData);await bucket().delete(objectKey)}catch{/* Keep the object if commit outcome cannot be verified. */}return fail(e)}}
