import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {customerAnchorFixture} from './crm-customer-anchor.mjs';

export const commercialAnchorAction='commercial_responsibility_anchor';
export const commercialAnchorConflict='commercial_responsibility_anchor_conflict';
export const commercialAnchorAccountConflict='commercial_responsibility_anchor_account_conflict';

// All records, accounts and bytes are synthetic. The existing customer fixture
// supplies separate invoice, production, meeting, file and private-data sentinels.
export function commercialAnchorFixture(core,ops){
 const fixture=customerAnchorFixture(core,ops),{state,id,customerId,otherId,owner,otherOwner,profiles,accounts,at}=fixture;
 const dealId=id('open-commercial-deal'),otherDealId=id('other-open-deal'),historicalDealId=id('historical-commercial-deal');
 const line={id:id('open-line'),kind:'product',description:'Syntetisk öppen affärsrad',quantity:45,unitPrice:125,unitCost:70};
 const make=(did,cid,title)=>core.DealSchema.parse({id:did,customerId:cid,title,owner,stage:'quoted',value:5625,cost:3150,lines:[line],need:'Syntetiskt redan dokumenterat behov',decisionMaker:'Syntetisk beslutsroll',deliveryDate:fixture.today,solution:'Syntetiskt bevarat offertunderlag',quoteRef:'SYNTHETIC-OPEN-QUOTE',decisionDate:fixture.today,nextAction:'Syntetiskt befintligt nästa affärssteg',nextDate:fixture.today});
 const legacyAudit={id:crypto.randomUUID(),targetType:'deal',targetId:historicalDealId,customerId:otherId,dealId:historicalDealId,fromProfileId:profiles.b,toProfileId:profiles.a,fromOwner:otherOwner,toOwner:owner,fromDisplayName:'Syntetiskt äldre namn',toDisplayName:'Syntetiskt äldre ansvarig',selectedTaskIds:[],reason:'Syntetisk tidigare verklig fixtureöverföring',at,byId:accounts.actor.user_id,byMemberId:accounts.actor.id,byName:accounts.actor.name};
 state.deals.push(make(dealId,customerId,'Syntetisk äldre öppen affär'),make(otherDealId,otherId,'Syntetisk separat öppen affär'),{...make(historicalDealId,otherId,'Syntetisk tidigare överförd affär'),ownerProfileId:profiles.a,responsibilityTransfers:[legacyAudit]});
 for(const [kind,taskOwner,done] of [['quote',owner,false],['manual',owner,false],['care',otherOwner,false],['quote',owner,true]])state.tasks.push(core.TaskSchema.parse({id:id('deal-task-'+kind+'-'+taskOwner+'-'+done),customerId,dealId,owner:taskOwner,kind,title:'Syntetiskt befintligt åtagande '+kind,due:fixture.today,done}));
 return {...fixture,dealId,otherDealId,historicalDealId,commercialLegacyAudit:legacyAudit};
}

export function assertCommercialAnchorOnly(before,after,dealId,profileId,actor){
 const old=before.deals.find(row=>row.id===dealId),next=after.deals.find(row=>row.id===dealId),audit=next.responsibilityTransfers.at(-1);
 assert.equal(old.ownerProfileId,'');assert.equal(old.responsibilityTransfers.length,0);
 assert.equal(audit.action,'anchor');assert.equal(audit.targetType,'deal');assert.equal(audit.targetId,dealId);assert.equal(audit.dealId,dealId);assert.equal(audit.customerId,old.customerId);assert.equal(audit.fromRecordedProfileId,'');
 assert.equal(audit.fromProfileId,profileId);assert.equal(audit.toProfileId,profileId);assert.equal(audit.fromOwner,old.owner);assert.equal(audit.toOwner,old.owner);assert.deepEqual(audit.selectedTaskIds,[]);
 assert.equal(audit.fromDisplayName,before.settings.sellerProfiles.find(profile=>profile.id===profileId).displayName);assert.equal(audit.toDisplayName,audit.fromDisplayName);
 assert.equal(audit.byId,actor.user_id);assert.equal(audit.byMemberId,actor.id);assert.equal(audit.byName,actor.name);assert.equal(new Date(audit.at).toISOString(),audit.at);assert.match(audit.id,/^[a-f0-9-]{36}$/);
 assert.deepEqual(next,{...old,ownerProfileId:profileId,responsibilityTransfers:[audit]});
 for(const row of before.deals.filter(row=>row.id!==dealId))assert.deepEqual(after.deals.find(candidate=>candidate.id===row.id),row);
 for(const name of ['settings','customers','orders','tasks','meetings','articles','notices','leads','companyEvents'])assert.deepEqual(after[name],before[name],name+' is independent of a deal-only anchor');
 const added=after.events.filter(row=>!before.events.some(oldEvent=>oldEvent.id===row.id));assert.equal(added.length,1);assert.equal(added[0].kind,commercialAnchorAction);assert.equal(added[0].customerId,old.customerId);assert.equal(added[0].dealId,dealId);assert.equal(added[0].at,audit.at);
 for(const row of before.events)assert.deepEqual(after.events.find(candidate=>candidate.id===row.id),row);
 return audit;
}

export async function verifyCommercialAnchor({core,ops,sqlite,objects,api}){
 const store=await import('../work/crm-store.mjs'),responsibility=await import('../work/commercial-responsibility.mjs'),membersApi=await import('../work/members-api.mjs'),restore=await import('../work/crm-restore.mjs'),backup=await import('../work/crm-backup.mjs'),stream=await import('../work/crm-backup-stream.mjs'),conflicts=await import('../work/record-conflicts.mjs');
 const fixture=commercialAnchorFixture(core,ops),{accounts,profiles,dealId,customerId,otherId}=fixture,space='live',db=globalThis.__crmEnv.DB,normalBatch=db.batch;
 const tables=sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(row=>row.name);assert.equal(tables.length,18);
 const raw=()=>({tables:Object.fromEntries(tables.map(table=>[table,sqlite.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()])),r2:Object.fromEntries([...objects].map(([key,bytes])=>[key,{size:bytes.byteLength,sha256:createHash('sha256').update(bytes).digest('hex')}]))});
 const original=raw(),originalKeys=new Set(objects.keys());let baseline,cases=0,races=0;
 function restoreTables(snapshot){db.batch=normalBatch;sqlite.exec('BEGIN');sqlite.exec('PRAGMA defer_foreign_keys=ON');try{for(const table of tables.toReversed())sqlite.prepare('DELETE FROM '+table).run();for(const table of tables)for(const row of snapshot.tables[table]){const columns=Object.keys(row);sqlite.prepare('INSERT INTO '+table+'('+columns.join(',')+')VALUES('+columns.map(()=>'?').join(',')+')').run(...columns.map(column=>row[column]));}sqlite.exec('COMMIT');}catch(error){sqlite.exec('ROLLBACK');throw error;}}
 const clearSpace=target=>{for(const table of ['crm_files','crm_orders','crm_tasks','crm_meetings','crm_events','crm_deals','crm_customers','crm_articles','crm_notices','crm_leads','crm_company_events','crm_mutations'])sqlite.prepare('DELETE FROM '+table+' WHERE space=?').run(target);};
 const who=account=>({'oai-authenticated-user-id':account.user_id,'oai-authenticated-user-email':account.email});
 const request=(path,account=accounts.actor,body)=>new Request('https://crm.test'+path,{method:body?'POST':'GET',headers:{...who(account),...(body?{'Content-Type':'application/json',Origin:'https://crm.test'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const result=async response=>({status:response.status,data:await response.json()});
 const get=async()=>{const r=await result(await api.GET(request('/api/crm?space='+space)));assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};
 const input=async(st,did=dealId,extra={})=>{const directory=await result(await membersApi.GET(request('/api/crm/members')));assert.equal(directory.status,200);assert.ok(directory.data.every(row=>!Object.hasOwn(row,'user_id')));return{dealId:did,targetProfileId:profiles.a,reason:'Granskad syntetisk koppling av samma affärsansvariga',reviewed:true,expectedContext:responsibility.commercialResponsibilityAnchorBasis(st,did),expectedAccount:directory.data.find(row=>row.id===accounts.target.id).expectedAccount,...extra};};
 const intent=async(st,did=dealId,extra={})=>({space,version:st.version,requestId:crypto.randomUUID(),type:commercialAnchorAction,data:await input(st,did,extra)});
 const post=(body,account=accounts.actor)=>api.POST(request('/api/crm',account,body)).then(result);
 const unchanged=(before,label)=>assert.deepEqual(raw(),before,label+' preserves all 18 raw tables and R2 bytes');
 const onlyAllowed=(before,after,label)=>{for(const table of tables.filter(table=>!['crm_spaces','crm_deals','crm_events','crm_mutations'].includes(table)))assert.deepEqual(after.tables[table],before.tables[table],label+' '+table);assert.deepEqual(after.r2,before.r2,label+' R2 bytes');};
 const reset=()=>restoreTables(baseline);
 const reject=async(body,status,code)=>{const before=raw(),r=await post(body);assert.equal(r.status,status,JSON.stringify(r.data));if(code)assert.equal(r.data.code,code);unchanged(before,'Rejected '+(code||'input'));return r;};
 try{
  clearSpace(space);sqlite.prepare('INSERT OR IGNORE INTO crm_spaces(id,version,write_token,settings)VALUES(?,?,?,?)').run(space,10,'',JSON.stringify(fixture.state.settings));sqlite.prepare('UPDATE crm_spaces SET version=10,write_token=?,settings=? WHERE id=?').run('',JSON.stringify(fixture.state.settings),space);
  for(const [name,table] of Object.entries(store.tables))for(const row of fixture.state[name]){const columns=['space','id',...(['customers','articles','notices','leads','companyEvents'].includes(name)?[]:['customer_id']),...(name==='orders'?['deal_id']:[]),'data'];sqlite.prepare('INSERT INTO '+table+'('+columns.join(',')+')VALUES('+columns.map(()=>'?').join(',')+')').run(space,row.id,...(['customers','articles','notices','leads','companyEvents'].includes(name)?[]:[row.customerId]),...(name==='orders'?[row.dealId]:[]),JSON.stringify(row));}
  for(const account of Object.values(accounts))sqlite.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active)VALUES(?,?,?,?,?,?,1)').run(account.id,account.email,account.user_id,account.name,account.role,account.owner);
  for(const account of [accounts.actor,accounts.target]){
   sqlite.prepare('INSERT INTO crm_drafts(space,user_id,id,kind,context,revision,request_id,title,data,archived,updated_at)VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(space,account.user_id,fixture.id('draft-'+account.id),'form','deal',3,crypto.randomUUID(),'Syntetiskt privat affärsutkast',' {"raw":"'+fixture.privateSecret+'"}\n',0,fixture.at);
   sqlite.prepare('INSERT INTO outlook_connections(user_id,microsoft_id,email,tokens,last_sync)VALUES(?,?,?,?,?)').run(account.user_id,fixture.id('ms-'+account.id),account.email,fixture.privateSecret,fixture.at);
   sqlite.prepare('INSERT INTO outlook_items(id,user_id,kind,data,customer_id,shared,happened_at,seen_at)VALUES(?,?,?,?,?,?,?,?)').run(fixture.id('mail-'+account.id),account.user_id,'mail',JSON.stringify({body:fixture.privateSecret}),customerId,0,fixture.at,fixture.at);
   sqlite.prepare('INSERT INTO outlook_oauth_states(hash,user_id,verifier,expires)VALUES(?,?,?,?)').run(fixture.id('oauth-'+account.id),account.user_id,fixture.privateSecret,1999999999000);
  }
  objects.set(fixture.objectKey,fixture.fileBytes);sqlite.prepare('INSERT INTO crm_files(id,space,customer_id,object_key,data)VALUES(?,?,?,?,?)').run(fixture.fileId,space,customerId,fixture.objectKey,JSON.stringify({id:fixture.fileId,name:'synthetic-commercial-anchor.txt',kind:'document',version:'v1',size:fixture.fileBytes.length,at:fixture.at,uploadedBy:accounts.actor.user_id}));baseline=raw();
  const state=await get(),data=await input(state),actor={id:accounts.actor.user_id,memberId:accounts.actor.id,name:accounts.actor.name,role:'admin',owner:accounts.actor.owner},target={memberId:accounts.target.id,userId:accounts.target.user_id,name:accounts.target.name,email:accounts.target.email,role:accounts.target.role,owner:accounts.target.owner,active:1,expectedAccount:data.expectedAccount};
  assert.throws(()=>core.applyAction(state,{type:commercialAnchorAction,data},actor),/konto|gransk|koppling/i);assert.throws(()=>core.applyAction(state,{type:commercialAnchorAction,data:{...data,target}},actor,target));assert.throws(()=>core.applyAction(state,{type:commercialAnchorAction,data:{...data,targetProfileId:profiles.b}},actor,target),/samma|ansvar/i);
  const deal=st=>st.deals.find(d=>d.id===dealId),profile=st=>st.settings.sellerProfiles.find(p=>p.id===profiles.a);
  const blockedMutations=[st=>deal(st).stage='won',st=>deal(st).stage='lost',st=>st.orders.push({...st.orders[0],id:fixture.id('linked-order'),dealId}),st=>deal(st).customerId=fixture.id('missing-customer'),st=>st.deals.push(structuredClone(deal(st))),st=>st.customers.push(structuredClone(st.customers.find(c=>c.id===customerId))),st=>st.settings.sellerProfilesInitialized=false,st=>profile(st).active=false,st=>profile(st).memberId='',st=>st.settings.sellerProfiles.push({...profile(st),id:crypto.randomUUID()}),st=>st.settings.owners=st.settings.owners.filter(owner=>owner!==fixture.owner),st=>deal(st).ownerProfileId=profiles.a,st=>deal(st).responsibilityTransfers=[{...fixture.commercialLegacyAudit,targetId:dealId,dealId,customerId}]];
  for(const mutate of blockedMutations){const bad=structuredClone(state);mutate(bad);assert.ok(responsibility.commercialResponsibilityAnchorReview(bad,dealId).blockedReason,'Changed or ambiguous existing evidence blocks the neutral link');cases++;}
  const noDeal=structuredClone(state);noDeal.deals=noDeal.deals.filter(row=>row.id!==dealId);assert.ok(responsibility.commercialResponsibilityAnchorReview(noDeal,dealId).blockedReason);
  const retired=structuredClone(state);profile(retired).retirementHistory=[{id:crypto.randomUUID(),at:fixture.at,byId:accounts.actor.user_id,byMemberId:accounts.actor.id,byName:accounts.actor.name,reason:'Syntetiskt tidigare avslutat profilansvar',reviewed:true}];assert.ok(responsibility.commercialResponsibilityAnchorReview(retired,dealId).blockedReason);
  const domainAfter=core.applyAction(state,{type:commercialAnchorAction,data},actor,target),audit=assertCommercialAnchorOnly(state,domainAfter,dealId,profiles.a,accounts.actor);assert.equal(audit.targetMemberId,accounts.target.id);assert.equal(audit.targetUserId,accounts.target.user_id);assert.equal(audit.targetName,accounts.target.name);assert.equal(audit.targetRole,accounts.target.role);unchanged(baseline,'Pure domain proof');
  const savedBody=await intent(state),saved=await post(savedBody);assert.equal(saved.status,200,JSON.stringify(saved.data));assertCommercialAnchorOnly(state,saved.data,dealId,profiles.a,accounts.actor);onlyAllowed(baseline,raw(),'Neutral deal write');assert.equal(saved.data.version,state.version+1);assert.ok(!JSON.stringify(saved.data).includes(fixture.privateSecret));
  const replayBefore=raw();assert.equal((await post(savedBody)).status,200);unchanged(replayBefore,'Lost ACK exact retry');await reject({...savedBody,data:{...savedBody.data,reason:'Annan syntetisk avsikt'}},409);await reject({...savedBody,requestId:crypto.randomUUID()},409,commercialAnchorConflict);await reject(await intent(await get()),400);
  for(const account of [accounts.target,accounts.production,accounts.reader]){const before=raw(),denied=await post(savedBody,account);assert.equal(denied.status,403);assert.deepEqual(Object.keys(denied.data),['error']);unchanged(before,'Non-admin replay');}const peerBefore=raw(),peer=await post(savedBody,accounts.peer);assert.equal(peer.status,409);unchanged(peerBefore,'Actor-bound replay');
  const after=await get(),anchored=after.deals.find(row=>row.id===dealId);
  for(const extra of [{ownerProfileId:''},{responsibilityTransfers:[]},{owner:fixture.otherOwner}])await reject({space,version:after.version,requestId:crypto.randomUUID(),type:'deal',expectedRecord:conflicts.recordBasis(anchored),data:{...anchored,...extra}},400);
  const ordinary={...anchored,solution:'Syntetiskt senare vanligt offertunderlag'};delete ordinary.ownerProfileId;delete ordinary.responsibilityTransfers;const edited=await post({space,version:after.version,requestId:crypto.randomUUID(),type:'deal',expectedRecord:conflicts.recordBasis(anchored),data:ordinary});assert.equal(edited.status,200,JSON.stringify(edited.data));assert.equal(edited.data.deals.find(row=>row.id===dealId).ownerProfileId,profiles.a);assert.deepEqual(edited.data.deals.find(row=>row.id===dealId).responsibilityTransfers,anchored.responsibilityTransfers);
  const historical=structuredClone(after),savedAudit=structuredClone(anchored.responsibilityTransfers),historicalProfile=profile(historical);historicalProfile.displayName='Syntetiskt senare visningsnamn';const linked=fixture.id('later-linked-member');historicalProfile.linkHistory.push({previousMemberId:historicalProfile.memberId,nextMemberId:linked,reason:'Syntetiskt senare granskat profilunderlag',at:fixture.at,byId:accounts.actor.user_id,byName:accounts.actor.name});historicalProfile.memberId=linked;assert.deepEqual(core.normalizeState(historical).deals.find(row=>row.id===dealId).responsibilityTransfers,savedAudit);
  const choices=responsibility.commercialResponsibilityCandidates(after,'deal',dealId),transferred=core.applyAction(after,{type:'commercial_responsibility_transfer',data:{targetType:'deal',targetId:dealId,targetProfileId:profiles.b,selectedTaskIds:choices.requiredTaskIds,reason:'Syntetisk senare granskad affärsöverlämning',reviewed:true,expectedContext:responsibility.commercialResponsibilityBasis(after,'deal',dealId)}},actor),transferredDeal=transferred.deals.find(row=>row.id===dealId);assert.equal(transferredDeal.ownerProfileId,profiles.b);assert.equal(transferredDeal.owner,fixture.otherOwner);assert.deepEqual(transferredDeal.responsibilityTransfers.slice(0,-1),savedAudit);assert.ok(!Object.hasOwn(transferredDeal.responsibilityTransfers.at(-1),'action'));assert.deepEqual(restore.restoreState(core.emptyState(),{format:'magnussons-crm-1',state:transferred},true).deals.find(row=>row.id===dealId).responsibilityTransfers,transferredDeal.responsibilityTransfers);assert.deepEqual(transferred.orders,after.orders);cases++;
  reset();const projectionOrder=structuredClone(fixture.state.orders[0]);projectionOrder.stage='shipping';projectionOrder.production.status='dispatched';projectionOrder.production.dispatchedAt=fixture.at;projectionOrder.production.dispatchedBy='Syntetisk produktionsaktör';projectionOrder.production.movements=['received','printed','dispatched'].map(kind=>({id:fixture.id('complete-'+kind),kind,entries:[{lineId:projectionOrder.production.lines[0].id,quantity:50}],at:fixture.at,by:'Syntetisk produktionsaktör',reason:''}));sqlite.prepare('UPDATE crm_orders SET data=? WHERE space=? AND id=?').run(JSON.stringify(projectionOrder),space,projectionOrder.id);const projected=await get(),receipt=projected.tasks.find(task=>task.id==='receipt-'+projectionOrder.id);assert.ok(receipt);assert.ok(!raw().tables.crm_tasks.some(row=>row.id===receipt.id));const projectionBefore=raw(),projectionSaved=await post(await intent(projected));assert.equal(projectionSaved.status,200,JSON.stringify(projectionSaved.data));assertCommercialAnchorOnly(projected,projectionSaved.data,dealId,profiles.a,accounts.actor);assert.deepEqual(projectionSaved.data.tasks.find(task=>task.id===receipt.id),receipt);onlyAllowed(projectionBefore,raw(),'Derived receipt stays a read projection');cases++;
  reset();const body=await intent(await get());
  for(const extra of [{reviewed:false},{reason:'   '},{expectedAccount:'bad-digest'},{selectedTaskIds:[]},{targetType:'order'},{targetMemberId:accounts.peer.id},{owner:'Forged owner'}])await reject({...body,data:{...body.data,...extra}},400);
  for(const targetProfileId of [profiles.b,profiles.old,crypto.randomUUID()])await reject({...body,data:{...body.data,targetProfileId}},409,commercialAnchorAccountConflict);
  await reject({...body,data:{...body.data,expectedContext:'stale'}},409,commercialAnchorConflict);await reject({...body,data:{...body.data,expectedAccount:'0'.repeat(64)}},409,commercialAnchorAccountConflict);
  const targetChanges=[['user_id',fixture.id('changed-user')],['user_id',null],['user_id',' noncanonical-user '],['owner',fixture.otherOwner],['role','production'],['active',0],['email',fixture.id('changed-email')+'@example.test'],['name','Syntetiskt ändrat kontonamn'],['id',fixture.id('changed-member')]];
  for(const [column,value] of targetChanges){reset();const mine=await intent(await get());sqlite.prepare('UPDATE crm_members SET '+column+'=? WHERE id=?').run(value,accounts.target.id);await reject(mine,409,commercialAnchorAccountConflict);cases++;}
  for(const which of ['target','actor']){reset();const before=raw();assert.throws(()=>sqlite.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active)VALUES(?,?,?,?,?,?,1)').run(fixture.id('duplicate-'+which),fixture.id('duplicate-email-'+which)+'@example.test',accounts[which].user_id,'Syntetiskt dubbelt användar-ID','seller',''),/UNIQUE constraint failed: crm_members.user_id/);unchanged(before,'Actual '+which+' uniqueness constraint');}
  for(const [column,value] of targetChanges){reset();const mine=await intent(await get());let fired=0,concurrent;db.batch=async statements=>{if(!fired&&statements[0].sql.startsWith('UPDATE crm_spaces')){fired++;races++;sqlite.prepare('UPDATE crm_members SET '+column+'=? WHERE id=?').run(value,accounts.target.id);concurrent=raw();}return normalBatch(statements);};const r=await post(mine);assert.equal(fired,1);assert.equal(r.status,409,JSON.stringify(r.data));assert.equal(r.data.code,commercialAnchorAccountConflict);unchanged(concurrent,'Actual target SQL race '+column);db.batch=normalBatch;}
  for(const [column,value] of [['role','seller'],['active',0],['owner','Syntetiskt ändrat adminansvar'],['user_id',fixture.id('changed-admin-user')],['name','Syntetiskt ändrat adminnamn']]){reset();const mine=await intent(await get());let fired=0,concurrent;db.batch=async statements=>{if(!fired&&statements[0].sql.startsWith('UPDATE crm_spaces')){fired++;races++;sqlite.prepare('UPDATE crm_members SET '+column+'=? WHERE id=?').run(value,accounts.actor.id);concurrent=raw();}return normalBatch(statements);};const r=await post(mine);assert.equal(fired,1);assert.equal(r.status,403,JSON.stringify(r.data));assert.deepEqual(Object.keys(r.data),['error']);unchanged(concurrent,'Actual actor SQL race '+column);db.batch=normalBatch;}
  for(const related of [false,true]){reset();const opened=await get(),mine=await intent(opened);let fired=0,concurrent;db.batch=async statements=>{if(!fired&&statements[0].sql.startsWith('UPDATE crm_spaces')){fired++;races++;sqlite.prepare('UPDATE crm_spaces SET version=version+1 WHERE id=?').run(space);if(related){const row=structuredClone(opened.deals.find(d=>d.id===dealId));row.solution+=' ändrat granskningsunderlag';sqlite.prepare('UPDATE crm_deals SET data=? WHERE space=? AND id=?').run(JSON.stringify(row),space,dealId);}else{const row=structuredClone(opened.customers.find(c=>c.id===otherId));row.phone='Syntetisk oberoende ändring';sqlite.prepare('UPDATE crm_customers SET data=? WHERE space=? AND id=?').run(JSON.stringify(row),space,otherId);}concurrent=raw();}return normalBatch(statements);};const r=await post(mine);assert.equal(fired,1);assert.equal(r.status,related?409:200,JSON.stringify(r.data));if(related){assert.equal(r.data.code,commercialAnchorConflict);unchanged(concurrent,'Reviewed deal context changed');}else{assert.equal(r.data.version,opened.version+2);assert.equal(r.data.customers.find(c=>c.id===otherId).phone,'Syntetisk oberoende ändring');assert.equal(r.data.deals.find(d=>d.id===dealId).responsibilityTransfers.length,1);}db.batch=normalBatch;}
  reset();const doubleBefore=await get(),doubleBody=await intent(doubleBefore),clicks=await Promise.all([post(doubleBody),post(doubleBody)]);for(const r of clicks)assert.equal(r.status,200,JSON.stringify(r.data));const doubleAfter=await get();assertCommercialAnchorOnly(doubleBefore,doubleAfter,dealId,profiles.a,accounts.actor);assert.equal(doubleAfter.version,doubleBefore.version+1);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM crm_mutations WHERE space=? AND id=?').get(space,doubleBody.requestId).n,1);
  reset();assert.equal((await post(await intent(await get()))).status,200);const source=await store.load(space),restored=restore.restoreState(core.emptyState(),{format:'magnussons-crm-1',state:source},true);assert.deepEqual(restored.deals,source.deals);assert.deepEqual(restored.settings.sellerProfiles,source.settings.sellerProfiles.map(profile=>({...profile,memberId:''})));
  for(const mutate of [d=>d.ownerProfileId='',d=>d.responsibilityTransfers.push(structuredClone(d.responsibilityTransfers.at(-1))),d=>d.responsibilityTransfers.at(-1).selectedTaskIds=[fixture.state.tasks[0].id],d=>d.responsibilityTransfers.at(-1).toProfileId=profiles.b,d=>d.responsibilityTransfers.at(-1).targetUserId='',d=>d.responsibilityTransfers.at(-1).action='transfer',d=>d.responsibilityTransfers.at(-1).targetType='order']){const bad=structuredClone(source);mutate(bad.deals.find(d=>d.id===dealId));assert.throws(()=>core.normalizeState(structuredClone(bad)));assert.throws(()=>restore.restoreState(core.emptyState(),{format:'magnussons-crm-1',state:bad},true));}
  const exported=await backup.exportBackup(space),serialized=await new Response(await stream.exportBackupStream(space)).text();assert.deepEqual(exported.state.deals,source.deals);assert.deepEqual(JSON.parse(serialized.split('\n')[0]).state.deals,source.deals);assert.ok(!JSON.stringify(exported).includes(fixture.privateSecret));assert.ok(!serialized.includes(fixture.privateSecret));assert.equal(exported.files[0].sha256,createHash('sha256').update(fixture.fileBytes).digest('hex'));
  for(const format of ['json','stream']){reset();clearSpace('demo');sqlite.prepare('UPDATE crm_drafts SET archived=1 WHERE space=?').run('demo');sqlite.prepare('INSERT OR IGNORE INTO crm_spaces(id,version,write_token,settings)VALUES(?,?,?,?)').run('demo',0,'',JSON.stringify(core.emptyState().settings));sqlite.prepare('UPDATE crm_spaces SET version=0,write_token=?,settings=? WHERE id=?').run('',JSON.stringify(core.emptyState().settings),'demo');const before=raw(),imported=format==='json'?await backup.importBackup('demo',exported,crypto.randomUUID(),0,actor):await stream.importBackupStream('demo',new Response(serialized).body,crypto.randomUUID(),0,actor);assert.deepEqual(imported.deals,source.deals);assert.deepEqual(imported.orders,source.orders);assert.deepEqual(imported.tasks,source.tasks);assert.deepEqual(imported.settings.sellerProfiles,source.settings.sellerProfiles.map(profile=>({...profile,memberId:''})));for(const table of ['crm_members','crm_drafts','outlook_connections','outlook_items','outlook_oauth_states'])assert.deepEqual(raw().tables[table],before.tables[table]);const files=sqlite.prepare('SELECT * FROM crm_files WHERE space=?').all('demo');assert.equal(files.length,1);assert.deepEqual(objects.get(files[0].object_key),fixture.fileBytes);for(const key of [...objects.keys()])if(!originalKeys.has(key)&&key!==fixture.objectKey)objects.delete(key);cases++;}
 }finally{db.batch=normalBatch;restoreTables(original);for(const key of [...objects.keys()])if(!originalKeys.has(key))objects.delete(key);unchanged(original,'Exact pre-fixture restoration');}
 console.log('PASS deal-only commercial anchor: '+JSON.stringify({cases,races,rawTables:tables.length})+'; strict current admin/account, unchanged tasks/customer/production/invoice/private/file data, actual tuple SQL races, frozen context/rebase, double-click/exact replay, future ordinary transfer and JSON/NDJSON recovery. Single SQLite adapter; no personal-account or hosted-restore claim.');
 return{commercialAnchorCases:cases,commercialAnchorSQLRaces:races,commercialAnchor18Tables:true,commercialAnchorJSONRestore:true};
}
