import ts from 'typescript';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync('work',{recursive:true});
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
class Prepared {constructor(sql,values=[]){this.sql=sql;this.values=values}bind(...v){return new Prepared(this.sql,v)}async first(){return sqlite.prepare(this.sql).get(...this.values)||null}async run(){return this.exec()}async all(){return this.exec()}exec(){const stmt=sqlite.prepare(this.sql);if(stmt.columns().length)return {results:stmt.all(...this.values),meta:{changes:0}};const r=stmt.run(...this.values);return {results:[],meta:{changes:Number(r.changes)}}}}
globalThis.__crmEnv={CRM_BOOTSTRAP_ADMINS:JSON.stringify([{email:'ludwig.rosenberg@kraftringen.se',name:'Ludwig Rosenberg',owner:''},{email:'sebastian.hansson@magnussonsreklam.se',name:'Sebastian Hansson',owner:'Sebastian Hansson'}]),DB:{prepare:sql=>new Prepared(sql),batch:async statements=>{sqlite.exec('BEGIN');try{const r=statements.map(s=>s.exec());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}}};
const transpile=(source,target)=>writeFileSync(target,ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
// Compile server-domain modules with their real dependencies, including v12 storage/recovery.
const modules={'crm-files':'crm-files','crm':'core','crm-auth':'auth','crm-db':'db','follow-up':'follow-up','record-conflicts':'record-conflicts','production-quantities':'production-quantities','order-work':'order-work','order-revisions':'order-revisions','drafts':'drafts','operations':'operations','crm-operations':'crm-operations','crm-visibility':'crm-visibility','business':'business','crm-store':'crm-store','crm-restore':'crm-restore','crm-backup':'crm-backup','export-references':'export-references','automation-signals':'automation-signals'};
function compileModule(file,target){let source=readFileSync(file,'utf8').replace("import { env } from 'cloudflare:workers';","const env=globalThis.__crmEnv;");for(const [from,to] of Object.entries(modules)){source=source.replaceAll("'./"+from+"'","'./"+to+".mjs'").replaceAll("'@/lib/"+from+"'","'./"+to+".mjs'");}transpile(source,target);}
for(const [from,to] of Object.entries(modules))compileModule('lib/'+from+'.ts','work/'+to+'.mjs');
compileModule('app/api/crm/route.ts','work/api.mjs');
compileModule('app/api/crm/backup/route.ts','work/backup-api.mjs');
const api=await import('../work/api.mjs'),core=await import('../work/core.mjs');
const headers={'oai-authenticated-user-id':'test-admin','oai-authenticated-user-email':'ludwig.rosenberg@kraftringen.se'};
const get=async(space='demo')=>{const r=await api.GET(new Request('https://crm.test/api/crm?space='+space,{headers}));assert.equal(r.status,200);return r.json()};
const conflicts=await import('../work/record-conflicts.mjs'),quantities=await import('../work/production-quantities.mjs');
const expectedRecord=(state,type,data)=>{const row=conflicts.editableRecord(state,type,data?.id||'');return row?conflicts.recordBasis(row):undefined};
// Existing whole-order scenarios explicitly select all currently available rows.
const movementData=(state,type,data)=>{if(!['production_received','production_printed','production_dispatched'].includes(type))return data;const p=state.orders.find(o=>o.id===data.orderId)?.production;if(!p)return data;const key=type==='production_received'?'toReceive':type==='production_printed'?'toPrint':'toDispatch';return {expectedProduction:quantities.productionBasis(p),entries:quantities.productionProgress(p).filter(r=>r[key]>0).map(r=>({lineId:r.line.id,quantity:r[key]})),address:p.deliveryAddress,...data}};
const post=async(st,type,data,space='demo',id=crypto.randomUUID())=>{const r=await api.POST(new Request('https://crm.test/api/crm',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:'https://crm.test'},body:JSON.stringify({space,version:st.version,requestId:id,expectedRecord:expectedRecord(st,type,data),type,data:movementData(st,type,data)})}));return{status:r.status,data:await r.json(),id}};
let st=await get();assert.equal(st.customers.length,8);assert.equal((await get()).version,st.version);assert.equal((await get('live')).customers.length,0);
let result=await post(st,'deal',{...st.deals[0],stage:'won',confirmed:false});assert.equal(result.status,400);
const d=st.deals.find(d=>d.stage==='quoted');result=await post(st,'deal',{...d,stage:'won',confirmed:true});assert.equal(result.status,200);const won=result.data;assert.equal(won.orders.length,2);assert.equal(won.deals.find(x=>x.id===d.id).stage,'won');
const retry=await post(st,'deal',{...d,stage:'won',confirmed:true},'demo',result.id);assert.equal(retry.status,200);assert.equal(retry.data.orders.length,2);
assert.equal((await post(st,'customer',{...st.customers[0],name:'Concurrent customer'})).status,200);
assert.equal((await post(won,'deal',{...d,stage:'won',confirmed:true})).status,400);
let o=won.orders.find(o=>o.dealId===d.id);assert.equal((await post(won,'order',{...o,stage:'production'})).status,400);
result=await post(won,'order',{...o,stage:'delivered',proofRequired:false,proofApproved:false,supplierConfirmed:true,deliveredDate:core.day()});assert.equal(result.status,200);st=result.data;const taskCount=st.tasks.filter(t=>t.dealId===d.id&&t.kind==='delivery').length;assert.equal(taskCount,1);
o=st.orders.find(o=>o.dealId===d.id);result=await post(st,'order',o);assert.equal(result.status,200);assert.equal(result.data.tasks.filter(t=>t.dealId===d.id&&t.kind==='delivery').length,1);
assert.equal((await post(result.data,'order',{...o,invoiceValue:100,invoiceRef:'',invoiceDate:''})).status,400);
assert.equal(core.margin(100,null),null);assert.equal(core.margin(100,0),100);
assert.equal((await post(result.data,'task',{customerId:'not-here',owner:'Sebastian Hansson',title:'Bad',due:core.day()})).status,400);
assert.equal((await get('live')).customers.length,0);
const csrf=await api.POST(new Request('https://crm.test/api/crm',{method:'POST',headers:{Origin:'https://evil.test','Content-Type':'application/json'},body:'{}'}));assert.equal(csrf.status,403);
console.log('PASS: migrations, demo isolation, persistent API writes, stage gates, won order, idempotency, stale revision, delivery follow-up, invoice requirements, unknown costs, invalid relations, origin protection.');
// Full acquisition -> first order -> onboarding -> recurring customer development.
let live=await get('live');
result=await post(live,'customer',{name:'Process Test AB',contact:'Inköpare Test',owner:'Sebastian Hansson'},'live');assert.equal(result.status,200);live=result.data;let c=live.customers[0];
assert.equal(c.prospecting.stage,'selected');assert.equal(live.deals.length,0);
assert.equal((await post(live,'qualify',{customerId:c.id},'live')).status,400);
const prospect={...c.prospecting,stage:'qualified',reason:'Passar sortimentet',need:'Jackor till medarbetare',scope:'30 jackor',timing:core.plusDays(core.day(),30),nextAction:'Förankra sortiment',nextDate:core.day()};
result=await post(live,'prospecting',{customerId:c.id,prospecting:prospect},'live');assert.equal(result.status,200);live=result.data;
assert.equal(live.deals.length,0);assert.equal(live.tasks.filter(t=>t.kind==='prospecting'&&!t.done).length,1);
result=await post(live,'qualify',{customerId:c.id},'live');assert.equal(result.status,200);live=result.data;c=live.customers[0];let first=live.deals[0];assert.equal(first.type,'new');assert.equal(first.value,null);assert.equal(first.customerId,c.id);assert.equal(c.prospecting.convertedDealId,first.id);assert.equal(live.tasks.find(t=>t.kind==='prospecting').done,true);
assert.equal((await post(live,'qualify',{customerId:c.id},'live')).status,400);
result=await post(live,'deal',{...first,stage:'won',decisionMaker:'Inköpschef Test',solution:'30 jackor med logotyp',quoteRef:'TEST-1',decisionDate:core.day(),value:30000,cost:18000,confirmed:true},'live');assert.equal(result.status,200);live=result.data;c=live.customers[0];assert.equal(c.status,'onboarding');assert.equal(c.onboarding.dealId,first.id);assert.equal(core.onboardingProgress(c),0);
const onboard={...c.onboarding,checks:{contacts:true,billing:true,handover:true,artwork:true,experience:true},feedback:'Bra passform',nextNeed:'Nya storlekar inför vintern'};
assert.equal((await post(live,'onboarding',{customerId:c.id,onboarding:onboard,complete:true},'live')).status,400);
// A generic customer edit cannot bypass the onboarding gate or forge completion.
assert.equal((await post(live,'customer',{...c,status:'active'},'live')).status,400);
let order=live.orders[0];result=await post(live,'order',{...order,stage:'delivered',proofRequired:false,proofApproved:false,supplierConfirmed:true,deliveredDate:core.day()},'live');assert.equal(result.status,200);live=result.data;
assert.equal((await post(live,'onboarding',{customerId:c.id,onboarding:onboard,complete:true},'live')).status,400);
c=live.customers[0];const plan={...c.plan,goal:'Enklare återbeställning',nextAction:'Stäm av nästa personalintag',nextNeed:'Vinterjackor',nextNeedDate:core.plusDays(core.day(),45),contacts:[{name:'Ekonomi Test',role:'Fakturor',email:'test@example.com',phone:''}]};
result=await post(live,'plan',{customerId:c.id,plan,nextReview:core.plusDays(core.day(),20),expectedOrder:'',reviewDays:60},'live');assert.equal(result.status,200);live=result.data;assert.equal(live.tasks.filter(t=>t.kind==='csm_need'&&!t.done).length,1);
result=await post(live,'onboarding',{customerId:c.id,onboarding:onboard,complete:true},'live');assert.equal(result.status,200);live=result.data;c=live.customers[0];assert.equal(c.status,'active');assert.ok(c.onboarding.completedAt);assert.equal(live.orders[0].stage,'followed');assert.equal(live.tasks.filter(t=>['onboarding','handover','delivery'].includes(t.kind)&&!t.done).length,0);
assert.equal((await post(live,'onboarding',{customerId:c.id,onboarding:onboard,complete:true},'live')).status,400);
result=await post(live,'deal',{customerId:c.id,owner:c.owner,title:'Nytt behov',type:'expansion',nextAction:'Boka behovsmöte',nextDate:core.day()},'live');assert.equal(result.status,200);live=result.data;assert.equal(live.customers[0].status,'active');assert.equal(live.deals.length,2);assert.equal(live.customers[0].plan.contacts.length,1);
c=live.customers[0];const issue={...c.plan,issueStatus:'open',issue:'Fel storlek',issueAction:'Byt plaggen',issueOwner:c.owner,issueDue:core.plusDays(core.day(),2)};
result=await post(live,'plan',{customerId:c.id,plan:issue,nextReview:c.nextReview,expectedOrder:'',reviewDays:60},'live');assert.equal(result.status,200);live=result.data;assert.equal(live.tasks.filter(t=>t.kind==='csm_issue'&&!t.done).length,1);
result=await post(live,'plan',{customerId:c.id,plan:{...issue,issueStatus:'resolved'},nextReview:c.nextReview,expectedOrder:'',reviewDays:60},'live');assert.equal(result.status,200);assert.equal(result.data.tasks.filter(t=>t.kind==='csm_issue'&&!t.done).length,0);
const roundtrip=await get('live');assert.equal(roundtrip.customers[0].plan.issueStatus,'resolved');assert.equal(roundtrip.customers[0].onboarding.completedAt,c.onboarding.completedAt);
// Existing records without new fields remain readable and are never marked complete.
const legacy=JSON.parse(JSON.stringify(core.seedState()));legacy.customers.forEach(c=>{delete c.prospecting;delete c.onboarding;delete c.plan});const normalized=core.normalizeState(legacy);assert.equal(normalized.customers.find(c=>c.id==='c3').onboarding.dealId,'dw');assert.equal(core.onboardingProgress(normalized.customers.find(c=>c.id==='c3')),0);
console.log('PASS: prospect gates, conversion once, no prospect revenue, first-order onboarding, no premature activation, customer plan, completion gate, recurrent sale preserves relationship, customer issue tasks, persisted new fields, backward compatibility.');

// Raw notes round-trip without changing the relationship, pipeline or task plan.
let noted=await get('live');
const noteText='  Anteckningar från mötet\n\n'+('Kanske 100 jackor – ej beslutat.\n'.repeat(180))+'  ';
const noteInput={customerId:noted.customers[0].id,title:'Behovsmöte',text:noteText,meetingDate:'2026-09-10',sourceFiles:['möte.txt']};
const beforeCustomer=structuredClone(noted.customers[0]),beforeTasks=structuredClone(noted.tasks),beforeDeals=structuredClone(noted.deals);
let noteResult=await post(noted,'customer_note',noteInput,'live');assert.equal(noteResult.status,200);
let savedNote=noteResult.data.events.find(e=>e.kind==='customer_note');
assert.equal(savedNote.text,noteText);assert.deepEqual(savedNote.note,{title:'Behovsmöte',meetingDate:'2026-09-10',sourceFiles:['möte.txt']});
assert.deepEqual(noteResult.data.customers[0],beforeCustomer);assert.deepEqual(noteResult.data.tasks,beforeTasks);assert.deepEqual(noteResult.data.deals,beforeDeals);
assert.equal((await get('live')).events.find(e=>e.id===savedNote.id).text,noteText);
const duplicate=await post(noted,'customer_note',noteInput,'live',noteResult.id);assert.equal(duplicate.status,200);assert.equal(duplicate.data.events.filter(e=>e.kind==='customer_note').length,1);
assert.equal((await get()).events.some(e=>e.id===savedNote.id),false);
noted=await get('live');
for(const invalid of [{text:'   '},{text:'x'.repeat(50001)},{customerId:'unknown'},{meetingDate:'2026-02-30'}])assert.equal((await post(noted,'customer_note',{...noteInput,...invalid},'live')).status,400);
assert.equal((await get('live')).events.filter(e=>e.kind==='customer_note').length,1);
console.log('PASS: long raw notes preserved verbatim, metadata persists, no customer or task side effects, duplicate request protection, workspace isolation and invalid-note rejection.');

// Business workflows and permissions exercise the persistent API, not just helpers.
const business=await import('../work/business.mjs');
assert.equal(business.addMonths('2028-02-29',12),'2029-02-28');
assert.deepEqual(business.calculateQuote([{id:'1',kind:'product',description:'Jacka',article:'',variant:'',quantity:3,unitPrice:99.90,unitCost:55}]),{value:299.7,cost:165});
assert.equal(business.calculateQuote([{quantity:1,unitPrice:25,unitCost:null}]).cost,null);
assert.deepEqual(business.parseCSV('\uFEFFFöretagsnamn;Kontaktperson\r\n"A; B AB";"Anna ""Test"""'),[['Företagsnamn','Kontaktperson'],['A; B AB','Anna "Test"']]);
assert.equal((await api.GET(new Request('https://crm.test/api/crm'))).status,401);
assert.equal((await api.GET(new Request('https://crm.test/api/crm',{headers:{...headers,'oai-authenticated-user-id':'impostor'}}))).status,403);
await globalThis.__crmEnv.DB.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active) VALUES(?,?,?,?,?,?,1)').bind('reader','reader@example.com','reader','Läsare','reader','').run();
const readerReq=new Request('https://crm.test/api/crm',{method:'POST',headers:{...headers,'oai-authenticated-user-id':'reader','oai-authenticated-user-email':'reader@example.com','Content-Type':'application/json'},body:'{}'});assert.equal((await api.POST(readerReq)).status,403);
let work=await get('live'),cust=work.customers[0];
let changed=await post(work,'customer',{...cust,organizationNumber:'556123-4567',billingAddress:{street:'Fakturagatan 1',city:'Lund'},deliveryAddress:{street:'Lagervägen 2',postalCode:'28831',city:'Vinslöv'},sites:[{name:'Lager',address:{street:'Lagervägen 2'}}]},'live');assert.equal(changed.status,200);work=changed.data;cust=work.customers[0];assert.equal(cust.deliveryAddress.city,'Vinslöv');assert.equal(cust.plan.contacts[0].email,'test@example.com');
assert.equal((await post(work,'customer',{name:'Annan stavning',owner:cust.owner,organizationNumber:'5561234567'},'live')).status,400);
const qualifiedAt=cust.prospecting.qualifiedAt;assert.ok(qualifiedAt);assert.equal(cust.prospecting.qualifiedOwner,'Sebastian Hansson');
let need={title:'Jackor inför hösten',category:'Arbetskläder',due:'2028-02-29',leadDays:45,intervalMonths:12,owner:cust.owner};
changed=await post(work,'year_need',{customerId:cust.id,need},'live');assert.equal(changed.status,200);work=changed.data;const needId=work.customers[0].yearNeeds[0].id;assert.equal(work.tasks.find(t=>t.kind==='year:'+needId&&!t.done).due,'2028-01-15');
changed=await post(work,'year_need',{customerId:cust.id,need:{...work.customers[0].yearNeeds[0],leadDays:30}},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.tasks.filter(t=>t.kind==='year:'+needId&&!t.done).length,1);
changed=await post(work,'need_deal',{customerId:cust.id,id:needId},'live');assert.equal(changed.status,200);work=changed.data;assert.equal((await post(work,'need_deal',{customerId:cust.id,id:needId},'live')).status,400);
changed=await post(work,'complete_need',{customerId:cust.id,id:needId},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.customers[0].yearNeeds[0].due,'2029-02-28');assert.equal(work.tasks.filter(t=>t.kind==='year:'+needId&&!t.done).length,1);
const oldWon=work.deals.find(d=>d.stage==='won');changed=await post(work,'repeat_order',{dealId:oldWon.id},'live');assert.equal(changed.status,200);work=changed.data;let repeated=work.deals.find(d=>d.sourceDealId===oldWon.id);assert.equal(repeated.type,'repeat');assert.equal(repeated.stage,'identified');assert.equal(repeated.quoteRef,'');assert.equal(repeated.priceChecked,false);assert.equal(work.customers[0].status,'active');
const pricing={...repeated,stage:'quoted',lines:[{id:'line1',kind:'product',description:'Jackor',article:'J-1',variant:'Blå M',quantity:10,unitPrice:100,unitCost:50},{id:'line2',kind:'marking',description:'Brodyr',article:'',variant:'Bröst',quantity:10,unitPrice:20,unitCost:10}],value:1,cost:0,quoteRef:'REPEAT-1',decisionDate:core.day(),deliveryDate:core.plusDays(core.day(),30),proofDeadline:core.plusDays(core.day(),5),orderDeadline:core.plusDays(core.day(),10)};
assert.equal((await post(work,'deal',pricing,'live')).status,400);
changed=await post(work,'deal',{...pricing,priceChecked:true},'live');assert.equal(changed.status,200);work=changed.data;repeated=work.deals.find(d=>d.id===repeated.id);assert.equal(repeated.value,1200);assert.equal(repeated.cost,600);assert.equal(repeated.quotes.length,1);
changed=await post(work,'deal',{...repeated,nextAction:'Följ upp svar'},'live');assert.equal(changed.status,200);work=changed.data;repeated=work.deals.find(d=>d.id===repeated.id);assert.equal(repeated.quotes.length,1);
changed=await post(work,'deal',{...repeated,lines:repeated.lines.map((l,i)=>i===0?{...l,unitPrice:110}:l)},'live');assert.equal(changed.status,200);work=changed.data;repeated=work.deals.find(d=>d.id===repeated.id);assert.equal(repeated.quotes.length,2);assert.equal(repeated.quotes[0].value,1200);assert.equal(repeated.value,1300);
const tasksBefore=work.tasks.length;changed=await post(work,'customer_note',{customerId:cust.id,text:'Skicka förslag',title:'Uppföljning',contact:true,meetingDate:core.day(),nextAction:'Skicka två alternativ',nextDate:core.plusDays(core.day(),2),owner:cust.owner},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.tasks.length,tasksBefore+1);assert.equal(work.customers[0].lastContact,core.day());assert.equal(work.events.find(e=>e.kind==='customer_note'&&e.text==='Skicka förslag').actor.name,'Ludwig Rosenberg');
assert.equal(work.customers[0].prospecting.qualifiedAt,qualifiedAt);
changed=await post(work,'import_customers',{customers:[{name:'Import A',owner:cust.owner,status:'active'},{name:'Import A',owner:cust.owner,status:'active'}]},'live');assert.equal(changed.status,400);assert.equal((await get('live')).customers.length,work.customers.length);
changed=await post(work,'import_customers',{customers:[{name:'Import A',owner:cust.owner,status:'active',organizationNumber:'1234567890'}]},'live');assert.equal(changed.status,200);work=changed.data;assert.ok(work.customers.find(c=>c.name==='Import A'));
const snapshot={format:'magnussons-crm-1',state:work};assert.equal((await post(work,'restore',snapshot,'live')).status,400);
// A clean test database exercises restore without touching hosted records.
for(const table of ['crm_files','crm_events','crm_meetings','crm_tasks','crm_orders','crm_deals','crm_customers','crm_mutations'])sqlite.prepare('DELETE FROM '+table+' WHERE space=?').run('live');
let empty=await get('live');changed=await post(empty,'restore',snapshot,'live');assert.equal(changed.status,200);work=changed.data;assert.deepEqual(work.customers,snapshot.state.customers);assert.deepEqual(work.deals,snapshot.state.deals);assert.deepEqual(work.tasks,snapshot.state.tasks);assert.equal(work.events.find(e=>e.id===savedNote.id).text,noteText);
console.log('PASS: personal role gates, identity binding, customer addresses, duplicate import rollback, recurring year wheel, one need/deal link, repeat-price gate, exact quote totals and version history, note-to-task, persistent qualification metrics, safe export/restore.');

// Uploaded bytes remain separate from CRM JSON and require the same account and workspace.
compileModule('app/api/crm/files/route.ts','work/files-api.mjs');
compileModule('app/api/crm/members/route.ts','work/members-api.mjs');
const fileApi=await import('../work/files-api.mjs'),objects=new Map();
globalThis.__crmEnv.BUCKET={put:async(key,stream)=>objects.set(key,new Uint8Array(await new Response(stream).arrayBuffer())),get:async key=>objects.has(key)?{body:objects.get(key),arrayBuffer:async()=>objects.get(key).buffer}:null,delete:async key=>objects.delete(key)};
const fileBody=new FormData();fileBody.set('space','live');fileBody.set('customerId',cust.id);fileBody.set('version','Korrektur 1');fileBody.set('kind','proof');fileBody.set('file',new File(['%PDF-1.4 test bytes'],'korrektur.pdf',{type:'application/pdf'}));
const upload=await fileApi.POST(new Request('https://crm.test/api/crm/files',{method:'POST',headers,body:fileBody}));assert.equal(upload.status,200);const uploaded=await upload.json();assert.equal(objects.size,1);
const downloadFile=await fileApi.GET(new Request('https://crm.test/api/crm/files?space=live&id='+uploaded.id,{headers}));assert.equal(downloadFile.status,200);assert.equal(await downloadFile.text(),'%PDF-1.4 test bytes');assert.match(downloadFile.headers.get('content-disposition'),/^attachment/);
assert.equal((await fileApi.GET(new Request('https://crm.test/api/crm/files?space=demo&id='+uploaded.id,{headers}))).status,404);
assert.equal((await fileApi.GET(new Request('https://crm.test/api/crm/files?space=live&id='+uploaded.id))).status,401);
work=await get('live');const repeatDeal=work.deals.find(d=>d.sourceDealId===oldWon.id);changed=await post(work,'deal',{...repeatDeal,stage:'won',confirmed:true},'live');assert.equal(changed.status,200);work=changed.data;const proofOrder=work.orders.find(o=>o.dealId===repeatDeal.id);
assert.equal((await post(work,'order',{...proofOrder,proofApproved:true,supplierConfirmed:true,stage:'supplier'},'live')).status,400);
assert.equal((await post(work,'order',{...proofOrder,proofApproved:true,proofFileId:uploaded.id,proofVersion:'Wrong version',approvedBy:'Kundens beställare',approvedDate:core.day(),supplierConfirmed:true,stage:'supplier'},'live')).status,400);
changed=await post(work,'order',{...proofOrder,proofApproved:true,proofFileId:uploaded.id,proofVersion:uploaded.version,approvedBy:'Kundens beställare',approvedDate:core.day(),supplierConfirmed:true,stage:'supplier'},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.orders.find(o=>o.id===proofOrder.id).approvedBy,'Kundens beställare');assert.equal(work.tasks.filter(t=>t.dealId===repeatDeal.id&&['proof_deadline','order_deadline'].includes(t.kind)&&!t.done).length,0);
console.log('PASS: real upload handler and binary round-trip with mocked object storage, private download, workspace isolation, precise proof version and customer approval requirements, deadline task completion.');

// Department workflows use the same persistent API and optimistic revision gate.
const ops=await import('../work/operations.mjs');
for(const role of ['print','warehouse','seller'])await globalThis.__crmEnv.DB.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active) VALUES(?,?,?,?,?,?,1)').bind('ops-'+role,role+'@example.com','ops-'+role,role,role,role==='seller'?cust.owner:'').run();
const roleHeaders=role=>({...headers,'oai-authenticated-user-id':'ops-'+role,'oai-authenticated-user-email':role+'@example.com'});
const roleGet=async role=>{const r=await api.GET(new Request('https://crm.test/api/crm?space=live',{headers:roleHeaders(role)}));assert.equal(r.status,200);return r.json()};
const rolePost=async(role,state,type,data,requestId=crypto.randomUUID())=>{const r=await api.POST(new Request('https://crm.test/api/crm',{method:'POST',headers:{...roleHeaders(role),'Content-Type':'application/json',Origin:'https://crm.test'},body:JSON.stringify({space:'live',version:state.version,requestId,expectedRecord:expectedRecord(state,type,data),type,data:movementData(state,type,data)})}));return{status:r.status,data:await r.json(),id:requestId}};
work=await get('live');let productionOrder=work.orders.find(o=>o.id===proofOrder.id);let productionDeal=work.deals.find(d=>d.id===productionOrder.dealId);
const productionData={orderId:productionOrder.id,production:{lines:productionDeal.lines.filter(l=>l.kind==='product'),sketchFileId:uploaded.id,sketchVersion:uploaded.version,instructions:'Brodyr vänster bröst enligt godkänd skiss',printDeadline:core.plusDays(core.day(),10),dispatchDeadline:core.plusDays(core.day(),20)}};
assert.equal((await post(work,'production_submit',{...productionData,production:{...productionData.production,lines:productionData.production.lines.map(l=>({...l,quantity:999}))}},'live')).status,400);
assert.equal((await post(work,'production_submit',{...productionData,production:{...productionData.production,dispatchDeadline:core.plusDays(core.day(),40)}},'live')).status,400);
changed=await post(work,'production_submit',productionData,'live');assert.equal(changed.status,200,JSON.stringify(changed.data));work=changed.data;productionOrder=work.orders.find(o=>o.id===proofOrder.id);assert.equal(productionOrder.production.status,'submitted');assert.equal(work.notices.length,2);assert.equal(productionOrder.production.submittedBy,'Ludwig Rosenberg');
assert.equal((await post(work,'order',{...productionOrder,stage:'shipping',production:{...productionOrder.production,status:'dispatched'}},'live')).status,400);
assert.equal((await post(work,'order',{...productionOrder,approvedBy:'Forged'},'live')).status,400);
assert.equal((await post(work,'order',{...productionOrder,stage:'handover',supplierConfirmed:false},'live')).status,400);
let printView=await roleGet('print'),warehouseView=await roleGet('warehouse');assert.ok(printView.orders.some(o=>o.id===productionOrder.id));assert.equal(printView.orders[0].production.lines[0].unitCost,null);assert.equal(printView.orders[0].production.lines[0].unitPrice,0);assert.equal(printView.deals[0].value,null);assert.equal(printView.customers[0].billingAddress.street,'');assert.equal(printView.tasks.length,0);assert.equal(printView.leads.length,0);assert.equal(printView.notices.every(n=>n.audience==='print'),true);
assert.equal((await rolePost('print',printView,'customer',cust)).status,403);assert.equal((await rolePost('warehouse',warehouseView,'order',productionOrder)).status,403);assert.equal((await rolePost('seller',await roleGet('seller'),'production_printed',{orderId:productionOrder.id})).status,403);
assert.equal((await rolePost('warehouse',warehouseView,'production_dispatched',{orderId:productionOrder.id})).status,400);assert.equal((await rolePost('print',printView,'production_printed',{orderId:productionOrder.id})).status,400);
const printDownload=await fileApi.GET(new Request('https://crm.test/api/crm/files?space=live&id='+uploaded.id,{headers:roleHeaders('print')}));assert.equal(printDownload.status,200);assert.equal((await fileApi.POST(new Request('https://crm.test/api/crm/files',{method:'POST',headers:roleHeaders('warehouse'),body:fileBody}))).status,403);
changed=await rolePost('print',printView,'production_accept',{orderId:productionOrder.id});assert.equal(changed.status,200);assert.equal(changed.data.orders.find(o=>o.id===productionOrder.id).production.acceptedBy,'print');
changed=await rolePost('warehouse',await roleGet('warehouse'),'production_received',{orderId:productionOrder.id});assert.equal(changed.status,200);
changed=await rolePost('print',await roleGet('print'),'production_issue',{orderId:productionOrder.id,message:'Saknar storlek XL'});assert.equal(changed.status,200);
assert.equal((await rolePost('print',await roleGet('print'),'production_printed',{orderId:productionOrder.id})).status,400);
let sellerView=await roleGet('seller');assert.equal(sellerView.notices.some(n=>n.title==='Åtgärd behövs i order'),true);
changed=await rolePost('print',await roleGet('print'),'production_issue',{orderId:productionOrder.id,message:''});assert.equal(changed.status,200);
changed=await rolePost('print',await roleGet('print'),'production_printed',{orderId:productionOrder.id});assert.equal(changed.status,200);assert.equal(changed.data.orders.find(o=>o.id===productionOrder.id).production.status,'printed');
warehouseView=await roleGet('warehouse');changed=await rolePost('warehouse',warehouseView,'production_dispatched',{orderId:productionOrder.id,tracking:'SHIP-123'});assert.equal(changed.status,200);const dispatchRetry=await rolePost('warehouse',warehouseView,'production_dispatched',{orderId:productionOrder.id,tracking:'SHIP-123'},changed.id);assert.equal(dispatchRetry.status,200);
work=await get('live');productionOrder=work.orders.find(o=>o.id===productionOrder.id);assert.equal(productionOrder.stage,'shipping');assert.equal(productionOrder.deliveredDate,'');assert.equal(productionOrder.invoiceValue,null);assert.equal(productionOrder.production.tracking,'SHIP-123');assert.equal(work.tasks.filter(t=>t.kind==='invoice_ready'&&t.dealId===productionOrder.dealId).length,1);
sellerView=await roleGet('seller');const sellerNotice=sellerView.notices.find(n=>n.orderId===productionOrder.id&&n.title.includes('faktureringsunderlag'));assert.ok(sellerNotice);changed=await rolePost('seller',sellerView,'notice_read',{id:sellerNotice.id});assert.equal(changed.status,200);assert.ok(changed.data.notices.find(n=>n.id===sellerNotice.id).readBy.includes('ops-seller'));assert.ok(!changed.data.notices.find(n=>n.id===sellerNotice.id).readBy.includes('test-admin'));
work=await get('live');changed=await post(work,'order',{...work.orders.find(o=>o.id===productionOrder.id),invoiceValue:1300,invoiceRef:'F-123',invoiceDate:core.day(),actualCost:600},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.tasks.find(t=>t.kind==='invoice_ready'&&t.dealId===productionOrder.dealId).done,true);
// Catalogue snapshots survive edits and a website replacement; missing cost cannot become a confirmed order.
changed=await post(work,'article_import',{articles:[{sourceId:'current',sku:'CAT-1',name:'Piké',variant:'Blå L',price:150,cost:70,url:'https://www.magnussonsreklam.se/test'}]},'live');assert.equal(changed.status,200);work=changed.data;const article=work.articles[0];
const catalogLines=[business.LineSchema.parse({id:'catline',sourceId:article.sourceId,productUrl:article.url,article:article.sku,description:article.name,variant:article.variant,quantity:50,unitPrice:150,unitCost:70})];
const catalogInput={customerId:cust.id,owner:cust.owner,title:'Katalogorder',lines:catalogLines,deliveryDate:core.plusDays(core.day(),30),accepted:true,nextDate:core.day()};
assert.equal((await post(work,'catalog_order',{...catalogInput,lines:catalogLines.map(l=>({...l,unitCost:null}))},'live')).status,400);
changed=await post(work,'catalog_order',catalogInput,'live');assert.equal(changed.status,200,JSON.stringify(changed.data));work=changed.data;const catDeal=work.deals.find(d=>d.title==='Katalogorder'),catOrder=work.orders.find(o=>o.dealId===catDeal.id);assert.equal(catDeal.value,7500);assert.equal(catDeal.lines[0].sourceId,'current');
changed=await post(work,'settings',{...work.settings,annualBudgets:{'2026':10000000},catalogSources:[...work.settings.catalogSources,{id:'newweb',name:'Nya hemsidan',url:'https://example.com',active:true}]},'live');assert.equal(changed.status,200);work=changed.data;
changed=await post(work,'article',{...article,price:250,sourceId:'newweb'},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.deals.find(d=>d.id===catDeal.id).lines[0].unitPrice,150);assert.equal(work.deals.find(d=>d.id===catDeal.id).lines[0].sourceId,'current');
// Cancel/re-submit saves the full earlier work revision and resets physical confirmations.
changed=await post(work,'order',{...catOrder,proofRequired:false,supplierConfirmed:true},'live');assert.equal(changed.status,200);work=changed.data;
const catProduction={...productionData,orderId:catOrder.id,production:{...productionData.production,lines:catalogLines}};
changed=await post(work,'production_submit',catProduction,'live');assert.equal(changed.status,200);work=changed.data;
changed=await post(work,'production_cancel',{orderId:catOrder.id,message:'Ny placering av trycket'},'live');assert.equal(changed.status,200);work=changed.data;
changed=await post(work,'production_submit',{...catProduction,production:{...catProduction.production,instructions:'Tryck på ryggen'}},'live');assert.equal(changed.status,200);work=changed.data;const revised=work.orders.find(o=>o.id===catOrder.id);assert.equal(revised.productionHistory.length,1);assert.equal(revised.productionHistory[0].cancellationReason,'Ny placering av trycket');assert.equal(revised.productionHistory[0].instructions,productionData.production.instructions);assert.equal(revised.production.instructions,'Tryck på ryggen');assert.equal(revised.production.goodsReceived,false);assert.equal((await roleGet('print')).orders.find(o=>o.id===catOrder.id).productionHistory[0].lines[0].unitCost,null);
// Licensed company lists, exact legal-entity matching, retained source, calendar and Fortnox IDs.
const leads=[{name:'Lokalt företag',organizationNumber:'556333-4444',source:'Testexport',employees:20,latitude:56.105,longitude:13.913,contacts:[{name:'Anna',role:'VD',email:'anna@example.com'}]},{name:cust.name,organizationNumber:'999999-9999',source:'Testexport',contacts:[]}];
changed=await post(work,'lead_import',{leads},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.leads.length,2);
changed=await post(work,'lead_import',{leads:[{...leads[0],contacts:[{name:'Bertil',role:'Marknadschef'}]}]},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.leads.find(l=>l.organizationNumber==='556333-4444').contacts.length,2);
assert.ok(ops.distanceKm(56.104866,13.913155,56.105,13.913)<1);assert.equal(ops.distanceKm(56,14,56,14),0);
const leadAction={id:work.leads.find(l=>l.organizationNumber==='556333-4444').id,owner:cust.owner,contactIndex:0,nextDate:core.day(),nextAction:'Ring VD'};
changed=await post(work,'lead_convert',leadAction,'live');assert.equal(changed.status,200);work=changed.data;const importedLead=work.customers.find(c=>c.id===work.leads.find(l=>l.organizationNumber==='556333-4444').customerId);assert.equal(importedLead.contact,'Anna');assert.equal(importedLead.source,'Testexport');assert.equal(importedLead.plan.contacts.length,2);assert.equal((await post(work,'lead_convert',leadAction,'live')).status,400);
changed=await post(work,'lead_convert',{...leadAction,id:work.leads.find(l=>l.organizationNumber==='999999-9999').id},'live');assert.equal(changed.status,200);work=changed.data;assert.notEqual(work.leads.find(l=>l.organizationNumber==='999999-9999').customerId,cust.id);assert.equal(work.customers.find(c=>c.id===work.leads.find(l=>l.organizationNumber==='999999-9999').customerId).organizationNumber,'999999-9999');
changed=await post(work,'customer',{name:'Fortnoxkund',owner:cust.owner,fortnoxNumber:'1009'},'live');assert.equal(changed.status,200);work=changed.data;
assert.equal((await post(work,'import_customers',{customers:[{name:'Samma kund annat namn',owner:cust.owner,fortnoxNumber:'1009'}]},'live')).status,400);
changed=await post(work,'company_event',{title:'Kundevent',date:core.plusDays(core.day(),60),owner:cust.owner,checklist:[{id:'prep1',title:'Boka lokal',owner:cust.owner,due:core.plusDays(core.day(),10)}]},'live');assert.equal(changed.status,200);work=changed.data;
changed=await post(work,'company_event',{...work.companyEvents[0],checklist:work.companyEvents[0].checklist.map(t=>({...t,done:true}))},'live');assert.equal(changed.status,200);assert.equal((await get('live')).companyEvents[0].checklist[0].done,true);assert.equal((await get('live')).settings.annualBudgets['2026'],10000000);
console.log('PASS: role-specific queues/visibility, real print and warehouse API transitions, immutable approved work, no premature shipping/revenue, individual notices, invoice tasks, historical revisions, article-source snapshots, lead conversion/deduplication, radius distance, Fortnox customer IDs, annual goals and shared event checklists.');

// Daily-work drafts have their own revision and private identity partition.
compileModule('app/api/crm/drafts/route.ts','work/draft-api.mjs');
const draftApi=await import('../work/draft-api.mjs'),orderWork=await import('../work/order-work.mjs');
const draftRead=async(id='',who=headers,space='live')=>{const r=await draftApi.GET(new Request('https://crm.test/api/crm/drafts?'+new URLSearchParams({space,...(id?{id}:{})}),{headers:who}));return{status:r.status,data:await r.json()}};
const draftWrite=async(data,who=headers,space='live')=>{const r=await draftApi.POST(new Request('https://crm.test/api/crm/drafts',{method:'POST',headers:{...who,Origin:'https://crm.test','Content-Type':'application/json'},body:JSON.stringify({space,...data})}));return{status:r.status,data:await r.json()}};
assert.equal((await draftApi.GET(new Request('https://crm.test/api/crm/drafts?space=live'))).status,401);
for(const who of [roleHeaders('print'),roleHeaders('warehouse'),{'oai-authenticated-user-id':'reader','oai-authenticated-user-email':'reader@example.com'}])assert.equal((await draftRead('',who)).status,403);
work=await get('live');const beforeDraftVersion=work.version;
const unfinished={id:'personal-unfinished',kind:'catalog',context:'',revision:0,requestId:crypto.randomUUID(),title:'Ofärdig beställning',data:{customerId:'',cart:[{quantity:'',unitCost:null}],notes:'PRIVATE UNSENT TEXT'}};
let dr=await draftWrite(unfinished);assert.equal(dr.status,200);assert.equal(dr.data.revision,1);assert.equal((await get('live')).version,beforeDraftVersion);assert.equal((await draftRead(unfinished.id)).data[0].data.notes,'PRIVATE UNSENT TEXT');assert.equal((await draftRead(unfinished.id,roleHeaders('seller'))).data.length,0);assert.equal((await draftRead(unfinished.id,headers,'demo')).data.length,0);assert.ok(!JSON.stringify(await get('live')).includes('PRIVATE UNSENT TEXT'));
const draftRetry=await draftWrite(unfinished);assert.equal(draftRetry.status,200);assert.equal(draftRetry.data.revision,1);
const raceBase={...dr.data,revision:1};const raced=await Promise.all([draftWrite({...raceBase,requestId:crypto.randomUUID(),data:{notes:'Flik A'}}),draftWrite({...raceBase,requestId:crypto.randomUUID(),data:{notes:'Flik B'}})]);assert.deepEqual(raced.map(r=>r.status).sort(),[200,409]);assert.equal((await draftRead(unfinished.id)).data[0].revision,2);
const lastDraft=(await draftRead(unfinished.id)).data[0];assert.equal((await draftWrite({...lastDraft,requestId:crypto.randomUUID(),archived:true})).status,200);assert.equal((await draftWrite({...lastDraft,requestId:crypto.randomUUID(),data:{notes:'Stale autosave'}})).status,409);assert.equal((await draftRead(unfinished.id)).data[0].archived,true);assert.ok(!(await draftRead()).data.some(d=>d.id===unfinished.id));
assert.equal((await draftWrite({...unfinished,id:'wrong-order',kind:'production',context:'unknown',requestId:crypto.randomUUID()})).status,400);
// Both users can use the same local draft ID without viewing or changing one another.
assert.equal((await draftWrite({...unfinished,requestId:crypto.randomUUID()},roleHeaders('seller'))).status,200);assert.equal((await draftRead(unfinished.id,roleHeaders('seller'))).data[0].revision,1);assert.equal((await draftRead(unfinished.id)).data[0].archived,true);
console.log('PASS: private incomplete drafts, reload persistence, independent CRM revision, role/identity/workspace isolation, same-request retry, concurrent draft CAS and archived-draft protection.');

// An accepted catalogue draft becomes one order and is archived in the same transaction.
work=await get('live');let cartDraft=(await draftWrite({...unfinished,id:'new-order-draft',requestId:crypto.randomUUID(),data:{cart:catalogLines,customerId:cust.id,title:'Sammanhängande order'}})).data;
const confirmedInput={...catalogInput,title:'Sammanhängande order',draft:{id:cartDraft.id,revision:cartDraft.revision}};
assert.equal((await post(work,'catalog_order',{...confirmedInput,lines:catalogLines.map(l=>({...l,unitCost:null}))},'live')).status,400);assert.equal((await draftRead(cartDraft.id)).data[0].archived,false);assert.equal((await get('live')).version,work.version);
changed=await post(work,'catalog_order',confirmedInput,'live');assert.equal(changed.status,200,JSON.stringify(changed.data));const catalogRequest=changed.id;work=changed.data;const guidedDeal=work.deals.find(d=>d.title==='Sammanhängande order');let guided=work.orders.find(o=>o.dealId===guidedDeal.id);assert.equal((await draftRead(cartDraft.id)).data[0].archived,true);assert.equal((await post(work,'catalog_order',confirmedInput,'live',catalogRequest)).status,200);assert.equal((await get('live')).orders.filter(o=>o.dealId===guidedDeal.id).length,1);
let prepareDraft=(await draftWrite({id:'prepare-draft',kind:'production',context:guided.id,revision:0,requestId:crypto.randomUUID(),title:guidedDeal.title,data:{instructions:'Draft not shared until submitted'}})).data;
const approval={proofRequired:true,proofApproved:true,proofFileId:uploaded.id,proofVersion:uploaded.version,approvedBy:'Anna hos kunden',approvedDate:core.day(),supplierConfirmed:true,deliveryDate:guided.deliveryDate};
let prepareInput={orderId:guided.id,expectedOrder:orderWork.orderBasis(guided),approval,deliveryAddress:{street:'Eventgatan 3',postalCode:'28831',city:'Vinslöv',country:'Sverige',reference:'Godsmottagning Anna'},production:{...productionData.production,lines:guidedDeal.lines.filter(l=>l.kind==='product')},draft:{id:prepareDraft.id,revision:prepareDraft.revision}};
const pristine=structuredClone(work);
for(const invalid of [{...prepareInput,approval:{...approval,approvedDate:core.plusDays(core.day(),1)}},{...prepareInput,production:{...prepareInput.production,sketchVersion:'wrong'}},{...prepareInput,production:{...prepareInput.production,lines:catalogLines.map(l=>({...l,quantity:999}))}},{...prepareInput,production:{...prepareInput.production,dispatchDeadline:core.plusDays(core.day(),50)}}]){const r=await post(work,'prepare_order',invalid,'live');assert.equal(r.status,400,JSON.stringify(r.data));const current=await get('live');assert.equal(current.version,pristine.version);assert.deepEqual(current.orders,pristine.orders);assert.deepEqual(current.notices,pristine.notices);assert.equal((await draftRead(prepareDraft.id)).data[0].archived,false);}
assert.equal((await rolePost('print',await roleGet('print'),'prepare_order',prepareInput)).status,403);
// Changes to this order are detected even if the caller already knows the latest global version.
changed=await post(work,'order',{...guided,deliveryDate:core.plusDays(guided.deliveryDate,1)},'live');assert.equal(changed.status,200);work=changed.data;assert.equal((await post(work,'prepare_order',prepareInput,'live')).status,409);guided=work.orders.find(o=>o.id===guided.id);prepareInput={...prepareInput,expectedOrder:orderWork.orderBasis(guided),approval:{...approval,deliveryDate:guided.deliveryDate}};
// A draft write between validation and commit must stop the whole handoff transaction.
const normalBatch=globalThis.__crmEnv.DB.batch;let injectDraftRace=true;globalThis.__crmEnv.DB.batch=async statements=>{if(injectDraftRace){injectDraftRace=false;sqlite.prepare('UPDATE crm_drafts SET revision=revision+1 WHERE space=? AND user_id=? AND id=?').run('live','test-admin',prepareDraft.id);}return normalBatch(statements)};
const versionBeforeRace=work.version;changed=await post(work,'prepare_order',prepareInput,'live');globalThis.__crmEnv.DB.batch=normalBatch;assert.equal(changed.status,409);work=await get('live');assert.equal(work.version,versionBeforeRace);assert.equal(work.orders.find(o=>o.id===guided.id).production.status,'draft');assert.equal((await draftRead(prepareDraft.id)).data[0].archived,false);
prepareDraft=(await draftRead(prepareDraft.id)).data[0];prepareInput={...prepareInput,draft:{id:prepareDraft.id,revision:prepareDraft.revision}};const noticesBefore=work.notices.length,prepareBefore=work;changed=await post(work,'prepare_order',prepareInput,'live');assert.equal(changed.status,200,JSON.stringify(changed.data));work=changed.data;guided=work.orders.find(o=>o.id===guided.id);assert.equal(work.version,prepareBefore.version+1);assert.equal(guided.production.status,'submitted');assert.equal(guided.proofApproved,true);assert.equal(guided.production.sketchFileId,uploaded.id);assert.equal(guided.production.deliveryAddress.street,'Eventgatan 3');assert.equal(work.customers.find(c=>c.id===cust.id).deliveryAddress.street,'Lagervägen 2');assert.equal(work.notices.length,noticesBefore+2);assert.equal((await draftRead(prepareDraft.id)).data[0].archived,true);assert.equal((await post(prepareBefore,'prepare_order',prepareInput,'live',changed.id)).status,200);assert.equal((await get('live')).notices.length,noticesBefore+2);
console.log('PASS: accepted draft-to-order, rollback without losing drafts, precise proof/deadline/quantity gates, same-order conflict detection, concurrent draft-versus-submit rollback, one atomic print handoff and immutable shipping snapshot.');

// Shipment remains actionable after invoicing. Legacy dispatched orders receive durable backfill.
work=await get('live');let receiptOrder=work.orders.find(o=>o.id===productionOrder.id);assert.equal(receiptOrder.invoiceValue,1300);let receiptTask=work.tasks.find(t=>t.kind==='receipt'&&t.dealId===receiptOrder.dealId);assert.ok(receiptTask&&!receiptTask.done);assert.ok(orderWork.awaitingReceipt(receiptOrder));
sqlite.prepare('DELETE FROM crm_tasks WHERE space=? AND id=?').run('live',receiptTask.id);const beforeBackfill=work.version;work=await get('live');assert.equal(work.version,beforeBackfill);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM crm_tasks WHERE space=? AND id=?').get('live',receiptTask.id).n,0);receiptTask=work.tasks.find(t=>t.kind==='receipt'&&t.dealId===receiptOrder.dealId);assert.ok(receiptTask&&!receiptTask.done);assert.equal(receiptTask.due,receiptOrder.deliveryDate);assert.equal((await get('live')).version,work.version);
assert.equal((await post(work,'task',{...receiptTask,done:true},'live')).status,400);assert.equal((await post(work,'task',{...receiptTask,kind:'manual',done:true},'live')).status,400);
const promised=receiptOrder.deliveryDate;changed=await post(work,'receipt_issue',{orderId:receiptOrder.id,message:'Transportören söker paketet',nextCheck:core.plusDays(core.day(),1)},'live');assert.equal(changed.status,200);work=changed.data;receiptOrder=work.orders.find(o=>o.id===receiptOrder.id);assert.equal(receiptOrder.deliveryDate,promised);assert.equal(receiptOrder.deliveryIssue,'Transportören söker paketet');assert.equal(work.tasks.find(t=>t.id===receiptTask.id).due,core.plusDays(core.day(),1));assert.equal(work.tasks.find(t=>t.id===receiptTask.id).done,false);assert.ok(orderWork.awaitingReceipt(receiptOrder));
const receiptInput={orderId:receiptOrder.id,receivedBy:'Anna bekräftade per telefon',note:'Hela leveransen framme',deliveredDate:core.day()};assert.equal((await post(work,'receipt_confirm',{...receiptInput,deliveredDate:core.plusDays(core.day(),1)},'live')).status,400);assert.equal((await post(work,'receipt_confirm',{...receiptInput,deliveredDate:core.plusDays(core.day(),-1)},'live')).status,400);assert.equal((await rolePost('warehouse',await roleGet('warehouse'),'receipt_confirm',receiptInput)).status,403);
const receiptBefore=work;changed=await post(work,'receipt_confirm',receiptInput,'live');assert.equal(changed.status,200,JSON.stringify(changed.data));work=changed.data;receiptOrder=work.orders.find(o=>o.id===receiptOrder.id);assert.equal(receiptOrder.deliveredDate,core.day());assert.equal(receiptOrder.receivedBy,receiptInput.receivedBy);assert.equal(receiptOrder.deliveryIssue,'');assert.equal(receiptOrder.invoiceValue,1300);assert.equal(receiptOrder.invoiceRef,'F-123');assert.equal(work.tasks.find(t=>t.id===receiptTask.id).done,true);assert.equal(orderWork.awaitingReceipt(receiptOrder),false);assert.equal(work.tasks.filter(t=>t.dealId===receiptOrder.dealId&&t.kind==='delivery').length,1);assert.equal((await post(receiptBefore,'receipt_confirm',receiptInput,'live',changed.id)).status,200);assert.equal((await post(work,'receipt_confirm',receiptInput,'live')).status,400);
// Repeat selection reuses real accepted lines, while prices and approvals need a fresh confirmation.
changed=await post(work,'repeat_order',{dealId:guidedDeal.id},'live');assert.equal(changed.status,200);work=changed.data;const repeatGuided=work.deals.find(d=>d.sourceDealId===guidedDeal.id);assert.deepEqual(repeatGuided.lines,guidedDeal.lines);assert.equal(repeatGuided.priceChecked,false);assert.equal(repeatGuided.confirmed,false);assert.equal(repeatGuided.stage,'identified');assert.equal(work.orders.some(o=>o.dealId===repeatGuided.id),false);
console.log('PASS: read-only receipt projection, dispatch stays visible after invoicing, receipt cannot be ticked away, delayed shipment gets a next check, valid actual receipt closes tracking and schedules one customer follow-up, repeat order copies accepted lines without old approval.');

// Personal dashboards must never inherit team totals or another salesperson's goals.
transpile(readFileSync('lib/sales-dashboard.ts','utf8').replace("'./crm'","'./core.mjs'"),'work/sales-dashboard.mjs');
const dashboards=await import('../work/sales-dashboard.mjs');
const metricState=core.emptyState();metricState.viewer={id:'metric-sebbe',name:'Sebbe',email:'sebbe@example.com',role:'admin',owner:'Sebastian Hansson'};
const own='Sebastian Hansson',otherOwner='Pelle Peolin',metricMonth='2026-09';metricState.settings.budgets[metricMonth]=10000;metricState.settings.annualBudgets['2026']=200000;metricState.settings.sellerGoals[own]={[metricMonth]:{revenue:200,grossProfit:80,qualified:3}};metricState.settings.sellerAnnualGoals[own]={'2026':1000};
metricState.orders=[{id:'metric-1',owner:own,invoiceValue:100,actualCost:60,invoiceDate:'2026-09-03'},{id:'metric-2',owner:own,invoiceValue:50,actualCost:null,invoiceDate:'2026-09-04'},{id:'metric-3',owner:own,invoiceValue:300,actualCost:100,invoiceDate:'2026-08-04'},{id:'metric-other',owner:otherOwner,invoiceValue:1000,actualCost:700,invoiceDate:'2026-09-04'},{id:'metric-not-invoiced',owner:own,invoiceValue:null,actualCost:null,invoiceDate:'2026-09-01'}];
metricState.deals=[core.DealSchema.parse({id:'metric-deal',customerId:'c',owner:own,title:'Egen pipeline',stage:'identified',value:500,nextDate:core.day()}),core.DealSchema.parse({id:'metric-other-deal',customerId:'c',owner:otherOwner,title:'Annan pipeline',value:900,nextDate:core.day()})];
metricState.customers=[core.CustomerSchema.parse({id:'metric-qualified',name:'Kvalificerad vid månadsskiftet',owner:otherOwner,prospecting:{qualifiedOwner:own,qualifiedAt:'2026-08-31T22:30:00.000Z'}})];
metricState.tasks=[core.TaskSchema.parse({id:'own-task',customerId:'c',owner:own,title:'Egen uppgift',due:core.day()}),core.TaskSchema.parse({id:'other-task',customerId:'c',owner:otherOwner,title:'Annans uppgift',due:core.day()})];
assert.equal(dashboards.personalOwner(metricState),own);let measured=dashboards.salesMetrics(metricState,metricMonth,dashboards.personalOwner(metricState));assert.equal(measured.revenue,150);assert.equal(measured.target,200);assert.equal(measured.profit,40);assert.equal(measured.margin,40);assert.equal(measured.known.length,1);assert.equal(measured.invoices.length,2);assert.equal(measured.yearRevenue,450);assert.equal(measured.yearTarget,1000);assert.equal(measured.pipeline,500);assert.equal(measured.qualified,1);assert.deepEqual(measured.tasks.map(t=>t.id),['own-task']);
const teamMeasured=dashboards.salesMetrics(metricState,metricMonth,'all');assert.equal(teamMeasured.revenue,1150);assert.equal(teamMeasured.target,10000);assert.equal(teamMeasured.yearRevenue,1450);assert.equal(teamMeasured.yearTarget,200000);assert.equal(teamMeasured.pipeline,1400);
metricState.viewer={...metricState.viewer,owner:otherOwner,name:'Pelle Peolin'};measured=dashboards.salesMetrics(metricState,metricMonth,dashboards.personalOwner(metricState));assert.equal(measured.revenue,1000);assert.equal(measured.target,null);assert.equal(measured.yearTarget,null);assert.equal(measured.pipeline,900);
metricState.viewer.owner='';assert.equal(dashboards.personalOwner(metricState),'');assert.equal(dashboards.salesMetrics(metricState,metricMonth,dashboards.personalOwner(metricState)).revenue,0);assert.equal(dashboards.salesMetrics(metricState,metricMonth,'').tasks.length,0);metricState.viewer.owner='Removed salesperson';assert.equal(dashboards.personalOwner(metricState),'');
delete metricState.settings.sellerAnnualGoals[own]['2026'];assert.equal(dashboards.salesMetrics(metricState,metricMonth,own).yearTarget,null);assert.equal(dashboards.salesMetrics(metricState,metricMonth,own).configuredMonths,1);
metricState.settings.sellerGoals[own]=Object.fromEntries(Array.from({length:12},(_,i)=>['2026-'+String(i+1).padStart(2,'0'),{revenue:100,grossProfit:null,qualified:null}]));assert.equal(dashboards.salesMetrics(metricState,metricMonth,own).yearTarget,1200);metricState.settings.sellerAnnualGoals[own]['2026']=0;metricState.settings.sellerGoals[own][metricMonth].revenue=0;assert.equal(dashboards.salesMetrics(metricState,metricMonth,own).yearTarget,0);assert.equal(dashboards.salesMetrics(metricState,metricMonth,own).target,0);
work=await get('live');changed=await post(work,'settings',{...work.settings,sellerAnnualGoals:{[own]:{'2026':2500000},[otherOwner]:{'2026':1500000}}},'live');assert.equal(changed.status,200);assert.equal((await get('live')).settings.sellerAnnualGoals[own]['2026'],2500000);assert.deepEqual((await roleGet('print')).settings.sellerAnnualGoals,{});
console.log('PASS: account-bound personal metrics for Sebbe/Pelle, no fallback to team without a linked profile, separate team/individual month and year goals, incomplete costs use the correct margin denominator, Swedish qualification month, explicit zero goals, incomplete annual targets and persistent personal annual goals.');

// Release 10: record guards survive a conflict retry with a newer workspace revision.
const rawPost=async(state,type,data,basis,requestId=crypto.randomUUID())=>{const r=await api.POST(new Request('https://crm.test/api/crm',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:'https://crm.test'},body:JSON.stringify({space:'live',version:state.version,requestId,type,data,expectedRecord:basis})}));return {status:r.status,data:await r.json(),id:requestId}};
work=await get('live');const baseCustomer=structuredClone(work.customers[0]),baseRecord=conflicts.recordBasis(baseCustomer),beforeEdit=work;
changed=await rawPost(work,'customer',{...baseCustomer,email:'new-email@example.com'},baseRecord);assert.equal(changed.status,200);work=changed.data;
const staleCustomer={...baseCustomer,phone:'0701112223'};
assert.equal((await rawPost(beforeEdit,'customer',staleCustomer,baseRecord)).status,409);
assert.equal((await rawPost(work,'customer',staleCustomer,baseRecord)).status,409);
assert.equal((await rawPost(work,'customer',staleCustomer,undefined)).status,409);
assert.equal((await get('live')).customers[0].email,'new-email@example.com');
const freshCustomer=work.customers[0];changed=await rawPost(work,'customer',{...freshCustomer,phone:staleCustomer.phone},conflicts.recordBasis(freshCustomer));assert.equal(changed.status,200);work=changed.data;assert.equal(work.customers[0].email,'new-email@example.com');assert.equal(work.customers[0].phone,staleCustomer.phone);
const sameCustomer=structuredClone(work.customers[0]),sameBasis=conflicts.recordBasis(sameCustomer),beforeUnrelated=work;
changed=await post(work,'customer_note',{customerId:sameCustomer.id,text:'Orelaterad anteckning utan kundändring'},'live');assert.equal(changed.status,200);work=changed.data;
changed=await rawPost(beforeUnrelated,'customer',{...sameCustomer,segment:'Bygg'},sameBasis);assert.equal(changed.status,200);const guardRequest=changed.id,guardEvents=changed.data.events.length;assert.equal((await rawPost(work,'customer',{...sameCustomer,segment:'Bygg'},sameBasis,guardRequest)).data.events.length,guardEvents);work=changed.data;
assert.ok(work.events.some(e=>e.customerId===sameCustomer.id&&e.text.includes('E-post:')&&e.text.includes('new-email@example.com')));
// Prefilled stage movement uses the saved record as its basis, not the proposed stage.
assert.notEqual(conflicts.recordBasis(core.seedState().deals[0]),conflicts.recordBasis({...core.seedState().deals[0],stage:'contact'}));
console.log('PASS: immutable record basis, missing-basis rejection, conflict retry cannot overwrite a colleague, unrelated changes can retry, idempotency and before/after audit.');

// The deal controls the one open next activity; finishing it does not recreate it on a text edit.
const activityInput=core.DealSchema.parse({customerId:cust.id,owner:own,title:'Test nästa aktivitet',stage:'quoted',need:'Behov',decisionMaker:'Inköpare',solution:'Jackor',value:1000,cost:500,quoteRef:'NEXT-1',decisionDate:core.day(),deliveryDate:core.plusDays(core.day(),30),nextAction:'Följ upp priset',nextDate:core.plusDays(core.day(),2)});
changed=await post(work,'deal',activityInput,'live');assert.equal(changed.status,200,JSON.stringify(changed.data));work=changed.data;let ad=work.deals.find(d=>d.title===activityInput.title),atask=work.tasks.find(t=>t.dealId===ad.id&&t.kind==='quote'&&!t.done);
changed=await post(work,'deal',{...ad,nextAction:'Ring inköparen',nextDate:core.plusDays(core.day(),10),owner:otherOwner},'live');assert.equal(changed.status,200);work=changed.data;ad=work.deals.find(d=>d.id===ad.id);let ats=work.tasks.filter(t=>t.dealId===ad.id&&t.kind==='quote'&&!t.done);assert.equal(ats.length,1);assert.equal(ats[0].id,atask.id);assert.equal(ats[0].due,ad.nextDate);assert.equal(ats[0].owner,otherOwner);assert.equal(ats[0].title,ad.nextAction);
assert.equal((await post(work,'task',{...ats[0],due:core.plusDays(core.day(),20)},'live')).status,400);
changed=await post(work,'task',{...ats[0],done:true},'live');assert.equal(changed.status,200);work=changed.data;
changed=await post(work,'deal',{...ad,need:'Förtydligat behov'},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.tasks.filter(t=>t.dealId===ad.id&&t.kind==='quote'&&!t.done).length,0);ad=work.deals.find(d=>d.id===ad.id);
changed=await post(work,'deal',{...ad,nextDate:core.plusDays(core.day(),11)},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.tasks.filter(t=>t.dealId===ad.id&&t.kind==='quote'&&!t.done).length,1);ad=work.deals.find(d=>d.id===ad.id);
changed=await post(work,'deal',{...ad,stage:'costing'},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.tasks.filter(t=>t.dealId===ad.id&&t.kind==='quote'&&!t.done).length,0);assert.equal(work.tasks.filter(t=>t.dealId===ad.id&&t.kind==='discovery'&&!t.done).length,1);
console.log('PASS: quote date/title/owner stay aligned, no duplicate or resurrected completed follow-up, direct date bypass blocked and backward stage movement changes activity.');

// Two sizes of the same SKU stay distinct through purchase, partial print and two shipments.
const qLines=['M','L'].map((size,i)=>business.LineSchema.parse({id:'q-'+size,sourceId:'current',article:'Q-1',description:'Profilpiké',color:'Svart',size,variantId:'Q-1-SVART-'+size,quantity:10,unitPrice:150,unitCost:70}));
changed=await post(work,'article_import',{articles:qLines.map(l=>({sourceId:l.sourceId,sku:l.article,name:l.description,color:l.color,size:l.size,variantId:l.variantId,price:l.unitPrice,cost:l.unitCost}))},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.articles.filter(a=>a.sku==='Q-1').length,2);
changed=await post(work,'catalog_order',{...catalogInput,title:'Två storlekar – delleverans',lines:qLines},'live');assert.equal(changed.status,200);work=changed.data;const qDeal=work.deals.find(d=>d.title==='Två storlekar – delleverans');let qOrder=work.orders.find(o=>o.dealId===qDeal.id);
const qPrepare={orderId:qOrder.id,expectedOrder:orderWork.orderBasis(qOrder),approval:{...approval,deliveryDate:qOrder.deliveryDate},deliveryAddress:prepareInput.deliveryAddress,production:{...productionData.production,lines:qLines}};
assert.equal((await post(work,'prepare_order',{...qPrepare,production:{...qPrepare.production,lines:qLines.map(l=>({...l,size:'XL'}))}},'live')).status,400);
changed=await post(work,'prepare_order',qPrepare,'live');assert.equal(changed.status,200);work=changed.data;qOrder=work.orders.find(o=>o.id===qOrder.id);const qInitial=structuredClone(qOrder.production),qAddress=qOrder.production.deliveryAddress;
const invalidInputs=[[],[{lineId:'q-M',quantity:0}],[{lineId:'q-M',quantity:-1}],[{lineId:'q-M',quantity:11}],[{lineId:'unknown',quantity:1}],[{lineId:'q-M',quantity:1},{lineId:'q-M',quantity:1}],[{lineId:'q-M',quantity:1},{lineId:'q-L',quantity:11}]];
for(const entries of invalidInputs){assert.equal((await post(work,'production_received',{orderId:qOrder.id,entries},'live')).status,400);assert.equal((await get('live')).version,work.version);assert.deepEqual((await get('live')).orders.find(o=>o.id===qOrder.id).production,qInitial);}
assert.equal((await rawPost(work,'production_received',{orderId:qOrder.id},undefined)).status,409);
const qBefore=work;changed=await post(work,'production_received',{orderId:qOrder.id,entries:[{lineId:'q-M',quantity:10}]},'live');assert.equal(changed.status,200);const qRequest=changed.id;work=changed.data;qOrder=work.orders.find(o=>o.id===qOrder.id);assert.equal(qOrder.production.goodsReceived,false);assert.deepEqual(quantities.productionProgress(qOrder.production).map(r=>r.received),[10,0]);
assert.equal((await post(qBefore,'production_received',{orderId:qOrder.id,entries:[{lineId:'q-M',quantity:10}]},'live',qRequest)).data.orders.find(o=>o.id===qOrder.id).production.movements.length,1);
assert.equal((await post(work,'production_received',{orderId:qOrder.id,expectedProduction:quantities.productionBasis(qInitial),entries:[{lineId:'q-L',quantity:1}]},'live')).status,409);
assert.equal((await post(work,'production_cancel',{orderId:qOrder.id,message:'Nytt original'},'live')).status,400);
assert.equal((await post(work,'production_printed',{orderId:qOrder.id,entries:[{lineId:'q-L',quantity:1}]},'live')).status,400);
assert.equal((await post(work,'production_dispatched',{orderId:qOrder.id,entries:[{lineId:'q-M',quantity:1}],address:qAddress},'live')).status,400);
changed=await post(work,'production_printed',{orderId:qOrder.id,entries:[{lineId:'q-M',quantity:10}]},'live');assert.equal(changed.status,200);work=changed.data;
changed=await post(work,'production_dispatched',{orderId:qOrder.id,entries:[{lineId:'q-M',quantity:10}],address:qAddress,tracking:'PART-1',recipient:'Arbetsplats A'},'live');assert.equal(changed.status,200);work=changed.data;qOrder=work.orders.find(o=>o.id===qOrder.id);assert.equal(qOrder.production.status,'submitted');assert.equal(qOrder.stage,'production');assert.equal(qOrder.production.dispatchedAt,'');assert.equal(work.tasks.filter(t=>t.dealId===qDeal.id&&['receipt','invoice_ready'].includes(t.kind)).length,0);
assert.equal((await post(work,'order',{...qOrder,invoiceValue:3000,invoiceRef:'EARLY',invoiceDate:core.day()},'live')).status,400);assert.equal((await post(work,'receipt_confirm',{orderId:qOrder.id,deliveredDate:core.day(),receivedBy:'För tidigt'},'live')).status,400);
changed=await post(work,'order',{...qOrder,production:{...qOrder.production,status:'dispatched',movements:[]}},'live');assert.equal(changed.status,200);work=changed.data;assert.equal(work.orders.find(o=>o.id===qOrder.id).production.movements.length,3);
for(const [type,n] of [['received',4],['received',6],['printed',10],['dispatched',10]]){changed=await post(work,'production_'+type,{orderId:qOrder.id,entries:[{lineId:'q-L',quantity:n}],address:{...qAddress,reference:'Arbetsplats B'},tracking:type==='dispatched'?'PART-2':''},'live');assert.equal(changed.status,200,JSON.stringify(changed.data));work=changed.data;}
qOrder=work.orders.find(o=>o.id===qOrder.id);assert.equal(qOrder.production.status,'dispatched');assert.equal(qOrder.stage,'shipping');assert.equal(qOrder.production.goodsReceived,true);assert.equal(work.tasks.filter(t=>t.dealId===qDeal.id&&t.kind==='invoice_ready').length,1);assert.equal(work.tasks.filter(t=>t.dealId===qDeal.id&&t.kind==='receipt').length,1);assert.deepEqual(qOrder.production.movements.filter(m=>m.kind==='dispatched').map(m=>m.tracking),['PART-1','PART-2']);assert.ok(quantities.productionProgress(qOrder.production).every(r=>r.remaining===0));
changed=await post(work,'repeat_order',{dealId:qDeal.id},'live');assert.equal(changed.status,200);work=changed.data;const qRepeat=work.deals.find(d=>d.sourceDealId===qDeal.id);assert.equal(qRepeat.repeatRecipe.sketchFileId,uploaded.id);assert.equal(qRepeat.repeatRecipe.instructions,qOrder.production.instructions);assert.equal(qRepeat.repeatRecipe.sourceWorkId,qOrder.production.workId);assert.equal(qRepeat.confirmed,false);assert.equal(qRepeat.priceChecked,false);assert.deepEqual(qRepeat.lines,qLines);
console.log('PASS: size-aware identity and order lock, per-row limits/atomic rollback, partial receive/print/dispatch, stale quantity retries, one final invoice/receipt task, immutable history and reusable production recipe without approvals.');

// Legacy progress is deterministic and large normal orders cannot poison notice parsing.
const legacyProduction=ops.ProductionSchema.parse({lines:qLines.map(l=>({...l,id:''})),status:'printed',goodsReceived:true,submittedAt:'2026-09-01T10:00:00Z',printedAt:'2026-09-02T10:00:00Z',printedBy:'Tidigare tryckare'});
quantities.normalizeProduction(legacyProduction);assert.equal(new Set(legacyProduction.lines.map(l=>l.id)).size,2);assert.ok(quantities.productionProgress(legacyProduction).every(r=>r.printed===10&&r.dispatched===0));quantities.materializeLegacy(legacyProduction);const legacyOnce=structuredClone(legacyProduction);quantities.materializeLegacy(legacyProduction);assert.deepEqual(legacyProduction,legacyOnce);assert.equal(legacyProduction.movements[1].by,'Tidigare tryckare');
const many=structuredClone(work),manyOrder=many.orders.find(o=>o.id===qOrder.id);manyOrder.production=ops.ProductionSchema.parse({...qInitial,workId:'large-order',lines:Array.from({length:100},(_,i)=>business.LineSchema.parse({...qLines[0],id:'many-'+i,description:'Profilpiké med brodyr och individuellt artikelutförande',quantity:1}))});manyOrder.stage='production';
let manyNext=many;for(const kind of ['received','printed','dispatched']){const pp=manyNext.orders.find(o=>o.id===qOrder.id).production;manyNext=core.applyAction(manyNext,{type:'production_'+kind,data:{orderId:qOrder.id,expectedProduction:quantities.productionBasis(pp),entries:pp.lines.map(l=>({lineId:l.id,quantity:1})),address:qAddress}},{id:'test-admin',name:'Test',role:'admin',owner:own});assert.doesNotThrow(()=>core.normalizeState(structuredClone(manyNext)));assert.ok(manyNext.notices.every(n=>n.body.length<=4000));}
const refs=await import('../work/export-references.mjs');assert.ok(refs.collectFileReferences(work).some(r=>r.id===uploaded.id));
const exportBase=core.emptyState();exportBase.customers=[core.CustomerSchema.parse({id:'restore-c',name:'Återställningstest',owner:own})];exportBase.deals=[core.DealSchema.parse({id:'restore-d',customerId:'restore-c',owner:own,title:'Historisk order'})];exportBase.orders=[core.OrderSchema.parse({...qOrder,id:'restore-o',customerId:'restore-c',dealId:'restore-d',proofFileId:'',production:{},productionHistory:[]})];
for(const field of ['proof','production','history','recipe']){const bad=structuredClone(exportBase);if(field==='proof')bad.orders[0].proofFileId='missing-file';if(field==='production')bad.orders[0].production.sketchFileId='missing-file';if(field==='history')bad.orders[0].productionHistory=[ops.ProductionSchema.parse({sketchFileId:'missing-file'})];if(field==='recipe')bad.deals[0].repeatRecipe={sourceOrderId:'restore-o',sourceWorkId:'',instructions:'Test',sketchFileId:'missing-file',sketchVersion:'v1'};assert.equal(refs.collectFileReferences(bad).length,1);}
// Exercise restore rejection in the existing isolated database, never in hosted data.
for(const table of ['crm_files','crm_orders','crm_tasks','crm_meetings','crm_events','crm_deals','crm_customers','crm_articles','crm_notices','crm_leads','crm_company_events'])sqlite.prepare('DELETE FROM '+table+' WHERE space=?').run('demo');
const restoreEmpty=await get('demo');for(const field of ['proof','production','history','recipe']){const bad=structuredClone(exportBase);if(field==='proof')bad.orders[0].proofFileId='missing-file';if(field==='production')bad.orders[0].production.sketchFileId='missing-file';if(field==='history')bad.orders[0].productionHistory=[ops.ProductionSchema.parse({sketchFileId:'missing-file'})];if(field==='recipe')bad.deals[0].repeatRecipe={sourceOrderId:'restore-o',sourceWorkId:'',instructions:'Test',sketchFileId:'missing-file',sketchVersion:'v1'};const rejected=await post(restoreEmpty,'restore',{format:'magnussons-crm-1',state:bad},'demo');assert.equal(rejected.status,400);assert.match(rejected.data.error,/kundfiler/);assert.equal((await get('demo')).customers.length,0);assert.equal((await get('demo')).version,restoreEmpty.version);}
console.log('PASS: deterministic legacy quantities, 100-row receive/print/dispatch notifications remain readable, and data-only restore rejects missing proof/production/history/recipe files atomically.');
// Old cancelled work with physical quantities cannot be silently reset on resubmission.
const cancelledState=structuredClone(many),cancelledOrder=cancelledState.orders.find(o=>o.id===qOrder.id);cancelledOrder.production=ops.ProductionSchema.parse({...qInitial,status:'cancelled',quantityMode:'legacy',goodsReceived:true,printedAt:'2026-09-01T10:00:00Z'});cancelledOrder.stage='handover';
assert.throws(()=>core.applyAction(cancelledState,{type:'production_submit',data:{orderId:cancelledOrder.id,production:{...productionData.production,lines:qLines}}},{id:'test-admin',name:'Test',role:'admin',owner:own}),/registrerade varor/);
const tinyState=structuredClone(cancelledState),tinyOrder=tinyState.orders.find(o=>o.id===qOrder.id);tinyOrder.production=ops.ProductionSchema.parse({});tinyOrder.stage='handover';
assert.throws(()=>core.applyAction(tinyState,{type:'production_submit',data:{orderId:tinyOrder.id,production:{...productionData.production,lines:[{...qLines[0],quantity:0.0000001},qLines[1]]}}},{id:'test-admin',name:'Test',role:'admin',owner:own}),/sex decimaler/);
console.log('PASS: old cancelled physical work cannot reset quantities; new sub-precision product rows cannot appear fully delivered without a movement.');

// Focused follow-up is one transaction and cannot complete production/business gates.
const followups=await import('../work/follow-up.mjs');
let fu=await get('live');const fuCustomer=fu.customers.find(c=>c.id===cust.id);
let fuResult=await post(fu,'deal',core.DealSchema.parse({customerId:fuCustomer.id,owner:own,title:'Uppföljning utan full affärsredigering',nextAction:'Stäm av önskemål',nextDate:core.day()}),'live');assert.equal(fuResult.status,200);fu=fuResult.data;
const fuDeal=fu.deals.find(d=>d.title==='Uppföljning utan full affärsredigering'),fuTask=fu.tasks.find(t=>t.dealId===fuDeal.id&&!t.done);
const fuPayload={taskId:fuTask.id,expectedContext:followups.followupBasis(fu,fuTask.id),outcome:'contact',occurredOn:core.day(),note:'Kunden önskar ett nytt prisförslag.',completed:true,nextAction:fuTask.title,nextDate:fuTask.due};
const fuBefore=fu;fuResult=await post(fu,'follow_up',fuPayload,'live');assert.equal(fuResult.status,200,JSON.stringify(fuResult.data));fu=fuResult.data;
assert.equal(fu.tasks.find(t=>t.id===fuTask.id).done,true);let fuNext=fu.tasks.find(t=>t.dealId===fuDeal.id&&!t.done);assert.ok(fuNext);assert.notEqual(fuNext.id,fuTask.id);assert.equal(fu.tasks.filter(t=>t.dealId===fuDeal.id&&!t.done).length,1);assert.equal(fu.customers.find(c=>c.id===fuCustomer.id).lastContact,core.day());assert.equal(fu.customers.find(c=>c.id===fuCustomer.id).nextReview,fuCustomer.nextReview);
const fuReplay=await post(fuBefore,'follow_up',fuPayload,'live',fuResult.id);assert.equal(fuReplay.status,200);assert.equal(fuReplay.data.events.length,fu.events.length);assert.equal(fuReplay.data.tasks.length,fu.tasks.length);
const historic=core.applyAction(fu,{type:'customer',data:{...fu.customers.find(c=>c.id===fuCustomer.id),lastContact:core.plusDays(core.day(),-10)}});
const noReply={...fuPayload,taskId:fuNext.id,expectedContext:followups.followupBasis(fu,fuNext.id),outcome:'no_reply',note:'Inget svar. Försöker imorgon.',completed:false,nextAction:'Ring igen',nextDate:core.plusDays(core.day(),1)};
const attempted=core.applyAction(historic,{type:'follow_up',data:noReply});assert.equal(attempted.customers.find(c=>c.id===fuCustomer.id).lastContact,core.plusDays(core.day(),-10));assert.equal(attempted.customers.find(c=>c.id===fuCustomer.id).nextReview,fuCustomer.nextReview);
fuResult=await post(fu,'follow_up',noReply,'live');assert.equal(fuResult.status,200);fu=fuResult.data;assert.equal(fu.customers.find(c=>c.id===fuCustomer.id).lastContact,core.day());assert.equal(fu.tasks.find(t=>t.id===fuNext.id).done,false);assert.equal(fu.tasks.find(t=>t.id===fuNext.id).due,noReply.nextDate);assert.equal(fu.deals.find(d=>d.id===fuDeal.id).nextAction,'Ring igen');assert.equal(fu.deals.find(d=>d.id===fuDeal.id).stage,fuDeal.stage);
// A fresh workspace version must not silently rebase an old focused dialog.
const staleFu=await post(fu,'follow_up',{...noReply,note:'Osparad anteckning efter konflikt'},'live');assert.equal(staleFu.status,409);assert.equal((await get('live')).version,fu.version);
const gateTask=fu.tasks.find(t=>t.kind==='receipt');assert.ok(gateTask);const invalidFollow={...fuPayload,taskId:gateTask.id,expectedContext:followups.followupBasis(fu,gateTask.id)};assert.equal((await post(fu,'follow_up',invalidFollow,'live')).status,400);assert.equal((await get('live')).version,fu.version);
assert.equal((await post(fu,'follow_up',{...noReply,expectedContext:followups.followupBasis(fu,fuNext.id),occurredOn:core.plusDays(core.day(),1)},'live')).status,400);
assert.equal((await post(fu,'follow_up',{...noReply,expectedContext:followups.followupBasis(fu,fuNext.id),nextAction:'',nextDate:''},'live')).status,400);
console.log('PASS: atomic focused follow-up, explicit completion and same-step continuation, idempotent retry, no-reply rescheduling, canonical deal sync, stale context conflict and business-gate protection.');

await (await import('./v12.mjs')).verifyV12({core,ops,business,quantities,sqlite,objects,headers,get,post,rolePost,roleGet,draftWrite,draftRead,catalogInput,productionData,own,cust});

await (await import('./v13.mjs')).verifyV13({core,ops,business,quantities,sqlite,objects,headers,get,post,rolePost,roleGet,roleHeaders,draftRead,catalogInput,productionData,own,cust,fileApi});
