import assert from 'node:assert/strict';

// Pure synthetic domain fixtures. Authenticated SQLite/Worker checks own the
// transactional membership, request replay and private-store boundaries.
export async function verifyCustomerReopen({core,business,ops}){
 const reopen=await import('../work/customer-reopen.mjs'),sellers=await import('../work/seller-profiles.mjs'),responsibility=await import('../work/customer-responsibility.mjs'),commercial=await import('../work/commercial-responsibility.mjs'),retirement=await import('../work/seller-profile-retirement.mjs'),dashboards=await import('../work/sales-dashboard.mjs');
 business ||= await import('../work/business.mjs');ops ||= await import('../work/operations.mjs');
 const ids={a:'56000000-0000-4000-8000-000000000001',b:'56000000-0000-4000-8000-000000000002',c:'56000000-0000-4000-8000-000000000003'};
 const owners={a:'Syntetiskt tidigare kundansvar A',b:'Syntetiskt valt kundansvar B',c:'Syntetiskt annat kundansvar C'};
 const actor={id:'synthetic-reopen-admin-user',memberId:'synthetic-reopen-admin-member',name:'Syntetisk återöppningsadmin',role:'admin',owner:''};
 const customerId='synthetic-reopen-customer',today=core.day(),future=core.plusDays(today,3),past=core.plusDays(today,-7),at=past+'T09:00:00.000Z',month=today.slice(0,7);
 function base({activeSource=false,legacy=false}={}){
  const st=core.emptyState();st.settings.owners=activeSource?[owners.a,owners.b,owners.c]:[owners.b,owners.c];st.settings.sellerProfilesInitialized=true;
  st.settings.sellerProfiles=Object.keys(ids).map(key=>sellers.SellerProfileSchema.parse({id:ids[key],legacyOwnerName:owners[key],displayName:'Samma syntetiska profilnamn',active:key!=='a'||activeSource,memberId:'synthetic-reopen-member-'+key,linkHistory:[{previousMemberId:'',nextMemberId:'synthetic-reopen-member-'+key,reason:'Syntetisk tidigare kontokoppling',at,byId:actor.id,byName:actor.name}],retirementHistory:key==='a'&&!activeSource&&!legacy?[{id:'56000000-0000-4000-8000-000000000004',profileId:ids.a,owner:owners.a,displayName:'Syntetiskt dåvarande profilnamn',reason:'Syntetiskt tidigare granskat profilavslut',at,byId:actor.id,byMemberId:actor.memberId,byName:actor.name}]:[]}));
  st.settings.sellerGoals[owners.a]={[month]:{revenue:5000,grossProfit:null,qualified:2}};st.settings.sellerGoalsById[ids.a]=structuredClone(st.settings.sellerGoals[owners.a]);st.settings.sellerAnnualGoals[owners.a]={[today.slice(0,4)]:50000};st.settings.sellerAnnualGoalsById[ids.a]=structuredClone(st.settings.sellerAnnualGoals[owners.a]);
  const prior=responsibility.CustomerResponsibilityHistorySchema.parse({id:'56000000-0000-4000-8000-000000000005',customerId,fromProfileId:ids.c,toProfileId:ids.a,fromOwner:owners.c,toOwner:owners.a,selectedTaskIds:[],reason:'Syntetisk tidigare kundöverlämning',at,byId:actor.id,byMemberId:actor.memberId,byName:actor.name});
  st.customers=[core.CustomerSchema.parse({id:customerId,name:'Syntetisk historisk återöppningskund',owner:owners.a,ownerProfileId:ids.a,status:'closed',responsibilityTransfers:[prior],contact:'Syntetisk kontakt',email:'synthetic-contact@example.test',lastContact:past,nextReview:past,expectedOrder:future,organizationNumber:'SYNTHETIC-ORG-56',fortnoxNumber:'SYNTHETIC-FORTNOX',billingAddress:{street:'Syntetisk fakturagata',city:'Syntetisk stad'},deliveryAddress:{street:'Syntetisk leveransgatan'},sites:[{id:'synthetic-reopen-site',name:'Syntetisk leveransplats'}],prospecting:{stage:'qualified',qualifiedAt:at,qualifiedOwner:owners.a,qualifiedOwnerId:ids.a,nextAction:'Syntetisk tidigare bearbetning',nextDate:past,convertedDealId:'synthetic-reopen-won'},onboarding:{owner:owners.a,ownerProfileId:ids.a,dealId:'synthetic-reopen-won',startedAt:at,completedAt:at,due:past,feedback:'Syntetisk tidigare första leverans'},plan:{issue:'Syntetiskt tidigare löst ärende',issueStatus:'resolved',issueOwner:owners.a,issueOwnerProfileId:ids.a,nextAction:'Syntetisk befintlig kundplan',nextDate:future,contacts:[{name:'Syntetisk ytterligare kontakt',role:'Syntetisk roll'}]},yearNeeds:[business.NeedSchema.parse({id:'synthetic-reopen-need-history',title:'Syntetiskt avslutat behov',owner:owners.a,ownerProfileId:ids.a,due:past,status:'done',completedAt:at}),business.NeedSchema.parse({id:'synthetic-reopen-need-other',title:'Syntetiskt separat kvarvarande behov',owner:owners.b,ownerProfileId:ids.b,due:future,status:'planned'})],products:[business.ProductSchema.parse({id:'synthetic-reopen-product',description:'Syntetiskt historiskt produktunderlag',marking:'Syntetiskt tidigare tryck'})]}),core.CustomerSchema.parse({id:'synthetic-reopen-other-customer',name:'Syntetisk annan kund',owner:owners.c,ownerProfileId:ids.c,status:'active'})];
  st.deals=[core.DealSchema.parse({id:'synthetic-reopen-won',customerId,owner:owners.a,ownerProfileId:ids.a,title:'Syntetisk historisk vunnen affär',stage:'won',confirmed:true,wonAt:at,value:1000,cost:600}),core.DealSchema.parse({id:'synthetic-reopen-lost',customerId,owner:owners.a,ownerProfileId:ids.a,title:'Syntetisk historisk förlorad affär',stage:'lost',reason:'Syntetisk historisk förlustorsak'})];
  st.orders=[core.OrderSchema.parse({id:'synthetic-reopen-order-history',customerId,dealId:'synthetic-reopen-won',owner:owners.a,ownerProfileId:ids.a,stage:'followed',proofRequired:false,proofApproved:false,supplierConfirmed:true,notes:'Syntetiska historiska ordervillkor',deliveryDate:past,deliveredDate:past,invoiceRef:'SYNTHETIC-REOPEN-INVOICE',invoiceDate:today,invoiceValue:1000,actualCost:600,invoiceOwner:owners.a,invoiceOwnerId:ids.a,invoiceOwnerSource:'recorded'})];
  st.tasks=[core.TaskSchema.parse({id:'synthetic-reopen-old-care-done',customerId,owner:owners.a,ownerProfileId:ids.a,title:'Syntetisk avslutad kundkontakt',due:past,kind:'care',done:true,doneAt:at}),core.TaskSchema.parse({id:'synthetic-reopen-old-care-open',customerId,owner:owners.b,ownerProfileId:ids.b,title:'Syntetisk redan öppen care-uppgift',due:future,kind:'care'}),core.TaskSchema.parse({id:'synthetic-reopen-old-quote-done',customerId,dealId:'synthetic-reopen-won',owner:owners.a,ownerProfileId:ids.a,title:'Syntetisk historisk offertuppgift',due:past,kind:'quote',done:true,doneAt:at})];
  st.meetings=[core.MeetingSchema.parse({id:'synthetic-reopen-old-meeting-done',customerId,owner:owners.a,ownerProfileId:ids.a,title:'Syntetiskt historiskt möte',date:past,time:'10:00',duration:30,status:'done'}),core.MeetingSchema.parse({id:'synthetic-reopen-other-planned',customerId,owner:owners.b,ownerProfileId:ids.b,title:'Syntetiskt separat planerat möte',date:future,time:'11:00',duration:30,status:'planned'})];
  st.events=[{id:'synthetic-reopen-note-history',customerId,dealId:'',kind:'customer_note',at,text:'Syntetisk tidigare kundanteckning',actor:{id:'synthetic-original-user',name:'Syntetisk ursprunglig aktör'}}];
  st.companyEvents=[ops.CompanyEventSchema.parse({id:'synthetic-reopen-company-history',title:'Syntetisk avslutad företagsaktivitet',owner:owners.a,date:past,status:'done',checklist:[{id:'synthetic-reopen-company-done',title:'Syntetisk avslutad förberedelse',owner:owners.a,due:past,done:true}]})];
  return core.normalizeState(st);
 }
 const input=(st,patch={})=>({customerId,targetProfileId:ids.b,status:'active',reason:'Syntetiskt granskat nytt kundrelationsansvar',nextAction:'Planera en verklig framtida kundkontakt',nextDate:future,reviewed:true,expectedContext:reopen.customerReopenBasis(st,customerId),...patch});
 const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
 const original=base(),before=structuredClone(original),frozen=freeze(original),review=reopen.customerReopenReview(frozen,customerId),basis=reopen.customerReopenBasis(frozen,customerId);
 assert.equal(review.customer.id,customerId);assert.equal(review.sourceProfile.id,ids.a);assert.equal(review.blockedReason,'');assert.equal(review.activeBlockedReason,'');assert.deepEqual(review.targetProfiles.map(profile=>profile.id),[ids.b,ids.c]);
 assert.deepEqual(new Set(review.remainingWork.map(row=>row.kind)),new Set(['yearwheel','task','meeting']));assert.ok(review.remainingWork.every(row=>row.customerId===customerId));
 assert.deepEqual(frozen,before,'Review and basis never mutate the graph or anchor legacy IDs.');
 for(const role of ['seller','reader','production','print','warehouse'])assert.equal(reopen.customerReopenBasis({...frozen,viewer:{id:'synthetic-viewer',name:'Syntetisk visning',email:'synthetic-viewer@example.test',owner:'',role}},customerId),basis,'Client viewer does not determine review authority or frozen basis.');
 const metricsBefore=dashboards.salesMetrics(frozen,month,ids.a);
 function assertReopened(old,next,payload,{transfer=true}={}){
  const customer=next.customers.find(row=>row.id===customerId),previous=old.customers.find(row=>row.id===customerId),profile=next.settings.sellerProfiles.find(row=>row.id===payload.targetProfileId),audit=customer.responsibilityTransfers.at(-1),added=next.tasks.filter(row=>!old.tasks.some(previous=>previous.id===row.id)),event=next.events.find(row=>row.kind==='customer_reopened');
  assert.equal(next.customers.length,old.customers.length);assert.equal(customer.id,previous.id);assert.equal(added.length,1);const task=added[0];assert.match(task.id,/^[0-9a-f]{8}-[0-9a-f-]{27}$/i);
  assert.deepEqual(task,core.TaskSchema.parse({id:task.id,customerId,dealId:'',owner:profile.legacyOwnerName,ownerProfileId:profile.id,title:payload.nextAction.trim(),due:payload.nextDate,kind:'care',done:false,doneAt:'',responsibilityTransfers:[]}));
  for(const previousTask of old.tasks)assert.deepEqual(next.tasks.find(row=>row.id===previousTask.id),previousTask,'No pre-existing task is reused, reopened, transferred or completed.');
  assert.equal(next.events.length,old.events.length+1);assert.equal(next.events.filter(row=>row.kind==='customer_reopened').length,1);assert.match(event.id,/^[0-9a-f]{8}-[0-9a-f-]{27}$/i);assert.equal(new Date(event.at).toISOString(),event.at);assert.equal(event.customerId,customerId);assert.equal(event.dealId,'');assert.deepEqual(event.actor,{id:actor.id,name:actor.name});assert.ok(event.text.includes(payload.reason.trim()));assert.ok(event.text.includes(payload.status==='active'?'Aktiv kund':payload.status==='prospect'?'Prospekt':'Vilande'));assert.ok(event.text.includes(profile.id));assert.ok(event.text.includes(ids.a));
  if(transfer){assert.equal(customer.responsibilityTransfers.length,previous.responsibilityTransfers.length+1);assert.match(audit.id,/^[0-9a-f]{8}-[0-9a-f-]{27}$/i);assert.deepEqual(audit,{id:audit.id,customerId,fromProfileId:ids.a,toProfileId:profile.id,fromOwner:owners.a,toOwner:profile.legacyOwnerName,selectedTaskIds:[],reason:payload.reason.trim(),at:event.at,byId:actor.id,byMemberId:actor.memberId,byName:actor.name});}else assert.deepEqual(customer.responsibilityTransfers,previous.responsibilityTransfers,'Same active profile creates no false transfer history.');
  assert.deepEqual(customer,{...previous,status:payload.status,owner:profile.legacyOwnerName,ownerProfileId:profile.id,responsibilityTransfers:transfer?[...previous.responsibilityTransfers,audit]:previous.responsibilityTransfers});
  for(const key of ['settings','deals','orders','meetings','articles','notices','leads','companyEvents','version','viewer'])assert.deepEqual(next[key],old[key],'Reopening changes no '+key+' or historical result identity.');
  assert.deepEqual(next.customers[1],old.customers[1]);for(const historical of old.events)assert.deepEqual(next.events.find(row=>row.id===historical.id),historical);
  for(const key of ['revenue','yearRevenue','profit','margin','qualified','qualifiedTarget','target','yearTarget'])assert.equal(dashboards.salesMetrics(next,month,ids.a)[key],dashboards.salesMetrics(old,month,ids.a)[key],'Historical KPI '+key+' remains with its original seller.');
  assert.equal(dashboards.salesMetrics(next,month,profile.id).revenue,dashboards.salesMetrics(old,month,profile.id).revenue);assert.equal(dashboards.salesMetrics(next,month,profile.id).qualified,dashboards.salesMetrics(old,month,profile.id).qualified);
  assert.deepEqual(core.normalizeState(structuredClone(next)),next,'Reading the result infers no new first order, customer contact or attribution.');
 }
 for(const status of ['prospect','active','dormant'])for(const legacy of [false,true]){
  const st=base({legacy}),old=structuredClone(st),payload=input(st,{status,reason:'  Syntetisk granskningsorsak  ',nextAction:'  Syntetisk kommande kontakt  '});assert.equal(reopen.reopenCustomer(st,payload,actor),st);assertReopened(old,st,payload);assert.equal(retirement.protectRetiredSellerResponsibilities(old,st),st);assert.deepEqual(st.settings.sellerProfiles[0].retirementHistory,old.settings.sellerProfiles[0].retirementHistory);
 }
 const active=base({activeSource:true});assert.ok(reopen.customerReopenReview(active,customerId).targetProfiles.some(profile=>profile.id===ids.a),'The same already-active source profile is available.');
 for(const blank of [false,true]){const st=base({activeSource:true});if(blank)st.customers[0].ownerProfileId='';const old=structuredClone(st),payload=input(st,{targetProfileId:ids.a,nextDate:today});reopen.reopenCustomer(st,payload,actor);assertReopened(old,st,payload,{transfer:false});}
 const legacyBlank=base();legacyBlank.customers[0].ownerProfileId='';const legacyBefore=structuredClone(legacyBlank);reopen.reopenCustomer(legacyBlank,input(legacyBlank),actor);assertReopened(legacyBefore,legacyBlank,input(legacyBefore));

 // A full chain can still reopen under the same active identity, but never
 // discard a row to make room for a different customer owner.
 function fullHistory(st){st.customers[0].responsibilityTransfers=[];for(let i=0;i<1000;i++){const from=i%2?ids.c:ids.a,to=i%2?ids.a:ids.c;st.customers[0].responsibilityTransfers.push(responsibility.CustomerResponsibilityHistorySchema.parse({id:crypto.randomUUID(),customerId,fromProfileId:from,toProfileId:to,fromOwner:i%2?owners.c:owners.a,toOwner:i%2?owners.a:owners.c,selectedTaskIds:[],reason:'Syntetisk full historikkedja',at,byId:actor.id,byMemberId:actor.memberId,byName:actor.name}));}return st;}
 const fullActive=fullHistory(base({activeSource:true}));assert.deepEqual(reopen.customerReopenReview(fullActive,customerId).targetProfiles.map(profile=>profile.id),[ids.a]);const fullOld=structuredClone(fullActive);reopen.reopenCustomer(fullActive,input(fullActive,{targetProfileId:ids.a}),actor);assertReopened(fullOld,fullActive,input(fullOld,{targetProfileId:ids.a}),{transfer:false});
 const fullRetired=fullHistory(base());assert.match(reopen.customerReopenReview(fullRetired,customerId).blockedReason,/gränsen/);assert.throws(()=>reopen.reopenCustomer(fullRetired,input(fullRetired),actor),/gränsen/);
 for(const role of ['seller','reader','production','print','warehouse']){const st=base(),old=structuredClone(st);assert.throws(()=>reopen.reopenCustomer(st,input(st),{...actor,role}),/administratör/);assert.deepEqual(st,old);}
 for(const patch of [{memberId:''},{id:''},{name:'   '}])assert.throws(()=>reopen.reopenCustomer(base(),input(frozen),{...actor,...patch}),/administratör/);
 const invalid=[{reviewed:false},{reviewed:undefined},{reason:'   '},{reason:'x'.repeat(4001)},{nextAction:''},{nextAction:'x'.repeat(201)},{nextDate:past},{nextDate:''},{nextDate:'2026-02-30'},{nextDate:'not-a-date'},{status:'onboarding'},{status:'growth'},{status:'closed'},{targetProfileId:'invalid-uuid'},{targetProfileId:ids.a},{targetProfileId:crypto.randomUUID()},{expectedContext:''},{expectedContext:'x'.repeat(3000001)},{customerId:'missing-customer'},{selectedTaskIds:[]},{actor},{responsibilityTransfers:[]},{owner:owners.c}];
 for(const patch of invalid){const st=base(),old=structuredClone(st);assert.throws(()=>reopen.reopenCustomer(st,input(st,patch),actor));assert.deepEqual(st,old,'Invalid review/date/identity cannot partially mutate the graph.');}
 for(const status of ['prospect','onboarding','active','growth','risk','dormant']){const st=base();st.customers[0].status=status;const old=structuredClone(st);assert.match(reopen.customerReopenReview(st,customerId).blockedReason,/redan öppen/);assert.throws(()=>reopen.reopenCustomer(st,input(st),actor),/redan öppen/);assert.deepEqual(st,old);}
 const uninitialized=base({legacy:true});uninitialized.settings.sellerProfilesInitialized=false;uninitialized.settings.sellerProfiles=[];assert.match(reopen.customerReopenReview(uninitialized,customerId).blockedReason,/Skapa och granska/);
 const unmapped=base({legacy:true});unmapped.customers[0].owner='Syntetiskt okänt äldre kundansvar';unmapped.customers[0].ownerProfileId='';unmapped.customers[0].responsibilityTransfers=[];assert.match(reopen.customerReopenReview(unmapped,customerId).blockedReason,/saknar/);assert.throws(()=>reopen.reopenCustomer(unmapped,input(unmapped),actor),/saknar/);
 const mismatched=base();mismatched.customers[0].ownerProfileId=ids.b;assert.match(reopen.customerReopenReview(mismatched,customerId).blockedReason,/saknar/);assert.throws(()=>reopen.reopenCustomer(mismatched,input(mismatched),actor));
 const retiredTarget=base();retiredTarget.settings.sellerProfiles[1].active=false;retiredTarget.settings.owners=[owners.c];assert.throws(()=>reopen.reopenCustomer(retiredTarget,input(retiredTarget),actor),/aktiv/);
 const noTarget=base();for(const profile of noTarget.settings.sellerProfiles)profile.active=false;assert.match(reopen.customerReopenReview(noTarget,customerId).blockedReason,/ingen aktiv/);assert.throws(()=>reopen.reopenCustomer(noTarget,input(noTarget),actor),/ingen aktiv/);

 // Existing separate workflows stay with their recorded identity, even when
 // old nested references are blank and the source profile is historical.
 for(const blank of [false,true])for(const status of ['prospect','dormant']){
  const st=base();st.customers[0].onboarding.completedAt='';st.customers[0].plan.issueStatus='open';st.customers[0].yearNeeds[0].status='planned';st.tasks[0].done=false;
  if(blank){st.customers[0].onboarding.ownerProfileId='';st.customers[0].plan.issueOwnerProfileId='';st.customers[0].yearNeeds[0].ownerProfileId='';st.tasks[0].ownerProfileId='';}
  const old=structuredClone(st),payload=input(st,{status});const pending=reopen.customerReopenReview(st,customerId);assert.match(pending.activeBlockedReason,/onboarding/);assert.ok(pending.remainingWork.some(row=>row.kind==='onboarding'));assert.ok(pending.remainingWork.some(row=>row.kind==='issue'));reopen.reopenCustomer(st,payload,actor);assertReopened(old,st,payload);assert.equal(retirement.protectRetiredSellerResponsibilities(old,st),st,'Old normalized legacy workflow keys do not look newly assigned to the retired profile.');
 }
 const incomplete=base();incomplete.customers[0].onboarding.completedAt='';const incompleteBefore=structuredClone(incomplete);assert.throws(()=>reopen.reopenCustomer(incomplete,input(incomplete),actor),/onboarding/);assert.deepEqual(incomplete,incompleteBefore);

 const changedCases=[['contact',st=>{st.customers[0].contact='Syntetisk ändrad kontakt';}],['billing address',st=>{st.customers[0].billingAddress.street='Syntetisk ny gata';}],['name',st=>{st.customers[0].name='Syntetiskt ändrat kundnamn';}],['nextReview',st=>{st.customers[0].nextReview=future;}],['lastContact',st=>{st.customers[0].lastContact=today;}],['nested need',st=>{st.customers[0].yearNeeds[1].notes='Syntetiskt ändrat behov';}],['old task',st=>{st.tasks[1].title='Syntetiskt ändrad uppgift';}],['old deal',st=>{st.deals[1].stage='paused';}],['old order',st=>{st.orders[0].invoiceValue=null;}],['old meeting',st=>{st.meetings[1].date=today;}],['available profile',st=>{st.settings.sellerProfiles[1].displayName='Syntetiskt ändrad profil';}],['profile account',st=>{st.settings.sellerProfiles[1].memberId='synthetic-new-linked-member';}],['operative roster',st=>{st.settings.owners=[owners.c];}]];
 for(const [label,modify] of changedCases){const st=base();modify(st);assert.notEqual(reopen.customerReopenBasis(st,customerId),basis,label+' requires new review.');const old=structuredClone(st);assert.throws(()=>reopen.reopenCustomer(st,input(frozen),actor),/ändrats/);assert.deepEqual(st,old);}
 function relatedWork(){const st=base();st.deals.push(core.DealSchema.parse({id:'synthetic-reopen-related-open-deal',customerId,owner:owners.b,ownerProfileId:ids.b,title:'Syntetisk separat öppen affär',stage:'paused',reason:'Syntetiskt pausskäl'}));st.orders.push(core.OrderSchema.parse({...st.orders[0],id:'synthetic-reopen-related-open-order',owner:owners.b,ownerProfileId:ids.b,stage:'handover',invoiceValue:null,invoiceRef:'',invoiceDate:'',invoiceOwner:'',invoiceOwnerId:'',actualCost:null}));return core.normalizeState(st);}
 for(const kind of ['deal','order']){
  const st=relatedWork(),payload=input(st),oldCustomerBasis=responsibility.customerResponsibilityBasis(st,customerId),oldReview=reopen.customerReopenReview(st,customerId),row=kind==='deal'?st.deals.at(-1):st.orders.at(-1);
  row.ownerProfileId='';core.normalizeState(st);
  assert.equal(responsibility.customerResponsibilityBasis(st,customerId),oldCustomerBasis,'The older customer basis alone omits the '+kind+' stable ID.');
  const changed=reopen.customerReopenReview(st,customerId).remainingWork.find(item=>item.action?.id===row.id||item.key===JSON.stringify([kind,row.id])),previous=oldReview.remainingWork.find(item=>item.key===changed.key);assert.equal(previous.ownerProfileId,ids.b);assert.equal(changed.ownerProfileId,'');assert.equal(previous.identity,'profile');assert.equal(changed.identity,'legacy');
  assert.notEqual(reopen.customerReopenBasis(st,customerId),payload.expectedContext,'The exact visible '+kind+' identity requires a fresh review.');const beforeReject=structuredClone(st);assert.throws(()=>reopen.reopenCustomer(st,payload,actor),/ändrats/);assert.deepEqual(st,beforeReject);
 }
 const hintOnly=relatedWork(),hintPayload=input(hintOnly),hintOldBasis=responsibility.customerResponsibilityBasis(hintOnly,customerId),hintOldReview=reopen.customerReopenReview(hintOnly,customerId),hintOrder=hintOnly.orders.at(-1);
 for(let i=0;i<1000;i++)hintOrder.responsibilityTransfers.push(commercial.CommercialResponsibilityHistorySchema.parse({id:crypto.randomUUID(),targetType:'order',targetId:hintOrder.id,customerId,dealId:hintOrder.dealId,fromProfileId:i%2?ids.c:ids.b,toProfileId:i%2?ids.b:ids.c,fromOwner:i%2?owners.c:owners.b,toOwner:i%2?owners.b:owners.c,fromDisplayName:'Samma syntetiska profilnamn',toDisplayName:'Samma syntetiska profilnamn',selectedTaskIds:[],reason:'Syntetisk gränshistorik för separat order',at,byId:actor.id,byMemberId:actor.memberId,byName:actor.name}));
 core.normalizeState(hintOnly);assert.equal(responsibility.customerResponsibilityBasis(hintOnly,customerId),hintOldBasis,'Changing only the related order audit limit was absent from the older customer basis.');
 const previousHint=hintOldReview.remainingWork.find(row=>row.key===JSON.stringify(['order',hintOrder.id])),changedHint=reopen.customerReopenReview(hintOnly,customerId).remainingWork.find(row=>row.key===previousHint.key);
 assert.deepEqual({...changedHint,action:previousHint.action,actionLabel:previousHint.actionLabel,hint:previousHint.hint},previousHint,'This change affects only the displayed destination/action/hint.');assert.equal(previousHint.action.kind,'order');assert.equal(changedHint.action.kind,'customer');assert.match(changedHint.hint,/gränsen/);
 assert.notEqual(reopen.customerReopenBasis(hintOnly,customerId),hintPayload.expectedContext);const hintBeforeReject=structuredClone(hintOnly);assert.throws(()=>reopen.reopenCustomer(hintOnly,hintPayload,actor),/ändrats/);assert.deepEqual(hintOnly,hintBeforeReject);
 const reordered=relatedWork(),canonical=reopen.customerReopenBasis(reordered,customerId);reordered.tasks.reverse();reordered.deals.reverse();reordered.orders.reverse();reordered.meetings.reverse();assert.equal(reopen.customerReopenBasis(reordered,customerId),canonical,'Canonical stable row keys prevent a storage row-order-only conflict.');
 const unrelated=base();unrelated.version+=1;unrelated.customers[1].name='Syntetiskt ändrad annan kund';unrelated.settings.budgets[month]=7000;unrelated.events.push({id:'synthetic-unrelated-note',customerId:unrelated.customers[1].id,dealId:'',kind:'customer_note',text:'Syntetisk annan kunds anteckning',at});assert.equal(reopen.customerReopenBasis(unrelated,customerId),basis,'Unrelated work can rebase without adopting the reviewed customer.');
 const already=base();reopen.reopenCustomer(already,input(already),actor);const afterOne=structuredClone(already);assert.throws(()=>reopen.reopenCustomer(already,input(already),actor),/redan öppen/);assert.deepEqual(already,afterOne,'A second new intent creates no task/event without a closed relation.');

 // Verify the integrated dispatcher retains its immutable input and v55's
 // invariant while preserving the old two-step route and generic rights.
 const dispatched=core.applyAction(frozen,{type:'customer_reopen',data:input(frozen)},actor);assertReopened(frozen,dispatched,input(frozen));assert.deepEqual(frozen,before);
 const nestedLegacy=base();nestedLegacy.customers[0].plan.issueStatus='open';nestedLegacy.customers[0].plan.issueOwnerProfileId='';nestedLegacy.customers[0].yearNeeds[0].status='planned';nestedLegacy.customers[0].yearNeeds[0].ownerProfileId='';nestedLegacy.tasks[0].done=false;nestedLegacy.tasks[0].ownerProfileId='';const nestedBefore=structuredClone(nestedLegacy);const nestedDispatched=core.applyAction(nestedLegacy,{type:'customer_reopen',data:input(nestedLegacy)},actor);assertReopened(nestedBefore,nestedDispatched,input(nestedBefore));
 const twoStep=base(),transferred=core.applyAction(twoStep,{type:'customer_responsibility_transfer',data:{customerId,targetProfileId:ids.b,selectedTaskIds:[],reason:'Syntetisk befintlig tvåstegsväg',reviewed:true,expectedContext:responsibility.customerResponsibilityBasis(twoStep,customerId)}},actor);assert.equal(transferred.customers[0].status,'closed');const genericOpened=core.applyAction(transferred,{type:'customer',data:{...transferred.customers[0],status:'active'}},actor);assert.equal(genericOpened.customers[0].status,'active');assert.deepEqual(genericOpened.customers[0].responsibilityTransfers,transferred.customers[0].responsibilityTransfers,'The pre-existing two-step path remains available.');
 const ordinary=base({activeSource:true});const genericSeller=core.applyAction(ordinary,{type:'customer',data:{...ordinary.customers[0],status:'active'}},{...actor,role:'seller',owner:owners.a});assert.equal(genericSeller.customers[0].status,'active','The existing generic customer action keeps its role/transition behavior.');
 for(const strip of [st=>{delete st.customers[0].plan;},st=>{delete st.customers[0].onboarding;},st=>{delete st.customers[0].yearNeeds;},st=>{delete st.companyEvents;}]){const raw=base();strip(raw);const old=structuredClone(raw),normalized=core.normalizeState(structuredClone(raw));const next=core.applyAction(raw,{type:'customer_reopen',data:input(normalized)},actor);assertReopened(normalized,next,input(normalized));assert.deepEqual(raw,old,'Raw older fields normalize without mutating the source.');}
 assert.equal(dashboards.salesMetrics(frozen,month,ids.a).revenue,metricsBefore.revenue);
 console.log('PASS reviewed customer reopening domain: retired/active/legacy identities, three explicit statuses, one new care task/event, unchanged history/KPIs, exact review conflicts, onboarding/date gates, legacy workflow keys and preserved two-step path.');
}
