import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {dirname,relative,resolve,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
import React,{act} from 'react';
import {create} from 'react-test-renderer';

const profileA='c5746101-f76b-4ec7-9f44-90d7e9c5a001',profileB='c5746101-f76b-4ec7-9f44-90d7e9c5a002';
const nameA='Syntetisk affärsansvarig A',nameB='Syntetisk affärsansvarig B',removedName='Syntetisk borttagen affärsansvarig';

// Real normalization and stable commercial responsibility validation apply to
// every fixture. Names, contacts, financial amounts and acceptances are synthetic.
export function dealScopeFixture(core,{link='b',owner=nameA,role='seller',initialized=true,inactive=false,memberId='synthetic-deal-member',owners=[nameA,nameB]}={}){
 const st=core.emptyState();st.viewer={id:'synthetic-deal-session',memberId,name:'Syntetisk person',email:'synthetic-deal-person@example.test',role,owner};
 st.settings.owners=owners;st.settings.sellerProfilesInitialized=initialized;
 st.settings.sellerProfiles=initialized?[
  {id:profileA,legacyOwnerName:nameA,displayName:'Samma syntetiska visningsnamn',memberId:link==='a'?'synthetic-deal-member':'',active:true,linkHistory:[],retirementHistory:[]},
  {id:profileB,legacyOwnerName:nameB,displayName:'Samma syntetiska visningsnamn',memberId:link==='b'?'synthetic-deal-member':'',active:!inactive,linkHistory:[],retirementHistory:[]}
 ]:[];
 st.customers=['a','b'].map((key,index)=>core.CustomerSchema.parse({id:'synthetic-deal-customer-'+key,name:'Syntetisk kund '+key,owner:index?nameB:nameA,contact:'Syntetisk provkontakt',status:index?'closed':'active'}));
 const deal=(id,stage='identified',profile='',assigned=nameA,value=100)=>core.DealSchema.parse({id,customerId:'synthetic-deal-customer-b',ownerProfileId:profile,owner:assigned,title:'Syntetisk affär '+id,stage,value,cost:20,nextAction:'Syntetisk nästa aktivitet '+id,nextDate:'2026-10-20',need:'Syntetiskt testbehov',decisionMaker:'Syntetisk provbeställare',solution:'Syntetisk testlösning',deliveryDate:'2026-11-10',quoteRef:'SYNTHETIC-'+id,decisionDate:'2026-10-20',reason:['paused','lost'].includes(stage)?'Syntetisk paus/förlustorsak':'',confirmed:stage==='won',wonAt:stage==='won'?'2026-10-09':'',category:'Syntetisk kategori'});
 st.deals=[...(initialized?[deal('profile-a','identified',profileA,nameA,200),...([...core.PIPELINE,...core.OUTCOMES]).map((entry,index)=>deal('profile-b-'+entry.id,entry.id,profileB,nameB,index===0?null:(index+1)*100))]:[]),deal('legacy-a','identified','',nameA,150),deal('legacy-a-paused','paused','',nameA,250),deal('legacy-b','identified','',nameB,350),deal('sentinel','identified','','_unassigned',450),deal('removed-alias','identified','',removedName,550)];
 st.orders=st.deals.filter(d=>d.stage==='won').map(d=>core.OrderSchema.parse({id:d.id+'-order',customerId:d.customerId,dealId:d.id,owner:d.owner,ownerProfileId:d.ownerProfileId,stage:'followed',proofRequired:false,proofApproved:false,supplierConfirmed:true,deliveryDate:'2026-11-10',deliveredDate:'2026-10-09',invoiceDate:'2026-10-09',invoiceRef:'SYNTHETIC-INVOICE',invoiceValue:900,actualCost:20,invoiceOwner:d.owner,invoiceOwnerId:d.ownerProfileId,invoiceOwnerSource:'recorded',notes:'Syntetisk historisk order'}));
 return core.normalizeState(st);
}

// Complete actual page selector, board, toolbar and Dashboard navigation run
// with production modules. Only visual primitives and callback destinations
// are adapters. No provider, transport, browser or personal login is asserted.
export async function verifyDealScope(){
 mkdirSync('work',{recursive:true});const directory=mkdtempSync(resolve('work/deal-scope-'));
 const compiled=new Set(),sourceBytes=new Map(),toTarget=file=>resolve(directory,file.replace(/\.tsx?$/,'.mjs')),helpers=resolve(directory,'helpers.mjs');
 const remember=file=>{const bytes=readFileSync(file);if(sourceBytes.has(file))assert.deepEqual(bytes,sourceBytes.get(file));else sourceBytes.set(file,bytes);return bytes.toString('utf8');};
 writeFileSync(helpers,`import React from 'react';const host=tag=>React.forwardRef(({children,...props},ref)=>React.createElement(tag,{...props,ref},children));export const Button=host('button'),Tabs=host('tabs'),TabsList=host('tabs-list'),TabsTrigger=host('tabs-trigger');`);
 function compile(file){
  file=relative(resolve('.'),resolve(file)).split(sep).join('/');assert.ok(file.startsWith('lib/'),'Only actual domain modules may be compiled');
  const target=toTarget(file);if(compiled.has(file))return target;compiled.add(file);
  let output=ts.transpileModule(remember(file),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
  output=output.replace(/(from\s+|import\s*)['"]([^'"]+)['"]/g,(whole,prefix,specifier)=>{
   let dependency;if(specifier.startsWith('@/lib/'))dependency=compile('lib/'+specifier.slice(6)+'.ts');else if(specifier.startsWith('./')||specifier.startsWith('../'))dependency=compile(resolve(dirname(file),specifier)+'.ts');else return whole;
   let local=relative(dirname(target),dependency).split(sep).join('/');if(!local.startsWith('.'))local='./'+local;return prefix+JSON.stringify(local);
  });mkdirSync(dirname(target),{recursive:true});writeFileSync(target,output);return target;
 }
 const originals=Object.fromEntries(['fetch','IS_REACT_ACT_ENVIRONMENT'].map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));
 let renderer,count=0,calls=[],http=[];
 const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value)}return value;};
 const text=node=>typeof node==='string'?node:Array.isArray(node)?node.map(text).join(''):node?.children?.map(text).join('')||'';
 const content=()=>text(renderer.toJSON()),button=caption=>renderer.root.findAllByType('button').find(node=>text(node)===caption);
 const rows=()=>renderer.root.findAll(node=>node.type==='button'&&['deal-card','list-row'].includes(node.props.className));
 const notice=()=>renderer.root.findAll(node=>node.props?.['data-profile-diagnostic']);
 async function unmount(){if(renderer){await act(async()=>renderer.unmount());renderer=null}}
 async function scenario(label,run){await unmount();calls=[];await run();await unmount();assert.equal(http.length,0,'No HTTP in '+label);count++;console.log('PASS Deal scope: '+label);}
 async function click(caption){const node=button(caption);assert.ok(node,'Expected '+caption);assert.ok(!node.props.disabled,'Enabled '+caption);await act(async()=>node.props.onClick());}
 try{
  Object.defineProperty(globalThis,'IS_REACT_ACT_ENVIRONMENT',{configurable:true,writable:true,value:true});
  Object.defineProperty(globalThis,'fetch',{configurable:true,writable:true,value:async(...args)=>{http.push(args);throw Error('Deal scope must not perform HTTP')}});
  const core=await import(pathToFileURL(compile('lib/crm.ts')).href),domain=await import(pathToFileURL(compile('lib/deal-scope.ts')).href),dashboard=await import(pathToFileURL(compile('lib/sales-dashboard.ts')).href);
  const source=remember('app/page.tsx'),ast=ts.createSourceFile('app/page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),nodes=[];
  function visit(node){nodes.push(node);ts.forEachChild(node,visit)}visit(ast);
  const variable=name=>{const matches=nodes.filter(node=>ts.isVariableDeclaration(node)&&node.name.getText(ast)===name);assert.equal(matches.length,1,'Exactly one actual declaration '+name);return matches[0].initializer.getText(ast);};
  const declaration=name=>{const matches=nodes.filter(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name);assert.equal(matches.length,1,'Exactly one actual function '+name);return matches[0].getText(ast);};
  const toolbar=nodes.filter(node=>ts.isJsxSelfClosingElement(node)&&node.tagName.getText(ast)==='Choice'&&node.attributes.properties.some(attr=>ts.isJsxAttribute(attr)&&attr.name.getText(ast)==='label'&&ts.isStringLiteral(attr.initializer)&&attr.initializer.text==='Ansvarig'));assert.equal(toolbar.length,1);
  const options=toolbar[0].attributes.properties.find(attr=>ts.isJsxAttribute(attr)&&attr.name.getText(ast)==='options').initializer.expression.getText(ast);
  const caption=nodes.filter(node=>ts.isJsxElement(node)&&node.openingElement.tagName.getText(ast)==='span'&&node.openingElement.attributes.properties.some(attr=>ts.isJsxAttribute(attr)&&attr.name.getText(ast)==='className'&&ts.isStringLiteral(attr.initializer)&&attr.initializer.text==='scope-caption'));assert.equal(caption.length,1);const captionExpression=caption[0].children.find(ts.isJsxExpression).expression.getText(ast);
  const board=nodes.filter(node=>ts.isJsxExpression(node)&&node.expression&&ts.isBinaryExpression(node.expression)&&node.expression.left.getText(ast)==="view==='deals'"&&node.expression.right.getText(ast).includes('className="board"'));assert.equal(board.length,1,'Exactly one complete actual Offers fragment');
  const noticeJSX=nodes.filter(node=>ts.isJsxExpression(node)&&node.expression&&ts.isBinaryExpression(node.expression)&&node.expression.getText(ast).startsWith("view==='deals'&&")&&node.expression.getText(ast).includes('<DealScopeNotice '));assert.equal(noticeJSX.length,1,'Exactly one actual Offers diagnostic condition');
  const result=nodes.find(node=>ts.isJsxSelfClosingElement(node)&&node.tagName.getText(ast)==='SalesDashboard').attributes.properties.find(attr=>ts.isJsxAttribute(attr)&&attr.name.getText(ast)==='onView').initializer.expression.getText(ast);
  const dashboardSource=remember('components/sales-dashboard.tsx'),dashboardAST=ts.createSourceFile('components/sales-dashboard.tsx',dashboardSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),dashboardNodes=[];(function find(n){dashboardNodes.push(n);ts.forEachChild(n,find)})(dashboardAST);
  const go=dashboardNodes.find(n=>ts.isVariableDeclaration(n)&&n.name.getText(dashboardAST)==='go').initializer.getText(dashboardAST);
  const declarations=['customers','dealScopeState','deals'].map(name=>'const '+name+'=('+variable(name)+');').join('\n');
  const parentFile=resolve(directory,'actual-parent.mjs'),code=`import React,{useId} from 'react';import {Clock,Plus,ArrowUpRight,AlertTriangle,Check} from 'lucide-react';import {Button,Tabs,TabsList,TabsTrigger} from ${JSON.stringify(pathToFileURL(helpers).href)};import {dealScope,dealInScope} from ${JSON.stringify(pathToFileURL(compile('lib/deal-scope.ts')).href)};import {personalOwner,personalResultScope,resultOperationalOwner} from ${JSON.stringify(pathToFileURL(compile('lib/sales-dashboard.ts')).href)};import {PIPELINE,OUTCOMES,isOpen,day} from ${JSON.stringify(pathToFileURL(compile('lib/crm.ts')).href)};
const groups=(${variable('groups')}),groupOf=(${variable('groupOf')}),sek=(${variable('sek')}),short=(${variable('short')}),dateLabel=(${variable('dateLabel')});${declaration('Empty')}${declaration('DealScopeNotice')}
export function selected(st,owner,search=''){${declarations}return {scope:dealScopeState,deals,portfolio:customers};}
export function frame(st,owner,search,filter,selectedView,calls,busy=false){const viewerReady=(${variable('viewerReady')}),department=(${variable('department')}),view=(${variable('view')});${declarations}const cname=(${variable('cname')}),setFilter=value=>calls.push({kind:'filter',value}),open=(type,data)=>calls.push({kind:'open',type,data}),create=type=>calls.push({kind:'create',type}),openCommercialAnchor=data=>calls.push({kind:'anchor',data}),setCommercialTransfer=data=>calls.push({kind:'transfer',data}),navigate=view=>calls.push({kind:'navigate',view});return <>{(${noticeJSX[0].expression.getText(ast)})}{(${board[0].expression.getText(ast)})}</>;}
export function toolbar(st,owner,view){const dealScopeState=st?dealScope(st,owner):null;return {options:(${options}),caption:(${captionExpression})};}
export function actualNavigation(st,view,observed){const workspaceReturn={current:'old'},setResumeDraft=value=>observed.push({kind:'draft',value}),setResumeArticleDraft=value=>observed.push({kind:'articleDraft',value}),setSearch=value=>observed.push({kind:'search',value}),setOwner=value=>observed.push({kind:'owner',value}),setView=value=>observed.push({kind:'view',value});${declaration('navigate')}return navigate;}
export function resultNavigation(st,view,setOwner,setSearch,setFilter,setView){return (${result});}
export function dashboardGo(st,owner,onView){return (${go});}
export function parentSave(st,saving,activeSpace,space,toast){${declaration('save')}return save;}
`;
  writeFileSync(parentFile,ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText);const parent=await import(pathToFileURL(parentFile).href);
  const fixture=options=>dealScopeFixture(core,options),own=st=>dashboard.personalOwner(st)||'_unassigned',scope=(st,owner=own(st))=>domain.dealScope(st,owner);
  const ids=(st,owner=own(st),search='')=>{const before=JSON.stringify(st);freeze(st);const selected=parent.selected(st,owner,search);assert.deepEqual(parent.selected(st,owner,'').deals,st.deals.filter(d=>domain.dealInScope(d,scope(st,owner))),'Actual parent delegates ownership to actual helper');assert.equal(JSON.stringify(st),before);return selected.deals.map(d=>d.id);};
  async function render(st,owner=own(st),{search='',filter='open',view='deals',update=false}={}){const before=JSON.stringify(st);freeze(st);await act(async()=>{const tree=parent.frame(st,owner,search,filter,view,calls);if(update){assert.ok(renderer);renderer.update(tree)}else renderer=create(tree)});assert.equal(JSON.stringify(st),before);return()=>assert.equal(JSON.stringify(st),before,'Callbacks preserve normalized fixture');}
  function diagnostic(kind){assert.equal(notice().length,kind?1:0);if(kind){assert.equal(notice()[0].props['data-profile-diagnostic'],kind);assert.equal(notice()[0].props.role,'status');assert.ok(notice()[0].findAllByType('h2').some(n=>n.props.id===notice()[0].props['aria-labelledby']));assert.match(text(notice()[0]),/synligt urval/i);assert.match(text(notice()[0]),/inte en bekräftad fullständig/i);assert.equal(renderer.root.findAllByType('section')[0],notice()[0],'Diagnostic precedes visible work');}}
  const ownAll=[...core.PIPELINE,...core.OUTCOMES].map(p=>'profile-b-'+p.id),ownOpen=core.PIPELINE.map(p=>'profile-b-'+p.id),ownLegacy=['legacy-a','legacy-a-paused'];

  await scenario('exact member B wins over operative A despite identical profile names',async()=>{const st=fixture(),unchanged=await render(st);assert.deepEqual(ids(st),[...ownAll,...ownLegacy]);assert.equal(scope(st).profileId,profileB);assert.equal(scope(st).legacyOwner,nameA);diagnostic('mismatch');assert.equal(rows().length,ownOpen.length+1);unchanged();});
  for(const owner of ['',removedName])await scenario((owner?'removed':'blank')+' operative alias retains exact B but excludes legacy and literal sentinel',async()=>{const st=fixture({owner}),unchanged=await render(st);assert.deepEqual(ids(st),ownAll);assert.equal(scope(st).legacyOwner,'');diagnostic('operational-missing');assert.equal(rows().length,ownOpen.length);unchanged();});
  await scenario('missing member link retains valid blank-ID A but never borrows named profile A',async()=>{const st=fixture({link:''}),unchanged=await render(st);assert.deepEqual(ids(st),ownLegacy);assert.equal(scope(st).profileId,'');diagnostic('missing');unchanged();});
  await scenario('missing immutable member cannot be replaced by matching runtime user ID',async()=>{const st=fixture({memberId:''});st.viewer.id='synthetic-deal-member';const unchanged=await render(st);assert.deepEqual(ids(st),ownLegacy);diagnostic('missing');unchanged();});
  await scenario('missing member and alias show incomplete zero rows without adopting sentinel',async()=>{const st=fixture({link:'',owner:''}),unchanged=await render(st);assert.deepEqual(ids(st),[]);assert.equal(rows().length,0);diagnostic('missing');unchanged();});
  await scenario('inactive exact profile retains historical and current own rows without activation',async()=>{const st=fixture({inactive:true,owner:'',owners:[nameA]}),unchanged=await render(st);assert.deepEqual(ids(st),ownAll);diagnostic('operational-missing');assert.equal(st.settings.sellerProfiles[1].active,false);unchanged();});
  for(const role of ['seller','reader','admin'])await scenario(role+' explicit team retains all existing commercial rows',async()=>{const st=fixture({role,owner:''}),unchanged=await render(st,'all');assert.deepEqual(ids(st,'all'),st.deals.map(d=>d.id));assert.equal(scope(st,'all').team,true);diagnostic('');unchanged();});
  await scenario('explicit other A retains A profile plus its older alias without selecting own B',async()=>{const st=fixture({owner:nameB}),unchanged=await render(st,nameA);assert.deepEqual(ids(st,nameA),['profile-a',...ownLegacy]);assert.equal(scope(st,nameA).personal,false);diagnostic('');unchanged();});
  await scenario('explicit B retains B profile plus B legacy while own account A stays separate',async()=>{const st=fixture(),unchanged=await render(st,nameB);assert.deepEqual(ids(st,nameB),[...ownAll,'legacy-b']);assert.equal(scope(st,nameB).personal,false);diagnostic('');unchanged();});
  for(const invalid of ['',profileB,'_unassigned',removedName])await scenario('invalid explicit selection '+(invalid||'(empty)')+' cannot adopt ID, alias or sentinel',async()=>{const st=fixture(),unchanged=await render(st,invalid);assert.deepEqual(ids(st,invalid),[]);assert.equal(scope(st,invalid).profileId,'');assert.equal(scope(st,invalid).legacyOwner,'');diagnostic('');unchanged();});
  await scenario('valid explicit roster alias without a profile retains only blank-ID B',async()=>{const st=fixture();st.settings.sellerProfiles.pop();st.deals=st.deals.filter(d=>d.ownerProfileId!==profileB);st.orders=[];core.normalizeState(st);const unchanged=await render(st,nameB);assert.deepEqual(ids(st,nameB),['legacy-b']);diagnostic('');unchanged();});
  await scenario('legacy before initialization uses actual valid alias without invented profile',async()=>{const st=fixture({initialized:false}),unchanged=await render(st);assert.deepEqual(ids(st),ownLegacy);assert.equal(scope(st).profileId,'');diagnostic('');unchanged();});
  await scenario('legacy before initialization with no alias excludes literal sentinel',async()=>{const st=fixture({initialized:false,owner:''}),unchanged=await render(st);assert.deepEqual(ids(st),[]);diagnostic('');unchanged();});
  await scenario('actual all-stage tabs retain counts and archive separation',async()=>{const st=fixture(),unchanged=await render(st);const tabs=renderer.root.findAllByType('tabs-trigger');assert.deepEqual(tabs.map(n=>text(n)),['Pågående 8','Vunnen 1','Pausad 2','Förlorad 1']);for(const stage of ['won','paused','lost']){await render(st,undefined,{filter:stage,update:true});const expected=stage==='paused'?['profile-b-paused','legacy-a-paused']:['profile-b-'+stage];assert.deepEqual(rows().map(n=>st.deals.find(d=>text(n.findAllByType('b')[0])===d.title)?.id),expected);diagnostic('mismatch');}unchanged();});
  await scenario('own profile card opens its exact existing editor and drag only proposes a reviewed stage',async()=>{const st=fixture(),unchanged=await render(st),row=st.deals.find(d=>d.id==='profile-b-identified'),card=rows().find(n=>text(n.findByType('h3'))===row.title);assert.ok(card);await act(async()=>card.props.onClick());assert.deepEqual(calls,[{kind:'open',type:'deal',data:row}]);calls.length=0;const transferred=[];card.props.onDragStart({dataTransfer:{setData:(kind,id)=>transferred.push([kind,id])}});assert.deepEqual(transferred,[['text/plain',row.id]]);const target=renderer.root.find(node=>node.type==='section'&&node.props['data-stage']==='contact');let prevented=0;await act(async()=>target.props.onDrop({preventDefault:()=>prevented++,dataTransfer:{getData:kind=>{assert.equal(kind,'text/plain');return row.id}}}));assert.equal(prevented,1);assert.deepEqual(calls,[{kind:'open',type:'deal',data:{...row,stage:'contact'}}]);assert.equal(st.deals.find(d=>d.id===row.id).stage,'identified');calls.length=0;await act(async()=>target.props.onDrop({preventDefault:()=>{},dataTransfer:{getData:()=> 'profile-b-contact'}}));assert.deepEqual(calls,[]);unchanged();});
  await scenario('won archive opens exact linked order while paused and lost open the existing deal',async()=>{const st=fixture(),unchanged=await render(st,undefined,{filter:'won'});await act(async()=>rows()[0].props.onClick());assert.deepEqual(calls,[{kind:'open',type:'order',data:st.orders[0]}]);for(const stage of ['paused','lost']){calls.length=0;await render(st,undefined,{filter:stage,update:true});await act(async()=>rows()[0].props.onClick());assert.deepEqual(calls,[{kind:'open',type:'deal',data:st.deals.find(d=>d.id==='profile-b-'+stage)}]);}unchanged();});
  await scenario('existing administrator anchor and transfer callbacks remain limited to eligible exact rows',async()=>{const st=fixture({role:'admin'}),unchanged=await render(st),legacy=st.deals.find(d=>d.id==='legacy-a'),byLabel=label=>renderer.root.findAllByType('button').find(n=>n.props['aria-label']===label);assert.equal(byLabel('Koppla affärsansvaret: '+st.deals.find(d=>d.id==='profile-b-identified').title),undefined);await act(async()=>byLabel('Koppla affärsansvaret: '+legacy.title).props.onClick());assert.deepEqual(calls,[{kind:'anchor',data:legacy}]);calls.length=0;await act(async()=>byLabel('Byt affärsansvar: '+st.deals.find(d=>d.id==='profile-b-identified').title).props.onClick());assert.deepEqual(calls,[{kind:'transfer',data:{targetType:'deal',targetId:'profile-b-identified'}}]);await render(st,undefined,{filter:'paused',update:true});assert.equal(renderer.root.findAllByProps({className:'commercial-anchor-trigger'}).filter(n=>n.type==='button').length,1);await render(fixture({role:'seller'}),undefined,{update:true});assert.equal(renderer.root.findAll(node=>node.type==='div'&&node.props.className?.startsWith('commercial-anchor-actions')).length,0);unchanged();});
  await scenario('board column counts and amounts use only actual visible deals; unknown price remains unknown',async()=>{const st=fixture(),unchanged=await render(st);const columns=renderer.root.findAll(node=>node.type==='section'&&node.props.className==='column');assert.equal(columns.length,core.PIPELINE.length);assert.deepEqual(columns.map(n=>text(n.findByProps({className:'column-total'}))),['150 kr','200 kr','300 kr','400 kr','500 kr','600 kr','700 kr']);assert.match(text(rows()[0]),/Ej angivet/);assert.deepEqual(columns.map(n=>text(n.findByProps({className:'column-head'}).findAllByType('span').at(-1))),['2','1','1','1','1','1','1']);unchanged();});
  for(const [kind,needle] of [['deal-title','SÖK AFFÄR'],['customer-name','SÖK KUND']])await scenario('case-insensitive actual '+kind+' search remains constrained to exact own scope',async()=>{const st=fixture();if(kind==='deal-title')for(const id of ['profile-a','profile-b-identified'])st.deals.find(d=>d.id===id).title='Syntetisk sök affär '+id;else st.customers.find(c=>c.id==='synthetic-deal-customer-b').name='Syntetisk sök kund';core.normalizeState(st);const unchanged=await render(st,undefined,{search:needle});assert.deepEqual(ids(st,undefined,needle),kind==='deal-title'?['profile-b-identified']:[...ownAll,...ownLegacy]);unchanged();});
  await scenario('customer portfolio remains on customer owner while deal scope follows distinct responsibility',async()=>{const st=fixture(),unchanged=await render(st);assert.deepEqual(parent.selected(st,own(st)).portfolio.map(c=>c.id),['synthetic-deal-customer-a']);assert.ok(ids(st).every(id=>st.deals.find(d=>d.id===id).customerId==='synthetic-deal-customer-b'));assert.equal(st.customers[1].status,'closed');unchanged();});
  await scenario('actual toolbar gives permanent personal entry, team label and honest diagnostic caption',async()=>{for(const options of [{},{owner:''},{link:''},{initialized:false}]){const st=fixture(options),actual=parent.toolbar(st,own(st),'deals');assert.equal(actual.caption,scope(st).caption);assert.equal(new Set(actual.options.map(o=>o.id)).size,actual.options.length);assert.ok(actual.options.some(o=>o.id===own(st)&&o.label.startsWith('Mina affärer')));assert.ok(actual.options.some(o=>o.id==='all'&&o.label==='Teamets affärer'));for(const selected of ['all',nameB])assert.ok(parent.toolbar(st,selected,'deals').options.some(o=>o.id===own(st)&&o.label.startsWith('Mina affärer')));}assert.equal(parent.toolbar(fixture(),'all','deals').caption,'Teamets affärer');assert.equal(parent.toolbar(fixture(),nameB,'deals').caption,'Affärer · '+nameB);});
  for(const [options,kind,action,route] of [[{role:'admin'},'mismatch','Öppna Mål & inställningar','settings'],[{role:'admin',link:''},'missing','Öppna Mål & inställningar','settings'],[{role:'admin',owner:''},'operational-missing','Öppna Konton & roller','accounts']])await scenario('actual administrator '+kind+' repair route preserves stored data',async()=>{const st=fixture(options),unchanged=await render(st);diagnostic(kind);await click(action);assert.deepEqual(calls,[{kind:'navigate',view:route}]);const observed=[];parent.actualNavigation(st,'deals',observed)(route);assert.deepEqual(observed,[{kind:'search',value:''},{kind:'view',value:route}]);unchanged();});
  for(const role of ['seller','reader'])await scenario(role+' diagnostic guides administrator without profile/account write',async()=>{const st=fixture({role}),unchanged=await render(st);diagnostic('mismatch');assert.match(content(),/Be en administratör/);assert.equal(button('Öppna Mål & inställningar'),undefined);assert.equal(button('Öppna Konton & roller'),undefined);unchanged();});
  await scenario('actual reader save rejects direct deal mutation before flush or HTTP',async()=>{const st=fixture({role:'reader'}),unchanged=await render(st),observed=[],saving={current:false},save=parent.parentSave(st,saving,{current:'synthetic'},'synthetic',{error:message=>observed.push(message)});assert.equal(await save('deal',st.deals[0]),false);assert.deepEqual(observed,['Ditt konto har läsbehörighet.']);assert.equal(saving.current,false);assert.equal(http.length,0);unchanged();});
  for(const role of ['production','print','warehouse'])await scenario(role+' remembered Offers view remains in its operational workspace',async()=>{const st=fixture({role}),unchanged=await render(st);assert.equal(renderer.toJSON(),null);assert.deepEqual(calls,[]);unchanged();});
  function resultNavigation(st,currentView,target,passedScope){const before=JSON.stringify(st);freeze(st);const selected={owner:'old',search:'old',filter:'old',view:currentView},set=key=>value=>selected[key]=value;parent.resultNavigation(st,currentView,set('owner'),set('search'),set('filter'),set('view'))(target,passedScope);assert.equal(JSON.stringify(st),before);return selected;}
  for(const owner of [nameA,'',removedName])await scenario('actual personal Resultat go to Offers uses account scope '+(owner||'(empty)')+' and exact linked B',async()=>{const st=fixture({owner}),observed=[];parent.dashboardGo(st,dashboard.personalResultScope(st),(v,o)=>observed.push([v,o]))('deals');assert.deepEqual(observed,[['deals',nameB]]);const next=resultNavigation(st,'overview',...observed[0]);assert.deepEqual(next,{owner:own(st),search:'',filter:'open',view:'deals'});assert.deepEqual(ids(st,next.owner),owner===nameA?[...ownAll,...ownLegacy]:ownAll);});
  await scenario('admin team Resultat keeps all and explicit other alias; personal explicit-other remains explicit',async()=>{const st=fixture({role:'admin'});assert.equal(resultNavigation(st,'team','deals','all').owner,'all');assert.equal(resultNavigation(st,'team','deals',nameB).owner,nameB);assert.equal(resultNavigation(st,'overview','deals',nameA).owner,nameA);assert.equal(resultNavigation(st,'overview','deals','all').owner,'all');});
  await scenario('sidebar Offers navigation retains explicit/team selection rather than reselecting personal',async()=>{for(const owner of ['all',nameB]){const st=fixture(),observed=[];parent.actualNavigation(st,'overview',observed)('deals');assert.deepEqual(observed,[{kind:'search',value:''},{kind:'view',value:'deals'}]);assert.equal(observed.some(v=>v.kind==='owner'),false);assert.ok(ids(st,owner).length>0);}});
  await scenario('every financial and attribution metric stays unchanged after scope reads and navigation',async()=>{const st=fixture(),before=JSON.stringify(st),snapshots=[profileA,profileB,'all'].map(id=>dashboard.salesMetrics(st,'2026-10',id));freeze(st);ids(st);parent.toolbar(st,own(st),'deals');resultNavigation(st,'overview','deals',nameB);assert.deepEqual([profileA,profileB,'all'].map(id=>dashboard.salesMetrics(st,'2026-10',id)),snapshots);assert.equal(JSON.stringify(st),before);assert.equal(snapshots[1].revenue,900);assert.equal(snapshots[1].profit,880);});
  await scenario('ordinary real domain deal writes retain reviewed profile and alias ownership guards',async()=>{const st=fixture(),before=JSON.stringify(st),row=st.deals.find(d=>d.id==='profile-b-identified'),actor={id:'synthetic-actor',memberId:'synthetic-deal-member',name:'Syntetisk aktör',role:'seller',owner:nameA};freeze(st);assert.throws(()=>core.applyAction(st,{type:'deal',data:{...row,ownerProfileId:profileA}},actor),/Ansvarsprofil/);assert.throws(()=>core.applyAction(st,{type:'deal',data:{...row,owner:nameA}},actor),/Byt affärsansvar/);const changed=core.applyAction(st,{type:'deal',data:{...row,title:'Syntetisk ändrad affärsrubrik'}},actor);assert.equal(changed.deals.find(d=>d.id===row.id).ownerProfileId,profileB);assert.equal(changed.deals.find(d=>d.id===row.id).owner,nameB);assert.equal(JSON.stringify(st),before);});
  await scenario('account, member and operative alias re-read cannot retain another account scope',async()=>{const a=fixture(),beforeA=await render(a);assert.deepEqual(ids(a),[...ownAll,...ownLegacy]);const b=fixture({link:'a',owner:nameB});b.viewer.id='synthetic-other-account';b.viewer.memberId='synthetic-other-member';b.settings.sellerProfiles[0].memberId='synthetic-other-member';const beforeB=await render(b,undefined,{update:true});assert.deepEqual(ids(b),['profile-a','legacy-b']);diagnostic('mismatch');const missing=fixture({link:'',owner:''}),beforeMissing=await render(missing,undefined,{update:true});assert.deepEqual(ids(missing),[]);diagnostic('missing');beforeA();beforeB();beforeMissing();});
  for(const [file,bytes] of sourceBytes)assert.deepEqual(readFileSync(file),bytes,'Actual source remains byte unchanged: '+file);
  const proof=Object.fromEntries([...sourceBytes].sort(([a],[b])=>a.localeCompare(b)).map(([file,bytes])=>[file,{bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}]));
  console.log('PASS Deal scope: '+count+' normalized domain/actual parent/React cases; immutable inputs, '+compiled.size+' byte-verified production modules, zero HTTP. Controlled presentation and callback destinations; no browser, personal login, integration or staff acceptance.');
  return {cases:count,compiledModules:compiled.size,httpRequests:http.length,sourceProof:proof};
 }finally{await unmount();rmSync(directory,{recursive:true,force:true});for(const [key,descriptor] of Object.entries(originals)){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}}
}
