import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {dirname,relative,resolve,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
import React,{act} from 'react';
import {create} from 'react-test-renderer';

const profileA='b5746101-f76b-4ec7-9f44-90d7e9c5a001',profileB='b5746101-f76b-4ec7-9f44-90d7e9c5a002';
const nameA='Syntetisk onboardingansvar A',nameB='Syntetisk onboardingansvar B',at='2026-10-10T08:00:00.000Z';

// Actual production normalization validates every fixture, including each
// explicit onboarding profile's first won deal and associated synthetic order.
// Exported only for the private, immutable-main baseline reproduction.
export function onboardingScopeFixture(core,{link='b',owner=nameA,role='seller',initialized=true,inactive=false,memberId='synthetic-member',owners=[nameA,nameB]}={}){
 const st=core.emptyState();st.viewer={id:'synthetic-session',memberId,name:'Syntetisk person',email:'synthetic-person@example.test',role,owner};
 st.settings.owners=owners;st.settings.sellerProfilesInitialized=initialized;
 st.settings.sellerProfiles=initialized?[
  {id:profileA,legacyOwnerName:nameA,displayName:'Samma syntetiska visningsnamn',memberId:link==='a'?'synthetic-member':'',active:true,linkHistory:[],retirementHistory:[]},
  {id:profileB,legacyOwnerName:nameB,displayName:'Samma syntetiska visningsnamn',memberId:link==='b'?'synthetic-member':'',active:!inactive,linkHistory:[],retirementHistory:[]}
 ]:[];
 const customer=(id,profile='',onboardingOwner=nameA,customerOwner=nameB,extra={})=>core.CustomerSchema.parse({id,name:'Syntetisk onboarding '+id,owner:customerOwner,status:'onboarding',onboarding:{owner:onboardingOwner,ownerProfileId:profile,dealId:id+'-deal',startedAt:at,due:'2026-10-20'},...extra});
 st.customers=[...(initialized?[customer('profile-a',profileA,nameA,nameB),customer('profile-b',profileB,nameB,nameA)]:[]),
  customer('legacy-a','',nameA,nameB),customer('legacy-b','',nameB,nameA),
  customer('fallback-a','','',nameA),customer('fallback-b','','',nameB),
  customer('sentinel','','_unassigned',nameA),customer('removed-alias','','Syntetisk borttagen ansvarig',nameA)];
 st.deals=st.customers.map(c=>core.DealSchema.parse({id:c.onboarding.dealId,customerId:c.id,owner:c.owner,title:'Syntetisk första affär '+c.id,stage:'won',confirmed:true,value:1000,cost:500,wonAt:at}));
 st.orders=st.deals.map(d=>core.OrderSchema.parse({id:d.customerId+'-order',customerId:d.customerId,dealId:d.id,owner:d.owner,stage:'delivered',proofRequired:false,proofApproved:false,supplierConfirmed:true,deliveryDate:'2026-10-10',deliveredDate:'2026-10-10',invoiceDate:'',invoiceRef:'',invoiceValue:null,actualCost:null,notes:'Syntetiskt underlag, inga verkliga order ändras'}));
 return core.normalizeState(st);
}

// Run the real scope, notice, workflow and complete page expressions. UI hosts,
// unopened editor dialogs and callback observation are controlled boundaries;
// this suite performs no HTTP, SQL, browser, account or customer writes.
export async function verifyOnboardingScope(){
 mkdirSync('work',{recursive:true});const directory=mkdtempSync(resolve('work/onboarding-scope-'));
 const compiled=new Set(),toTarget=file=>resolve(directory,file.replace(/\.tsx?$/,'.mjs')),helpers=resolve(directory,'helpers.mjs');
 writeFileSync(helpers,`import React from 'react';
const host=tag=>React.forwardRef(({children,...props},ref)=>React.createElement(tag,{...props,ref},children));
export const Button=host('button'),Progress=host('progress'),Tabs=host('tabs'),TabsList=host('tabs-list'),TabsTrigger=host('tabs-trigger');
export const Select=host('select'),SelectTrigger=host('select-trigger'),SelectValue=host('select-value'),SelectContent=host('select-content'),SelectItem=host('select-item');
export const CustomerWorkflowDraft=({request})=>React.createElement('synthetic-editor',{request});
export const IssueResponsibilityDialog=()=>{throw Error('Unrelated issue editor must remain closed')};
`);
 function compile(file){
  file=relative(resolve('.'),resolve(file)).split(sep).join('/');assert.ok(file.startsWith('lib/')||['components/onboarding-scope-notice.tsx','components/crm-workflows.tsx'].includes(file));
  const target=toTarget(file);if(compiled.has(file))return target;compiled.add(file);
  let output=ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
  output=output.replace(/(from\s+|import\s*)['"]([^'"]+)['"]/g,(whole,prefix,specifier)=>{
   let dependency;
   if(specifier.startsWith('@/components/ui/')||file==='components/crm-workflows.tsx'&&['./customer-workflow-draft','./issue-responsibility-dialog'].includes(specifier))dependency=helpers;
   else if(specifier.startsWith('@/lib/'))dependency=compile('lib/'+specifier.slice(6)+'.ts');
   else if(specifier.startsWith('./')||specifier.startsWith('../'))dependency=compile(resolve(dirname(file),specifier)+'.ts');
   else return whole;
   let local=relative(dirname(target),dependency).split(sep).join('/');if(!local.startsWith('.'))local='./'+local;return prefix+JSON.stringify(local);
  });mkdirSync(dirname(target),{recursive:true});writeFileSync(target,output);return target;
 }
 const originals=Object.fromEntries(['fetch','IS_REACT_ACT_ENVIRONMENT'].map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));
 let renderer,count=0,calls=[],http=[];
 const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;};
 const text=node=>typeof node==='string'?node:Array.isArray(node)?node.map(text).join(''):node?.children?.map(text).join('')||'';
 const content=()=>text(renderer.toJSON()),button=caption=>renderer.root.findAllByType('button').find(node=>text(node)===caption);
 const cards=()=>renderer.root.findAll(node=>node.type==='section'&&node.props.className?.split(' ').includes('wf-card'));
 const cardIds=()=>cards().map(card=>card.findAllByType('button').find(node=>node.props['data-customer-id'])?.props['data-customer-id']);
  const summary=()=>{const container=renderer.root.findAll(node=>node.type==='div'&&node.props.className==='wf-summary')[0];assert.ok(container);return container.findAllByType('strong').map((node,index)=>({count:Number(text(node)),caption:text(container.findAllByType('span')[index])}));};
 const diagnostic=kind=>{const nodes=renderer.root.findAll(node=>node.type==='section'&&node.props['data-profile-diagnostic']);assert.equal(nodes.length,kind?1:0);if(kind){const notice=nodes[0];assert.equal(notice.props['data-profile-diagnostic'],kind);assert.equal(notice.props.role,'status');assert.ok(notice.findAllByType('h2').some(heading=>heading.props.id===notice.props['aria-labelledby']));assert.equal(renderer.root.findAllByType('section')[0],notice,'Notice precedes workflow cards');assert.match(text(notice),/inte en bekräftad fullständig onboardinglista/);}};
 async function unmount(){if(renderer){await act(async()=>renderer.unmount());renderer=null;}}
 async function scenario(label,run){await unmount();calls=[];await run();await unmount();assert.equal(http.length,0,'No HTTP in '+label);count++;console.log('PASS Onboarding scope: '+label);}
 async function click(caption){const node=button(caption);assert.ok(node,'Expected '+caption);assert.ok(!node.props.disabled,'Enabled '+caption);await act(async()=>node.props.onClick());}
 try{
  Object.defineProperty(globalThis,'IS_REACT_ACT_ENVIRONMENT',{configurable:true,writable:true,value:true});
  Object.defineProperty(globalThis,'fetch',{configurable:true,writable:true,value:async(...args)=>{http.push(args);throw Error('Onboarding scope must not perform HTTP');}});
  const core=await import(pathToFileURL(compile('lib/crm.ts')).href),domain=await import(pathToFileURL(compile('lib/onboarding-scope.ts')).href),dashboard=await import(pathToFileURL(compile('lib/sales-dashboard.ts')).href);
  const noticePath=compile('components/onboarding-scope-notice.tsx'),workflowPath=compile('components/crm-workflows.tsx');
  // Extract complete production selectors, scope options, navigation, role
  // gates and both JSX expressions unchanged. The full CRM root is not mounted.
  const source=readFileSync('app/page.tsx','utf8'),ast=ts.createSourceFile('app/page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),nodes=[];
  function visit(node){nodes.push(node);ts.forEachChild(node,visit);}visit(ast);
  const variable=name=>{const matches=nodes.filter(node=>ts.isVariableDeclaration(node)&&node.name.getText(ast)===name);assert.equal(matches.length,1,'Exactly one actual declaration '+name);return matches[0].initializer.getText(ast);};
  const element=tag=>{const found=nodes.filter(node=>(ts.isJsxSelfClosingElement(node)||ts.isJsxElement(node))&&(ts.isJsxElement(node)?node.openingElement.tagName:node.tagName).getText(ast)===tag);assert.equal(found.length,1,'Exactly one actual '+tag);return found[0];};
  const jsxCondition=tag=>{let found=element(tag);while(!ts.isJsxExpression(found)){assert.ok(found.parent);found=found.parent;}assert.ok(found.expression);return found.expression.getText(ast);};
  const toolbar=nodes.filter(node=>ts.isJsxSelfClosingElement(node)&&node.tagName.getText(ast)==='Choice'&&node.attributes.properties.some(attr=>ts.isJsxAttribute(attr)&&attr.name.getText(ast)==='label'&&ts.isStringLiteral(attr.initializer)&&attr.initializer.text==='Ansvarig'));assert.equal(toolbar.length,1);
  const options=toolbar[0].attributes.properties.find(attr=>ts.isJsxAttribute(attr)&&attr.name.getText(ast)==='options').initializer.expression.getText(ast);
  const caption=nodes.filter(node=>ts.isJsxElement(node)&&node.openingElement.tagName.getText(ast)==='span'&&node.openingElement.attributes.properties.some(attr=>ts.isJsxAttribute(attr)&&attr.name.getText(ast)==='className'&&ts.isStringLiteral(attr.initializer)&&attr.initializer.text==='scope-caption'));assert.equal(caption.length,1);const captionExpression=caption[0].children.find(ts.isJsxExpression).expression.getText(ast);
  const navigate=nodes.filter(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='navigate');assert.equal(navigate.length,1);
  const save=nodes.filter(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='save');assert.equal(save.length,1);
  const parentFile=resolve(directory,'actual-parent.mjs'),scopeDeclarations=['customers','onboardingScopeState','onboardingCustomers','issueScope','issueCustomers','issueScopeLabel'].map(name=>'const '+name+'=('+variable(name)+');').join('\n');
  const controls='const save=(...args)=>{calls.push({kind:"save",args});throw Error("No CRM write allowed")},refresh=()=>{throw Error("No refresh allowed")},refreshResponsibility=refresh,workflowResume=null,setWorkflowResume=value=>calls.push({kind:"resume",value}),showCustomer=id=>calls.push({kind:"customer",id}),create=()=>{throw Error("No create allowed")},open=()=>{throw Error("No open allowed")},setRepeatCustomer=()=>{throw Error("No repeat allowed")};';
  const code=`import React from 'react';import {OnboardingScopeNotice} from ${JSON.stringify(pathToFileURL(noticePath).href)};import {CustomerWorkflows} from ${JSON.stringify(pathToFileURL(workflowPath).href)};import {onboardingScope,onboardingCustomerInScope} from ${JSON.stringify(pathToFileURL(compile('lib/onboarding-scope.ts')).href)};import {personalOwner,personalResultScope} from ${JSON.stringify(pathToFileURL(compile('lib/sales-dashboard.ts')).href)};import {sellerProfileForOwner} from ${JSON.stringify(pathToFileURL(compile('lib/seller-profiles.ts')).href)};
const groups=(${variable('groups')}),groupOf=(${variable('groupOf')});
export function selected(st,owner,search=''){${scopeDeclarations}return {scope:onboardingScopeState,customers:onboardingCustomers,portfolio:customers,issues:issueCustomers};}
export function frame(st,owner,search,selectedView,calls,busy=false,space='synthetic'){const viewerReady=(${variable('viewerReady')}),department=(${variable('department')}),view=(${variable('view')});${scopeDeclarations}${controls}const navigate=view=>calls.push({kind:'navigate',view});return <>{(${jsxCondition('OnboardingScopeNotice')})}{(${jsxCondition('CustomerWorkflows')})}</>;}
export function toolbar(st,owner,view){const onboardingScopeState=st?onboardingScope(st,owner):null;return {options:(${options}),caption:(${captionExpression})};}
export function actualNavigation(st,view,space,observed){const workspaceReturn={current:'old'},setResumeDraft=value=>observed.push({kind:'draft',value}),setResumeArticleDraft=value=>observed.push({kind:'articleDraft',value}),setSearch=value=>observed.push({kind:'search',value}),setOwner=value=>observed.push({kind:'owner',value}),setView=value=>observed.push({kind:'view',value});${navigate[0].getText(ast)}return navigate;}
export function parentSave(st,saving,activeSpace,space,toast){${save[0].getText(ast)}return save;}
`;
  writeFileSync(parentFile,ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText);const parent=await import(pathToFileURL(parentFile).href);
  const fixture=options=>onboardingScopeFixture(core,options),scope=(st,owner=dashboard.personalOwner(st)||'_unassigned')=>domain.onboardingScope(st,owner);
  const ids=(st,owner=dashboard.personalOwner(st)||'_unassigned',search='')=>{const before=JSON.stringify(st);freeze(st);const selected=parent.selected(st,owner,search),direct=st.customers.filter(c=>domain.onboardingCustomerInScope(c,scope(st,owner)));assert.deepEqual(parent.selected(st,owner,'').customers,direct,'Actual parent delegates its row gate to production helper');assert.equal(JSON.stringify(st),before);return selected.customers.map(c=>c.id);};
  async function render(st,owner=dashboard.personalOwner(st)||'_unassigned',{search='',view='onboarding',busy=false,update=false,space='synthetic'}={}){const before=JSON.stringify(st);freeze(st);await act(async()=>{const tree=parent.frame(st,owner,search,view,calls,busy,space);if(update){assert.ok(renderer);renderer.update(tree);}else renderer=create(tree);});assert.equal(JSON.stringify(st),before,'Render preserves normalized fixture bytes');return()=>assert.equal(JSON.stringify(st),before,'Callbacks preserve normalized fixture bytes');}
  const selected=(expected,st,owner)=>{assert.deepEqual(ids(st,owner),expected);assert.deepEqual(cardIds(),expected);};

  await scenario('exact member-linked B wins over account alias A and identical profile display names',async()=>{const st=fixture(),unchanged=await render(st);selected(['profile-b','legacy-a','fallback-a'],st);assert.equal(scope(st).profileId,profileB);assert.equal(scope(st).legacyOwner,nameA);diagnostic('mismatch');assert.ok(content().includes(nameB));await click('Kundkort');assert.deepEqual(calls,[{kind:'customer',id:'profile-b'}]);unchanged();});
  await scenario('missing account alias retains own exact B without adopting its historic legacy alias',async()=>{const st=fixture({owner:''}),unchanged=await render(st);selected(['profile-b'],st);diagnostic('operational-missing');assert.equal(scope(st).legacyOwner,'');unchanged();});
  await scenario('removed operative alias retains own ID but never stale legacy or sentinel rows',async()=>{const st=fixture({owner:'Syntetisk borttagen ansvarig',owners:[nameB]}),unchanged=await render(st);selected(['profile-b'],st);diagnostic('operational-missing');unchanged();});
  await scenario('missing member link never adopts matching A; only valid blank-ID legacy A remains',async()=>{const st=fixture({link:''}),unchanged=await render(st);selected(['legacy-a','fallback-a'],st);assert.equal(scope(st).profileId,'');diagnostic('missing');unchanged();});
  await scenario('missing profile and alias explain incomplete empty selection without sentinel fallback',async()=>{const st=fixture({link:'',owner:''}),unchanged=await render(st);selected([],st);diagnostic('missing');assert.match(content(),/saknar giltigt kundansvar och koppling/);unchanged();});
  await scenario('runtime user ID never substitutes for missing immutable member ID',async()=>{const st=fixture({memberId:''});st.viewer.id='synthetic-member';const unchanged=await render(st);selected(['legacy-a','fallback-a'],st);diagnostic('missing');unchanged();});
  await scenario('inactive linked profile preserves exact history without activation or relinking',async()=>{const st=fixture({inactive:true,owner:'',owners:[nameA]}),unchanged=await render(st);selected(['profile-b'],st);diagnostic('operational-missing');assert.equal(st.settings.sellerProfiles[1].active,false);unchanged();});
  await scenario('explicit other active alias selects its profile and legacy rows instead of personal B',async()=>{const st=fixture({owner:nameB}),unchanged=await render(st,nameA);selected(['profile-a','legacy-a','fallback-a'],st,nameA);assert.equal(scope(st,nameA).personal,false);assert.equal(scope(st,nameA).profileId,profileA);diagnostic('');unchanged();});
  await scenario('explicit valid B alias may show B with its own legacy work while account A remains unchanged',async()=>{const st=fixture(),unchanged=await render(st,nameB);selected(['profile-b','legacy-b','fallback-b'],st,nameB);assert.equal(scope(st,nameB).personal,false);diagnostic('');unchanged();});
  for(const role of ['seller','reader','admin'])await scenario(role+' retains established all-team onboarding reading',async()=>{const st=fixture({role,link:'',owner:''}),unchanged=await render(st,'all');selected(st.customers.map(c=>c.id),st,'all');assert.equal(scope(st,'all').team,true);diagnostic('');assert.equal(parent.toolbar(st,'all','onboarding').caption,'Teamets onboarding');unchanged();});
  for(const invalid of ['',profileB,'_unassigned','Syntetisk borttagen ansvarig'])await scenario('invalid explicit scope '+(invalid||'(empty)')+' never falls back to profile, alias or sentinel work',async()=>{const st=fixture(),unchanged=await render(st,invalid);selected([],st,invalid);assert.equal(scope(st,invalid).profileId,'');assert.equal(scope(st,invalid).legacyOwner,'');diagnostic('');unchanged();});
  await scenario('pre-initialization valid alias keeps blank-ID onboarding owner or customer fallback',async()=>{const st=fixture({initialized:false}),unchanged=await render(st);selected(['legacy-a','fallback-a'],st);assert.equal(scope(st).profileId,'');diagnostic('');unchanged();});
  await scenario('pre-initialization missing alias never adopts historic or sentinel names',async()=>{const st=fixture({initialized:false,owner:''}),unchanged=await render(st);selected([],st);assert.equal(scope(st).legacyOwner,'');diagnostic('');unchanged();});
  const fields=[['name',{name:'Syntetiskt Alfastart Företag'},'ALFASTART'],['contact',{contact:'Syntetisk Betakontakt'},'BETAKONTAKT'],['need',{need:'Syntetiskt Gammabehov'},'GAMMABEHOV'],['organizationNumber',{organizationNumber:'555555-ZETASOK'},'ZETASOK'],['plan-contact-name',{plan:{contacts:[{name:'Syntetisk Deltakontakt',email:'delta@example.test',role:'Syntetisk inköpskontakt'}]}},'DELTAKONTAKT'],['plan-contact-email',{plan:{contacts:[{name:'Syntetisk Kontakt',email:'epsilon@example.test',role:'Syntetisk inköpskontakt'}]}},'EPSILON@EXAMPLE.TEST']];
  for(const [field,patch,search] of fields)await scenario('actual page case-insensitive '+field+' search remains constrained to selected profile',async()=>{const st=fixture();for(const index of [0,1])st.customers[index]=core.CustomerSchema.parse({...st.customers[index],...patch});core.normalizeState(st);const unchanged=await render(st,undefined,{search});assert.deepEqual(ids(st,undefined,search),['profile-b']);assert.deepEqual(cardIds(),['profile-b']);diagnostic('mismatch');unchanged();});
  await scenario('actual toolbar labels distinguish personal, explicit, missing-profile and team selections',async()=>{for(const options of [{},{owner:''},{link:''},{initialized:false}]){const st=fixture(options),owner=dashboard.personalOwner(st)||'_unassigned',actual=parent.toolbar(st,owner,'onboarding');assert.equal(actual.caption,scope(st,owner).caption);assert.equal(new Set(actual.options.map(option=>option.id)).size,actual.options.length);assert.ok(actual.options.some(option=>option.id==='all'&&option.label==='Teamets onboarding'));assert.ok(actual.options.some(option=>option.id===owner&&option.label.startsWith('Min onboarding')));assert.equal(st.viewer.owner,options.owner??nameA);}const st=fixture();assert.equal(parent.toolbar(st,nameB,'onboarding').caption,'Onboarding · '+nameB);});
  await scenario('completed onboarding and no-start records retain actual workflow tab rules',async()=>{const st=fixture();st.customers[1].onboarding.completedAt=at;st.customers.push(core.CustomerSchema.parse({id:'not-started',name:'Syntetisk ej påbörjad',owner:nameA,status:'prospect'}));core.normalizeState(st);const unchanged=await render(st);assert.deepEqual(ids(st),['profile-b','legacy-a','fallback-a','not-started']);assert.deepEqual(cardIds(),['legacy-a','fallback-a']);await act(async()=>renderer.root.findByType('tabs').props.onValueChange('done'));assert.deepEqual(cardIds(),['profile-b']);assert.equal(button('Öppna kundplan').props.disabled,false);unchanged();});
  await scenario('mismatch summary counts only two active, one late and one completed visible onboarding',async()=>{const st=fixture();st.customers.find(c=>c.id==='legacy-a').onboarding.due='2000-01-01';st.customers.find(c=>c.id==='fallback-a').onboarding.completedAt=at;core.normalizeState(st);const unchanged=await render(st);diagnostic('mismatch');assert.deepEqual(summary(),[{count:2,caption:'Pågående onboarding i synligt urval'},{count:1,caption:'Försenade i synligt urval'},{count:1,caption:'Överlämnade till CSM i synligt urval'}]);assert.deepEqual(cardIds(),['profile-b','legacy-a']);await act(async()=>renderer.root.findByType('tabs').props.onValueChange('done'));assert.deepEqual(cardIds(),['fallback-a']);assert.equal(summary()[0].count,2,'Changing tab does not redefine the ongoing total');unchanged();});
  for(const kind of ['missing','operational-missing'])await scenario(kind+' empty subset gives honest zero counts and empty messages in both actual tabs',async()=>{const st=fixture(kind==='missing'?{link:''}:{owner:''});if(kind==='missing'){for(const id of ['legacy-a','fallback-a']){const row=st.customers.find(c=>c.id===id);row.onboarding.owner=nameB;row.owner=nameB;}}else{const row=st.customers.find(c=>c.id==='profile-b');row.onboarding.ownerProfileId=profileA;row.onboarding.owner=nameA;}core.normalizeState(st);const unchanged=await render(st);diagnostic(kind);assert.deepEqual(cardIds(),[]);assert.deepEqual(summary(),[{count:0,caption:'Pågående onboarding i synligt urval'},{count:0,caption:'Försenade i synligt urval'},{count:0,caption:'Överlämnade till CSM i synligt urval'}]);assert.ok(content().includes('Ingen pågående onboarding visas i detta urval.'));assert.ok(content().includes('Kontokopplingen behöver kontrolleras innan listan kan bedömas som fullständig.'));assert.ok(!content().includes('Första vunna affären hos ett prospekt startar onboarding automatiskt.'));await act(async()=>renderer.root.findByType('tabs').props.onValueChange('done'));assert.ok(content().includes('Ingen avslutad onboarding visas i detta urval.'));assert.deepEqual(cardIds(),[]);unchanged();});
  await scenario('healthy and team summaries preserve full-list captions, while prospects and care never receive subset mode',async()=>{const st=fixture({link:'a'}),unchanged=await render(st);diagnostic('');assert.deepEqual(summary(),[{count:3,caption:'Pågående onboarding'},{count:0,caption:'Försenade'},{count:0,caption:'Överlämnade till CSM'}]);await render(st,'all',{update:true});assert.deepEqual(summary(),[{count:8,caption:'Pågående onboarding'},{count:0,caption:'Försenade'},{count:0,caption:'Överlämnade till CSM'}]);for(const view of ['prospects','care']){const fragment=parent.frame(st,nameA,'',view,[]),workflow=fragment.props.children[1];assert.equal(workflow.props.onboardingVisibleSubset,false);await render(st,nameA,{update:true,view});diagnostic('');assert.ok(!content().includes('onboarding i synligt urval'));}unchanged();});
  for(const [options,kind,action,route] of [[{role:'admin'},'mismatch','Öppna Mål & inställningar','settings'],[{role:'admin',link:''},'missing','Öppna Mål & inställningar','settings'],[{role:'admin',owner:''},'operational-missing','Öppna Konton & roller','accounts']])await scenario('administrator '+kind+' repair uses actual notice and parent navigation callback',async()=>{const st=fixture(options),unchanged=await render(st);diagnostic(kind);await click(action);assert.deepEqual(calls,[{kind:'navigate',view:route}]);const observed=[];parent.actualNavigation(st,'onboarding','synthetic',observed)(route);assert.deepEqual(observed,[{kind:'search',value:''},{kind:'view',value:route}]);unchanged();});
  for(const role of ['seller','reader'])await scenario(role+' receives administrator guidance without self-service role or profile writes',async()=>{const st=fixture({role}),unchanged=await render(st);diagnostic('mismatch');assert.match(content(),/Be en administratör/);assert.equal(button('Öppna Mål & inställningar'),undefined);assert.equal(button('Öppna Konton & roller'),undefined);assert.equal(button('Öppna checklistan').props.disabled,role==='reader');unchanged();});
  await scenario('reader direct checklist handler and whole parent save reject edits before any flush or HTTP',async()=>{const st=fixture({role:'reader'}),unchanged=await render(st);await act(async()=>button('Öppna checklistan').props.onClick());assert.equal(renderer.root.findAllByType('synthetic-editor').length,0);const observed=[],saving={current:false},save=parent.parentSave(st,saving,{current:'synthetic'},'synthetic',{error:message=>observed.push({kind:'error',message})});assert.equal(await save('onboarding',{customerId:'profile-b'}),false);assert.deepEqual(observed,[{kind:'error',message:'Ditt konto har läsbehörighet.'}]);observed.length=0;assert.equal(await save('onboarding',{customerId:'profile-b'},false,{onFailure:(status,message)=>observed.push({kind:'failure',status,message})}),false);assert.deepEqual(observed,[{kind:'failure',status:403,message:'Ditt konto har läsbehörighet.'}]);assert.equal(saving.current,false);assert.deepEqual(calls,[]);unchanged();});
  for(const role of ['production','print','warehouse'])await scenario(role+' remembered onboarding view remains gated to its operative workspace',async()=>{const st=fixture({role}),unchanged=await render(st);assert.equal(renderer.toJSON(),null,'Actual parent conditions render no onboarding fragment for operative roles');assert.deepEqual(calls,[]);unchanged();});
  await scenario('account, scope, workspace and reader updates keep selection fresh without cached personal work',async()=>{const a=fixture(),unchangedA=await render(a);assert.deepEqual(cardIds(),['profile-b','legacy-a','fallback-a']);await click('Öppna checklistan');assert.equal(renderer.root.findByType('synthetic-editor').props.request.customerId,'profile-b');const b=fixture({link:'a',owner:nameB});b.viewer.id='synthetic-other-session';const unchangedB=await render(b,undefined,{update:true,space:'synthetic-other'});assert.deepEqual(cardIds(),['profile-a','legacy-b','fallback-b']);assert.equal(renderer.root.findAllByType('synthetic-editor').length,0);diagnostic('mismatch');const reader=fixture({role:'reader',owner:''}),unchangedReader=await render(reader,undefined,{update:true});assert.deepEqual(cardIds(),['profile-b']);assert.equal(button('Öppna checklistan').props.disabled,true);diagnostic('operational-missing');unchangedA();unchangedB();unchangedReader();});
  await scenario('diagnostic only renders on onboarding and clears on healthy profile, explicit or team scope',async()=>{const st=fixture();await render(st);diagnostic('mismatch');await render(st,'all',{update:true});diagnostic('');await render(st,nameB,{update:true});diagnostic('');await render(st,undefined,{update:true,view:'prospects'});diagnostic('');await render(fixture({link:'a'}),undefined,{update:true});diagnostic('');});
  console.log('PASS Onboarding scope: '+count+' normalized domain/actual parent/React cases; immutable input, zero HTTP; controlled presentation and unopened editor boundaries, no browser, personal login or staff acceptance.');
  return {cases:count,compiledModules:compiled.size,httpRequests:http.length};
 }finally{await unmount();rmSync(directory,{recursive:true,force:true});for(const [key,descriptor] of Object.entries(originals)){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}}
}
