import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {dirname,relative,resolve,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
import React,{act} from 'react';
import {create} from 'react-test-renderer';

const profileA='d5746101-f76b-4ec7-9f44-90d7e9c5a001',profileB='d5746101-f76b-4ec7-9f44-90d7e9c5a002';
const nameA='Syntetiskt orderansvar A',nameB='Syntetiskt orderansvar B',removedName='Syntetiskt borttaget orderansvar';
const groups=['active','receipt','invoice','history'];
const responsibilities=['a','b','legacy-a','legacy-b','sentinel','removed'];
const expected=(suffixes,stages=groups)=>stages.flatMap(stage=>suffixes.map(suffix=>stage+'-'+suffix));

// Every row passes actual schemas and reference validation. Customer and deal
// responsibility deliberately differs from the order. All data is synthetic.
export function orderScopeFixture(core,{link='b',owner=nameA,role='seller',initialized=true,inactive=false,memberId='synthetic-order-member',owners=[nameA,nameB]}={}){
 const st=core.emptyState(),today=core.day();
 st.viewer={id:'synthetic-order-session',memberId,name:'Syntetisk person',email:'synthetic-order-person@example.test',role,owner};
 st.settings.owners=owners;st.settings.sellerProfilesInitialized=initialized;
 st.settings.sellerProfiles=initialized?[
  {id:profileA,legacyOwnerName:nameA,displayName:'Samma syntetiska visningsnamn',memberId:link==='a'?'synthetic-order-member':'',active:true,linkHistory:[],retirementHistory:[]},
  {id:profileB,legacyOwnerName:nameB,displayName:'Samma syntetiska visningsnamn',memberId:link==='b'?'synthetic-order-member':'',active:!inactive,linkHistory:[],retirementHistory:[]}
 ]:[];
 st.customers=[core.CustomerSchema.parse({id:'synthetic-order-customer',name:'Syntetisk orderkund',owner:nameA,ownerProfileId:initialized?profileA:'',contact:'Syntetisk provkontakt',status:'closed'})];
 for(const group of groups)for(const responsibility of responsibilities){
  if(!initialized&&['a','b'].includes(responsibility))continue;
  const id=group+'-'+responsibility,assigned=responsibility==='b'||responsibility==='legacy-b'?nameB:responsibility==='sentinel'?'_unassigned':responsibility==='removed'?removedName:nameA;
  const profile=responsibility==='a'?profileA:responsibility==='b'?profileB:'';
  const line={id:'line-'+id,description:'Syntetisk provartikel',article:'SYNTHETIC',quantity:2,unitPrice:50,unitCost:10};
  const deal=core.DealSchema.parse({id:'deal-'+id,customerId:'synthetic-order-customer',owner:nameA,ownerProfileId:initialized?profileA:'',title:'Syntetisk order '+id,stage:'won',confirmed:true,value:100,cost:20,wonAt:today,lines:[line]});
  st.deals.push(deal);
  st.orders.push(core.OrderSchema.parse({id,customerId:deal.customerId,dealId:deal.id,owner:assigned,ownerProfileId:profile,stage:group==='active'?'production':group==='receipt'?'shipping':group==='invoice'?'delivered':'followed',proofRequired:false,proofApproved:false,supplierConfirmed:true,deliveryDate:today,deliveredDate:['invoice','history'].includes(group)?today:'',receivedBy:['invoice','history'].includes(group)?'Syntetiskt mottagningsunderlag':'',invoiceDate:group==='history'?today:'',invoiceRef:group==='history'?'SYNTHETIC-'+id:'',invoiceValue:group==='history'?100:null,actualCost:group==='history'?20:null,invoiceOwner:group==='history'?assigned:'',invoiceOwnerId:group==='history'?profile:'',invoiceOwnerSource:'recorded',notes:'Syntetisk orderregression',production:group==='active'?{status:'submitted',workId:'work-'+id,issue:'SYNTHETIC_ISSUE_'+id,issueOwnerId:id==='active-a'?'synthetic-order-session':'synthetic-other-session',issueOwnerName:'Syntetisk rapportör',issueAt:'2026-10-01T10:00:00Z',printDeadline:today,dispatchDeadline:today,deliveryDate:today}:{},directShipments:group==='invoice'?[{id:'shipment-'+id,entries:[{lineId:line.id,quantity:2}],dispatchedOn:today,method:'carrier',recipient:'Syntetisk mottagare',address:{},evidence:'Syntetiskt avsändningsunderlag',recordedAt:'2026-10-01T10:00:00Z',recordedById:'synthetic-shipper',recordedBy:'Syntetisk avsändare'}]:[]}));
  // A receipt projection can retain a different historical profile. Its due
  // date remains useful; the order's responsibility determines visibility.
  if(group==='receipt')st.tasks.push(core.TaskSchema.parse({id:'receipt-task-'+id,customerId:deal.customerId,dealId:deal.id,owner:initialized?(responsibility==='b'?nameA:nameB):assigned,ownerProfileId:initialized?(responsibility==='b'?profileA:profileB):'',title:'Syntetisk äldre kvittensuppgift '+id,due:today,kind:'receipt'}));
 }
 return core.normalizeState(st);
}

// Actual components, domain modules, page JSX and navigation statements run.
// Only visual primitives, private draft loading and closed unrelated dialogs
// are boundaries. No browser, personal login, live data or network is used.
export async function verifyOrderScope(){
 mkdirSync('work',{recursive:true});const directory=mkdtempSync(resolve('work/order-scope-'));
 const compiled=new Set(),sourceBytes=new Map(),toTarget=file=>resolve(directory,file.replace(/\.tsx?$/,'.mjs')),helpers=resolve(directory,'helpers.mjs');
 const remember=file=>{const bytes=readFileSync(file);if(sourceBytes.has(file))assert.deepEqual(bytes,sourceBytes.get(file));else sourceBytes.set(file,bytes);return bytes.toString('utf8');};
 writeFileSync(helpers,`import React from 'react';const host=tag=>React.forwardRef(({children,...props},ref)=>React.createElement(tag,{...props,ref},children));
export const Button=host('button'),Input=host('input'),Textarea=host('textarea'),Progress=host('progress'),Tabs=host('tabs'),TabsList=host('tabs-list'),TabsTrigger=host('tabs-trigger'),Choice=host('choice');
export const Sheet=({open,children})=>open?React.createElement('sheet',{},children):null,SheetContent=host('sheet-content'),SheetHeader=host('sheet-header'),SheetTitle=host('sheet-title'),SheetDescription=host('sheet-description');
export const BusinessField=host('field'),Pick=host('pick');
export const useDrafts=()=>({ready:true,records:[],archive:async()=>{throw Error('Unexpected private draft write')}});
export const DraftStatus=()=>null,PrivateDraftCopyEntry=()=>null,ReceiptDraftPreview=()=>null,ArticleDraftPreview=()=>null,YearwheelResponsibilityDraftPreview=()=>null,YearNeedDraftPreview=()=>null,CompanyEventDraftPreview=()=>null,TaskResponsibility=()=>null,TaskResponsibilityHistory=()=>null,MeetingResponsibility=()=>null,OrderChanges=()=>null,ProductionProgress=()=>null,QuantityDialog=()=>null,ProductionIssueResponsibilityHistory=()=>null,ReceiptDialog=()=>null;`);
 const formatterSource=remember('components/business-ui.tsx'),formatterAst=ts.createSourceFile('business-ui.tsx',formatterSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
 const formatters=formatterAst.statements.filter(statement=>ts.isVariableStatement(statement)&&statement.declarationList.declarations.some(declaration=>ts.isIdentifier(declaration.name)&&['money','displayDate'].includes(declaration.name.text)));assert.equal(formatters.length,2);
 const formatterFile=resolve(directory,'formatters.mjs');writeFileSync(formatterFile,ts.transpileModule(formatters.map(statement=>statement.getText(formatterAst)).join('\n')+`\nexport {BusinessField,Pick} from ${JSON.stringify(pathToFileURL(helpers).href)};`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
 const actualComponents=new Set(['components/production-board.tsx','components/receipt-queue.tsx','components/my-day.tsx']);
 function compile(file){
  file=relative(resolve('.'),resolve(file)).split(sep).join('/');assert.ok(file.startsWith('lib/')||actualComponents.has(file),'Only actual domains and target components are compiled');
  const target=toTarget(file);if(compiled.has(file))return target;compiled.add(file);
  let output=ts.transpileModule(remember(file),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
  output=output.replace(/(from\s+|import\s*)['"]([^'"]+)['"]/g,(whole,prefix,specifier)=>{
   let dependency;
   if(actualComponents.has(file)&&specifier==='./business-ui')dependency=formatterFile;
   else if(file==='components/my-day.tsx'&&specifier==='./receipt-queue')dependency=compile('components/receipt-queue.tsx');
   else if(specifier.startsWith('@/components/')||actualComponents.has(file)&&specifier.startsWith('./'))dependency=helpers;
   else if(specifier.startsWith('@/lib/'))dependency=compile('lib/'+specifier.slice(6)+'.ts');
   else if(specifier.startsWith('./')||specifier.startsWith('../'))dependency=compile(resolve(dirname(file),specifier)+'.ts');
   else return whole;
   let local=relative(dirname(target),dependency).split(sep).join('/');if(!local.startsWith('.'))local='./'+local;return prefix+JSON.stringify(local);
  });mkdirSync(dirname(target),{recursive:true});writeFileSync(target,output);return target;
 }
 const originals=Object.fromEntries(['fetch','IS_REACT_ACT_ENVIRONMENT'].map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));
 let renderer,count=0,calls=[],http=[];
 const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value)}return value;};
 const text=node=>typeof node==='string'?node:Array.isArray(node)?node.map(text).join(''):node?.children?.map(text).join('')||'';
 const byClass=name=>renderer.root.findAll(node=>typeof node.type==='string'&&node.props.className?.split(' ').includes(name));
 const button=label=>renderer.root.findAllByType('button').find(node=>text(node)===label);
 const rowIds=nodes=>nodes.map(node=>{const title=node.findAllByType('b')[0]||node.findAllByType('h3')[0];return text(title).replace('Syntetisk order ','');});
 const boardIds=()=>byClass('production-card').map(node=>text(node.findAllByType('h3')[0]).replace('Syntetisk order ',''));
 const receiptIds=()=>rowIds(byClass('receipt-queue')[0].findAll(node=>node.type==='div'&&node.props.className==='daily-row'));
 const blockedIds=()=>{const section=renderer.root.findAll(node=>node.type==='section'&&node.props.id==='daily-blocked')[0];return section?rowIds(section.findAll(node=>node.type==='div'&&node.props.className==='daily-row')):[];};
 async function unmount(){if(renderer){await act(async()=>renderer.unmount());renderer=null}}
 async function scenario(label,run){await unmount();calls=[];await run();await unmount();assert.equal(http.length,0,'Zero HTTP in '+label);count++;console.log('PASS Order scope: '+label);}
 async function click(label){const node=button(label);assert.ok(node,'Expected '+label);assert.ok(!node.props.disabled);await act(async()=>node.props.onClick());}
 try{
  Object.defineProperty(globalThis,'IS_REACT_ACT_ENVIRONMENT',{configurable:true,writable:true,value:true});
  Object.defineProperty(globalThis,'fetch',{configurable:true,writable:true,value:async(...args)=>{http.push(args);throw Error('Order scope must not perform HTTP')}});
  const core=await import(pathToFileURL(compile('lib/crm.ts')).href),domain=await import(pathToFileURL(compile('lib/order-scope.ts')).href),dashboard=await import(pathToFileURL(compile('lib/sales-dashboard.ts')).href);
  const {ProductionBoard}=await import(pathToFileURL(compile('components/production-board.tsx')).href),{ReceiptQueue}=await import(pathToFileURL(compile('components/receipt-queue.tsx')).href),{MyDay}=await import(pathToFileURL(compile('components/my-day.tsx')).href);
  const source=remember('app/page.tsx'),ast=ts.createSourceFile('app/page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),nodes=[];(function visit(node){nodes.push(node);ts.forEachChild(node,visit)})(ast);
  const variable=name=>{const matches=nodes.filter(node=>ts.isVariableDeclaration(node)&&node.name.getText(ast)===name);assert.equal(matches.length,1,'One actual declaration '+name);return matches[0].initializer.getText(ast);};
  const declaration=name=>{const matches=nodes.filter(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name);assert.equal(matches.length,1,'One actual function '+name);return matches[0].getText(ast);};
  const fragment=nodes.filter(node=>ts.isJsxExpression(node)&&node.expression?.getText(ast).startsWith("view==='orders'&&orderScopeState&&")&&node.expression.getText(ast).includes('<OrderScopeNotice '));assert.equal(fragment.length,1,'One complete actual Orders selector and notice');
  const boardFragment=nodes.filter(node=>ts.isJsxExpression(node)&&node.expression&&ts.isBinaryExpression(node.expression)&&node.expression.right.getText(ast).startsWith('<ProductionBoard '));assert.equal(boardFragment.length,1,'One complete actual production board condition');
  const receiptFragment=nodes.filter(node=>ts.isJsxExpression(node)&&node.expression?.getText(ast).startsWith("view==='orders'&&<ReceiptQueue "));assert.equal(receiptFragment.length,1,'One complete actual Orders receipt condition');
  const result=nodes.find(node=>ts.isJsxSelfClosingElement(node)&&node.tagName.getText(ast)==='SalesDashboard').attributes.properties.find(attr=>ts.isJsxAttribute(attr)&&attr.name.getText(ast)==='onView').initializer.expression.getText(ast);
  const dashboardSource=remember('components/sales-dashboard.tsx'),dashboardAST=ts.createSourceFile('sales-dashboard.tsx',dashboardSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),dashboardNodes=[];(function visit(node){dashboardNodes.push(node);ts.forEachChild(node,visit)})(dashboardAST);
  const go=dashboardNodes.find(node=>ts.isVariableDeclaration(node)&&node.name.getText(dashboardAST)==='go').initializer.getText(dashboardAST);
  const parentFile=resolve(directory,'actual-parent.mjs');writeFileSync(parentFile,ts.transpileModule(`import React,{useId} from 'react';import {AlertTriangle} from 'lucide-react';import {Button,Choice} from ${JSON.stringify(pathToFileURL(helpers).href)};import {orderScope,orderInScope} from ${JSON.stringify(pathToFileURL(compile('lib/order-scope.ts')).href)};import {personalOwner,personalResultScope,resultOperationalOwner} from ${JSON.stringify(pathToFileURL(compile('lib/sales-dashboard.ts')).href)};import {ProductionBoard} from ${JSON.stringify(pathToFileURL(compile('components/production-board.tsx')).href)};import {ReceiptQueue} from ${JSON.stringify(pathToFileURL(compile('components/receipt-queue.tsx')).href)};
const groups=(${variable('groups')}),groupOf=(${variable('groupOf')});${declaration('OrderScopeNotice')}
export function selector(st,owner,selectedView,calls){const viewerReady=(${variable('viewerReady')}),department=(${variable('department')}),view=(${variable('view')}),orderScopeState=(${variable('orderScopeState')}),setOwner=value=>calls.push({kind:'owner',value}),navigate=view=>calls.push({kind:'navigate',view});return <>{(${fragment[0].expression.getText(ast)})}</>;}
export function pageOrders(st,owner,selectedView,calls){const viewerReady=(${variable('viewerReady')}),department=(${variable('department')}),view=(${variable('view')}),orderScopeState=(${variable('orderScopeState')}),space='synthetic-order-space',busy=false,save=(...args)=>calls.push({kind:'save',args}),setOwner=value=>calls.push({kind:'owner',value}),navigate=view=>calls.push({kind:'navigate',view}),open=(type,data)=>calls.push({kind:'open',type,data}),openReceipt=id=>calls.push({kind:'receipt',id}),setCommercialTransfer=data=>calls.push({kind:'transfer',data}),openOrderAnchor=data=>calls.push({kind:'anchor',data}),openProductionAssignment=data=>calls.push({kind:'assignment',data}),openProductionIssueResponsibility=data=>calls.push({kind:'issueResponsibility',data});return <>{(${fragment[0].expression.getText(ast)})}{(${boardFragment[0].expression.getText(ast)})}{(${receiptFragment[0].expression.getText(ast)})}</>;}
export function actualNavigation(st,view,observed){const workspaceReturn={current:'old'},setResumeDraft=value=>observed.push({kind:'draft',value}),setResumeArticleDraft=value=>observed.push({kind:'articleDraft',value}),setSearch=value=>observed.push({kind:'search',value}),setOwner=value=>observed.push({kind:'owner',value}),setView=value=>observed.push({kind:'view',value});${declaration('navigate')}return navigate;}
export function resultNavigation(st,view,setOwner,setSearch,setFilter,setView){return (${result});}
export function dashboardGo(st,owner,onView){return (${go});}
export function parentSave(st,saving,activeSpace,space,toast){${declaration('save')}return save;}`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText);
  const parent=await import(pathToFileURL(parentFile).href),fixture=options=>orderScopeFixture(core,options),own=st=>dashboard.personalOwner(st)||'_unassigned',scope=(st,owner=own(st))=>domain.orderScope(st,owner);
  const scopedIds=(st,owner=own(st))=>{const before=JSON.stringify(st);freeze(st);const result=st.orders.filter(order=>domain.orderInScope(order,scope(st,owner))).map(order=>order.id);assert.equal(JSON.stringify(st),before);return result;};
  const record=kind=>(...args)=>calls.push({kind,args});
  async function render(kind,st,owner=own(st),extra={}){const before=JSON.stringify(st);freeze(st);const props={st,owner,space:'synthetic-order-space',busy:false,save:record('save'),saveResponsibility:record('saveResponsibility'),refreshResponsibility:async()=>st,onOwnerChange:record('owner'),onCustomer:record('customer'),onTask:record('task'),onCreate:record('create'),onOrder:record('order'),onProductionOrder:record('productionOrder'),onMeeting:record('meeting'),onReceipt:record('receipt'),onView:record('view'),onDraft:record('draft'),onResponsibility:record('responsibility'),onResponsibilityAnchor:record('anchor'),mode:'sales',...extra};await act(async()=>{const tree=kind==='selector'?parent.selector(st,owner,'orders',calls):kind==='page'?parent.pageOrders(st,owner,'orders',calls):React.createElement({board:ProductionBoard,receipt:ReceiptQueue,day:MyDay}[kind],props);if(renderer)renderer.update(tree);else renderer=create(tree)});assert.equal(JSON.stringify(st),before);return()=>assert.equal(JSON.stringify(st),before,'Rendering and callbacks preserve normalized state');}
  async function tab(value){await act(async()=>renderer.root.findByType('tabs').props.onValueChange(value));}
  function diagnostic(kind){const notices=renderer.root.findAll(node=>node.type==='section'&&node.props['data-profile-diagnostic']);assert.equal(notices.length,kind?1:0);if(kind){assert.equal(notices[0].props['data-profile-diagnostic'],kind);assert.equal(notices[0].props.role,'status');assert.ok(notices[0].findAllByType('h2').some(node=>node.props.id===notices[0].props['aria-labelledby']));assert.match(text(notices[0]),/synligt urval/i);assert.match(text(notices[0]),/inte en bekräftad fullständig/i);}}

  const matrix=[
   ['exact member B plus valid account alias A',{},{suffixes:['b','legacy-a'],profile:profileB,alias:nameA,diagnostic:'mismatch'}],
   ['missing member-profile link',{link:''},{suffixes:['legacy-a'],profile:'',alias:nameA,diagnostic:'missing'}],
   ['removed immutable member link',{memberId:''},{suffixes:['legacy-a'],profile:'',alias:nameA,diagnostic:'missing'}],
   ['no account alias',{owner:''},{suffixes:['b'],profile:profileB,alias:'',diagnostic:'operational-missing'}],
   ['removed account alias',{owner:removedName},{suffixes:['b'],profile:profileB,alias:'',diagnostic:'operational-missing'}],
   ['inactive exact member B',{inactive:true},{suffixes:['b','legacy-a'],profile:profileB,alias:nameA,diagnostic:'mismatch'}],
   ['healthy exact member A',{link:'a'},{suffixes:['a','legacy-a'],profile:profileA,alias:nameA,diagnostic:''}],
   ['before profile initialization',{initialized:false},{suffixes:['legacy-a'],profile:'',alias:nameA,diagnostic:''}],
   ['before initialization without alias',{initialized:false,owner:''},{suffixes:[],profile:'',alias:'',diagnostic:''}],
   ['missing link and alias',{link:'',owner:''},{suffixes:[],profile:'',alias:'',diagnostic:'missing'}]
  ];
  for(const [label,options,want] of matrix)await scenario(label+' scopes all sales queues and their counts',async()=>{const st=fixture(options);assert.deepEqual(scopedIds(st),expected(want.suffixes));assert.deepEqual({profile:scope(st).profileId,alias:scope(st).legacyOwner,diagnostic:scope(st).diagnostic},{profile:want.profile,alias:want.alias,diagnostic:want.diagnostic});const unchanged=await render('board',st);assert.deepEqual(boardIds(),expected(want.suffixes,['active']).sort());assert.ok(byClass('biz-head')[0].findAllByProps({className:'pill'}).some(node=>text(node)===want.suffixes.length+' order'+(want.diagnostic?' · synligt urval':'')));assert.equal(text(renderer.root.findAllByType('tabs-trigger').find(node=>node.props.value==='invoice')),'Att fakturera ('+want.suffixes.length+')'+(want.diagnostic?' · synligt urval':''));await tab('invoice');assert.deepEqual(boardIds(),expected(want.suffixes,['invoice']).sort());await tab('history');assert.deepEqual(boardIds(),expected(want.suffixes,['receipt','invoice','history']).sort());await render('receipt',st);assert.deepEqual(receiptIds(),expected(want.suffixes,['receipt']));assert.equal(text(byClass('receipt-queue')[0].findByProps({className:'count'})),String(want.suffixes.length));unchanged();});
  await scenario('runtime user ID cannot substitute for immutable missing member ID',async()=>{const st=fixture({memberId:''});st.viewer.id='synthetic-order-member';core.normalizeState(st);assert.deepEqual(scopedIds(st),expected(['legacy-a']));assert.equal(scope(st).profileId,'');});
  for(const [owner,options,suffixes] of [[nameA,{owner:nameB},['a','legacy-a']],[nameB,{},['b','legacy-b']],['all',{},responsibilities]])await scenario('explicit selection '+owner+' resolves current roster profile or team',async()=>{const st=fixture(options),unchanged=await render('board',st,owner);assert.deepEqual(scopedIds(st,owner),expected(suffixes));assert.deepEqual(boardIds(),expected(suffixes,['active']).sort());await render('receipt',st,owner);assert.deepEqual(receiptIds(),expected(suffixes,['receipt']));assert.equal(scope(st,owner).diagnostic,'');unchanged();});
  for(const selected of ['',profileB,'_unassigned',removedName])await scenario('invalid explicit selection '+(selected||'(empty)')+' never adopts a profile or sentinel',async()=>{const st=fixture(),unchanged=await render('board',st,selected);assert.deepEqual(scopedIds(st,selected),[]);assert.deepEqual(boardIds(),[]);await render('receipt',st,selected);assert.deepEqual(receiptIds(),[]);unchanged();});
  await scenario('valid named other without current profile retains blank-ID rows only',async()=>{const st=fixture({link:'a'});st.settings.sellerProfiles.pop();st.orders=st.orders.filter(row=>row.ownerProfileId!==profileB);st.tasks=[];core.normalizeState(st);assert.deepEqual(scopedIds(st,nameB),expected(['legacy-b']));});
  await scenario('customer and deal responsibility changes cannot move existing orders',async()=>{const st=fixture(),before=st.orders.map(row=>({id:row.id,owner:row.owner,profile:row.ownerProfileId}));st.customers[0]={...st.customers[0],owner:nameB,ownerProfileId:profileB,status:'active'};st.deals=st.deals.map(row=>({...row,owner:nameB,ownerProfileId:profileB}));core.normalizeState(st);assert.deepEqual(scopedIds(st),expected(['b','legacy-a']));assert.deepEqual(st.orders.map(row=>({id:row.id,owner:row.owner,profile:row.ownerProfileId})),before);const unchanged=await render('board',st);assert.deepEqual(boardIds(),['active-b','active-legacy-a']);await render('receipt',st);assert.deepEqual(receiptIds(),['receipt-b','receipt-legacy-a']);unchanged();});
  for(const mode of ['print','warehouse'])await scenario(mode+' operational queue keeps cross-owner bypass for every supplied selection',async()=>{for(const owner of [nameA,nameB,'_unassigned','']){const st=fixture(),unchanged=await render('board',st,owner,{mode});assert.deepEqual(boardIds(),expected(responsibilities,['active']).sort());assert.equal(renderer.root.findAllByType('tabs-trigger').some(node=>node.props.value==='invoice'),false);await tab('history');assert.deepEqual(boardIds(),[]);unchanged();await unmount();}});
  await scenario('sales search stays inside responsibility scope and exact callback opens existing order',async()=>{const st=fixture(),unchanged=await render('board',st);await act(async()=>renderer.root.findByType('input').props.onChange({target:{value:'ACTIVE-B'}}));assert.deepEqual(boardIds(),['active-b']);await click('Order & leverans');assert.deepEqual(calls,[{kind:'order',args:[st.orders.find(row=>row.id==='active-b')]}]);unchanged();});
  await scenario('compact and complete receipts show own IDs despite frozen foreign receipt-task profiles',async()=>{const st=fixture();const row=st.orders.find(row=>row.id==='receipt-b'),deal=st.deals.find(row=>row.id==='deal-receipt-b');for(let index=1;index<=5;index++){const id='receipt-b-extra-'+index;st.deals.push(core.DealSchema.parse({...deal,id:'deal-'+id,title:'Syntetisk order '+id}));st.orders.push(core.OrderSchema.parse({...row,id,dealId:'deal-'+id}));}core.normalizeState(st);const unchanged=await render('receipt',st,undefined,{compact:true});assert.deepEqual(receiptIds(),['receipt-b','receipt-legacy-a','receipt-b-extra-1','receipt-b-extra-2','receipt-b-extra-3']);assert.equal(text(byClass('receipt-queue')[0].findByProps({className:'count'})),'7');assert.match(text(byClass('receipt-queue')[0]),/första fem/i);await render('receipt',st,undefined,{compact:false});assert.deepEqual(receiptIds(),['receipt-b','receipt-legacy-a',...Array.from({length:5},(_,index)=>'receipt-b-extra-'+(index+1))]);assert.equal(st.tasks.find(task=>task.dealId==='deal-receipt-b').ownerProfileId,profileA);await act(async()=>byClass('receipt-queue')[0].findAllByType('button')[0].props.onClick());assert.deepEqual(calls,[{kind:'receipt',args:['receipt-b']}]);unchanged();});
  await scenario('real preserved blank receipt anchor projection cannot replace the order profile',async()=>{const st=fixture({owner:''}),row=st.orders.find(order=>order.id==='receipt-b');row.responsibilityTransfers=[{id:'d5746101-f76b-4ec7-9f44-90d7e9c5a003',action:'anchor',targetType:'order',targetId:row.id,customerId:row.customerId,dealId:row.dealId,fromRecordedProfileId:'',fromProfileId:profileB,toProfileId:profileB,fromOwner:nameB,toOwner:nameB,fromDisplayName:'Samma syntetiska visningsnamn',toDisplayName:'Samma syntetiska visningsnamn',selectedTaskIds:[],targetMemberId:'synthetic-order-member',targetUserId:'synthetic-order-session',targetName:'Syntetisk person',targetRole:'seller',receiptProjection:{taskId:'receipt-'+row.id,ownerProfileId:''},reason:'Syntetisk bevarad kvittensprojektion',at:'2026-10-01T10:00:00Z',byId:'synthetic-reviewer',byMemberId:'synthetic-reviewer-member',byName:'Syntetisk granskare'}];st.tasks=st.tasks.filter(task=>task.dealId!==row.dealId);core.normalizeState(st);const orderWork=await import(pathToFileURL(compile('lib/order-work.ts')).href);orderWork.ensureReceiptTasks(st);core.normalizeState(st);assert.equal(st.tasks.find(task=>task.id==='receipt-'+row.id).ownerProfileId,'');const unchanged=await render('receipt',st);assert.deepEqual(receiptIds(),['receipt-b']);await render('day',st);assert.deepEqual(receiptIds(),['receipt-b']);unchanged();});
  for(const [options,kind,suffixes] of [[{},'mismatch',['b','legacy-a']],[{link:''},'missing',['legacy-a']],[{owner:''},'operational-missing',['b']],[{owner:removedName},'operational-missing',['b']],[{inactive:true,owner:''},'operational-missing',['b']]])await scenario('MyDay '+kind+' order blockers, receipts and focus follow actual order identity',async()=>{const st=fixture(options),unchanged=await render('day',st);diagnostic(kind);assert.deepEqual(blockedIds(),expected(suffixes,['active']));assert.deepEqual(receiptIds(),expected(suffixes,['receipt']));assert.deepEqual(byClass('day-work-counts')[0].findAllByType('b').map(text),['0','0',String(suffixes.length)]);assert.match(text(byClass('day-focus')[0]),new RegExp('Syntetisk order active-'+suffixes[0]));await act(async()=>byClass('day-focus')[0].findByType('button').props.onClick());assert.deepEqual(calls,[{kind:'view',args:['orders']},{kind:'order',args:[st.orders.find(row=>row.id==='active-'+suffixes[0])]}]);const assigned=renderer.root.findAll(node=>node.type==='div'&&node.props['data-production-issue-order']);assert.deepEqual(assigned.map(node=>node.props['data-production-issue-order']),['active-a'],'Actual issue responsibility stays independent of order owner');calls=[];await act(async()=>assigned[0].findByType('button').props.onClick());assert.deepEqual(calls,[{kind:'productionOrder',args:[st.orders.find(row=>row.id==='active-a')]}]);unchanged();});
  await scenario('MyDay receipt-only focus survives missing alias without inferred task ownership',async()=>{const st=fixture({owner:''});st.orders=st.orders.filter(row=>row.id==='receipt-b'||row.id==='receipt-a');core.normalizeState(st);const unchanged=await render('day',st);diagnostic('operational-missing');assert.deepEqual(blockedIds(),[]);assert.deepEqual(receiptIds(),['receipt-b']);assert.match(text(byClass('day-focus')[0]),/LEVERANS ATT FÖLJA UPP/);await act(async()=>byClass('day-focus')[0].findByType('button').props.onClick());assert.deepEqual(calls,[{kind:'receipt',args:['receipt-b']}]);unchanged();});
  await scenario('MyDay customer concerns retain valid account alias independently of order selection',async()=>{const st=fixture();st.customers.push(core.CustomerSchema.parse({id:'synthetic-b-contact',name:'Syntetisk annan kontaktkund',owner:nameB,status:'risk',riskReason:'SYNTHETIC_B_CONTACT'}));st.customers[0]={...st.customers[0],status:'risk',riskReason:'SYNTHETIC_A_CONTACT'};core.normalizeState(st);const unchanged=await render('day',st);assert.match(text(byClass('day-contacts')[0]),/SYNTHETIC_A_CONTACT/);assert.ok(!text(byClass('day-contacts')[0]).includes('SYNTHETIC_B_CONTACT'));assert.deepEqual(blockedIds(),['active-b','active-legacy-a']);unchanged();});
  for(const [owner,riskId,wantSignal] of [[nameA,'active-a',false],['','active-b',true]])await scenario('MyDay actual order-risk signal '+riskId+' follows exact member rather than alias '+(owner||'(empty)'),async()=>{const st=fixture({owner});st.orders=st.orders.filter(order=>['active-a','active-b'].includes(order.id)).map(order=>({...order,supplierConfirmed:order.id!==riskId,production:{...order.production,issue:''}}));core.normalizeState(st);const unchanged=await render('day',st);assert.deepEqual(blockedIds(),[]);const signalSections=byClass('day-blocked').filter(node=>text(node).includes('Prioritera nu'));assert.equal(signalSections.length,wantSignal?1:0);assert.equal(text(byClass('day-focus')[0]).includes('KRÄVER UPPMÄRKSAMHET'),wantSignal);if(wantSignal){await act(async()=>byClass('day-focus')[0].findByType('button').props.onClick());assert.deepEqual(calls,[{kind:'order',args:[st.orders.find(order=>order.id==='active-b')]}]);}else assert.ok(!text(renderer.toJSON()).includes('Leveransdatumet är nära'));unchanged();});
  await scenario('MyDay task-based quote signal retains separate exact task responsibility',async()=>{const st=fixture({owner:''});st.orders=[];st.deals[0]={...st.deals[0],stage:'quoted'};st.tasks=[core.TaskSchema.parse({id:'synthetic-profile-quote',customerId:st.customers[0].id,dealId:st.deals[0].id,owner:nameB,ownerProfileId:profileB,title:'Syntetisk exakt uppgiftskontakt',due:core.plusDays(core.day(),-5),kind:'quote'})];core.normalizeState(st);const unchanged=await render('day',st);assert.match(text(byClass('day-focus')[0]),/KRÄVER UPPMÄRKSAMHET/);await act(async()=>byClass('day-focus')[0].findByType('button').props.onClick());assert.deepEqual(calls,[{kind:'task',args:[st.tasks[0]]}]);unchanged();});
  await scenario('authorized admin team day keeps all orders and no personal diagnostic',async()=>{const st=fixture({role:'admin',owner:''}),unchanged=await render('day',st,'all');diagnostic('');assert.deepEqual(blockedIds(),expected(responsibilities,['active']));assert.equal(text(byClass('receipt-queue')[0].findByProps({className:'count'})),'6');assert.deepEqual(receiptIds(),expected(responsibilities.slice(0,5),['receipt']));unchanged();});
  for(const selected of ['all',nameB])await scenario('seller selected '+selected+' does not acquire an unauthorized or another personal day',async()=>{const st=fixture(),unchanged=await render('day',st,selected);assert.deepEqual(blockedIds(),[]);assert.equal(byClass('receipt-queue').length,0);assert.equal(byClass('day-work-counts').length,0);diagnostic('');assert.deepEqual(renderer.root.findAll(node=>node.type==='div'&&node.props['data-production-issue-order']).map(node=>node.props['data-production-issue-order']),['active-a']);unchanged();});
  await scenario('reader receipts remain view actions and direct parent writes reject before HTTP',async()=>{const st=fixture({role:'reader',owner:''}),unchanged=await render('receipt',st);assert.deepEqual(receiptIds(),['receipt-b']);await click('Visa leveransunderlag');assert.deepEqual(calls,[{kind:'receipt',args:['receipt-b']}]);const observed=[],saving={current:false},save=parent.parentSave(st,saving,{current:'synthetic'},'synthetic',{error:message=>observed.push(message)});assert.equal(await save('order',st.orders[0]),false);assert.deepEqual(observed,['Ditt konto har läsbehörighet.']);assert.equal(saving.current,false);unchanged();});
  for(const [options,kind,action,route] of [[{role:'admin'},'mismatch','Öppna Mål & inställningar','settings'],[{role:'admin',link:''},'missing','Öppna Mål & inställningar','settings'],[{role:'admin',owner:''},'operational-missing','Öppna Konton & roller','accounts']])await scenario('actual Orders '+kind+' notice and administrator repair route preserve stored records',async()=>{const st=fixture(options),unchanged=await render('selector',st);diagnostic(kind);await click(action);assert.deepEqual(calls,[{kind:'navigate',view:route}]);const observed=[];parent.actualNavigation(st,'orders',observed)(route);assert.deepEqual(observed,[{kind:'search',value:''},{kind:'view',value:route}]);unchanged();});
  await scenario('actual Orders selector always retains permanent personal entry after team or other selection',async()=>{for(const options of [{},{owner:''},{owner:removedName},{link:''},{initialized:false}])for(const selected of [own(fixture(options)),'all',nameB]){const st=fixture(options),unchanged=await render('selector',st,selected),choice=renderer.root.findByType('choice');assert.equal(new Set(choice.props.options.map(option=>option.id)).size,choice.props.options.length);assert.ok(choice.props.options.some(option=>option.id===own(st)&&option.label.startsWith('Mina order')));assert.ok(choice.props.options.some(option=>option.id==='all'&&option.label==='Teamets order'));assert.equal(text(byClass('scope-caption')[0]),scope(st,selected).caption);unchanged();}});
  for(const [options,want] of [[{},['b','legacy-a']],[{owner:''},['b']],[{link:''},['legacy-a']]])await scenario('actual Orders parent passes the same responsibility selection to board and receipt queue '+JSON.stringify(options),async()=>{const st=fixture(options),unchanged=await render('page',st);assert.deepEqual(boardIds(),expected(want,['active']).sort());assert.deepEqual(receiptIds(),expected(want,['receipt']));assert.equal(renderer.root.findAllByType('section')[0].props['data-profile-diagnostic'],scope(st).diagnostic);await act(async()=>byClass('receipt-queue')[0].findAllByType('button')[0].props.onClick());assert.deepEqual(calls,[{kind:'receipt',id:'receipt-'+want[0]}]);unchanged();});
  await scenario('diagnostic empty sales and receipt subsets stay honest while healthy empty queues retain existing wording',async()=>{for(const options of [{link:'',owner:''},{link:'a'}]){const st=fixture(options);st.orders=[];st.tasks=[];core.normalizeState(st);const incomplete=options.link==='',unchanged=await render('page',st);diagnostic(incomplete?'missing':'');const empties=byClass('biz-empty').map(text);assert.equal(empties.length,2);if(incomplete){assert.ok(empties.every(value=>/synliga urval.*Kontokopplingen behöver kontrolleras/.test(value)));assert.ok(!empties.includes('Inga order i denna kö.'));assert.ok(!empties.includes('Inga skickade order väntar på kundbekräftelse.'));}else assert.deepEqual(empties,['Inga order i denna kö.','Inga skickade order väntar på kundbekräftelse.']);unchanged();await unmount();}});
  for(const role of ['seller','reader'])await scenario(role+' actual Orders notice offers administrator guidance without privileged write',async()=>{const st=fixture({role}),unchanged=await render('selector',st);diagnostic('mismatch');assert.match(text(renderer.toJSON()),/Be en administratör/);assert.equal(button('Öppna Mål & inställningar'),undefined);assert.equal(button('Öppna Konton & roller'),undefined);unchanged();});
  for(const role of ['production','print','warehouse'])await scenario(role+' remembered Orders selector remains in operative workspace',async()=>{const st=fixture({role}),unchanged=await render('selector',st);assert.equal(renderer.toJSON(),null);assert.deepEqual(calls,[]);unchanged();});
  function resultNavigation(st,currentView,target,passedScope){const before=JSON.stringify(st);freeze(st);const selected={owner:'old',search:'old',filter:'old',view:currentView},set=key=>value=>selected[key]=value;parent.resultNavigation(st,currentView,set('owner'),set('search'),set('filter'),set('view'))(target,passedScope);assert.equal(JSON.stringify(st),before);return selected;}
  for(const owner of [nameA,'',removedName])await scenario('actual personal Resultat Orders drill opens exact B with account alias '+(owner||'(empty)'),async()=>{const st=fixture({owner}),observed=[];parent.dashboardGo(st,dashboard.personalResultScope(st),(view,selected)=>observed.push([view,selected]))('orders');assert.deepEqual(observed,[['orders',nameB]]);const next=resultNavigation(st,'overview',...observed[0]);assert.deepEqual(next,{owner:own(st),search:'',filter:'old',view:'orders'});assert.deepEqual(scopedIds(st,next.owner),expected(owner===nameA?['b','legacy-a']:['b']));});
  await scenario('Resultat team and explicit other drills retain their chosen roster or all scope',async()=>{const st=fixture({role:'admin'});assert.equal(resultNavigation(st,'team','orders','all').owner,'all');assert.equal(resultNavigation(st,'team','orders',nameB).owner,nameB);assert.equal(resultNavigation(st,'overview','orders',nameA).owner,nameA);assert.equal(resultNavigation(st,'overview','orders','all').owner,'all');const other=fixture({owner:nameB});assert.equal(resultNavigation(other,'overview','orders',nameA).owner,nameA);});
  await scenario('ordinary Orders navigation retains selected scope and financial attribution remains immutable',async()=>{const st=fixture(),before=JSON.stringify(st),snapshots=[profileA,profileB,'all'].map(id=>dashboard.salesMetrics(st,core.day().slice(0,7),id));freeze(st);const observed=[];parent.actualNavigation(st,'overview',observed)('orders');assert.deepEqual(observed,[{kind:'search',value:''},{kind:'view',value:'orders'}]);scopedIds(st);resultNavigation(st,'overview','orders',nameB);assert.deepEqual([profileA,profileB,'all'].map(id=>dashboard.salesMetrics(st,core.day().slice(0,7),id)),snapshots);assert.equal(snapshots[1].revenue,100);assert.equal(snapshots[1].profit,80);assert.equal(JSON.stringify(st),before);});
  await scenario('same mounted day rereads current member, removed link and workspace without stale order identity',async()=>{const first=fixture(),checks=[await render('day',first)];assert.deepEqual(blockedIds(),['active-b','active-legacy-a']);const next=fixture({link:'a',owner:nameB});next.viewer.id='synthetic-next-session';next.viewer.memberId='synthetic-next-member';next.settings.sellerProfiles[0].memberId='synthetic-next-member';core.normalizeState(next);checks.push(await render('day',next,undefined,{space:'synthetic-next-space'}));assert.deepEqual(blockedIds(),['active-a','active-legacy-b']);assert.deepEqual(receiptIds(),['receipt-a','receipt-legacy-b']);const missing=fixture({link:'',owner:''});checks.push(await render('day',missing,undefined,{space:'synthetic-next-space'}));assert.deepEqual(blockedIds(),[]);assert.equal(byClass('receipt-queue').length,0);assert.deepEqual(calls,[]);for(const check of checks)check();});
  for(const [file,bytes] of sourceBytes)assert.deepEqual(readFileSync(file),bytes,'Actual source stays byte unchanged: '+file);
  const proof=Object.fromEntries([...sourceBytes].sort(([a],[b])=>a.localeCompare(b)).map(([file,bytes])=>[file,{bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}]));
  console.log('PASS Order scope: '+count+' normalized domain/actual page/React cases; immutable inputs, '+compiled.size+' byte-verified production modules, zero HTTP. Synthetic presentation/private-draft boundaries; no browser, personal login, integration or staff acceptance.');
  return {cases:count,compiledModules:compiled.size,httpRequests:http.length,sourceProof:proof};
 }finally{await unmount();rmSync(directory,{recursive:true,force:true});for(const [key,descriptor] of Object.entries(originals)){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}}
}
