import './crm.mjs';
import ts from 'typescript';import {readFileSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const transpile=(source,target)=>writeFileSync(target,ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
transpile(readFileSync('lib/outlook-shared.ts','utf8'),'work/outlook-shared.mjs');
transpile(readFileSync('lib/outlook.ts','utf8').replace("import {env} from 'cloudflare:workers';","const env=globalThis.__crmEnv;").replace("'./crm'","'./core.mjs'").replace("'./outlook-shared'","'./outlook-shared.mjs'"),'work/outlook.mjs');
transpile(readFileSync('app/api/outlook/route.ts','utf8').replace("'@/lib/outlook'","'./outlook.mjs'").replace("'@/lib/crm-auth'","'./auth.mjs'"),'work/outlook-api.mjs');
const o=await import('../work/outlook.mjs'),api=await import('../work/outlook-api.mjs');
const origin='https://magnussons-crm.rosen123.chatgpt.site';
const request=(user='seller1',method='GET',body)=>new Request(origin+'/api/outlook',{method,headers:{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.com',Origin:origin,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
for(const id of ['seller1','seller2'])await globalThis.__crmEnv.DB.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active) VALUES(?,?,?,?,?,?,1)').bind(id,id+'@example.com',id,id,'seller','').run();
assert.equal((await api.GET(new Request(origin+'/api/outlook'))).status,401);
for(const role of ['print','warehouse','production'])assert.equal((await api.GET(new Request(origin+'/api/outlook',{headers:{'oai-authenticated-user-id':'ops-'+role,'oai-authenticated-user-email':role+'@example.com'}}))).status,403);
assert.equal((await o.readState(request())).configured,false);
assert.equal((await api.POST(request('seller1','POST',{action:'sync'}))).status,503);
Object.assign(globalThis.__crmEnv,{MS_TENANT_ID:'00000000-0000-0000-0000-000000000001',MS_CLIENT_ID:'00000000-0000-0000-0000-000000000002',MS_CLIENT_SECRET:'test-client-secret',OUTLOOK_TOKEN_KEY:Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64url')});
const sealed=await o.seal({s:'test-token'},'seller1');assert.ok(!sealed.includes('test-token'));assert.deepEqual(await o.unseal(sealed,'seller1'),{s:'test-token'});await assert.rejects(()=>o.unseal(sealed,'seller2'));
let eventExists=true,meetingHour='10',version=1,tokenCalls=0;const realFetch=globalThis.fetch;
const recipient=address=>({emailAddress:{address}});
const mail={id:'mail-one',subject:'Kunddialog',body:{contentType:'text',content:'Hej kund'},from:recipient('test@example.com'),toRecipients:[recipient('seller@company.test')],receivedDateTime:new Date().toISOString(),sensitivity:'normal',webLink:'https://outlook.office.com/mail/read/test'};
const meeting=()=>({id:'event-one',subject:'Kundmöte',body:{contentType:'text',content:'Behovsmöte'},organizer:recipient('seller@company.test'),attendees:[recipient('test@example.com')],start:{dateTime:new Date().toISOString().slice(0,10)+'T'+meetingHour+':00:00'},end:{dateTime:new Date().toISOString().slice(0,10)+'T12:00:00'},sensitivity:'normal',isCancelled:version>1,webLink:'https://outlook.office.com/calendar/item/test'});
globalThis.fetch=async(url,options)=>{const u=new URL(url);if(u.hostname==='login.microsoftonline.com'){tokenCalls++;assert.equal(new URLSearchParams(options.body).get('client_secret'),'test-client-secret');return Response.json({access_token:'fake-access',refresh_token:'fake-refresh',expires_in:3600})}assert.equal(u.origin,'https://graph.microsoft.com');assert.equal(options.headers.Authorization,'Bearer fake-access');if(u.pathname==='/v1.0/me')return Response.json({id:'ms-seller-one',mail:'seller@company.test'});if(u.pathname.includes('calendarView'))return Response.json({value:eventExists?[meeting()]:[]});if(u.pathname.includes('inbox'))return Response.json({value:[mail,{...mail,id:'internal',from:recipient('colleague@company.test')},{...mail,id:'private',sensitivity:'private'}]});return Response.json({value:[]})};
try{
 const consent=await o.startConsent('seller1');const authUrl=new URL(consent.url);assert.equal(authUrl.searchParams.get('code_challenge_method'),'S256');assert.ok(authUrl.searchParams.get('scope').includes('Mail.Read'));assert.ok(!authUrl.searchParams.get('scope').includes('Mail.Send'));
 const callback=(cookie,state=consent.state)=>new Request(origin+'/api/outlook/callback?code=abc&state='+state,{headers:{'oai-authenticated-user-id':'seller1','oai-authenticated-user-email':'s@example.com',cookie:'__Host-outlook-state='+cookie}});
 await assert.rejects(()=>o.finishConsent(callback('wrong')));assert.equal(tokenCalls,0);
 await o.finishConsent(callback(consent.state));assert.equal(tokenCalls,1);await assert.rejects(()=>o.finishConsent(callback(consent.state)));assert.equal(tokenCalls,1);
 const stored=await o.connection('seller1');assert.ok(!stored.tokens.includes('fake-access'));assert.ok(!stored.tokens.includes('fake-refresh'));
 await o.sync('seller1');let st=await o.readState(request());assert.equal(st.items.length,2);assert.ok(st.items.every(i=>i.mine&&!i.shared));assert.ok(st.connection.lastSync);assert.equal((await o.readState(request('seller2'))).items.length,0);
 const first=st.items.find(i=>i.kind==='mail'),event=st.items.find(i=>i.kind==='meeting');assert.ok(first.customerId);assert.equal(event.at.endsWith('Z'),true);
 await assert.rejects(()=>o.publishItem('seller2',first.id,first.customerId,'',true));
 await assert.rejects(()=>o.publishItem('seller1',first.id,'unknown-customer','',true));
 await o.publishItem('seller1',first.id,first.customerId,'',true);let peer=await o.readState(request('seller2'));assert.equal(peer.items.length,1);assert.equal(peer.items[0].mine,false);
 version=2;meetingHour='11';await o.sync('seller1');st=await o.readState(request());assert.equal(st.items.length,2);assert.equal(st.items.find(i=>i.id===event.id).cancelled,true);assert.ok(st.items.find(i=>i.id===event.id).at.includes('T11:'));assert.equal(st.items.find(i=>i.id===first.id).shared,true);
 eventExists=false;await o.sync('seller1');st=await o.readState(request());assert.equal(st.items.find(i=>i.id===event.id).removed,true);
 await assert.rejects(()=>o.graph('https://evil.example/v1.0/mail','fake-access'));
 const csrf=await api.POST(new Request(origin+'/api/outlook',{method:'POST',headers:{'oai-authenticated-user-id':'seller1','oai-authenticated-user-email':'s@example.com',Origin:'https://evil.example','Content-Type':'application/json'},body:'{"action":"disconnect"}'}));assert.equal(csrf.status,403);
 await o.disconnect('seller1');assert.equal(await o.connection('seller1'),null);st=await o.readState(request());assert.equal(st.items.length,1);assert.equal(st.items[0].shared,true);
 await o.publishItem('seller1',first.id,first.customerId,'',false);assert.equal((await o.readState(request('seller2'))).items.length,0);
}finally{globalThis.fetch=realFetch}
console.log('PASS: Outlook configuration gate, authenticated identity, encrypted credentials, PKCE/state replay protection, private matching, visibility isolation, explicit sharing, stable IDs, updated/cancelled/removed meetings, preserved sharing, provider URL validation, CSRF, disconnect. Microsoft responses mocked; no live Microsoft account used.');
