import assert from 'node:assert/strict';
import { readdirSync, readFileSync, mkdtempSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const { Miniflare, Log, LogLevel }=await import(pathToFileURL(wranglerRequire.resolve('miniflare')).href);
import * as core from '../work/core.mjs';
import * as conflicts from '../work/record-conflicts.mjs';
import {assertParentTaskTransfer} from './task-responsibility-transfer.mjs';
// Run after tests/outlook.mjs and pnpm build. No production bindings or data.
const root = fileURLToPath(new URL('../',import.meta.url)), statePath = mkdtempSync(join(tmpdir(),'magnussons-runtime-'));
const serverRoot=root+'/dist/server';
const moduleFiles=readdirSync(serverRoot,{recursive:true}).filter(f=>/\.m?js$/.test(f));
const mf = new Miniflare({ modulesRoot:serverRoot, modules:[
  {type:'ESModule',path:serverRoot+'/index.js'},
  ...moduleFiles.filter(f=>f!=='index.js').map(f=>({type:'ESModule',path:serverRoot+'/'+f}))],
  compatibilityDate:'2026-05-15', compatibilityFlags:['nodejs_compat'], cf:false,
  log:new Log(LogLevel.ERROR), d1Databases:{DB:'crm-runtime'}, r2Buckets:{BUCKET:'crm-runtime'},
  d1Persist:statePath+'/d1', r2Persist:statePath+'/r2',
  assets:{directory:root+'/dist/client',binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}} });
const origin='http://localhost', headers={'oai-authenticated-user-id':'runtime-admin','oai-authenticated-user-email':'runtime-admin@example.test'};
const api = (url,options={})=>mf.dispatchFetch(origin+url,options);
try {
  const db=await mf.getD1Database('DB');
  for(const file of readdirSync(root+'/drizzle').filter(f=>f.endsWith('.sql')).sort())
    for(const sql of readFileSync(root+'/drizzle/'+file,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean)) await db.prepare(sql).run();
  await db.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active) VALUES(?,?,?,?,?,?,1)').bind('runtime-admin','runtime-admin@example.test','runtime-admin','Runtime test','admin','Sebastian Hansson').run();
  assert.equal((await api('/api/crm?space=live')).status,401);
  const home=await api('/');assert.equal(home.status,200);assert.match(await home.text(),/Magnussons/);
  const get=async(space='live')=>{const r=await api('/api/crm?space='+space,{headers});assert.equal(r.status,200);return r.json();};
  let state=await get();
  const post=async(type,data)=>{const record=conflicts.editableRecord(state,type,data.id||''),r=await api('/api/crm',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:origin},body:JSON.stringify({space:'live',version:state.version,requestId:crypto.randomUUID(),expectedRecord:record?conflicts.recordBasis(record):undefined,type,data})});const value=await r.json();assert.equal(r.status,200,JSON.stringify(value));state=value;return value;};
  const savePlan=async(customerId,changes,workflow={})=>{
    const current=state.customers.find(c=>c.id===customerId);assert.ok(current);
    return post('plan',{customerId,expectedContext:conflicts.customerWorkflowBasis(state,'plan',customerId),plan:{...current.plan,...changes},nextReview:current.nextReview||core.plusDays(core.day(),7),expectedOrder:current.expectedOrder,reviewDays:current.reviewDays,reviewed:false,...workflow});
  };
  await post('customer',{name:'Isolerat körprov AB',owner:'Sebastian Hansson',contact:'Testbeställare'});
  const customer=state.customers[0], today=core.day();
  await post('meeting',{customerId:customer.id,owner:customer.owner,title:'Äldre syntetiskt runtime-möte',date:today,time:'10:00',duration:30});
  const legacyRuntimeMeeting=state.meetings.find(m=>m.title==='Äldre syntetiskt runtime-möte');assert.ok(legacyRuntimeMeeting);assert.equal(legacyRuntimeMeeting.ownerProfileId,'');assert.deepEqual(legacyRuntimeMeeting.responsibilityTransfers,[]);
  await post('catalog_order',{customerId:customer.id,owner:customer.owner,title:'Körprov med filer',lines:[{id:'runtime-line',kind:'product',article:'TEST-1',description:'Jacka',quantity:50,unitPrice:100,unitCost:50}],deliveryDate:core.plusDays(today,30),accepted:true,nextDate:today});
  let order=state.orders[0];
  const sources=[];
  async function upload(name,kind,photo=false){
    const bytes=new Uint8Array(4500000);for(let i=0;i<bytes.length;i++)bytes[i]=(i+sources.length*61)%251;
    bytes.set(photo?[137,80,78,71,13,10,26,10]:[37,80,68,70,45]);
    const form=new FormData();form.set('space','live');form.set('customerId',customer.id);form.set('version','runtime-v1');form.set('kind',kind);form.set('file',new File([bytes],name));
    if(photo){form.set('purpose','production');form.set('orderId',order.id);form.set('workId',order.production.workId);}
    const serialized=new Request(origin+'/api/crm/files',{method:'POST',headers:{...headers,Origin:origin},body:form});
    const r=await api('/api/crm/files',{method:'POST',headers:Object.fromEntries(serialized.headers),body:new Uint8Array(await serialized.arrayBuffer())});const value=await r.json();assert.equal(r.status,200,JSON.stringify(value));sources.push({metadata:value,sha256:createHash('sha256').update(bytes).digest('hex')});state=await get();return value;
  }
  const proof=await upload('korrektur.pdf','proof');
  order=state.orders[0];await post('order',{...order,proofApproved:true,proofFileId:proof.id,proofVersion:proof.version,approvedBy:'Testkund',approvedDate:today,supplierConfirmed:true});
  order=state.orders[0];await post('production_submit',{orderId:order.id,production:{lines:state.deals[0].lines,sketchFileId:proof.id,sketchVersion:proof.version,instructions:'Brösttryck enligt godkänt korrektur',printDeadline:core.plusDays(today,10),dispatchDeadline:core.plusDays(today,20)}});
  order=state.orders[0];await upload('arbetsfoto.png','document',true);await upload('original.pdf','logo');
  const before=await get();
  // Use the real HTTP listener: RPC dispatch can hide framing/stream errors.
  const exported=await fetch(new URL('/api/crm/backup?space=live&format=stream',await mf.ready),{headers:{...headers,'Accept-Encoding':'identity'}});assert.equal(exported.status,200);
  const bytes=new Uint8Array(await exported.arrayBuffer()), records=new TextDecoder().decode(bytes).trimEnd().split('\n');
  assert.equal(Number(exported.headers.get('Content-Length')),bytes.byteLength,'Built workerd declares the exact complete backup length');
  const end=JSON.parse(records.at(-1));assert.equal(end.bytes,13500000);assert.equal(end.files,3);
  await db.prepare('INSERT INTO crm_spaces(id,version,write_token,settings) VALUES(?,0,?,?)').bind('demo','',JSON.stringify(core.emptyState().settings)).run();
  const requestId=crypto.randomUUID(), restoreUrl='/api/crm/backup?space=demo&version=0&requestId='+requestId;
  const restoreOptions={method:'POST',headers:{...headers,'Content-Type':'application/x-ndjson',Origin:origin},body:bytes};
  const restoredResponse=await api(restoreUrl,restoreOptions);const restored=await restoredResponse.json();assert.equal(restoredResponse.status,200,JSON.stringify(restored));
  assert.equal(restored.customers.length,1);assert.equal(restored.orders.length,1);assert.equal(restored.orders[0].proofApproved,true);
  const filesResponse=await api('/api/crm/files?space=demo&customerId='+restored.customers[0].id,{headers}),files=await filesResponse.json();assert.equal(files.length,3);
  for(const source of sources){const file=files.find(f=>f.name===source.metadata.name);assert.ok(file);assert.notEqual(file.id,source.metadata.id);const r=await api('/api/crm/files?space=demo&id='+file.id,{headers});assert.equal(r.status,200);assert.equal(createHash('sha256').update(new Uint8Array(await r.arrayBuffer())).digest('hex'),source.sha256);}
  assert.equal(restored.orders[0].proofFileId,files.find(f=>f.kind==='proof').id);
  assert.equal(restored.orders[0].production.sketchFileId,restored.orders[0].proofFileId);
  const photo=files.find(f=>f.purpose==='production');assert.equal(photo.orderId,restored.orders[0].id);assert.equal(photo.workId,restored.orders[0].production.workId);
  const retry=await api(restoreUrl,restoreOptions);assert.equal(retry.status,200);assert.equal((await retry.json()).version,restored.version);
  assert.deepEqual(await get(),before);
  // The built Worker stores unfinished workflow text privately, then consumes
  // its revision in the same D1 transaction as the explicit customer update.
  const privateBaseline=await get(),workflowCustomer=privateBaseline.customers.find(c=>c.id===customer.id),workflowBasis=conflicts.customerWorkflowBasis(privateBaseline,'plan',workflowCustomer.id),draftId=crypto.randomUUID();
  const draftWrite=async data=>{const r=await api('/api/crm/drafts',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:origin},body:JSON.stringify({space:'live',...data})});return {status:r.status,data:await r.json()};};
  const draftRead=async who=>{const r=await api('/api/crm/drafts?space=live&id='+draftId,{headers:who});return {status:r.status,data:await r.json()};};
  assert.equal((await api('/api/crm/drafts?space=live&id='+draftId)).status,401);
  const unfinished=await draftWrite({id:draftId,kind:'plan',context:workflowCustomer.id,revision:0,requestId:crypto.randomUUID(),title:'Privat kundplan i riktig Worker',data:{values:{goal:'PRIVATE WORKER DRAFT',contacts:[{name:'',role:'',email:'ofullständig'}]},expectedContext:workflowBasis,customerName:workflowCustomer.name}});
  assert.equal(unfinished.status,200,JSON.stringify(unfinished.data));assert.deepEqual(await get(),privateBaseline);assert.equal((await draftRead(headers)).data[0].data.values.goal,'PRIVATE WORKER DRAFT');
  await db.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active) VALUES(?,?,?,?,?,?,1)').bind('runtime-workflow-other','runtime-workflow-other@example.test','runtime-workflow-other','Annan runtime-säljare','seller','Sebastian Hansson').run();
  const otherRead=await draftRead({'oai-authenticated-user-id':'runtime-workflow-other','oai-authenticated-user-email':'runtime-workflow-other@example.test'});assert.equal(otherRead.status,200);assert.deepEqual(otherRead.data,[]);
  const workflowValues={...workflowCustomer.plan,goal:'Explicit publicerad kundplan',nextAction:'Stäm av körprovskundens nästa behov',nextReview:core.plusDays(today,7),expectedOrder:workflowCustomer.expectedOrder,reviewDays:workflowCustomer.reviewDays,reviewed:false};
  const ready=await draftWrite({...unfinished.data,requestId:crypto.randomUUID(),data:{...unfinished.data.data,values:workflowValues}});assert.equal(ready.status,200,JSON.stringify(ready.data));
  const publicationId=crypto.randomUUID(),publication={space:'live',version:privateBaseline.version,requestId:publicationId,type:'plan',data:{customerId:workflowCustomer.id,expectedContext:workflowBasis,plan:workflowValues,nextReview:workflowValues.nextReview,expectedOrder:workflowValues.expectedOrder,reviewDays:workflowValues.reviewDays,reviewed:false,draft:{id:draftId,revision:ready.data.revision}}};
  const publicationOptions={method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:origin},body:JSON.stringify(publication)};
  const publishedResponse=await api('/api/crm',publicationOptions),published=await publishedResponse.json();assert.equal(publishedResponse.status,200,JSON.stringify(published));assert.equal(published.customers.find(c=>c.id===workflowCustomer.id).plan.goal,workflowValues.goal);assert.equal(published.customers.find(c=>c.id===workflowCustomer.id).lastContact,workflowCustomer.lastContact);assert.deepEqual(published.orders,privateBaseline.orders);assert.equal((await draftRead(headers)).data[0].archived,true);
  const persistedPublication=await get(),{mutationResult:publicationResult,...publicationState}=published;assert.deepEqual(persistedPublication,publicationState);assert.ok(publicationResult.eventId);assert.ok(publicationResult.taskId);
  const publishedPlanTask=persistedPublication.tasks.find(t=>t.id===publicationResult.taskId);assert.ok(publishedPlanTask);assert.equal(publishedPlanTask.kind,'csm');assert.equal(publishedPlanTask.customerId,workflowCustomer.id);assert.equal(publishedPlanTask.title,workflowValues.nextAction);assert.ok(!privateBaseline.tasks.some(t=>t.id===publishedPlanTask.id),'Explicit private plan publication creates a new task in the same commit.');
  const publicationReplay=await api('/api/crm',publicationOptions);assert.equal(publicationReplay.status,200);const replayedPublication=await publicationReplay.json();assert.deepEqual(replayedPublication.mutationResult,publicationResult);assert.deepEqual(replayedPublication,{...persistedPublication,mutationResult:publicationResult});assert.deepEqual(await get(),persistedPublication);
  const lateAutosave=await draftWrite({...ready.data,requestId:crypto.randomUUID(),data:{...ready.data.data,values:{goal:'Late private autosave'}}});assert.equal(lateAutosave.status,409);assert.equal((await draftRead(headers)).data[0].archived,true);assert.deepEqual(await get(),persistedPublication);
  // Exercise the built commercial handover API with real local D1/R2, stable
  // profiles and duplicate display names. Old operational IDs stay unguessed.
  const sellers=await import('../work/seller-profiles.mjs'),commercial=await import('../work/commercial-responsibility.mjs'),quantities=await import('../work/production-quantities.mjs');
  const savedPrivateDraft=(await draftRead(headers)).data;
  state=await get();const sourceOwner=customer.owner,targetOwner=state.settings.owners.find(name=>name!==sourceOwner),targetMember='runtime-commercial-target';assert.ok(targetOwner);
  await db.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active) VALUES(?,?,?,?,?,?,1)').bind(targetMember,'runtime-commercial-target@example.test',targetMember,'Identiskt kontonamn','seller',targetOwner).run();
  // Seed the legacy issue after the independent publication insertion above,
  // while profiles are still uninitialized and operational IDs remain blank.
  await savePlan(customer.id,{nextAction:'Följ upp den fiktiva kundrelationen',issueStatus:'open',issue:'Äldre syntetiskt storleksärende',issueAction:'Granska de fiktiva storlekarna',issueOwner:customer.owner,issueDue:core.plusDays(today,3)});
  const legacyIssueTask=state.tasks.find(t=>t.customerId===customer.id&&t.kind==='csm_issue'&&!t.done);assert.ok(legacyIssueTask);
  await post('task',{customerId:customer.id,owner:customer.owner,title:'Separat äldre ärendeuppgift som lämnas kvar',kind:'csm_issue',due:core.plusDays(today,4)});
  const unselectedIssueTask=state.tasks.find(t=>t.title==='Separat äldre ärendeuppgift som lämnas kvar');assert.ok(unselectedIssueTask);
  const legacyIssuePlan=state.customers.find(c=>c.id===customer.id).plan;
  assert.equal(state.settings.sellerProfilesInitialized,false);assert.equal(legacyIssuePlan.issueOwnerProfileId,'');assert.deepEqual(legacyIssuePlan.issueResponsibilityTransfers,[]);
  for(const task of [legacyIssueTask,unselectedIssueTask]){assert.equal(task.ownerProfileId,'');assert.deepEqual(task.responsibilityTransfers,[]);}
  await post('seller_profiles_init',{expectedContext:conflicts.sellerProfilesBasis(state),profiles:sellers.legacySellerNames(state).map(legacyOwnerName=>({legacyOwnerName,displayName:'Identiskt runtime-namn',memberId:legacyOwnerName===sourceOwner?'runtime-admin':legacyOwnerName===targetOwner?targetMember:''}))});
  const sourceProfile=state.settings.sellerProfiles.find(p=>p.legacyOwnerName===sourceOwner),targetProfile=state.settings.sellerProfiles.find(p=>p.legacyOwnerName===targetOwner);assert.ok(sourceProfile&&targetProfile);assert.notEqual(sourceProfile.id,targetProfile.id);assert.equal(sourceProfile.displayName,targetProfile.displayName);assert.equal(state.orders.find(o=>o.id===order.id).ownerProfileId,'','Profile initialization is not automatic operational migration.');
  const runtimeTables=(await db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all()).results.map(r=>r.name).filter(n=>/^(?:crm_|outlook_)[a-z_]+$/.test(n));assert.equal(runtimeTables.length,18);
  const bucket=await mf.getR2Bucket('BUCKET'),raw=async()=>({tables:Object.fromEntries(await Promise.all(runtimeTables.map(async table=>[table,(await db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()).results]))),r2:Object.fromEntries(await Promise.all((await bucket.list()).objects.map(async item=>[item.key,createHash('sha256').update(new Uint8Array(await (await bucket.get(item.key)).arrayBuffer())).digest('hex')]))) });
  const commercialRequest=async(payload)=>{const r=await api('/api/crm',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:origin},body:JSON.stringify(payload)});return {status:r.status,data:await r.json()};};
  await post('catalog_order',{customerId:customer.id,owner:sourceOwner,title:'Isolerad granskad orderöverlämning',lines:[{id:'runtime-commercial-line',kind:'product',article:'TEST-COMMERCIAL',description:'Fiktiv provjacka',quantity:2,unitPrice:100,unitCost:60}],deliveryDate:core.plusDays(today,30),accepted:true,nextDate:today});
  const newOrder=state.orders.find(o=>o.id!==order.id);assert.ok(newOrder);assert.equal(newOrder.ownerProfileId,sourceProfile.id);assert.equal(state.deals.find(d=>d.id===newOrder.dealId).ownerProfileId,sourceProfile.id);
  const choices=commercial.commercialResponsibilityCandidates(state,'order',newOrder.id);assert.ok(choices.requiredTaskIds.length,'The built new-order flow supplies actual required handover work.');
  const opened=state,request=crypto.randomUUID(),transferData={targetType:'order',targetId:newOrder.id,targetProfileId:targetProfile.id,selectedTaskIds:choices.requiredTaskIds,reason:'Granskat lokalt runtimeprov',reviewed:true,expectedContext:commercial.commercialResponsibilityBasis(opened,'order',newOrder.id)},transferPayload={space:'live',version:opened.version,requestId:request,type:'commercial_responsibility_transfer',data:transferData};
  const omittedBefore=await raw(),omitted=await commercialRequest({...transferPayload,requestId:crypto.randomUUID(),data:{...transferData,selectedTaskIds:[]}});assert.equal(omitted.status,400);assert.deepEqual(await raw(),omittedBefore,'Omitted required work leaves all 18 native D1 tables and every R2 object unchanged.');
  const transferred=await Promise.all([commercialRequest(transferPayload),commercialRequest(transferPayload)]);for(const r of transferred)assert.equal(r.status,200,JSON.stringify(r.data));state=await get();assert.equal(state.version,opened.version+1);const handed=state.orders.find(o=>o.id===newOrder.id);assert.equal(handed.owner,targetOwner);assert.equal(handed.ownerProfileId,targetProfile.id);assert.equal(handed.responsibilityTransfers.length,1);assert.deepEqual(state.customers,opened.customers);assert.deepEqual(state.deals,opened.deals);assert.deepEqual(handed.production,newOrder.production);for(const old of opened.tasks)if(choices.requiredTaskIds.includes(old.id))assertParentTaskTransfer(old,state.tasks.find(t=>t.id===old.id),handed.responsibilityTransfers[0],state.settings.sellerProfiles,'order');else assert.deepEqual(state.tasks.find(t=>t.id===old.id),old);
  const replayBefore=await raw(),lostAckReplay=await commercialRequest(transferPayload);assert.equal(lostAckReplay.status,200);assert.deepEqual(await raw(),replayBefore,'A lost handover acknowledgment replays one stored commit.');const changedIntent=await commercialRequest({...transferPayload,data:{...transferData,reason:'Different intent'}});assert.equal(changedIntent.status,409);assert.deepEqual(await raw(),replayBefore);
  await post('production_claim',{orderId:order.id,expectedAssignment:quantities.assignmentBasis(state.orders.find(o=>o.id===order.id).production)});
  const productionBefore=state,oldProductionOrder=productionBefore.orders.find(o=>o.id===order.id),productionChoices=commercial.commercialResponsibilityCandidates(productionBefore,'order',order.id);assert.equal(oldProductionOrder.ownerProfileId,'');assert.equal(oldProductionOrder.production.assigneeId,'runtime-admin');
  await post('commercial_responsibility_transfer',{targetType:'order',targetId:order.id,targetProfileId:targetProfile.id,selectedTaskIds:productionChoices.requiredTaskIds,reason:'Granskad äldre produktionsorder, arbetsansvaret bevaras',reviewed:true,expectedContext:commercial.commercialResponsibilityBasis(productionBefore,'order',order.id)});
  const productionTransferred=state.orders.find(o=>o.id===order.id);assert.equal(productionTransferred.ownerProfileId,targetProfile.id);assert.deepEqual(productionTransferred.production,oldProductionOrder.production);assert.deepEqual(productionTransferred.productionHistory,oldProductionOrder.productionHistory);assert.deepEqual(state.customers,productionBefore.customers);assert.deepEqual(state.deals,productionBefore.deals);assert.equal(productionTransferred.proofFileId,oldProductionOrder.proofFileId);assert.equal(productionTransferred.responsibilityTransfers[0].fromProfileId,sourceProfile.id);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);
  // Customer handover anchors only the reviewed relationship and explicitly
  // selected independent work. Commercial and production ownership stay put.
  const customers=await import('../work/customer-responsibility.mjs');
  assert.equal(state.customers.find(c=>c.id===customer.id).ownerProfileId,'');
  await post('customer',{name:'Ny fiktiv runtime-kund',owner:sourceOwner,contact:'Syntetisk runtime-beställare'});
  const newCustomer=state.customers.find(c=>c.name==='Ny fiktiv runtime-kund');assert.equal(newCustomer.ownerProfileId,sourceProfile.id);
  await post('task',{customerId:customer.id,owner:sourceOwner,title:'Fristående runtime-kundkontakt',kind:'manual',due:today});
  const selectedCustomerTask=state.tasks.find(t=>t.title==='Fristående runtime-kundkontakt');assert.ok(selectedCustomerTask);assert.equal(selectedCustomerTask.ownerProfileId,sourceProfile.id);
  const customerBefore=await get(),customerRaw=await raw(),customerTransfer={space:'live',version:customerBefore.version,requestId:crypto.randomUUID(),type:'customer_responsibility_transfer',data:{customerId:customer.id,targetProfileId:targetProfile.id,selectedTaskIds:[selectedCustomerTask.id],reason:'Uttryckligen granskad fiktiv kundöverlämning',reviewed:true,expectedContext:customers.customerResponsibilityBasis(customerBefore,customer.id)}};
  const customerResponses=await Promise.all([commercialRequest(customerTransfer),commercialRequest(customerTransfer)]);for(const response of customerResponses)assert.equal(response.status,200,JSON.stringify(response.data));
  state=await get();assert.equal(state.version,customerBefore.version+1);const assignedCustomer=state.customers.find(c=>c.id===customer.id);assert.equal(assignedCustomer.ownerProfileId,targetProfile.id);assert.equal(assignedCustomer.owner,targetOwner);assert.equal(assignedCustomer.responsibilityTransfers.length,1);
  assert.deepEqual(state.orders,customerBefore.orders);assert.deepEqual(state.deals,customerBefore.deals);assert.deepEqual(state.settings,customerBefore.settings);
  for(const t of customerBefore.tasks)if(t.id===selectedCustomerTask.id)assertParentTaskTransfer(t,state.tasks.find(current=>current.id===t.id),assignedCustomer.responsibilityTransfers[0],state.settings.sellerProfiles,'customer');else assert.deepEqual(state.tasks.find(current=>current.id===t.id),t);
  const customerAfterRaw=await raw(),customerAllowed=new Set(['crm_customers','crm_tasks','crm_events','crm_spaces','crm_mutations']);for(const table of runtimeTables.filter(table=>!customerAllowed.has(table)))assert.deepEqual(customerAfterRaw.tables[table],customerRaw.tables[table],table);assert.deepEqual(customerAfterRaw.r2,customerRaw.r2);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);
  const customerReplay=await commercialRequest(customerTransfer);assert.equal(customerReplay.status,200);assert.deepEqual(await raw(),customerAfterRaw);
  // The same task can subsequently change independently, with its previous
  // customer-bundle evidence intact. Use the built HTTP Worker, native local
  // D1 transactions and R2, rather than a helper-only projection.
  const taskResponsibility=await import('../work/task-responsibility.mjs'),taskBefore=await get(),taskBeforeRaw=await raw(),oldTask=taskBefore.tasks.find(t=>t.id===selectedCustomerTask.id),taskTransfer={space:'live',version:taskBefore.version,requestId:crypto.randomUUID(),type:'task_responsibility_transfer',data:{taskId:oldTask.id,targetProfileId:sourceProfile.id,reason:'Uttryckligt granskat fristående runtime-ansvar',reviewed:true,expectedContext:taskResponsibility.taskResponsibilityBasis(taskBefore,oldTask.id)}};
  assert.equal(oldTask.responsibilityTransfers.length,1);assert.equal(oldTask.responsibilityTransfers[0].sourceTransferId,assignedCustomer.responsibilityTransfers[0].id);
  const taskClicks=await Promise.all([commercialRequest(taskTransfer),commercialRequest(taskTransfer)]);for(const r of taskClicks)assert.equal(r.status,200,JSON.stringify(r.data));state=await get();assert.equal(state.version,taskBefore.version+1);const assignedTask=state.tasks.find(t=>t.id===oldTask.id),taskAudit=assignedTask.responsibilityTransfers.at(-1);
  assert.equal(new Date(taskAudit.at).toISOString(),taskAudit.at);assert.deepEqual(taskAudit,{id:taskAudit.id,taskId:oldTask.id,customerId:oldTask.customerId,dealId:oldTask.dealId,source:'task',sourceTransferId:'',action:'transfer',fromRecordedProfileId:targetProfile.id,fromProfileId:targetProfile.id,toProfileId:sourceProfile.id,fromOwner:targetOwner,toOwner:sourceOwner,fromDisplayName:targetProfile.displayName,toDisplayName:sourceProfile.displayName,reason:taskTransfer.data.reason,at:taskAudit.at,byId:state.viewer.id,byMemberId:state.viewer.memberId,byName:state.viewer.name});assert.deepEqual(assignedTask,{...oldTask,owner:sourceOwner,ownerProfileId:sourceProfile.id,responsibilityTransfers:[...oldTask.responsibilityTransfers,taskAudit]});
  for(const t of taskBefore.tasks)if(t.id!==oldTask.id)assert.deepEqual(state.tasks.find(current=>current.id===t.id),t);for(const name of ['customers','deals','orders','meetings','settings','notices','companyEvents'])assert.deepEqual(state[name],taskBefore[name]);
  const taskAfterRaw=await raw(),taskAllowed=new Set(['crm_tasks','crm_events','crm_spaces','crm_mutations']);for(const table of runtimeTables.filter(table=>!taskAllowed.has(table)))assert.deepEqual(taskAfterRaw.tables[table],taskBeforeRaw.tables[table],table+' not part of standalone task handover');assert.deepEqual(taskAfterRaw.r2,taskBeforeRaw.r2);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);
  assert.equal((await commercialRequest(taskTransfer)).status,200);assert.deepEqual(await raw(),taskAfterRaw,'Lost acknowledgment cannot append another task audit');assert.equal((await commercialRequest({...taskTransfer,data:{...taskTransfer.data,reason:'Different task intent'}})).status,409);assert.deepEqual(await raw(),taskAfterRaw);
  const sellerDenied=await api('/api/crm',{method:'POST',headers:{'oai-authenticated-user-id':'runtime-workflow-other','oai-authenticated-user-email':'runtime-workflow-other@example.test','Content-Type':'application/json',Origin:origin},body:JSON.stringify({...taskTransfer,version:state.version,requestId:crypto.randomUUID(),data:{...taskTransfer.data,targetProfileId:targetProfile.id,expectedContext:taskResponsibility.taskResponsibilityBasis(state,oldTask.id)}})});assert.equal(sellerDenied.status,403);assert.deepEqual(await raw(),taskAfterRaw);
  const staleTaskPayload={space:'live',version:state.version,requestId:crypto.randomUUID(),type:'task_responsibility_transfer',data:{taskId:oldTask.id,targetProfileId:targetProfile.id,reason:'Äldre runtime-granskningsunderlag',reviewed:true,expectedContext:taskResponsibility.taskResponsibilityBasis(state,oldTask.id)}};
  await post('task',{...assignedTask,title:'Ny faktisk runtime-instruktion'});const changedTaskRaw=await raw(),staleTaskResponse=await commercialRequest(staleTaskPayload);assert.equal(staleTaskResponse.status,409);assert.equal(staleTaskResponse.data.code,'task_responsibility_conflict');assert.deepEqual(await raw(),changedTaskRaw);assert.deepEqual(state.tasks.find(t=>t.id===oldTask.id).responsibilityTransfers,assignedTask.responsibilityTransfers);
  await post('task_responsibility_transfer',{...staleTaskPayload.data,reason:'Aktuellt omgranskat runtime-underlag',expectedContext:taskResponsibility.taskResponsibilityBasis(state,oldTask.id)});assert.equal(state.tasks.find(t=>t.id===oldTask.id).responsibilityTransfers.length,3);assert.equal(state.tasks.find(t=>t.id===oldTask.id).ownerProfileId,targetProfile.id);
  // Anchor and transfer a real built-Worker Meeting. Each review has its own
  // immutable intent, and no existing Task or private calendar item follows.
  await db.prepare('INSERT INTO outlook_connections(user_id,microsoft_id,email,tokens,last_sync) VALUES(?,?,?,?,?)').bind('runtime-admin','runtime-meeting-synthetic-ms','runtime-admin@example.test','synthetic-sealed-sentinel',today+'T08:00:00Z').run();
  for(const shared of [0,1])await db.prepare('INSERT INTO outlook_items(id,user_id,kind,data,customer_id,shared,happened_at,seen_at) VALUES(?,?,?,?,?,?,?,?)').bind('runtime-meeting-outlook-'+shared,'runtime-admin','meeting',JSON.stringify({subject:'Syntetisk bevarad kalenderpost '+shared}),customer.id,shared,today+'T08:00:00Z',today+'T08:00:00Z').run();
  await db.prepare('INSERT INTO outlook_oauth_states(hash,user_id,verifier,expires) VALUES(?,?,?,?)').bind('runtime-meeting-synthetic-oauth','runtime-admin','synthetic-pkce-sentinel',Date.now()+60000).run();
  const meetingResponsibility=await import('../work/meeting-responsibility.mjs'),meetingBefore=await get(),meetingBeforeRaw=await raw(),oldMeeting=meetingBefore.meetings.find(m=>m.id===legacyRuntimeMeeting.id);
  assert.equal(oldMeeting.ownerProfileId,'','Initializing result profiles did not anchor the old meeting.');
  const oldMeetingDraft={...oldMeeting};delete oldMeetingDraft.ownerProfileId;delete oldMeetingDraft.responsibilityTransfers;
  const oldMeetingDraftResponse=await api('/api/crm',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:origin},body:JSON.stringify({space:'live',version:state.version,requestId:crypto.randomUUID(),type:'meeting',expectedRecord:conflicts.recordBasis(oldMeetingDraft),data:{...oldMeetingDraft,notes:'Ofärdig äldre privat originaltext'}})});assert.equal(oldMeetingDraftResponse.status,409);assert.equal((await oldMeetingDraftResponse.json()).code,'record_conflict');assert.deepEqual(await raw(),meetingBeforeRaw);
  const meetingGenericBypass=await commercialRequest({space:'live',version:state.version,requestId:crypto.randomUUID(),type:'meeting',expectedRecord:conflicts.recordBasis(oldMeeting),data:{...oldMeeting,owner:targetOwner}});assert.equal(meetingGenericBypass.status,400);assert.deepEqual(await raw(),meetingBeforeRaw);
  const meetingTransfer={space:'live',version:meetingBefore.version,requestId:crypto.randomUUID(),type:'meeting_responsibility_transfer',data:{meetingId:oldMeeting.id,targetProfileId:sourceProfile.id,reason:'Uttryckligt förankrat äldre runtime-möte',reviewed:true,expectedContext:meetingResponsibility.meetingResponsibilityBasis(meetingBefore,oldMeeting.id)}};
  const meetingClicks=await Promise.all([commercialRequest(meetingTransfer),commercialRequest(meetingTransfer)]);for(const r of meetingClicks)assert.equal(r.status,200,JSON.stringify(r.data));state=await get();assert.equal(state.version,meetingBefore.version+1);const anchoredMeeting=state.meetings.find(m=>m.id===oldMeeting.id),meetingAudit=anchoredMeeting.responsibilityTransfers.at(-1);
  assert.equal(new Date(meetingAudit.at).toISOString(),meetingAudit.at);assert.deepEqual(meetingAudit,{id:meetingAudit.id,meetingId:oldMeeting.id,customerId:oldMeeting.customerId,action:'anchor',fromRecordedProfileId:'',fromProfileId:sourceProfile.id,toProfileId:sourceProfile.id,fromOwner:sourceOwner,toOwner:sourceOwner,fromDisplayName:sourceProfile.displayName,toDisplayName:sourceProfile.displayName,reason:meetingTransfer.data.reason,at:meetingAudit.at,byId:state.viewer.id,byMemberId:state.viewer.memberId,byName:state.viewer.name});assert.deepEqual(anchoredMeeting,{...oldMeeting,ownerProfileId:sourceProfile.id,responsibilityTransfers:[meetingAudit]});
  const meetingAfterRaw=await raw(),meetingAllowed=new Set(['crm_meetings','crm_events','crm_spaces','crm_mutations']);for(const table of runtimeTables.filter(table=>!meetingAllowed.has(table)))assert.deepEqual(meetingAfterRaw.tables[table],meetingBeforeRaw.tables[table],table+' not part of meeting anchoring');assert.deepEqual(meetingAfterRaw.r2,meetingBeforeRaw.r2);for(const name of ['customers','deals','orders','tasks','settings','notices','companyEvents'])assert.deepEqual(state[name],meetingBefore[name]);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);
  assert.equal((await commercialRequest(meetingTransfer)).status,200);assert.deepEqual(await raw(),meetingAfterRaw,'Lost acknowledgment cannot append another meeting audit');assert.equal((await commercialRequest({...meetingTransfer,data:{...meetingTransfer.data,reason:'Different meeting intent'}})).status,409);assert.deepEqual(await raw(),meetingAfterRaw);
  const sellerMeetingDenied=await api('/api/crm',{method:'POST',headers:{'oai-authenticated-user-id':'runtime-workflow-other','oai-authenticated-user-email':'runtime-workflow-other@example.test','Content-Type':'application/json',Origin:origin},body:JSON.stringify({...meetingTransfer,version:state.version,requestId:crypto.randomUUID(),data:{...meetingTransfer.data,targetProfileId:targetProfile.id,expectedContext:meetingResponsibility.meetingResponsibilityBasis(state,oldMeeting.id)}})});assert.equal(sellerMeetingDenied.status,403);assert.deepEqual(await raw(),meetingAfterRaw);
  const staleMeetingPayload={space:'live',version:state.version,requestId:crypto.randomUUID(),type:'meeting_responsibility_transfer',data:{meetingId:oldMeeting.id,targetProfileId:targetProfile.id,reason:'Äldre runtime-mötesunderlag',reviewed:true,expectedContext:meetingResponsibility.meetingResponsibilityBasis(state,oldMeeting.id)}};
  await post('meeting',{...anchoredMeeting,notes:'Ny faktisk runtime-mötesinstruktion'});const changedMeetingRaw=await raw(),staleMeetingResponse=await commercialRequest(staleMeetingPayload);assert.equal(staleMeetingResponse.status,409);assert.equal(staleMeetingResponse.data.code,'meeting_responsibility_conflict');assert.deepEqual(await raw(),changedMeetingRaw);
  const freshMeetingTransfer={...staleMeetingPayload,version:state.version,requestId:crypto.randomUUID(),data:{...staleMeetingPayload.data,reason:'Aktuellt omgranskat runtime-mötesunderlag',expectedContext:meetingResponsibility.meetingResponsibilityBasis(state,oldMeeting.id)}};
  await db.prepare('UPDATE crm_members SET role=? WHERE id=?').bind('production',targetMember).run();const revokedMeetingRaw=await raw(),revokedMeetingResponse=await commercialRequest(freshMeetingTransfer);assert.equal(revokedMeetingResponse.status,403);assert.deepEqual(await raw(),revokedMeetingRaw);await db.prepare('UPDATE crm_members SET role=? WHERE id=?').bind('seller',targetMember).run();
  await post('meeting_responsibility_transfer',freshMeetingTransfer.data);const transferredMeeting=state.meetings.find(m=>m.id===oldMeeting.id);assert.equal(transferredMeeting.responsibilityTransfers.length,2);assert.equal(transferredMeeting.ownerProfileId,targetProfile.id);assert.equal(transferredMeeting.owner,targetOwner);assert.equal(transferredMeeting.responsibilityTransfers[1].fromRecordedProfileId,sourceProfile.id);assert.deepEqual(state.tasks,meetingBefore.tasks,'Meeting transfer never moves existing meeting_followup or other tasks.');
  const tasksBeforeMeetingDone=structuredClone(state.tasks);await post('meeting',{...transferredMeeting,status:'done'});const meetingNextTask=state.tasks.find(t=>t.title==='Följ upp mötet: '+transferredMeeting.title);assert.ok(meetingNextTask);assert.equal(meetingNextTask.ownerProfileId,targetProfile.id);assert.deepEqual(meetingNextTask.responsibilityTransfers,[]);assert.equal(state.tasks.length,tasksBeforeMeetingDone.length+1);for(const t of tasksBeforeMeetingDone)assert.deepEqual(state.tasks.find(current=>current.id===t.id),t);assert.deepEqual(state.meetings.find(m=>m.id===oldMeeting.id).responsibilityTransfers,transferredMeeting.responsibilityTransfers);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);
  await post('meeting',{customerId:customer.id,owner:sourceOwner,title:'Nytt stabilt runtime-möte',date:core.plusDays(today,8),time:'10:00',duration:30});const newlyStableMeeting=state.meetings.find(m=>m.title==='Nytt stabilt runtime-möte');assert.equal(newlyStableMeeting.ownerProfileId,sourceProfile.id);assert.deepEqual(newlyStableMeeting.responsibilityTransfers,[]);
  const meetingCompletedRaw=await raw();for(const table of ['outlook_connections','outlook_items','outlook_oauth_states','crm_drafts'])assert.deepEqual(meetingCompletedRaw.tables[table],meetingBeforeRaw.tables[table],table+' remains byte-identical after all built meeting workflows');assert.deepEqual(meetingCompletedRaw.r2,meetingBeforeRaw.r2);
  // Onboarding responsibility is separate from the customer, accepted deal,
  // order and production work. Anchor the actual pre-profile workflow first;
  // the existing customer handover above did not silently assign it.
  const onboardingResponsibility=await import('../work/onboarding-responsibility.mjs'),onboardingBefore=await get(),legacyOnboardingCustomer=onboardingBefore.customers.find(c=>c.id===customer.id),legacyOnboarding=legacyOnboardingCustomer.onboarding;
  assert.equal(legacyOnboardingCustomer.ownerProfileId,targetProfile.id);assert.equal(legacyOnboarding.owner,sourceOwner);assert.equal(legacyOnboarding.ownerProfileId,'');assert.deepEqual(legacyOnboarding.responsibilityTransfers,[]);assert.ok(legacyOnboarding.startedAt&&legacyOnboarding.dealId&&!legacyOnboarding.completedAt);
  const onboardingChoices=onboardingResponsibility.onboardingResponsibilityCandidates(onboardingBefore,customer.id),onboardingTaskIds=onboardingChoices.eligible.map(t=>t.id);assert.equal(onboardingChoices.blockedReason,'');assert.ok(onboardingTaskIds.length,'The original built first-order flow has actual selectable onboarding work.');for(const id of onboardingTaskIds){const task=onboardingBefore.tasks.find(t=>t.id===id);assert.equal(task.kind,'onboarding');assert.equal(task.owner,sourceOwner);assert.equal(task.ownerProfileId,'');assert.equal(task.done,false);}
  const assertOnboardingTaskTransfer=(old,next,parent)=>{const audit=next.responsibilityTransfers.at(-1);assert.ok(audit);assert.ok(!old.responsibilityTransfers.some(row=>row.id===audit.id));assert.deepEqual(audit,{id:audit.id,taskId:old.id,customerId:old.customerId,dealId:old.dealId,source:'onboarding',sourceTransferId:parent.id,action:parent.action,fromRecordedProfileId:old.ownerProfileId,fromProfileId:parent.fromProfileId,toProfileId:parent.toProfileId,fromOwner:old.owner,toOwner:parent.toOwner,fromDisplayName:parent.fromDisplayName,toDisplayName:parent.toDisplayName,reason:parent.reason,at:parent.at,byId:parent.byId,byMemberId:parent.byMemberId,byName:parent.byName});assert.deepEqual(next,{...old,owner:parent.toOwner,ownerProfileId:parent.toProfileId,responsibilityTransfers:[...old.responsibilityTransfers,audit]});};
  const onboardingDraftId=crypto.randomUUID(),onboardingDraftBasis=conflicts.customerWorkflowBasis(onboardingBefore,'onboarding',customer.id),onboardingDraftValues={...legacyOnboarding,feedback:'  Privat ofärdig återkoppling\n behåll råtexten  '};
  const unfinishedOnboarding=await draftWrite({id:onboardingDraftId,kind:'onboarding',context:customer.id,revision:0,requestId:crypto.randomUUID(),title:'Privat äldre onboarding i riktig Worker',data:{values:onboardingDraftValues,expectedContext:onboardingDraftBasis,customerName:customer.name}});assert.equal(unfinishedOnboarding.status,200,JSON.stringify(unfinishedOnboarding.data));assert.deepEqual(await get(),onboardingBefore);
  const readOnboardingDraft=async who=>{const r=await api('/api/crm/drafts?space=live&id='+onboardingDraftId,{headers:who});assert.equal(r.status,200);return r.json();};
  const savedOnboardingDraft=await readOnboardingDraft(headers);assert.equal(savedOnboardingDraft.length,1);assert.equal(savedOnboardingDraft[0].archived,false);assert.equal(savedOnboardingDraft[0].data.values.feedback,onboardingDraftValues.feedback);assert.deepEqual(await readOnboardingDraft({'oai-authenticated-user-id':'runtime-workflow-other','oai-authenticated-user-email':'runtime-workflow-other@example.test'}),[]);
  const onboardingRaw=await raw();for(const table of ['crm_drafts','outlook_connections','outlook_items','outlook_oauth_states'])assert.ok(onboardingRaw.tables[table].length,table+' has positive privacy/external sentinels');assert.ok(Object.keys(onboardingRaw.r2).length>=3,'There are actual preserved source and restored R2 objects.');
  const onboardingTransfer={space:'live',version:onboardingBefore.version,requestId:crypto.randomUUID(),type:'onboarding_responsibility_transfer',data:{customerId:customer.id,targetProfileId:sourceProfile.id,selectedTaskIds:onboardingTaskIds,reason:'Granskad förankring av äldre fiktiv onboarding',reviewed:true,expectedContext:onboardingResponsibility.onboardingResponsibilityBasis(onboardingBefore,customer.id)}};
  const staleOnboardingTransfer={...onboardingTransfer,requestId:crypto.randomUUID(),data:{...onboardingTransfer.data,targetProfileId:targetProfile.id,reason:'Äldre granskning före stabil förankring'}};
  const unrelatedOnboardingTask=onboardingBefore.tasks.find(t=>t.kind!=='onboarding'&&!t.done);assert.ok(unrelatedOnboardingTask);const invalidOnboardingSelection=await commercialRequest({...onboardingTransfer,requestId:crypto.randomUUID(),data:{...onboardingTransfer.data,selectedTaskIds:[...onboardingTaskIds,unrelatedOnboardingTask.id]}});assert.equal(invalidOnboardingSelection.status,400,JSON.stringify(invalidOnboardingSelection.data));assert.deepEqual(await raw(),onboardingRaw,'Unrelated task selection cannot write part of an onboarding handover.');
  const onboardingClicks=await Promise.all([commercialRequest(onboardingTransfer),commercialRequest(onboardingTransfer)]);for(const response of onboardingClicks)assert.equal(response.status,200,JSON.stringify(response.data));state=await get();assert.equal(state.version,onboardingBefore.version+1);const anchoredOnboardingCustomer=state.customers.find(c=>c.id===customer.id),anchoredOnboarding=anchoredOnboardingCustomer.onboarding,onboardingAnchorAudit=anchoredOnboarding.responsibilityTransfers[0];
  assert.equal(anchoredOnboarding.owner,sourceOwner);assert.equal(anchoredOnboarding.ownerProfileId,sourceProfile.id);assert.equal(anchoredOnboarding.responsibilityTransfers.length,1);assert.equal(new Date(onboardingAnchorAudit.at).toISOString(),onboardingAnchorAudit.at);
  assert.deepEqual(onboardingAnchorAudit,{id:onboardingAnchorAudit.id,customerId:customer.id,dealId:legacyOnboarding.dealId,action:'anchor',fromRecordedProfileId:'',fromProfileId:sourceProfile.id,toProfileId:sourceProfile.id,fromOwner:sourceOwner,toOwner:sourceOwner,fromDisplayName:sourceProfile.displayName,toDisplayName:sourceProfile.displayName,selectedTaskIds:onboardingTaskIds,reason:onboardingTransfer.data.reason,at:onboardingAnchorAudit.at,byId:state.viewer.id,byMemberId:state.viewer.memberId,byName:state.viewer.name});
  assert.deepEqual(anchoredOnboarding,{...legacyOnboarding,ownerProfileId:sourceProfile.id,responsibilityTransfers:[onboardingAnchorAudit]});assert.deepEqual(anchoredOnboardingCustomer,{...legacyOnboardingCustomer,onboarding:anchoredOnboarding});for(const current of onboardingBefore.customers.filter(c=>c.id!==customer.id))assert.deepEqual(state.customers.find(c=>c.id===current.id),current);
  for(const old of onboardingBefore.tasks)if(onboardingTaskIds.includes(old.id))assertOnboardingTaskTransfer(old,state.tasks.find(t=>t.id===old.id),onboardingAnchorAudit);else assert.deepEqual(state.tasks.find(t=>t.id===old.id),old);for(const name of ['orders','deals','meetings','settings','notices','companyEvents'])assert.deepEqual(state[name],onboardingBefore[name]);
  const onboardingAllowed=new Set(['crm_customers','crm_tasks','crm_events','crm_spaces','crm_mutations']),assertOnboardingIsolation=(before,after)=>{for(const table of runtimeTables.filter(table=>!onboardingAllowed.has(table)))assert.deepEqual(after.tables[table],before.tables[table],table+' independent of onboarding handover');assert.deepEqual(after.r2,before.r2);for(const table of runtimeTables.filter(table=>table.startsWith('crm_')&&table!=='crm_members')){const outside=rows=>rows.filter(row=>row.space&&row.space!=='live');assert.deepEqual(outside(after.tables[table]),outside(before.tables[table]),table+' other workspace unchanged');}};
  const onboardingAnchorRaw=await raw();assertOnboardingIsolation(onboardingRaw,onboardingAnchorRaw);assert.deepEqual(await readOnboardingDraft(headers),savedOnboardingDraft);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);
  assert.equal((await commercialRequest(onboardingTransfer)).status,200);assert.deepEqual(await raw(),onboardingAnchorRaw,'Lost anchoring acknowledgment replays one stored parent/task commit.');assert.equal((await commercialRequest({...onboardingTransfer,data:{...onboardingTransfer.data,reason:'Different onboarding intent'}})).status,409);assert.deepEqual(await raw(),onboardingAnchorRaw);
  const staleOnboardingResponse=await commercialRequest(staleOnboardingTransfer);assert.equal(staleOnboardingResponse.status,409);assert.equal(staleOnboardingResponse.data.code,'onboarding_responsibility_conflict');assert.deepEqual(await raw(),onboardingAnchorRaw,'Same owner label with a newly anchored stable ID requires a fresh review.');
  const oldChecklistResponse=await commercialRequest({space:'live',version:state.version,requestId:crypto.randomUUID(),type:'onboarding',data:{customerId:customer.id,expectedContext:onboardingDraftBasis,onboarding:onboardingDraftValues,complete:false,draft:{id:onboardingDraftId,revision:unfinishedOnboarding.data.revision}}});assert.equal(oldChecklistResponse.status,409);assert.equal(oldChecklistResponse.data.code,'customer_workflow_conflict');assert.deepEqual(await raw(),onboardingAnchorRaw);assert.deepEqual(await readOnboardingDraft(headers),savedOnboardingDraft,'Stale private checklist text and its unarchived revision survive.');
  const currentChecklistCustomer=state.customers.find(c=>c.id===customer.id),genericOnboardingBypass=await commercialRequest({space:'live',version:state.version,requestId:crypto.randomUUID(),type:'onboarding',data:{customerId:customer.id,expectedContext:conflicts.customerWorkflowBasis(state,'onboarding',customer.id),onboarding:{...currentChecklistCustomer.onboarding,owner:targetOwner},complete:false}});assert.equal(genericOnboardingBypass.status,400,JSON.stringify(genericOnboardingBypass.data));assert.deepEqual(await raw(),onboardingAnchorRaw,'The checklist cannot bypass reviewed stable responsibility.');
  const freshOnboardingTransfer={...staleOnboardingTransfer,version:state.version,requestId:crypto.randomUUID(),data:{...staleOnboardingTransfer.data,reason:'Aktuellt omgranskat ansvar för fiktiv onboarding',expectedContext:onboardingResponsibility.onboardingResponsibilityBasis(state,customer.id)}};
  const sellerOnboardingDenied=await api('/api/crm',{method:'POST',headers:{'oai-authenticated-user-id':'runtime-workflow-other','oai-authenticated-user-email':'runtime-workflow-other@example.test','Content-Type':'application/json',Origin:origin},body:JSON.stringify(freshOnboardingTransfer)});assert.equal(sellerOnboardingDenied.status,403);assert.deepEqual(await raw(),onboardingAnchorRaw);
  await db.prepare('UPDATE crm_members SET active=0 WHERE id=?').bind(targetMember).run();const revokedOnboardingRaw=await raw(),revokedOnboardingResponse=await commercialRequest(freshOnboardingTransfer);assert.equal(revokedOnboardingResponse.status,403,JSON.stringify(revokedOnboardingResponse.data));assert.deepEqual(await raw(),revokedOnboardingRaw,'Revoked target account cannot write onboarding, selected tasks, ledger, drafts or files.');await db.prepare('UPDATE crm_members SET active=1 WHERE id=?').bind(targetMember).run();
  const onboardingMoveBefore=await get(),onboardingMoveRaw=await raw(),onboardingMoveClicks=await Promise.all([commercialRequest(freshOnboardingTransfer),commercialRequest(freshOnboardingTransfer)]);for(const response of onboardingMoveClicks)assert.equal(response.status,200,JSON.stringify(response.data));state=await get();assert.equal(state.version,onboardingMoveBefore.version+1);const movedOnboardingCustomer=state.customers.find(c=>c.id===customer.id),movedOnboarding=movedOnboardingCustomer.onboarding,onboardingMoveAudit=movedOnboarding.responsibilityTransfers.at(-1);assert.equal(movedOnboarding.owner,targetOwner);assert.equal(movedOnboarding.ownerProfileId,targetProfile.id);assert.equal(movedOnboarding.responsibilityTransfers.length,2);assert.equal(onboardingMoveAudit.action,'transfer');assert.equal(onboardingMoveAudit.fromRecordedProfileId,sourceProfile.id);assert.equal(onboardingMoveAudit.fromProfileId,sourceProfile.id);assert.equal(onboardingMoveAudit.toProfileId,targetProfile.id);assert.deepEqual(onboardingMoveAudit.selectedTaskIds,onboardingTaskIds);assert.equal(onboardingMoveAudit.reason,freshOnboardingTransfer.data.reason);assert.equal(onboardingMoveAudit.byMemberId,state.viewer.memberId);assert.deepEqual(movedOnboardingCustomer,{...onboardingMoveBefore.customers.find(c=>c.id===customer.id),onboarding:movedOnboarding});
  for(const old of onboardingMoveBefore.tasks)if(onboardingTaskIds.includes(old.id))assertOnboardingTaskTransfer(old,state.tasks.find(t=>t.id===old.id),onboardingMoveAudit);else assert.deepEqual(state.tasks.find(t=>t.id===old.id),old);for(const name of ['orders','deals','meetings','settings','notices','companyEvents'])assert.deepEqual(state[name],onboardingMoveBefore[name]);const onboardingMoveAfterRaw=await raw();assertOnboardingIsolation(onboardingMoveRaw,onboardingMoveAfterRaw);assert.equal((await commercialRequest(freshOnboardingTransfer)).status,200);assert.deepEqual(await raw(),onboardingMoveAfterRaw,'Lost transfer acknowledgment cannot duplicate parent/task history.');assert.deepEqual(await readOnboardingDraft(headers),savedOnboardingDraft);
  // A fresh first order after profile initialization inherits the customer's
  // exact verified profile. Generated work starts with an empty audit chain.
  await post('catalog_order',{customerId:newCustomer.id,owner:sourceOwner,title:'Fiktiv första order med stabil onboarding',lines:[{id:'runtime-onboarding-new-line',kind:'product',article:'TEST-ONBOARDING',description:'Fiktiv provprodukt',quantity:1,unitPrice:100,unitCost:60}],deliveryDate:core.plusDays(today,30),accepted:true,nextDate:today});const newOnboardingCustomer=state.customers.find(c=>c.id===newCustomer.id);assert.equal(newOnboardingCustomer.onboarding.ownerProfileId,sourceProfile.id);assert.deepEqual(newOnboardingCustomer.onboarding.responsibilityTransfers,[]);const newOnboardingTask=state.tasks.find(t=>t.customerId===newCustomer.id&&t.kind==='onboarding'&&!t.done);assert.ok(newOnboardingTask);assert.equal(newOnboardingTask.ownerProfileId,sourceProfile.id);assert.deepEqual(newOnboardingTask.responsibilityTransfers,[]);assert.deepEqual(state.customers.find(c=>c.id===customer.id).onboarding,movedOnboarding);assert.deepEqual(await readOnboardingDraft(headers),savedOnboardingDraft);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);
  const unselectedOnboardingBefore=await get(),unselectedOnboardingRaw=await raw();await post('onboarding_responsibility_transfer',{customerId:newCustomer.id,targetProfileId:targetProfile.id,selectedTaskIds:[],reason:'Granskad separat onboarding utan att flytta befintliga uppgifter',reviewed:true,expectedContext:onboardingResponsibility.onboardingResponsibilityBasis(state,newCustomer.id)});const unselectedOnboarding=state.customers.find(c=>c.id===newCustomer.id).onboarding;assert.equal(unselectedOnboarding.ownerProfileId,targetProfile.id);assert.deepEqual(unselectedOnboarding.responsibilityTransfers[0].selectedTaskIds,[]);assert.deepEqual(state.tasks,unselectedOnboardingBefore.tasks,'Unselected onboarding work stays with its existing exact profile.');const unselectedOnboardingAfterRaw=await raw();assert.deepEqual(unselectedOnboardingAfterRaw.tables.crm_tasks,unselectedOnboardingRaw.tables.crm_tasks);assertOnboardingIsolation(unselectedOnboardingRaw,unselectedOnboardingAfterRaw);for(const name of ['orders','deals','meetings','settings','notices','companyEvents'])assert.deepEqual(state[name],unselectedOnboardingBefore[name]);
  const onboardingCompletedRaw=await raw();for(const table of ['outlook_connections','outlook_items','outlook_oauth_states','crm_drafts'])assert.deepEqual(onboardingCompletedRaw.tables[table],onboardingRaw.tables[table],table+' remains byte-identical after all built onboarding workflows');assert.deepEqual(onboardingCompletedRaw.r2,onboardingRaw.r2);
  // The issue belongs to the customer plan, with its own reviewed parent and
  // selected Task audits. Profile initialization and customer handover above
  // leave both original blank-ID tasks and the separate issue owner untouched.
  const issues=await import('../work/issue-responsibility.mjs'),followups=await import('../work/follow-up.mjs');
  const issueBefore=await get(),oldIssueCustomer=issueBefore.customers.find(c=>c.id===customer.id),oldIssuePlan=oldIssueCustomer.plan;
  assert.equal(oldIssuePlan.issueOwner,sourceOwner);assert.equal(oldIssuePlan.issueOwnerProfileId,'');assert.deepEqual(oldIssuePlan.issueResponsibilityTransfers,[]);
  for(const id of [legacyIssueTask.id,unselectedIssueTask.id]){const task=issueBefore.tasks.find(t=>t.id===id);assert.equal(task.ownerProfileId,'');assert.deepEqual(task.responsibilityTransfers,[]);}
  const issueChoices=issues.issueResponsibilityCandidates(issueBefore,customer.id),selectedIssueIds=[legacyIssueTask.id];
  assert.equal(issueChoices.blockedReason,'');assert.deepEqual(issueChoices.eligible.map(t=>t.id).sort(),[legacyIssueTask.id,unselectedIssueTask.id].sort());
  const issueDraftId=crypto.randomUUID(),issueDraftBasis=conflicts.customerWorkflowBasis(issueBefore,'plan',customer.id);
  const issueDraftValues={...oldIssuePlan,issueAction:'  Ofärdig privat ärendetext\n behåll råtexten  ',nextReview:oldIssueCustomer.nextReview,expectedOrder:oldIssueCustomer.expectedOrder,reviewDays:oldIssueCustomer.reviewDays,reviewed:false};
  const unfinishedIssue=await draftWrite({id:issueDraftId,kind:'plan',context:customer.id,revision:0,requestId:crypto.randomUUID(),title:'Privat äldre kundärende i riktig Worker',data:{values:issueDraftValues,expectedContext:issueDraftBasis,customerName:customer.name}});
  assert.equal(unfinishedIssue.status,200,JSON.stringify(unfinishedIssue.data));assert.deepEqual(await get(),issueBefore);
  const readIssueDraft=async who=>{const response=await api('/api/crm/drafts?space=live&id='+issueDraftId,{headers:who});assert.equal(response.status,200);return response.json();};
  const savedIssueDraft=await readIssueDraft(headers);assert.equal(savedIssueDraft[0].archived,false);assert.equal(savedIssueDraft[0].data.values.issueAction,issueDraftValues.issueAction);
  assert.deepEqual(await readIssueDraft({'oai-authenticated-user-id':'runtime-workflow-other','oai-authenticated-user-email':'runtime-workflow-other@example.test'}),[]);
  const issueRaw=await raw(),issueAllowed=new Set(['crm_customers','crm_tasks','crm_events','crm_spaces','crm_mutations']);
  const assertIssueIsolation=(before,after)=>{
    for(const table of runtimeTables.filter(table=>!issueAllowed.has(table)))assert.deepEqual(after.tables[table],before.tables[table],table+' independent of issue responsibility');
    assert.deepEqual(after.r2,before.r2,'Every synthetic R2 byte remains unchanged.');
    for(const table of runtimeTables.filter(table=>table.startsWith('crm_')&&table!=='crm_members')){const outside=rows=>rows.filter(row=>row.space&&row.space!=='live');assert.deepEqual(outside(after.tables[table]),outside(before.tables[table]),table+' other workspace unchanged');}
  };
  const issuePayload=(snapshot,targetProfileId,reason)=>({space:'live',version:snapshot.version,requestId:crypto.randomUUID(),type:'issue_responsibility_transfer',data:{customerId:customer.id,targetProfileId,selectedTaskIds:selectedIssueIds,reason,reviewed:true,expectedContext:issues.issueResponsibilityBasis(snapshot,customer.id)}});
  const assertIssueCommit=async(previous,stored,payload,action)=>{
    state=await get();assert.equal(state.version,previous.version+1);
    const prior=previous.customers.find(c=>c.id===customer.id),current=state.customers.find(c=>c.id===customer.id),parent=current.plan.issueResponsibilityTransfers.at(-1),target=state.settings.sellerProfiles.find(p=>p.id===payload.data.targetProfileId);
    assert.equal(new Date(parent.at).toISOString(),parent.at);
    assert.deepEqual(parent,{id:parent.id,customerId:customer.id,action,fromRecordedProfileId:prior.plan.issueOwnerProfileId,fromProfileId:sourceProfile.id,toProfileId:target.id,fromOwner:prior.plan.issueOwner,toOwner:target.legacyOwnerName,fromDisplayName:sourceProfile.displayName,toDisplayName:target.displayName,selectedTaskIds:selectedIssueIds,reason:payload.data.reason,at:parent.at,byId:state.viewer.id,byMemberId:state.viewer.memberId,byName:state.viewer.name});
    assert.deepEqual(current,{...prior,plan:{...prior.plan,issueOwner:target.legacyOwnerName,issueOwnerProfileId:target.id,issueResponsibilityTransfers:[...prior.plan.issueResponsibilityTransfers,parent]}});
    for(const other of previous.customers.filter(c=>c.id!==customer.id))assert.deepEqual(state.customers.find(c=>c.id===other.id),other);
    for(const old of previous.tasks){
      const next=state.tasks.find(t=>t.id===old.id);
      if(!selectedIssueIds.includes(old.id)){assert.deepEqual(next,old);continue;}
      const audit=next.responsibilityTransfers.at(-1);assert.ok(!old.responsibilityTransfers.some(row=>row.id===audit.id));
      assert.deepEqual(audit,{id:audit.id,taskId:old.id,customerId:old.customerId,dealId:old.dealId,source:'customer_issue',sourceTransferId:parent.id,action,fromRecordedProfileId:old.ownerProfileId,fromProfileId:parent.fromProfileId,toProfileId:parent.toProfileId,fromOwner:old.owner,toOwner:parent.toOwner,fromDisplayName:parent.fromDisplayName,toDisplayName:parent.toDisplayName,reason:parent.reason,at:parent.at,byId:parent.byId,byMemberId:parent.byMemberId,byName:parent.byName});
      assert.deepEqual(next,{...old,owner:parent.toOwner,ownerProfileId:parent.toProfileId,responsibilityTransfers:[...old.responsibilityTransfers,audit]});
    }
    for(const name of ['orders','deals','meetings','settings','notices','companyEvents'])assert.deepEqual(state[name],previous[name]);
    const after=await raw();assertIssueIsolation(stored,after);assert.deepEqual(await readIssueDraft(headers),savedIssueDraft);return after;
  };
  const issueAnchor=issuePayload(issueBefore,sourceProfile.id,'Granskad förankring av äldre fiktivt kundärende');
  const staleIssueTransfer={...issueAnchor,requestId:crypto.randomUUID(),data:{...issueAnchor.data,targetProfileId:targetProfile.id,reason:'Äldre ärendegranskning före stabil förankring'}};
  const unrelatedIssueTask=issueBefore.tasks.find(t=>t.kind!=='csm_issue'&&!t.done);assert.ok(unrelatedIssueTask);
  const invalidIssueSelection=await commercialRequest({...issueAnchor,requestId:crypto.randomUUID(),data:{...issueAnchor.data,selectedTaskIds:[...selectedIssueIds,unrelatedIssueTask.id]}});
  assert.equal(invalidIssueSelection.status,400,JSON.stringify(invalidIssueSelection.data));assert.deepEqual(await raw(),issueRaw);
  const issueAnchorClicks=await Promise.all([commercialRequest(issueAnchor),commercialRequest(issueAnchor)]);for(const response of issueAnchorClicks)assert.equal(response.status,200,JSON.stringify(response.data));
  const issueAnchorRaw=await assertIssueCommit(issueBefore,issueRaw,issueAnchor,'anchor');
  assert.equal((await commercialRequest(issueAnchor)).status,200);assert.deepEqual(await raw(),issueAnchorRaw,'Lost anchoring acknowledgment replays one stored issue/task commit.');
  assert.equal((await commercialRequest({...issueAnchor,data:{...issueAnchor.data,reason:'Different issue intent'}})).status,409);assert.deepEqual(await raw(),issueAnchorRaw);
  const staleIssueResponse=await commercialRequest(staleIssueTransfer);assert.equal(staleIssueResponse.status,409);assert.equal(staleIssueResponse.data.code,'issue_responsibility_conflict');assert.deepEqual(await raw(),issueAnchorRaw);
  const staleIssuePublication=await commercialRequest({space:'live',version:state.version,requestId:crypto.randomUUID(),type:'plan',data:{customerId:customer.id,expectedContext:issueDraftBasis,plan:issueDraftValues,nextReview:issueDraftValues.nextReview,expectedOrder:issueDraftValues.expectedOrder,reviewDays:issueDraftValues.reviewDays,reviewed:false,draft:{id:issueDraftId,revision:unfinishedIssue.data.revision}}});
  assert.equal(staleIssuePublication.status,409);assert.equal(staleIssuePublication.data.code,'customer_workflow_conflict');assert.deepEqual(await raw(),issueAnchorRaw);assert.deepEqual(await readIssueDraft(headers),savedIssueDraft,'Stale plan text and its unarchived private revision survive.');
  const anchoredIssueCustomer=state.customers.find(c=>c.id===customer.id),issueBypass=await commercialRequest({space:'live',version:state.version,requestId:crypto.randomUUID(),type:'plan',data:{customerId:customer.id,expectedContext:conflicts.customerWorkflowBasis(state,'plan',customer.id),plan:{...anchoredIssueCustomer.plan,issueOwner:targetOwner},nextReview:anchoredIssueCustomer.nextReview,expectedOrder:anchoredIssueCustomer.expectedOrder,reviewDays:anchoredIssueCustomer.reviewDays}});
  assert.equal(issueBypass.status,400,JSON.stringify(issueBypass.data));assert.deepEqual(await raw(),issueAnchorRaw,'Ordinary plan work cannot bypass a reviewed issue identity.');
  const freshIssueTransfer=issuePayload(state,targetProfile.id,'Aktuellt omgranskat ansvar för fiktivt kundärende');
  const sellerIssueDenied=await api('/api/crm',{method:'POST',headers:{'oai-authenticated-user-id':'runtime-workflow-other','oai-authenticated-user-email':'runtime-workflow-other@example.test','Content-Type':'application/json',Origin:origin},body:JSON.stringify(freshIssueTransfer)});
  assert.equal(sellerIssueDenied.status,403);assert.deepEqual(await raw(),issueAnchorRaw);
  await db.prepare('UPDATE crm_members SET active=0 WHERE id=?').bind(targetMember).run();
  const revokedIssueRaw=await raw(),revokedIssueResponse=await commercialRequest(freshIssueTransfer);assert.equal(revokedIssueResponse.status,403,JSON.stringify(revokedIssueResponse.data));assert.deepEqual(await raw(),revokedIssueRaw,'Actual SQL account revocation preserves all 18 tables, private drafts and R2 bytes.');
  await db.prepare('UPDATE crm_members SET active=1 WHERE id=?').bind(targetMember).run();
  // A different customer's note advances the actual D1 version. The reviewed
  // issue still rebases safely, and concurrent duplicate requests commit once.
  await post('note',{customerId:newCustomer.id,text:'Syntetisk oberoende anteckning före ärendets CAS',contact:false,nextReview:''});
  const issueMoveBefore=await get(),issueMoveRaw=await raw();assert.ok(issueMoveBefore.version>freshIssueTransfer.version);
  const issueMoveClicks=await Promise.all([commercialRequest(freshIssueTransfer),commercialRequest(freshIssueTransfer)]);for(const response of issueMoveClicks)assert.equal(response.status,200,JSON.stringify(response.data));
  const issueMoveAfterRaw=await assertIssueCommit(issueMoveBefore,issueMoveRaw,freshIssueTransfer,'transfer');
  assert.equal((await commercialRequest(freshIssueTransfer)).status,200);assert.deepEqual(await raw(),issueMoveAfterRaw,'Lost transfer acknowledgment cannot duplicate issue/task history.');
  const keptUnselectedIssue=structuredClone(state.tasks.find(t=>t.id===unselectedIssueTask.id)),keptSelectedIssue=structuredClone(state.tasks.find(t=>t.id===legacyIssueTask.id)),keptIssueAudit=structuredClone(state.customers.find(c=>c.id===customer.id).plan.issueResponsibilityTransfers);
  await savePlan(customer.id,{goal:'Förtydligad fiktiv kundplan',issueAction:'Planens förtydligade ärendeåtgärd',issueDue:core.plusDays(today,5)});
  assert.deepEqual(state.tasks.find(t=>t.id===unselectedIssueTask.id),keptUnselectedIssue,'Normal plan refresh preserves the whole unselected issue task.');
  const refreshedIssueTask=state.tasks.find(t=>t.id===legacyIssueTask.id);assert.equal(refreshedIssueTask.ownerProfileId,targetProfile.id);assert.deepEqual(refreshedIssueTask.responsibilityTransfers,keptSelectedIssue.responsibilityTransfers);assert.deepEqual(state.customers.find(c=>c.id===customer.id).plan.issueResponsibilityTransfers,keptIssueAudit);
  const issueFollowBefore=await get(),issueFollowPlan=issueFollowBefore.customers.find(c=>c.id===customer.id).plan,issueFollowTask=issueFollowBefore.tasks.find(t=>t.id===legacyIssueTask.id);
  const issueNextAction='Följ upp fiktivt storleksbesked',issueNextDate=core.plusDays(today,6);
  await post('follow_up',{taskId:issueFollowTask.id,expectedContext:followups.followupBasis(state,issueFollowTask.id),outcome:'internal',occurredOn:today,note:'Fiktiv intern uppföljning av det överlämnade ärendet',completed:false,nextAction:issueNextAction,nextDate:issueNextDate});
  assert.deepEqual(state.customers.find(c=>c.id===customer.id).plan,{...issueFollowPlan,issueAction:issueNextAction,issueDue:issueNextDate});
  assert.deepEqual(state.tasks.find(t=>t.id===issueFollowTask.id),{...issueFollowTask,title:issueNextAction,due:issueNextDate});
  for(const old of issueFollowBefore.tasks.filter(t=>t.id!==issueFollowTask.id))assert.deepEqual(state.tasks.find(t=>t.id===old.id),old);
  const resolvingIssuePlan=structuredClone(state.customers.find(c=>c.id===customer.id).plan);await savePlan(customer.id,{issueStatus:'resolved'});
  assert.deepEqual(state.customers.find(c=>c.id===customer.id).plan,{...resolvingIssuePlan,issueStatus:'resolved'});assert.ok(state.tasks.filter(t=>t.customerId===customer.id&&t.kind==='csm_issue').every(t=>t.done));
  const completedIssueTasks=state.tasks.filter(t=>t.customerId===customer.id&&t.kind==='csm_issue');await savePlan(customer.id,{issueStatus:'open'});
  const replacementIssueTask=state.tasks.find(t=>t.customerId===customer.id&&t.kind==='csm_issue'&&!t.done);assert.ok(replacementIssueTask);assert.ok(!completedIssueTasks.some(t=>t.id===replacementIssueTask.id));assert.equal(replacementIssueTask.owner,targetOwner);assert.equal(replacementIssueTask.ownerProfileId,targetProfile.id);assert.deepEqual(replacementIssueTask.responsibilityTransfers,[]);
  assert.deepEqual(state.customers.find(c=>c.id===customer.id).plan,{...resolvingIssuePlan,issueStatus:'open'});for(const old of completedIssueTasks)assert.deepEqual(state.tasks.find(t=>t.id===old.id),old);
  // The first clean issue after initialization requires the explicit active
  // UUID; an owner label alone never creates a stable responsibility link.
  const pristineIssueCustomer=state.customers.find(c=>c.id===newCustomer.id),freshIssuePlan={...pristineIssueCustomer.plan,nextAction:'Följ upp den nya fiktiva kundrelationen',issueStatus:'open',issue:'Fiktivt första ärende efter profilstart',issueAction:'Granska fiktivt kundbesked',issueOwner:sourceOwner,issueDue:core.plusDays(today,8)},freshIssueRaw=await raw();
  assert.equal(pristineIssueCustomer.plan.issueStatus,'none');assert.equal(pristineIssueCustomer.plan.issueOwner,'');assert.equal(pristineIssueCustomer.plan.issueOwnerProfileId,'');assert.deepEqual(pristineIssueCustomer.plan.issueResponsibilityTransfers,[]);
  const missingIssueId=await commercialRequest({space:'live',version:state.version,requestId:crypto.randomUUID(),type:'plan',data:{customerId:newCustomer.id,expectedContext:conflicts.customerWorkflowBasis(state,'plan',newCustomer.id),plan:freshIssuePlan,nextReview:pristineIssueCustomer.nextReview||core.plusDays(today,7),expectedOrder:pristineIssueCustomer.expectedOrder,reviewDays:pristineIssueCustomer.reviewDays}});
  assert.equal(missingIssueId.status,400,JSON.stringify(missingIssueId.data));assert.deepEqual(await raw(),freshIssueRaw);
  await savePlan(newCustomer.id,{...freshIssuePlan,issueOwnerProfileId:sourceProfile.id,nextAction:'Följ upp den nya fiktiva kundrelationen'});
  const firstIssue=state.customers.find(c=>c.id===newCustomer.id).plan,firstIssueTask=state.tasks.find(t=>t.customerId===newCustomer.id&&t.kind==='csm_issue'&&!t.done);
  assert.equal(firstIssue.issueOwnerProfileId,sourceProfile.id);assert.deepEqual(firstIssue.issueResponsibilityTransfers,[]);assert.ok(firstIssueTask);assert.equal(firstIssueTask.ownerProfileId,sourceProfile.id);assert.deepEqual(firstIssueTask.responsibilityTransfers,[]);
  const noSelectionIssueBefore=await get(),noSelectionIssueRaw=await raw();
  await post('issue_responsibility_transfer',{customerId:newCustomer.id,targetProfileId:targetProfile.id,selectedTaskIds:[],reason:'Granskat separat ärendeansvar utan flytt av befintlig uppgift',reviewed:true,expectedContext:issues.issueResponsibilityBasis(state,newCustomer.id)});
  const noSelectionIssue=state.customers.find(c=>c.id===newCustomer.id).plan;
  assert.equal(noSelectionIssue.issueOwnerProfileId,targetProfile.id);assert.deepEqual(noSelectionIssue.issueResponsibilityTransfers[0].selectedTaskIds,[]);assert.deepEqual(state.tasks,noSelectionIssueBefore.tasks);assertIssueIsolation(noSelectionIssueRaw,await raw());
  const unselectedCanonicalAction='Förtydligad åtgärd hos befintlig uppgiftsansvarig',unselectedCanonicalDue=core.plusDays(today,9);
  await savePlan(newCustomer.id,{goal:'Fiktiv planuppdatering efter separat ärendeöverlämning',issueAction:unselectedCanonicalAction,issueDue:unselectedCanonicalDue});
  assert.deepEqual(state.tasks.find(t=>t.id===firstIssueTask.id),{...firstIssueTask,title:unselectedCanonicalAction,due:unselectedCanonicalDue},'An unaudited canonical task keeps its exact owner and empty audit after an unselected handover and later plan refresh.');
  assert.equal(state.customers.find(c=>c.id===newCustomer.id).plan.issueOwnerProfileId,targetProfile.id);assert.deepEqual(state.customers.find(c=>c.id===newCustomer.id).plan.issueResponsibilityTransfers,noSelectionIssue.issueResponsibilityTransfers);
  const unselectedFollowTask=structuredClone(state.tasks.find(t=>t.id===firstIssueTask.id)),unselectedFollowPlan=structuredClone(state.customers.find(c=>c.id===newCustomer.id).plan),unselectedFollowAction='Följ upp kvarlämnad fiktiv ärendeuppgift',unselectedFollowDue=core.plusDays(today,10);
  await post('follow_up',{taskId:unselectedFollowTask.id,expectedContext:followups.followupBasis(state,unselectedFollowTask.id),outcome:'internal',occurredOn:today,note:'Fiktiv intern uppföljning hos kvarvarande uppgiftsansvarig',completed:false,nextAction:unselectedFollowAction,nextDate:unselectedFollowDue});
  assert.deepEqual(state.tasks.find(t=>t.id===unselectedFollowTask.id),{...unselectedFollowTask,title:unselectedFollowAction,due:unselectedFollowDue});assert.deepEqual(state.customers.find(c=>c.id===newCustomer.id).plan,{...unselectedFollowPlan,issueAction:unselectedFollowAction,issueDue:unselectedFollowDue});
  const issueCompletedRaw=await raw();for(const table of ['outlook_connections','outlook_items','outlook_oauth_states','crm_drafts'])assert.deepEqual(issueCompletedRaw.tables[table],issueRaw.tables[table],table+' remains byte-identical after all built issue workflows');assert.deepEqual(issueCompletedRaw.r2,issueRaw.r2);
  assertIssueIsolation(issueRaw,issueCompletedRaw);assert.deepEqual(await readIssueDraft(headers),savedIssueDraft);assert.deepEqual(await readOnboardingDraft(headers),savedOnboardingDraft);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);
  const commercialSource=await get(),commercialExport=await fetch(new URL('/api/crm/backup?space=live&format=stream',await mf.ready),{headers:{...headers,'Accept-Encoding':'identity'}});assert.equal(commercialExport.status,200);const commercialBytes=new Uint8Array(await commercialExport.arrayBuffer()),commercialRecords=new TextDecoder().decode(commercialBytes).trimEnd().split('\n'),commercialEnd=JSON.parse(commercialRecords.at(-1));assert.equal(Number(commercialExport.headers.get('Content-Length')),commercialBytes.length);assert.equal(commercialEnd.bytes,13500000);assert.equal(commercialEnd.files,3);assert.deepEqual(JSON.parse(commercialRecords[0]).state.orders,commercialSource.orders);assert.deepEqual(JSON.parse(commercialRecords[0]).state.deals,commercialSource.deals);
  assert.deepEqual(JSON.parse(commercialRecords[0]).state.customers,commercialSource.customers);assert.deepEqual(JSON.parse(commercialRecords[0]).state.tasks,commercialSource.tasks);
  // Clear only the temporary destination created above. Source customer data,
  // original files and the separate private draft remain untouched.
  const destinationObjects=(await db.prepare('SELECT object_key FROM crm_files WHERE space=?').bind('demo').all()).results.map(r=>r.object_key);for(const key of destinationObjects)await bucket.delete(key);
  for(const table of ['crm_files','crm_orders','crm_tasks','crm_meetings','crm_events','crm_deals','crm_customers','crm_articles','crm_notices','crm_leads','crm_company_events','crm_drafts','crm_mutations'])await db.prepare('DELETE FROM '+table+' WHERE space=?').bind('demo').run();
  await db.prepare('UPDATE crm_spaces SET version=0,write_token=?,settings=? WHERE id=?').bind('',JSON.stringify(core.emptyState().settings),'demo').run();
  const commercialRestoreResponse=await api('/api/crm/backup?space=demo&version=0&requestId='+crypto.randomUUID(),{method:'POST',headers:{...headers,'Content-Type':'application/x-ndjson',Origin:origin},body:commercialBytes}),commercialRestored=await commercialRestoreResponse.json();assert.equal(commercialRestoreResponse.status,200,JSON.stringify(commercialRestored));for(const o of commercialSource.orders){const restoredOrder=commercialRestored.orders.find(r=>r.id===o.id);assert.equal(restoredOrder.ownerProfileId,o.ownerProfileId);assert.deepEqual(restoredOrder.responsibilityTransfers,o.responsibilityTransfers);assert.equal(restoredOrder.production.assigneeId,o.production.assigneeId);assert.equal(restoredOrder.production.workId,o.production.workId);assert.deepEqual(restoredOrder.production.movements,o.production.movements);}for(const c of commercialSource.customers){const restoredCustomer=commercialRestored.customers.find(r=>r.id===c.id);assert.equal(restoredCustomer.ownerProfileId,c.ownerProfileId);assert.deepEqual(restoredCustomer.responsibilityTransfers,c.responsibilityTransfers);assert.deepEqual(restoredCustomer.onboarding,c.onboarding);assert.deepEqual(restoredCustomer.plan,c.plan);}assert.deepEqual(commercialRestored.meetings,commercialSource.meetings);assert.deepEqual(commercialRestored.tasks,commercialSource.tasks);assert.deepEqual(commercialRestored.deals,commercialSource.deals);assert.deepEqual(commercialRestored.settings.sellerProfiles,commercialSource.settings.sellerProfiles.map(p=>({...p,memberId:''})));assert.deepEqual(await get(),commercialSource);assert.deepEqual((await draftRead(headers)).data,savedPrivateDraft);assert.deepEqual(await readOnboardingDraft(headers),savedOnboardingDraft);assert.deepEqual(await readIssueDraft(headers),savedIssueDraft);const afterMeetingRestoreRaw=await raw();for(const table of ['outlook_connections','outlook_items','outlook_oauth_states'])assert.deepEqual(afterMeetingRestoreRaw.tables[table],meetingBeforeRaw.tables[table],table+' preserved by built backup restoration');
  const commercialFilesResponse=await api('/api/crm/files?space=demo&customerId='+customer.id,{headers}),commercialFiles=await commercialFilesResponse.json();assert.equal(commercialFilesResponse.status,200);assert.equal(commercialFiles.length,3);for(const source of sources){const file=commercialFiles.find(f=>f.name===source.metadata.name);assert.ok(file);assert.notEqual(file.id,source.metadata.id);const response=await api('/api/crm/files?space=demo&id='+file.id,{headers});assert.equal(response.status,200);assert.equal(createHash('sha256').update(new Uint8Array(await response.arrayBuffer())).digest('hex'),source.sha256);}const restoredProductionOrder=commercialRestored.orders.find(o=>o.id===order.id),restoredProof=commercialFiles.find(f=>f.kind==='proof'),restoredPhoto=commercialFiles.find(f=>f.purpose==='production');assert.equal(restoredProductionOrder.proofFileId,restoredProof.id);assert.equal(restoredProductionOrder.production.sketchFileId,restoredProof.id);assert.equal(restoredPhoto.orderId,order.id);assert.equal(restoredPhoto.workId,restoredProductionOrder.production.workId);
  // Recompute the full stream integrity chain after corrupting a valid audit.
  // These requests fail the domain audit relation, not a file hash or framing
  // check, and preserve the already restored destination and every R2 byte.
  const corruptedResponsibilityStream=mutate=>{const lines=[...commercialRecords],header=JSON.parse(lines[0]);mutate(header.state);lines[0]=JSON.stringify(header);const digest=text=>createHash('sha256').update(text).digest('hex');let hash=digest(lines[0]);for(const line of lines.slice(1,-1))hash=digest(hash+':'+digest(line));const final=JSON.parse(lines.at(-1));final.sha256=hash;lines[lines.length-1]=JSON.stringify(final);return new TextEncoder().encode(lines.join('\n')+'\n');};
  const responsibilityCorruptions=[
    ['missing onboarding parent selection',st=>{const parent=st.customers.find(c=>c.id===customer.id).onboarding.responsibilityTransfers[0];assert.ok(parent.selectedTaskIds.length);parent.selectedTaskIds=[];}],
    ['onboarding task actor differs from parent',st=>{const task=st.tasks.find(t=>t.id===onboardingTaskIds[0]),audit=task.responsibilityTransfers.find(row=>row.source==='onboarding');assert.ok(audit);audit.byId='synthetic-forged-onboarding-actor';}],
    ['missing issue parent selection',st=>{const parent=st.customers.find(c=>c.id===customer.id).plan.issueResponsibilityTransfers[0];assert.ok(parent.selectedTaskIds.length);parent.selectedTaskIds=[];}],
    ['issue task actor differs from parent',st=>{const task=st.tasks.find(t=>t.id===legacyIssueTask.id),audit=task.responsibilityTransfers.find(row=>row.source==='customer_issue');assert.ok(audit);audit.byId='synthetic-forged-issue-actor';}]
  ];
  for(const [label,mutate] of responsibilityCorruptions){
    const corruptionBefore=await raw(),response=await api('/api/crm/backup?space=demo&version='+commercialRestored.version+'&requestId='+crypto.randomUUID(),{method:'POST',headers:{...headers,'Content-Type':'application/x-ndjson',Origin:origin},body:corruptedResponsibilityStream(mutate)}),body=await response.json();
    assert.equal(response.status,400,label+': '+JSON.stringify(body));assert.match(body.error,/ansvar|historik|överlämning/i,label+' is rejected by responsibility validation');assert.deepEqual(await raw(),corruptionBefore,'Valid-integrity '+label+' leaves all 18 tables and R2 bytes unchanged.');
    assert.deepEqual(await get('demo'),commercialRestored);assert.deepEqual(await readOnboardingDraft(headers),savedOnboardingDraft);assert.deepEqual(await readIssueDraft(headers),savedIssueDraft);
  }
  const issueEvidence={issueLegacyReadAndInitPreserved:true,issueStableProfileAndAudit:true,issueSelectedTaskParentAudit:true,issueUnselectedTasksUnchanged:true,issueAnchorAndTransferDoubleClick:true,issueLostAckReplay:true,issueSameLabelIdentityConflict:true,issuePrivatePlanConflictPreserved:true,issueGenericBypassDenied:true,issueSellerRoleDenied:true,issueTargetAccountRevocationDenied:true,issueActualD1VersionRebase:true,issueFollowupActionAndDue:true,issueResolvedAndReopenedAuditPreserved:true,issueReplacementExactProfile:true,issueInitialAssignmentRequiresUUID:true,issueUnrelatedTablesAndPositivePrivacyUnchanged:true,issueStreamRestorePreserved:true,issueValidIntegrityCorruptAuditRejected:true};
  console.log(JSON.stringify({result:'PASS',runtime:'Cloudflare workerd + persisted local D1/R2 through built HTTP API',fileBytes:end.bytes,archiveBytes:bytes.length,files:end.files,proofLinks:true,photoLinks:true,hashesVerified:true,idempotentRetry:true,sourceUnchanged:true,anonymousDenied:true,homeRendered:true,privateWorkflowDraft:true,atomicWorkflowPublication:true,lateAutosaveDenied:true,commercialStableProfiles:true,commercialRequiredWork:true,commercialDoubleClick:true,commercialLostAckReplay:true,commercialProductionUnchanged:true,commercialAuditRestore:true,customerStableProfiles:true,customerDoubleClick:true,customerLostAckReplay:true,customerUnrelatedTablesUnchanged:true,customerAuditRestore:true,task_owner_profile_id_preserved:true,task_profile_audit_transfer_atomic:true,task_stream_restore_preserved:true,taskParentHistoryPreserved:true,taskStandaloneDoubleClick:true,taskStandaloneLostAckReplay:true,taskStandaloneRoleDenied:true,taskStandaloneStaleContext:true,taskStandaloneFreshReview:true,meetingLegacyReadAndInitPreserved:true,meetingStableProfileAndAudit:true,meetingAnchorDoubleClick:true,meetingLostAckReplay:true,meetingFrozenV44DraftConflict:true,meetingGenericBypassDenied:true,meetingSellerRoleDenied:true,meetingTargetAccountRevocationDenied:true,meetingStaleContextAndFreshReview:true,meetingExistingTasksUnchanged:true,meetingDoneExactFollowupProfile:true,meetingNewTaskAuditEmpty:true,meetingStreamRestorePreserved:true,meetingPositivePrivateAndSharedOutlookUnchanged:true,onboardingLegacyReadAndInitPreserved:true,onboardingStableProfileAndAudit:true,onboardingSelectedTaskParentAudit:true,onboardingUnselectedTasksUnchanged:true,onboardingAnchorAndTransferDoubleClick:true,onboardingLostAckReplay:true,onboardingSameLabelIdentityConflict:true,onboardingPrivateChecklistConflictPreserved:true,onboardingGenericBypassDenied:true,onboardingSellerRoleDenied:true,onboardingTargetAccountRevocationDenied:true,onboardingNewTaskExactProfile:true,onboardingUnrelatedTablesAndPositivePrivacyUnchanged:true,onboardingStreamRestorePreserved:true,onboardingValidIntegrityCorruptAuditRejected:true,customer_owner_profile_id_preserved:true,blank_legacy_customer_ids_preserved:true,...issueEvidence,rawTables:runtimeTables.length,hostedProductionRestoreVerified:false}));
} finally {await mf.dispose();rmSync(statePath,{recursive:true,force:true});}
