import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
export async function verifyV13(h){
 const {core,business,quantities,sqlite,objects,headers,get,post,rolePost,roleGet,roleHeaders,draftRead,catalogInput,productionData,fileApi}=h;
 for(const role of ['production','operator2'])sqlite.prepare('INSERT INTO crm_members(id,email,user_id,name,role,owner,active) VALUES(?,?,?,?,?,?,1)').run('ops-'+role,role+'@example.com','ops-'+role,role,'production','');
 let s=await get('live');
 async function create(title){let r=await post(s,'catalog_order',{...catalogInput,title,accepted:true},'live');assert.equal(r.status,200,JSON.stringify(r.data));s=r.data;let o=s.orders.find(o=>o.id===r.data.mutationResult.orderId);r=await post(s,'order',{...o,proofRequired:false,proofApproved:false,supplierConfirmed:true},'live');assert.equal(r.status,200);s=r.data;r=await post(s,'production_submit',{orderId:o.id,production:{...productionData.production,lines:s.deals.find(d=>d.id===o.dealId).lines.filter(l=>l.kind==='product')}},'live');assert.equal(r.status,200,JSON.stringify(r.data));s=r.data;return o.id;}
 const id=await create('V13 gemensamt jobb'),id2=await create('V13 andra jobbet');
 const order=(state,id)=>state.orders.find(o=>o.id===id),basis=state=>({orderId:id,expectedAssignment:quantities.assignmentBasis(order(state,id).production)});
 let a=await roleGet('production'),b=await roleGet('operator2');const originalBasis=basis(a);
 const claims=await Promise.all([rolePost('production',a,'production_claim',originalBasis),rolePost('operator2',b,'production_claim',originalBasis)]);assert.deepEqual(claims.map(r=>r.status).sort(),[200,409]);
 const winner=claims[0].status===200?'production':'operator2',loser=winner==='production'?'operator2':'production',success=claims.find(r=>r.status===200),failure=claims.find(r=>r.status===409);
 assert.equal(failure.data.code,'production_assignment_conflict');assert.equal(order(failure.data.state,id).invoiceValue,null);assert.equal(order(success.data,id).production.assigneeId,'ops-'+winner);assert.equal(order(success.data,id).production.assignmentRevision,1);
 let r=await rolePost(winner,a,'production_claim',originalBasis,success.id);assert.equal(r.status,200);assert.equal(order(r.data,id).production.assignmentRevision,1);
 r=await rolePost(loser,await roleGet(loser),'production_release',basis(await roleGet(loser)));assert.equal(r.status,400);
 r=await rolePost(winner,await roleGet(winner),'production_release',basis(await roleGet(winner)));assert.equal(r.status,200);
 r=await rolePost(loser,await roleGet(loser),'production_claim',originalBasis);assert.equal(r.status,409); // ABA, even though unassigned again.
 a=await roleGet('production');b=await roleGet('operator2');
 const db=globalThis.__crmEnv.DB,normalBatch=db.batch;let injected=false;
 db.batch=async statements=>{if(!injected&&statements[0].sql.startsWith('UPDATE crm_spaces')){injected=true;const other=await rolePost('operator2',b,'production_claim',{orderId:id2,expectedAssignment:quantities.assignmentBasis(order(b,id2).production)});assert.equal(other.status,200);}return normalBatch(statements)};
 r=await rolePost('production',a,'production_claim',basis(a));db.batch=normalBatch;assert.equal(r.status,200);assert.equal(order(r.data,id2).production.assigneeId,'ops-operator2');
 const full=await get('live');r=await post(full,'production_release',basis(full),'live');assert.equal(r.status,200);
 a=await roleGet('production');assert.ok(a.notices.some(n=>n.audience==='print'));assert.ok(a.notices.some(n=>n.audience==='warehouse'));assert.ok(!a.notices.some(n=>n.audience==='seller'));assert.equal(a.articles.length,0);assert.equal(a.tasks.length,0);assert.equal(a.events.some(e=>e.kind!=='production'),false);assert.ok(a.orders.every(o=>o.invoiceValue===null&&o.actualCost===null&&o.commercialValue===null&&o.notes===''&&o.production.lines.every(l=>l.unitPrice===0&&l.unitCost===null)));
 const notice=a.notices.find(n=>n.orderId===id);r=await rolePost('production',a,'notice_read',{id:notice.id});assert.equal(r.status,200);assert.ok(r.data.notices.find(n=>n.id===notice.id).readBy.includes('ops-production'));assert.ok(!(await roleGet('operator2')).notices.find(n=>n.id===notice.id).readBy.includes('ops-operator2'));
 assert.equal((await draftRead('',roleHeaders('production'))).status,403);
 const backupApi=await import('../work/backup-api.mjs'),members=await import('../work/members-api.mjs');for(const [api,url] of [[backupApi,'backup?space=live'],[members,'members']])assert.equal((await api.GET(new Request('https://crm.test/api/crm/'+url,{headers:roleHeaders('production')}))).status,403);
 console.log('PASS v13: same-job contention, real CAS retry on separate jobs, ABA/replay safety, self/admin release, redaction and private notices.');
 const o=order(await roleGet('production'),id),png=readFileSync('public/icons/icon-192.png');
 const photoForm=(extra={})=>{const form=new FormData();for(const [k,v] of Object.entries({space:'live',customerId:o.customerId,orderId:id,workId:o.production.workId,purpose:'production',kind:'document',version:'v13',...extra}))form.set(k,v);form.set('file',new File([png],'arbete.png',{type:'image/png'}));return form;};
 const upload=(form,who='production')=>fileApi.POST(new Request('https://crm.test/api/crm/files',{method:'POST',headers:roleHeaders(who),body:form}));
 assert.equal((await upload(photoForm({purpose:''}))).status,403);assert.equal((await upload(photoForm({workId:'old-work'}))).status,409);assert.equal((await upload(photoForm({customerId:s.customers.find(c=>c.id!==o.customerId).id}))).status,409);assert.equal((await upload(photoForm({kind:'proof'}))).status,403);
 const forged=photoForm();forged.set('file',new File(['<script>bad</script>'],'fake.png'));assert.equal((await upload(forged)).status,400);
 const beforeCount=objects.size;const saved=await upload(photoForm());assert.equal(saved.status,200);const photo=await saved.json();assert.equal(photo.workId,o.production.workId);assert.equal(objects.size,beforeCount+1);
 const fileGet=(query,who='production')=>fileApi.GET(new Request('https://crm.test/api/crm/files?space=live&'+query,{headers:roleHeaders(who)}));
 const legacy=sqlite.prepare('SELECT data FROM crm_orders WHERE space=? AND id=?').get('live',id2).data;const rawLegacy=JSON.parse(legacy);delete rawLegacy.productionHistory;delete rawLegacy.production;sqlite.prepare('UPDATE crm_orders SET data=? WHERE space=? AND id=?').run(JSON.stringify(rawLegacy),'live',id2);
 assert.equal((await fileGet('id='+photo.id)).status,200);
 sqlite.prepare('UPDATE crm_orders SET data=? WHERE space=? AND id=?').run(legacy,'live',id2);assert.equal((await fileGet('id='+o.production.sketchFileId)).status,200);
 const privateFile=sqlite.prepare('SELECT data FROM crm_files WHERE space=?').all('live').map(r=>JSON.parse(r.data)).find(f=>f.name==='max-size.pdf');assert.ok(privateFile);assert.equal((await fileGet('id='+privateFile.id)).status,403);
 const listed=await (await fileGet('customerId='+o.customerId+'&orderId='+id)).json();assert.ok(listed.some(f=>f.id===photo.id));assert.ok(!listed.some(f=>f.id===privateFile.id));
 // Lost database response must never delete a successfully stored photo.
 let lost=false;db.batch=async statements=>{const result=await normalBatch(statements);if(!lost&&statements.some(s=>s.sql.includes('INSERT INTO crm_files'))){lost=true;throw Error('lost response')}return result};const recovered=await upload(photoForm());db.batch=normalBatch;assert.equal(recovered.status,200);const recoveredPhoto=await recovered.json();assert.equal((await fileGet('id='+recoveredPhoto.id)).status,200);
 // Order changes while photo upload runs cannot silently attach to an obsolete version.
 const bucket=globalThis.__crmEnv.BUCKET,normalPut=bucket.put;let changed=false;bucket.put=async(...args)=>{const result=await normalPut(...args);if(!changed){changed=true;const row=sqlite.prepare('SELECT data FROM crm_orders WHERE space=? AND id=?').get('live',id),v=JSON.parse(row.data);v.production.instructions+=' changed during upload';sqlite.prepare('UPDATE crm_orders SET data=? WHERE space=? AND id=?').run(JSON.stringify(v),'live',id);}return result};const objectCount=objects.size;const obsolete=await upload(photoForm());bucket.put=normalPut;assert.equal(obsolete.status,409);assert.equal(objects.size,objectCount);
 const backup=await import('../work/crm-backup.mjs'),store=await import('../work/crm-store.mjs'),snapshot=await backup.exportBackup('live');assert.equal(snapshot.files.find(f=>f.metadata.id===photo.id).metadata.workId,o.production.workId);
 for(const key of [...objects.keys()])if(key.startsWith('demo/'))objects.delete(key);for(const table of ['crm_files','crm_orders','crm_tasks','crm_meetings','crm_events','crm_deals','crm_customers','crm_articles','crm_notices','crm_leads','crm_company_events','crm_drafts','crm_mutations'])sqlite.prepare('DELETE FROM '+table+' WHERE space=?').run('demo');await store.initialize('demo');sqlite.prepare('UPDATE crm_spaces SET version=1 WHERE id=?').run('demo');
 await backup.importBackup('demo',snapshot,crypto.randomUUID(),1,{id:'test-admin',name:'Test admin',role:'admin',owner:''});const copy=sqlite.prepare('SELECT data FROM crm_files WHERE space=?').all('demo').map(r=>JSON.parse(r.data)).find(f=>f.purpose==='production');assert.ok(copy);assert.equal(copy.orderId,id);assert.equal(copy.workId,o.production.workId);assert.notEqual(copy.id,photo.id);
 console.log('PASS v13: private-file isolation, scoped image validation, work-version race, committed-response loss and photo backup/restore.');
 for(const kind of ['received','printed','dispatched']){a=await roleGet('production');const current=order(a,id),rows=quantities.productionProgress(current.production);r=await rolePost('production',a,'production_'+kind,{orderId:id,expectedProduction:quantities.productionBasis(current.production),entries:rows.map(row=>({lineId:row.line.id,quantity:kind==='received'?row.toReceive:kind==='printed'?row.toPrint:row.toDispatch})),address:current.production.deliveryAddress});assert.equal(r.status,200,JSON.stringify(r.data));}
 a=await roleGet('production');assert.equal(order(a,id).production.status,'dispatched');assert.equal((await rolePost('production',a,'production_claim',basis(a))).status,400);assert.equal((await upload(photoForm())).status,409);
 const manifest=JSON.parse(readFileSync('public/manifest.webmanifest'));assert.equal(manifest.display,'standalone');for(const icon of manifest.icons)assert.ok(existsSync('public'+icon.src));assert.ok(existsSync('public/icons/apple-touch-icon.png'));
 console.log('PASS v13: combined operator completes receive/print/dispatch, completed-work guards and install manifest assets.');
}
