import {load,projectState} from '@/lib/crm-store';
import {z} from 'zod';
import {database} from '@/lib/crm-db';
import {member,AccessError,sameOrigin} from '@/lib/crm-auth';
import {DraftInput,type DraftRecord} from '@/lib/drafts';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const spaceOf=(v:unknown)=>z.enum(['demo','live']).parse(v);
type Row={id:string;kind:DraftRecord['kind'];context:string;revision:number;request_id:string;title:string;data:string;archived:number;updated_at:string};
const record=(r:Row):DraftRecord=>({id:r.id,kind:r.kind,context:r.context,revision:r.revision,requestId:r.request_id,title:r.title,data:JSON.parse(r.data),archived:!!r.archived,updatedAt:r.updated_at});
const fail=(e:unknown)=>e instanceof AccessError?reply({error:e.message},e.status):e instanceof z.ZodError?reply({error:e.issues.map(i=>i.message).join(' ')},400):reply({error:'Utkastet kunde inte sparas. Behåll sidan öppen och försök igen.'},503);
async function user(req:Request){const m=await member(req);if(!['admin','seller'].includes(m.role))throw new AccessError('Privata utkast används av säljteamet.');return m;}
export async function GET(req:Request){try{const m=await user(req),u=new URL(req.url),space=spaceOf(u.searchParams.get('space')),id=u.searchParams.get('id');const rows=await database().prepare('SELECT * FROM crm_drafts WHERE space=? AND user_id=?'+(id?' AND id=?':' AND archived=0')+' ORDER BY updated_at DESC').bind(space,m.user_id!,...(id?[id]:[])).all<Row>();return reply(rows.results.map(record));}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const m=await user(req);const raw=await req.text();if(raw.length>1500000)throw new AccessError('Utkastet är för stort.',413);const body=JSON.parse(raw),space=spaceOf(body.space),p=DraftInput.parse(body),db=database();if(['production','note','followup'].includes(p.kind)){const state=projectState(await load(space),space);const exists=p.kind==='production'?state.orders.some(o=>o.id===p.context):p.kind==='note'?state.customers.some(c=>c.id===p.context):state.tasks.some(t=>t.id===p.context);if(!exists)throw new AccessError('Utkastets kund, order eller aktivitet finns inte i arbetsytan.',400);}const previous=await db.prepare('SELECT * FROM crm_drafts WHERE space=? AND user_id=? AND id=?').bind(space,m.user_id!,p.id).first<Row>();if(previous?.request_id===p.requestId)return reply(record(previous));if(previous&&(previous.kind!==p.kind||previous.context!==p.context))throw new AccessError('Utkastets koppling får inte ändras.',400);if(previous?.archived||((previous?.revision||0)!==p.revision))return reply({error:'Utkastet har ändrats på en annan enhet. Ditt öppna underlag finns kvar.',current:previous?record(previous):null},409);
 if(!previous){const count=await db.prepare('SELECT COUNT(*) AS n FROM crm_drafts WHERE space=? AND user_id=? AND archived=0').bind(space,m.user_id!).first<{n:number}>();if((count?.n||0)>=100)throw new AccessError('Avsluta något av dina 100 öppna utkast först.',400);}
 const at=new Date().toISOString();const r=previous?await db.prepare('UPDATE crm_drafts SET revision=revision+1,request_id=?,title=?,data=?,archived=?,updated_at=? WHERE space=? AND user_id=? AND id=? AND revision=? AND archived=0').bind(p.requestId,p.title,JSON.stringify(p.data),p.archived?1:0,at,space,m.user_id!,p.id,p.revision).run():await db.prepare('INSERT OR IGNORE INTO crm_drafts(space,user_id,id,kind,context,revision,request_id,title,data,archived,updated_at) VALUES(?,?,?,?,?,1,?,?,?,?,?)').bind(space,m.user_id!,p.id,p.kind,p.context,p.requestId,p.title,JSON.stringify(p.data),p.archived?1:0,at).run();
 const latest=await db.prepare('SELECT * FROM crm_drafts WHERE space=? AND user_id=? AND id=?').bind(space,m.user_id!,p.id).first<Row>();if(r.meta.changes!==1||latest?.request_id!==p.requestId||latest.revision!==p.revision+1)return reply({error:'En annan ändring hann före. Ditt öppna underlag finns kvar.',current:latest?record(latest):null},409);return reply(record(latest!));}catch(e){return fail(e)}}
