'use client';
import { useEffect,useRef,useState } from 'react';
import { FileUp,Download,Plus,Trash2,RotateCcw } from 'lucide-react';
import { Input } from '@/components/ui/input';import { Textarea } from '@/components/ui/textarea';import { Button } from '@/components/ui/button';import { toast } from 'sonner';
import type { Customer,State } from '@/lib/crm';import type { CustomerFile } from '@/lib/crm-files';import type { Product } from '@/lib/business';
import { BusinessField as F,Pick,displayDate,type SaveAction } from './business-ui';
function useFiles(space:string,customerId:string){const [files,setFiles]=useState<CustomerFile[]>([]),[error,setError]=useState('');async function refresh(){try{const r=await fetch('/api/crm/files?'+new URLSearchParams({space,customerId}));const data:any=await r.json();if(!r.ok)throw Error(data.error);setFiles(data);setError('')}catch(e){setError((e as Error).message)}}useEffect(()=>{setFiles([]);void refresh()},[space,customerId]);return {files,error,refresh}}
export function ProofFields({space,customerId,data,onChange}:{space:string;customerId:string;data:Record<string,any>;onChange:(key:string,v:unknown)=>void}){const {files,error}=useFiles(space,customerId);return <div className="business-ui"><F label="Korrekturfil på kunden"><Pick label="Korrekturfil" value={data.proofFileId||''} items={[{id:'',label:'Välj uppladdad fil'},...files.filter(f=>f.kind==='proof').map(f=>({id:f.id,label:f.name+' · '+f.version}))]} onChange={id=>{onChange('proofFileId',id);onChange('proofVersion',files.find(f=>f.id===id)?.version||'');onChange('proofApproved',false);onChange('approvedBy','');onChange('approvedDate','')}}/></F>{error&&<p className="error">{error}</p>}<div className="biz-grid"><F label="Kunden godkände – namn"><Input value={data.approvedBy||''} onChange={e=>onChange('approvedBy',e.target.value)}/></F><F label="Godkännandedatum"><Input type="date" value={data.approvedDate||''} onChange={e=>onChange('approvedDate',e.target.value)}/></F></div><p className="biz-hint">Registrera kundens faktiska godkännande. En uppladdad fil är inte i sig godkänd. Filer laddas upp på kundkortet.</p></div>}
export function CustomerFiles({customer:c,st,space,save,busy,refresh}:{customer:Customer;st:State;space:string;save:SaveAction;busy:boolean;refresh:()=>Promise<void>}){
 const {files,error,refresh:refreshFiles}=useFiles(space,c.id),[uploading,setUploading]=useState(false),[file,setFile]=useState<File|null>(null),[version,setVersion]=useState('1'),[kind,setKind]=useState('proof'),[products,setProducts]=useState<Product[]|null>(null),ref=useRef<HTMLInputElement>(null);
 const writable=st.viewer?.role!=='reader';const approvals=st.orders.filter(o=>o.customerId===c.id&&o.proofApproved);const won=st.deals.filter(d=>d.customerId===c.id&&d.stage==='won');
 async function upload(){if(!file||uploading)return;setUploading(true);try{const data=new FormData();data.set('space',space);data.set('customerId',c.id);data.set('version',version);data.set('kind',kind);data.set('file',file);const r=await fetch('/api/crm/files',{method:'POST',body:data});const body:any=await r.json();if(!r.ok)throw Error(body.error);setFile(null);if(ref.current)ref.current.value='';await refreshFiles();await refresh();toast.success('Filen är sparad på kunden.')}catch(e){toast.error((e as Error).message)}finally{setUploading(false)}}
 return <section className="business-ui biz-section"><div className="biz-head"><div><span className="biz-kicker">KUNDUNDERLAG</span><h2>Filer, sortiment och återköp</h2></div><FileUp size={24}/></div><div className="biz-file-list">{files.map(f=>{const approved=approvals.filter(o=>o.proofFileId===f.id);return <article key={f.id}><a href={'/api/crm/files?'+new URLSearchParams({space,id:f.id})} className="biz-file-link"><Download size={17}/><b>{f.name}</b></a><small>{f.kind==='proof'?'Korrektur':f.kind==='logo'?'Logotyp':'Dokument'} · version {f.version} · {(f.size/1000).toFixed(0)} kB</small><small>{displayDate(f.at)} · {f.uploadedBy}</small>{approved.map(o=><span className="biz-approved" key={o.id}>Godkänd för {st.deals.find(d=>d.id===o.dealId)?.title} · {o.approvedBy||'Tidigare registrering'} · {displayDate(o.approvedDate)}</span>)}</article>})}</div>{!files.length&&<p className="biz-hint">Inga filer sparade ännu.</p>}{error&&<p role="alert" className="error">{error}</p>}{writable&&<details className="biz-details"><summary><Plus size={17}/>Ladda upp kundunderlag</summary><F label="Fil, högst 5 MB"><Input ref={ref} type="file" accept=".pdf,.png,.jpg,.jpeg,.svg,.eps,.ai,.webp,.xlsx,.docx" disabled={uploading} onChange={e=>setFile(e.target.files?.[0]||null)}/></F><div className="biz-grid"><F label="Typ"><Pick label="Filtyp" value={kind} onChange={setKind} items={[{id:'proof',label:'Korrektur'},{id:'logo',label:'Logotyp'},{id:'document',label:'Dokument'}]}/></F><F label="Version *"><Input value={version} onChange={e=>setVersion(e.target.value)}/></F></div><p className="biz-hint">Varje uppladdning sparas separat. Äldre versioner finns kvar.</p><Button disabled={!file||!version.trim()||uploading||busy} onClick={upload}>{uploading?'Laddar upp…':'Spara fil på kunden'}</Button></details>}
 <h3>Återkommande sortiment</h3><p className="biz-hint">Artikel, variant och märkning att återanvända i nästa dialog.</p>{(products||c.products).map((p,i)=>products?<fieldset className="biz-group" key={p.id||i}><legend>Produkt {i+1}</legend>{(['description','article','color','size','variant','marking','notes'] as const).map((k,n)=><F key={k} label={['Produkt *','Artikelnummer / leverantör','Färg','Storlek','Övrig variant','Märkning och placering','Övriga instruktioner'][n]}><Input value={p[k]} onChange={e=>setProducts(products.map((v,j)=>j===i?{...v,[k]:e.target.value}:v))}/></F>)}<Button variant="ghost" onClick={()=>setProducts(products.filter((_,j)=>j!==i))}><Trash2 size={15}/>Ta bort från sortimentet</Button></fieldset>:<article className="biz-product" key={p.id}><b>{p.description}</b><span>{[p.article,p.color,p.size,p.variant].filter(Boolean).join(' · ')}</span><p>{p.marking}</p>{p.notes&&<small>{p.notes}</small>}</article>)}{!products&&!c.products.length&&<p className="biz-hint">Dokumentera det sortiment kunden brukar beställa.</p>}{writable&&<div className="biz-buttons">{products?<><Button variant="outline" onClick={()=>setProducts([...products,{id:crypto.randomUUID(),description:'',article:'',variant:'',variantId:'',color:'',size:'',unit:'st',marking:'',notes:''}])}><Plus size={15}/>Produkt</Button><Button disabled={busy} onClick={async()=>{if(await save('products',{customerId:c.id,products},false))setProducts(null)}}>Spara sortiment</Button><Button variant="ghost" onClick={()=>setProducts(null)}>Avbryt</Button></>:<Button variant="outline" onClick={()=>setProducts(structuredClone(c.products))}>Redigera sortiment</Button>}</div>}
 <h3>Beställ igen</h3>{won.length?won.map(d=><div className="biz-repeat" key={d.id}><div><b>{d.title}</b><small>Order bekräftad {displayDate(d.wonAt)}</small></div>{writable&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>save('repeat_order',{dealId:d.id},false)}><RotateCcw size={15}/>Skapa återköp</Button>}</div>):<p className="biz-hint">När första affären är vunnen kan underlaget användas för ett nytt återköp.</p>}<p className="biz-hint">Återköpet hamnar bland Affärer. Bekräfta antal, aktuella priser och leveranstid innan offert.</p>
 </section>
}
