'use client';
import { Plus,Trash2,MapPin,Users } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { BusinessField as F } from './business-ui';
import { AddressSchema,SiteSchema } from '@/lib/business';
import type { Customer } from '@/lib/crm';
export function CustomerProfileFields({customer:c,update}:{customer:Customer;update:(key:string,value:unknown)=>void}){
 function address(key:'billingAddress'|'deliveryAddress',title:string){return <fieldset className="biz-group"><legend>{title}</legend><div className="biz-grid">{(['street','postalCode','city','country','reference'] as const).map((k,i)=><F key={k} label={['Gatuadress','Postnummer','Ort','Land','Referens / avdelning'][i]}><Input value={c[key]?.[k]||''} onChange={e=>update(key,{...AddressSchema.parse(c[key]||{}),[k]:e.target.value})}/></F>)}</div></fieldset>}
 return <div className="business-ui"><div className="biz-grid"><F label="Organisationsnummer"><Input value={c.organizationNumber||''} onChange={e=>update('organizationNumber',e.target.value)}/></F><F label="Kundnummer i Fortnox"><Input value={c.fortnoxNumber} onChange={e=>update('fortnoxNumber',e.target.value)}/></F><F label="Webbplats"><Input value={c.website||''} onChange={e=>update('website',e.target.value)}/></F><F label="Faktura-e-post"><Input type="email" value={c.billingEmail||''} onChange={e=>update('billingEmail',e.target.value)}/></F></div><details className="biz-details"><summary><MapPin size={17}/>Adresser och arbetsplatser</summary>{address('billingAddress','Fakturaadress')}<Button type="button" size="sm" variant="outline" onClick={()=>update('deliveryAddress',{...c.billingAddress})}>Kopiera fakturaadress till leveransadress</Button>{address('deliveryAddress','Leveransadress')}{c.sites.map((site,i)=><fieldset className="biz-group" key={site.id||i}><legend>Arbetsplats {i+1}</legend><F label="Namn"><Input value={site.name} onChange={e=>update('sites',c.sites.map((s,n)=>n===i?{...s,name:e.target.value}:s))}/></F><F label="Kontakt / beställare"><Input value={site.contact} onChange={e=>update('sites',c.sites.map((s,n)=>n===i?{...s,contact:e.target.value}:s))}/></F><div className="biz-grid">{(['street','postalCode','city','country','reference'] as const).map((k,n)=><F key={k} label={['Gatuadress','Postnummer','Ort','Land','Referens'][n]}><Input value={site.address[k]} onChange={e=>update('sites',c.sites.map((s,j)=>j===i?{...s,address:{...s.address,[k]:e.target.value}}:s))}/></F>)}</div><Button type="button" variant="ghost" onClick={()=>update('sites',c.sites.filter((_,n)=>n!==i))}><Trash2 size={16}/>Ta bort arbetsplats</Button></fieldset>)}<Button type="button" variant="outline" onClick={()=>update('sites',[...c.sites,SiteSchema.parse({id:crypto.randomUUID(),name:'Ny arbetsplats'})])}><Plus size={16}/>Arbetsplats</Button></details><details className="biz-details"><summary><Users size={17}/>Fler kontaktpersoner och roller ({c.plan.contacts.length})</summary>{c.plan.contacts.map((contact,i)=><fieldset key={i} className="biz-group"><legend>Kontakt {i+1}</legend><div className="biz-grid">{(['name','role','email','phone'] as const).map((k,n)=><F key={k} label={['Namn *','Roll, t.ex. beställare eller godkännare *','E-post','Telefon'][n]}><Input type={k==='email'?'email':'text'} value={contact[k]} onChange={e=>update('plan',{...c.plan,contacts:c.plan.contacts.map((p,j)=>j===i?{...p,[k]:e.target.value}:p)})}/></F>)}</div><Button type="button" variant="ghost" onClick={()=>update('plan',{...c.plan,contacts:c.plan.contacts.filter((_,n)=>n!==i)})}><Trash2 size={16}/>Ta bort kontakt</Button></fieldset>)}<Button type="button" variant="outline" onClick={()=>update('plan',{...c.plan,contacts:[...c.plan.contacts,{name:'',role:'',email:'',phone:''}]})}><Plus size={16}/>Kontaktperson</Button></details></div>
}
export function CustomerProfileSummary({customer:c}:{customer:Customer}){return <details className="biz-details business-ui"><summary>Företagsuppgifter och kontaktvägar</summary><dl className="biz-facts"><dt>Organisationsnummer</dt><dd>{c.organizationNumber||'Ej angivet'}</dd><dt>Kundnummer Fortnox</dt><dd>{c.fortnoxNumber||'Ej angivet'}</dd><dt>Bransch</dt><dd>{c.segment||'Ej angivet'}</dd><dt>Webbplats</dt><dd>{c.website||'Ej angivet'}</dd><dt>Faktura</dt><dd>{[c.billingAddress.street,c.billingAddress.postalCode,c.billingAddress.city,c.billingEmail,c.billingAddress.reference].filter(Boolean).join(', ')||'Ej angivet'}</dd><dt>Leverans</dt><dd>{[c.deliveryAddress.street,c.deliveryAddress.postalCode,c.deliveryAddress.city,c.deliveryAddress.reference].filter(Boolean).join(', ')||'Ej angivet'}</dd></dl>{c.sites.map((s,i)=><p key={s.id||i}><b>{s.name}</b> · {[s.address.street,s.address.postalCode,s.address.city,s.contact].filter(Boolean).join(', ')}</p>)}{c.plan.contacts.map((p,i)=><div className="biz-contact" key={i}><b>{p.name}</b><span>{p.role}</span><span>{p.email} {p.phone}</span></div>)}</details>}
