'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import type {DraftRecord} from '@/lib/drafts';
type LocalDraft=DraftRecord&{status:'saved'|'pending'|'saving'|'error'|'conflict';error?:string;server?:DraftRecord|null;generation:number};
type Workspace={ready:boolean;error:string;records:LocalDraft[];create:(kind:DraftRecord['kind'],context:string,data:Record<string,any>,title:string,id?:string)=>string;update:(id:string,data:Record<string,any>,title?:string)=>void;flush:(id:string)=>Promise<{id:string;revision:number}|null>;consume:(id:string)=>void;resolve:(id:string,useServer:boolean)=>void;archive:(id:string)=>Promise<boolean>;retry:()=>void};
const Context=createContext<Workspace|null>(null);
export const useDrafts=()=>{const ctx=useContext(Context);if(!ctx)throw Error('Draft workspace missing');return ctx;};
export function DraftProvider({space,userId,enabled,children}:{space:string;userId:string;enabled:boolean;children:ReactNode}){
 const [records,setRecords]=useState<LocalDraft[]>([]),[ready,setReady]=useState(!enabled),[error,setError]=useState('');const entries=useRef<LocalDraft[]>([]),jobs=useRef(new Map<string,Promise<any>>()),requests=useRef(new Map<string,{body:any;generation:number}>());const storageKey='magnussons-unsaved-v1:'+space+':'+userId;
 function put(next:LocalDraft[]){entries.current=next;setRecords(next);try{localStorage.setItem(storageKey,JSON.stringify(next.filter(d=>!d.archived&&d.status!=='saved')))}catch{setError('Webbläsaren kunde inte spara en lokal reservkopia. Vänta på ”Sparat” innan du lämnar sidan.')}}
 const patch=(id:string,change:(d:LocalDraft)=>LocalDraft)=>put(entries.current.map(d=>d.id===id?change(d):d));
 async function load(){if(!enabled){setReady(true);return;}try{const response=await fetch('/api/crm/drafts?space='+space),rows=await response.json() as any;if(!response.ok)throw Error(rows.error);let pending:LocalDraft[]=[];try{pending=JSON.parse(localStorage.getItem(storageKey)||'[]').filter((d:any)=>d&&typeof d.id==='string'&&d.data&&['catalog','production','note','followup','form'].includes(d.kind))}catch{}const merged:LocalDraft[]=rows.map((d:DraftRecord)=>({...d,generation:0,status:'saved'}));for(const local of pending){const saved=merged.find(d=>d.id===local.id);if(saved&&JSON.stringify(saved.data)===JSON.stringify(local.data))continue;const recovered={...local,status:(!saved||saved.revision===local.revision?'pending':'conflict') as LocalDraft['status'],server:saved||null,generation:local.generation||0,error:saved&&saved.revision!==local.revision?'En annan version har sparats. Välj vilket underlag du vill fortsätta med.':''};if(saved)merged.splice(merged.indexOf(saved),1,recovered);else merged.push(recovered);}setError('');put(merged);setReady(true)}catch(e){setError((e as Error).message);setReady(false)}}
 useEffect(()=>{void load()},[space,userId,enabled]);
 async function flush(id:string):Promise<{id:string;revision:number}|null>{if(jobs.current.has(id)){await jobs.current.get(id);const d=entries.current.find(d=>d.id===id);return d?.status==='saved'?{id,revision:d.revision}:d?.status==='pending'?flush(id):null;}const work=(async()=>{for(let attempt=0;attempt<5;attempt++){const current=entries.current.find(d=>d.id===id);if(!current||current.archived||current.status==='conflict')return null;if(current.status==='saved')return {id,revision:current.revision};let request=requests.current.get(id);if(!request){request={generation:current.generation,body:{space,id,kind:current.kind,context:current.context,revision:current.revision,requestId:crypto.randomUUID(),title:current.title,data:current.data,archived:false}};requests.current.set(id,request);}patch(id,d=>({...d,status:'saving',error:''}));try{const response=await fetch('/api/crm/drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request.body)}),result=await response.json() as any;if(response.status===409){requests.current.delete(id);patch(id,d=>({...d,status:'conflict',server:result.current,error:result.error}));return null;}if(!response.ok)throw Error(result.error);if(result.archived){requests.current.delete(id);patch(id,d=>({...d,status:'conflict',server:result,error:'Utkastet är redan avslutat på en annan enhet.'}));return null;}requests.current.delete(id);patch(id,d=>({...d,revision:result.revision,requestId:result.requestId,updatedAt:result.updatedAt,status:d.generation===request!.generation?'saved':'pending',error:''}));}catch(e){patch(id,d=>({...d,status:'error',error:(e as Error).message}));return null;}}return null;})();jobs.current.set(id,work);try{return await work}finally{jobs.current.delete(id)}}
 useEffect(()=>{if(!ready||!enabled)return;const timer=setInterval(()=>{for(const d of entries.current)if(!d.archived&&d.status==='pending')void flush(d.id)},700);const guard=(e:BeforeUnloadEvent)=>{if(entries.current.some(d=>!d.archived&&d.status!=='saved')){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',guard);return()=>{clearInterval(timer);window.removeEventListener('beforeunload',guard)}},[ready,enabled]);
 function create(kind:DraftRecord['kind'],context:string,data:Record<string,any>,title:string,id=crypto.randomUUID()){if(!ready||!enabled)return '';const existing=entries.current.find(d=>d.id===id);if(existing)return existing.archived?'':id;put([...entries.current,{id,kind,context,data,title,revision:0,requestId:'',archived:false,updatedAt:new Date().toISOString(),status:'pending',generation:1}]);return id;}
 function update(id:string,data:Record<string,any>,title?:string){patch(id,d=>({...d,data,title:title||d.title,generation:d.generation+1,status:d.status==='conflict'?'conflict':'pending',updatedAt:new Date().toISOString()}));}
 const consume=(id:string)=>{requests.current.delete(id);put(entries.current.filter(d=>d.id!==id));};
 function resolve(id:string,useServer:boolean){requests.current.delete(id);patch(id,d=>useServer?d.server?{...d.server,generation:d.generation+1,status:'saved'}:{...d,archived:true,status:'saved'}:({...d,revision:d.server?.revision||0,status:d.server?.archived?'conflict':'pending',error:d.server?.archived?'Utkastet är redan avslutat på en annan enhet. Öppna den skapade ordern.':'',generation:d.generation+1}));}
 async function archive(id:string){const saved=await flush(id);if(!saved)return false;const d=entries.current.find(d=>d.id===id)!;try{const r=await fetch('/api/crm/drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,...saved,space,requestId:crypto.randomUUID(),archived:true})}),data=await r.json() as any;if(r.status===409){patch(id,d=>({...d,status:'conflict',server:data.current,error:data.error}));return false;}if(!r.ok)throw Error(data.error);consume(id);return true}catch(e){patch(id,d=>({...d,status:'error',error:(e as Error).message}));return false}}
 return <Context.Provider value={{ready,error,records:records.filter(d=>!d.archived),create,update,flush,consume,resolve,archive,retry:()=>{if(!ready)void load();else for(const d of entries.current)if(d.status==='error')void flush(d.id)}}}>{children}</Context.Provider>
}
export function DraftStatus({id,onClosed,onResolved,disabled=false}:{id:string;onClosed?:()=>void;onResolved?:(data:Record<string,any>)=>void;disabled?:boolean}){const w=useDrafts(),d=w.records.find(d=>d.id===id);if(!w.ready)return <div className="draft-status">{w.error||'Hämtar dina utkast…'}{w.error&&<Button type="button" variant="outline" size="sm" disabled={disabled} onClick={w.retry}>Försök igen</Button>}</div>;if(!d)return null;return <div className={'draft-status '+d.status}><span>{d.status==='saved'?'Sparat som privat utkast':d.status==='pending'?'Ändringar väntar på sparning':d.status==='saving'?'Sparar utkast…':d.error||'Kontrollera utkastet'}{d.status==='saved'&&d.updatedAt?' · '+new Date(d.updatedAt).toLocaleTimeString('sv-SE',{timeZone:'Europe/Stockholm',hour:'2-digit',minute:'2-digit'}):''}</span>{d.status==='error'&&<Button type="button" size="sm" variant="outline" disabled={disabled} onClick={()=>w.flush(id)}>Försök spara igen</Button>}{d.status==='conflict'&&<div className="biz-buttons"><Button type="button" size="sm" variant="outline" disabled={disabled} onClick={()=>{w.resolve(id,true);if(!d.server||d.server.archived)onClosed?.();else if(d.server)onResolved?.(d.server.data)}}>{d.server?.archived?'Stäng avslutat utkast':'Använd sparad version'}</Button>{!d.server?.archived&&<Button type="button" size="sm" disabled={disabled} onClick={()=>w.resolve(id,false)}>Ersätt med mitt öppna underlag</Button>}</div>}</div>}
