'use client';
import {useEffect,useState,useRef} from 'react';
import {Phone,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {Checkbox} from '@/components/ui/checkbox';
import {BusinessField as F,Pick,type SaveAction} from './business-ui';
import {day,plusDays,type State,type Deal} from '@/lib/crm';
import {followupBasis,protectedFollowUp} from '@/lib/follow-up';
import {DraftStatus,useDrafts} from './draft-workspace';
export function FollowUpDialog({st,taskId,save,busy,onClose,onDeal,onWorkflow}:{st:State;taskId:string;save:SaveAction;busy:boolean;onClose:()=>void;onDeal:(d:Deal)=>void;onWorkflow:()=>void}){
 const task=st.tasks.find(t=>t.id===taskId)!,customer=st.customers.find(c=>c.id===task.customerId),deal=st.deals.find(d=>d.id===task.dealId),w=useDrafts(),current=w.records.find(d=>d.kind==='followup'&&d.context===taskId),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false),lock=useRef(false),readonly=st.viewer?.role==='reader';
 busy=busy||submitting;
 const protectedWork=protectedFollowUp(task),canonical=['quote','discovery','csm','prospecting'].includes(task.kind);
 useEffect(()=>{if(w.ready&&!current&&!task.done&&!readonly)w.create('followup',taskId,{taskId,expectedContext:followupBasis(st,taskId),outcome:'contact',occurredOn:day(),note:'',completed:false,nextAction:task.title,nextDate:plusDays(day(),1)},'Uppföljning · '+(customer?.name||task.title));},[w.ready,current?.id,taskId,task.done]);
 async function leave(next=onClose){if(lock.current)return;if(!current||readonly){next();return}lock.current=true;setSubmitting(true);try{const blank=!current.data.note?.trim();if(blank?await w.archive(current.id):await w.flush(current.id))next();}finally{lock.current=false;setSubmitting(false)}}
 if(!current)return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent><DialogHeader><DialogTitle>Följ upp aktiviteten</DialogTitle><DialogDescription>{task.title}</DialogDescription></DialogHeader>{readonly?<p>Ditt konto har läsbehörighet.</p>:task.done?<p>Aktiviteten är redan avslutad.</p>:<DraftStatus id=""/>}</DialogContent></Dialog>;
 const v=current.data,changed=v.expectedContext!==followupBasis(st,taskId),required=canonical||protectedWork||v.outcome==='no_reply'||!v.completed;
 const update=(key:string,value:unknown)=>w.update(current.id,{...v,[key]:value});
 async function submit(){if(lock.current||readonly)return;lock.current=true;setSubmitting(true);try{setError('');const ref=await w.flush(current!.id);if(!ref)return;if(await save('follow_up',{...v,completed:protectedWork?false:v.completed,nextDate:v.nextAction.trim()?v.nextDate:'',draft:ref},false)){w.consume(current!.id);onClose();}else setError('Det gick inte att spara uppföljningen. Ditt utkast finns kvar.');}finally{lock.current=false;setSubmitting(false)}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)void leave()}}><DialogContent className="follow-dialog business-ui"><DialogHeader><DialogTitle><Phone size={20}/>Följ upp {task.kind==='quote'?'offerten':'kundkontakten'}</DialogTitle><DialogDescription>{customer?.name} · {task.owner}</DialogDescription></DialogHeader><div className="follow-context"><b>{task.title}</b>{deal&&<span>{deal.title}</span>}</div><DraftStatus id={current.id} disabled={busy} onClosed={onClose}/><form onSubmit={e=>{e.preventDefault();void submit()}}><fieldset disabled={busy||current.status==='conflict'}><div className="biz-grid"><F label="Vad hände?"><Pick label="Resultat av uppföljning" value={v.outcome} onChange={value=>update('outcome',value)} items={[{id:'contact',label:'Vi hade kontakt'},{id:'no_reply',label:'Jag fick inget svar'},{id:'internal',label:'Jag arbetade med uppgiften'}]}/></F><F label="Datum"><Input type="date" required max={day()} value={v.occurredOn} onChange={e=>update('occurredOn',e.target.value)}/></F></div><F label={v.outcome==='contact'?'Vad kom ni överens om?':'Kort anteckning'}><Textarea autoFocus required rows={4} maxLength={49000} value={v.note} onChange={e=>update('note',e.target.value)} placeholder="Kundens besked, frågor och vad du lovade…"/></F>
 {!protectedWork&&<><label className="check-field"><Checkbox checked={v.completed} onCheckedChange={value=>update('completed',value===true)}/>Den tidigare aktiviteten är utförd</label><p className="biz-hint">{v.completed?'Den avslutas när du sparar.':'Den ligger kvar och får nästa datum och aktivitet nedan.'}</p></>}
 {protectedWork&&<p className="biz-callout">Kontakten sparas här. Kontrollpunkter, kundärenden och inköpsbehov avslutas i sitt arbetsflöde.</p>}
 <F label={'Nästa aktivitet'+(required?' *':' (valfritt)')}><Input required={required} maxLength={240} value={v.nextAction} onChange={e=>update('nextAction',e.target.value)} placeholder="Till exempel: Skicka uppdaterat prisförslag"/></F>{(required||v.nextAction.trim())&&<F label="När ska du göra det?"><Input required type="date" min={day()} value={v.nextDate} onChange={e=>update('nextDate',e.target.value)}/></F>}{v.outcome==='no_reply'&&<p className="biz-hint">Kontaktförsöket sparas. Senaste kundkontakt ändras först när ni har haft kontakt.</p>}</fieldset>
 {changed&&<div className="record-conflict" role="alert"><b>Aktiviteten har ändrats</b><p>Läs in det senaste nästa steget. Din anteckning och ditt kontaktbesked behålls.</p><Button type="button" disabled={busy||task.done} variant="outline" onClick={()=>w.update(current.id,{...v,expectedContext:followupBasis(st,taskId),nextAction:task.title,nextDate:task.due<day()?day():task.due,completed:false})}>Läs in aktuellt nästa steg</Button>{task.done&&<p>Aktiviteten är redan avslutad. Din text finns kvar som privat utkast.</p>}</div>}{error&&<p className="error" role="alert">{error}</p>}<div className="follow-footer"><Button type="button" variant="outline" disabled={busy} onClick={()=>void leave()}>Spara utkast & stäng</Button><Button type="submit" disabled={busy||changed||task.done||current.status==='conflict'||!v.note.trim()||st.viewer?.role==='reader'}><Check size={16}/>{busy?'Sparar…':'Spara uppföljning & nästa steg'}</Button></div></form>
 {(protectedWork||task.kind==='prospecting'||task.kind==='csm')&&<Button type="button" variant="ghost" disabled={busy} onClick={()=>void leave(onWorkflow)}>Hantera {task.kind==='onboarding'?'nya kundens checklista':task.kind.startsWith('year:')?'inköpsbehovet':task.kind==='prospecting'?'bearbetningen':'kundplanen'}</Button>}
 {deal&&!['won','lost'].includes(deal.stage)&&<Button type="button" variant="ghost" disabled={busy} onClick={()=>void leave(()=>onDeal(deal))}>Öppna offerten</Button>}
 </DialogContent></Dialog>;
}
