'use client';
import {useEffect,useState} from 'react';
import {Smartphone,Share,Download} from 'lucide-react';
import {Button} from './ui/button';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './ui/sheet';
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export function MobileApp(){
 const [open,setOpen]=useState(false),[prompt,setPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(false),[online,setOnline]=useState(true);
 useEffect(()=>{const mode=window.matchMedia('(display-mode: standalone)');const check=()=>setInstalled(mode.matches||!!(navigator as Navigator&{standalone?:boolean}).standalone);check();const ready=(e:Event)=>{e.preventDefault();setPrompt(e as InstallPrompt)},done=()=>{setInstalled(true);setPrompt(null)},connection=()=>setOnline(navigator.onLine);connection();window.addEventListener('beforeinstallprompt',ready);window.addEventListener('appinstalled',done);window.addEventListener('online',connection);window.addEventListener('offline',connection);mode.addEventListener('change',check);return()=>{window.removeEventListener('beforeinstallprompt',ready);window.removeEventListener('appinstalled',done);window.removeEventListener('online',connection);window.removeEventListener('offline',connection);mode.removeEventListener('change',check)}},[]);
 return <><Button className="mobile-app-trigger" variant="ghost" size="sm" aria-label="Använd CRM i mobilen" onClick={()=>setOpen(true)}><Smartphone size={18}/><span>I mobilen</span></Button>{!online&&<div className="connection-banner" role="alert">Ingen internetanslutning. Anslut igen innan du sparar.</div>}<Sheet open={open} onOpenChange={setOpen}><SheetContent className="crm-sheet"><SheetHeader><SheetTitle>Magnussons i mobilen</SheetTitle><SheetDescription>Öppna ditt arbete direkt från hemskärmen.</SheetDescription></SheetHeader><div className="sheet-body business-ui install-guide">{installed?<p><b>Du använder redan appvyn.</b></p>:<>{prompt&&<Button onClick={async()=>{await prompt.prompt();await prompt.userChoice;setPrompt(null)}}><Download size={18}/>Lägg till på hemskärmen</Button>}<section><h3>iPhone</h3><ol><li>Öppna CRM-adressen i Safari.</li><li>Tryck på <Share size={15}/> Dela och ”Lägg till på hemskärmen”.</li><li>Välj ”Öppna som webbapp” om alternativet visas och tryck på Lägg till.</li></ol></section><section><h3>Android</h3><ol><li>Öppna CRM-adressen i Chrome.</li><li>Öppna menyn ⋮ och välj ”Lägg till på startskärmen” eller ”Installera app”.</li></ol></section></>}<p>Samma personliga konto och arbetsyta som på datorn. Internet krävs för att läsa in och spara ändringar.</p><p>Ordernotiser visas inne i CRM. Telefonens pushnotiser är inte aktiverade.</p></div></SheetContent></Sheet></>;
}
