'use client';
import {useState} from 'react';
import {workSignals} from '@/lib/automation-signals';
import type {DraftRecord} from '@/lib/drafts';
import {canFollowUp} from '@/lib/follow-up';
import {personalOwner,salesMetrics} from '@/lib/sales-dashboard';
import {ArrowRight,Search,Plus,FilePenLine,Phone,AlertTriangle} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Progress} from '@/components/ui/progress';
import {day,plusDays,concerns,type State,type Order,type Task,type Meeting} from '@/lib/crm';
import {useDrafts,DraftStatus} from './draft-workspace';import {ReceiptQueue} from './receipt-queue';import {money,displayDate} from './business-ui';
export function MyDay({st,owner,onOwnerChange,onCustomer,onTask,onCreate,onOrder,onMeeting,onReceipt,onView,onDraft}:{st:State;owner:string;onOwnerChange:(owner:string)=>void;onCustomer:(id:string)=>void;onTask:(t:Task)=>void;onCreate:(type:string)=>void;onOrder:(o:Order)=>void;onMeeting:(m:Meeting)=>void;onReceipt:(id:string)=>void;onView:(view:string)=>void;onDraft:(draft:DraftRecord)=>void}){
 const [showAllDrafts,setShowAllDrafts]=useState(false),[discardDraft,setDiscardDraft]=useState(''),drafts=useDrafts(),personal=personalOwner(st),canTeam=st.viewer?.role==='admin',team=owner==='all',today=day(),readonly=st.viewer?.role==='reader';
 const match=(v:{owner:string})=>team||v.owner===owner,stats=salesMetrics(st,today.slice(0,7),owner),tasks=st.tasks.filter(t=>match(t)&&!t.done&&t.kind!=='receipt').sort((a,b)=>a.due.localeCompare(b.due)),now=tasks.filter(t=>t.due<=today),later=tasks.filter(t=>t.due>today&&t.due<=plusDays(today,7)),meetings=st.meetings.filter(m=>match(m)&&m.status==='planned'&&m.date>=today&&m.date<=plusDays(today,7)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)),issues=st.orders.filter(o=>match(o)&&['submitted','printed'].includes(o.production.status)&&o.production.issue),customers=st.customers.filter(c=>match(c)&&concerns(c,day(),st).length);
 const signals=workSignals(st).filter(s=>team||s.owner===owner);
 function taskRows(list:Task[]){return list.map(t=><div className="daily-row" key={t.id} data-late={t.due<today}><div><b>{t.title}</b><button className="daily-customer" onClick={()=>onCustomer(t.customerId)}>{st.customers.find(c=>c.id===t.customerId)?.name}</button><small>{t.due<today?'Försenad · ':t.due===today?'Idag · ':''}{displayDate(t.due)}{team?' · '+t.owner:''}</small></div><Button variant="outline" onClick={()=>onTask(t)}>{t.kind==='quote'?'Följ upp offerten':t.kind==='invoice_ready'?'Registrera faktura':['handover','proof_deadline','order_deadline'].includes(t.kind)?'Färdigställ underlag':canFollowUp(t)?'Följ upp':'Hantera aktivitet'}</Button></div>)}
 return <div className="business-ui my-day"><div className="day-scope"><span>{new Date(today+'T12:00:00').toLocaleDateString('sv-SE',{weekday:'long',day:'numeric',month:'long'})}</span><div className="biz-buttons">{personal&&<Button variant={!team?'default':'outline'} onClick={()=>onOwnerChange(personal)}>Mina uppgifter</Button>}{canTeam&&<Button variant={team?'default':'outline'} onClick={()=>onOwnerChange('all')}>Teamets uppgifter</Button>}</div></div>
 <div className="day-actions"><Button variant="outline" onClick={()=>onCreate('search')}><Search/><span>Sök kund<small>Kontaktuppgifter & historik</small></span><ArrowRight/></Button>{!readonly&&<><Button onClick={()=>onCreate('deal')}><Plus/><span>Ny offert/order<small>Välj kund och börja här</small></span><ArrowRight/></Button><Button variant="outline" onClick={()=>onCreate('notes')}><FilePenLine/><span>Skriv anteckning<small>Från samtalet eller mötet</small></span><ArrowRight/></Button></>}</div>
 {!personal&&!team&&<div className="biz-callout"><b>Välj vem kontot tillhör</b><p>Ditt konto saknar en egen säljarprofil. Därför visas inga personliga uppgifter än.</p>{canTeam?<Button variant="outline" onClick={()=>onView('accounts')}>Koppla min säljarprofil</Button>:<p>Be Sebbe koppla ditt konto till rätt säljare.</p>}</div>}
 <div className="day-result"><div><small>{team?'Teamets':'Din'} fakturerade försäljning denna månad</small><b>{money(stats.revenue)} <span>av {stats.target===null?'mål ej satt':money(stats.target)}</span></b></div><Progress aria-label="Andel av månadens försäljningsmål" value={stats.target&&stats.target>0?Math.min(100,stats.revenue/stats.target*100):0}/><Button variant="ghost" onClick={()=>onView(team?'team':'overview')}>Visa resultat <ArrowRight size={16}/></Button></div>
 {signals.length>0&&<section className="panel day-blocked"><div className="panel-head"><h2><AlertTriangle size={19}/>Prioritera nu <span className="count">{signals.length}</span></h2></div>{signals.slice(0,6).map(signal=><div className="daily-row" key={signal.id}><div><b>{signal.title}{team&&signal.escalated?' · behöver chefsuppföljning':''}</b><p>{signal.reason}</p><small>{st.customers.find(c=>c.id===signal.customerId)?.name}{team?' · '+signal.owner:''}</small></div><Button variant="outline" onClick={()=>{if(signal.taskId){const t=st.tasks.find(t=>t.id===signal.taskId);if(t)onTask(t)}else {const o=st.orders.find(o=>o.id===signal.orderId);if(o)onOrder(o)}}}>Hantera</Button></div>)}</section>}
 {issues.length>0&&<section className="panel day-blocked"><div className="panel-head"><h2><AlertTriangle size={20}/>Order som behöver din hjälp <span className="count">{issues.length}</span></h2></div>{issues.map(o=><div className="daily-row" key={o.id}><div><b>{st.deals.find(d=>d.id===o.dealId)?.title}</b><p>{o.production.issue}</p><small>{st.customers.find(c=>c.id===o.customerId)?.name} · hos kund {displayDate(o.deliveryDate)}</small></div><Button onClick={()=>{onView('orders');onOrder(o)}}>Hantera ordern</Button></div>)}</section>}
 <div className="daily-columns"><div className="day-primary"><section className="panel" id="daily-tasks"><div className="panel-head"><h2>{team?'Teamets uppgifter idag':'Att göra idag'} <span className="count">{now.length}</span></h2><Button variant="ghost" size="sm" onClick={()=>onCreate('task')}>Planera aktivitet</Button></div>{taskRows(now)}{!now.length&&<div className="day-empty"><b>Inga uppgifter att ta hand om idag</b><p>Planera en kundkontakt eller fortsätt med en offert.</p></div>}{later.length>0&&<details className="day-upcoming"><summary>Kommande sju dagar · {later.length} aktiviteter</summary>{taskRows(later)}</details>}</section>
 <section className="panel daily-drafts"><div className="panel-head"><h2><FilePenLine size={19}/>Fortsätt där du slutade</h2></div>{!drafts.ready&&<DraftStatus id=""/>}{drafts.records.slice(0,showAllDrafts?undefined:6).map(d=><div className="daily-row" key={d.id}><div><b>{d.title}</b><small>{{catalog:'Offert-/orderutkast',production:'Tryckunderlag',note:'Anteckning',followup:'Kunduppföljning',form:'Påbörjade uppgifter'}[d.kind]} · ditt privata utkast</small><DraftStatus id={d.id}/></div><div className="biz-buttons"><Button variant="outline" onClick={()=>onDraft(d)}>Fortsätt <ArrowRight size={15}/></Button>{discardDraft===d.id?<><Button variant="outline" onClick={async()=>{if(await drafts.archive(d.id))setDiscardDraft('')}}>Ja, ta bort utkast</Button><Button variant="ghost" onClick={()=>setDiscardDraft('')}>Behåll</Button></>:<Button variant="ghost" onClick={()=>setDiscardDraft(d.id)}>Ta bort</Button>}</div></div>)}{drafts.records.length>6&&<Button variant="ghost" onClick={()=>setShowAllDrafts(!showAllDrafts)}>{showAllDrafts?'Visa färre':'Visa alla '+drafts.records.length+' utkast'}</Button>}{drafts.ready&&!drafts.records.length&&<p className="biz-empty">Dina påbörjade anteckningar, uppföljningar och order visas här.</p>}</section></div>
 <div className="day-secondary"><section className="panel"><div className="panel-head"><h2>Nästa möten</h2><Button variant="ghost" size="sm" onClick={()=>onView('calendar')}>Kalender</Button></div>{meetings.slice(0,5).map(m=><div className="daily-row" key={m.id}><div><small>{displayDate(m.date)} · {m.time}</small><b>{m.title}</b><small>{st.customers.find(c=>c.id===m.customerId)?.name}</small></div><Button size="sm" variant="outline" onClick={()=>onMeeting(m)}>Förbered</Button></div>)}{!meetings.length&&<p className="biz-empty">Inga CRM-möten inom sju dagar.</p>}</section>
 <section className="panel"><div className="panel-head"><h2><Phone size={18}/>Kunder att kontakta</h2></div>{customers.slice(0,5).map(c=><div className="daily-row" key={c.id}><div><b>{c.name}</b><small>{concerns(c,day(),st)[0]}</small></div><Button size="sm" variant="outline" onClick={()=>onCustomer(c.id)}>Öppna kund</Button></div>)}{!customers.length&&<p className="biz-empty">Ingen kund har en aktuell uppföljningssignal.</p>}{customers.length>5&&<Button variant="ghost" onClick={()=>onView('care')}>Visa alla {customers.length} kunder</Button>}</section></div></div>
 <div id="daily-receipts"><ReceiptQueue st={st} owner={owner} onReceipt={onReceipt} compact/></div></div>
}
