'use client';
import {useId,useState} from 'react';
import {Search,Plus,FilePenLine,Phone,AlertTriangle,CalendarDays,Clock3,Package,Users,UserRound,CheckCircle2,TrendingUp} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {workSignals} from '@/lib/automation-signals';
import type {DraftRecord} from '@/lib/drafts';
import {awaitingReceipt} from '@/lib/order-work';
import {canFollowUp} from '@/lib/follow-up';
import {personalOwner,personalResultScope,salesMetrics} from '@/lib/sales-dashboard';
import {day,plusDays,concerns,type State,type Order,type Task,type Meeting} from '@/lib/crm';
import {useDrafts,DraftStatus} from './draft-workspace';
import {ReceiptQueue} from './receipt-queue';
import {ReceiptDraftPreview} from './receipt-draft-preview';
import {money,displayDate} from './business-ui';

const taskLabel=(t:Task)=>t.kind==='quote'?'Följ upp offerten':t.kind==='invoice_ready'?'Registrera faktura':['handover','proof_deadline','order_deadline'].includes(t.kind)?'Färdigställ underlag':canFollowUp(t)?'Följ upp':'Hantera aktivitet';
function openSection(id:string){const section=document.getElementById(id);if(section){section.focus({preventScroll:true});section.scrollIntoView({block:'start',behavior:'smooth'})}}

export function MyDay({st,owner,onOwnerChange,onCustomer,onTask,onCreate,onOrder,onMeeting,onReceipt,onView,onDraft}:{st:State;owner:string;onOwnerChange:(owner:string)=>void;onCustomer:(id:string)=>void;onTask:(t:Task)=>void;onCreate:(type:string)=>void;onOrder:(o:Order)=>void;onMeeting:(m:Meeting)=>void;onReceipt:(id:string)=>void;onView:(view:string)=>void;onDraft:(draft:DraftRecord)=>void}){
 const draftListId=useId();
 const [showAllDrafts,setShowAllDrafts]=useState(false),[discardDraft,setDiscardDraft]=useState('');
 const drafts=useDrafts(),personal=personalOwner(st),canTeam=st.viewer?.role==='admin',team=owner==='all',hasScope=team||!!personal&&owner===personal,today=day(),readonly=st.viewer?.role==='reader';
 const match=(v:{owner:string})=>hasScope&&(team||v.owner===owner);
 const resultScope=hasScope?(team?'all':personalResultScope(st)):'',hasResultScope=team||!!resultScope;
 const stats=salesMetrics(st,today.slice(0,7),resultScope);
 const tasks=st.tasks.filter(t=>match(t)&&!t.done&&t.kind!=='receipt').sort((a,b)=>a.due.localeCompare(b.due)),now=tasks.filter(t=>t.due<=today),late=now.filter(t=>t.due<today),todayTasks=now.filter(t=>t.due===today),later=tasks.filter(t=>t.due>today&&t.due<=plusDays(today,7));
 const meetings=st.meetings.filter(m=>match(m)&&m.status==='planned'&&m.date>=today&&m.date<=plusDays(today,7)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 const issues=st.orders.filter(o=>match(o)&&['submitted','printed'].includes(o.production.status)&&o.production.issue),customers=st.customers.filter(c=>match(c)&&concerns(c,today,st).length);
 const receipts=st.orders.filter(o=>match(o)&&awaitingReceipt(o)).sort((a,b)=>(a.deliveryNextCheck||a.deliveryDate).localeCompare(b.deliveryNextCheck||b.deliveryDate));
 const signals=workSignals(st).filter(s=>hasScope&&(team||s.owner===owner)),cname=(id:string)=>st.customers.find(c=>c.id===id)?.name||'Kund';
 const percentage=stats.target!==null&&stats.target>0?Math.round(stats.revenue/stats.target*100):null;
 const dateLabel=new Date(today+'T12:00:00').toLocaleDateString('sv-SE',{weekday:'long',day:'numeric',month:'long'});
 const issue=issues[0],task=now[0],signal=signals.find(s=>s.escalated)||(!task?signals[0]:undefined),meeting=meetings.find(m=>m.date===today),customer=customers[0],receipt=receipts[0];
 const handleSignal=(id:string)=>{const s=signals.find(s=>s.id===id);if(s?.taskId){const t=st.tasks.find(t=>t.id===s.taskId);if(t)onTask(t)}else if(s?.orderId){const o=st.orders.find(o=>o.id===s.orderId);if(o)onOrder(o)}};
 const focus=issue?{label:'ORDERHINDER',title:st.deals.find(d=>d.id===issue.dealId)?.title||'En order behöver hjälp',description:issue.production.issue,meta:cname(issue.customerId)+' · hos kund '+displayDate(issue.deliveryDate),actionLabel:'Hantera ordern',action:()=>{onView('orders');onOrder(issue)},urgent:true}
  :signal?{label:'KRÄVER UPPMÄRKSAMHET',title:signal.title,description:signal.reason,meta:cname(signal.customerId)+(team?' · '+signal.owner:''),actionLabel:'Hantera',action:()=>handleSignal(signal.id),urgent:true}
  :task?{label:task.due<today?'FÖLJ UPP FÖRST':'NÄSTA HANDLING',title:task.title,description:'',meta:cname(task.customerId)+' · '+(task.due<today?'försenad sedan ':task.due===today?'idag, ':'')+displayDate(task.due)+(team?' · '+task.owner:''),actionLabel:taskLabel(task),action:()=>onTask(task),urgent:task.due<today}
  :meeting?{label:'DAGENS MÖTE',title:meeting.title,description:'',meta:cname(meeting.customerId)+' · '+meeting.time,actionLabel:'Förbered mötet',action:()=>onMeeting(meeting),urgent:false}
  :receipt?{label:'LEVERANS ATT FÖLJA UPP',title:st.deals.find(d=>d.id===receipt.dealId)?.title||'Följ upp en leverans',description:'Kontrollera att hela leveransen har kommit fram.',meta:cname(receipt.customerId)+' · utlovad leverans '+displayDate(receipt.deliveryDate),actionLabel:readonly?'Visa leveransunderlag':'Följ upp leveransen',action:()=>onReceipt(receipt.id),urgent:(receipt.deliveryNextCheck||receipt.deliveryDate)<=today}
  :customer?{label:'KUND ATT KONTAKTA',title:customer.name,description:concerns(customer,today,st)[0],meta:customer.owner,actionLabel:'Öppna kunden',action:()=>onCustomer(customer.id),urgent:false}
  :{label:'UTRYMME FÖR NÄSTA STEG',title:'Inga aktiviteter planerade till idag',description:'Planera nästa kundkontakt eller fortsätt med en offert.',meta:'',actionLabel:readonly?'Sök kund':'Planera aktivitet',action:()=>onCreate(readonly?'search':'task'),urgent:false};

 function taskRows(list:Task[]){return list.map(t=><div className="daily-row" key={t.id} data-late={t.due<today}>
  <div><span className="day-row-kind">{t.kind==='quote'?'Offertuppföljning':t.kind==='invoice_ready'?'Fakturering':'Kundaktivitet'}</span><b>{t.title}</b><button className="daily-customer" onClick={()=>onCustomer(t.customerId)}>{cname(t.customerId)}</button><small>{t.due<today?'Försenad · ':t.due===today?'Idag · ':''}{displayDate(t.due)}{team?' · '+t.owner:''}</small></div>
  <Button variant="outline" onClick={()=>onTask(t)}>{readonly?'Visa aktivitet':taskLabel(t)}</Button>
 </div>)}

 return <div className="business-ui my-day visual-day" data-has-scope={hasScope}>
  <div className="day-scope"><span>{dateLabel}</span>{(personal||canTeam)&&<div className="day-scope-switch" aria-label="Välj arbetsdag">{personal&&<Button variant="ghost" aria-pressed={!team} onClick={()=>onOwnerChange(personal)}><UserRound size={16}/>Mina uppgifter</Button>}{canTeam&&<Button variant="ghost" aria-pressed={team} onClick={()=>onOwnerChange('all')}><Users size={16}/>Teamets uppgifter</Button>}</div>}</div>
  <section className="day-focus" aria-label={hasScope?'Nästa handling':'Börja här'} data-urgent={hasScope&&focus.urgent}>
   {hasScope?<><div className="day-focus-top"><span>{team?'TEAMETS DAG':st.viewer?.name?.split(' ')[0]||'DIN DAG'}</span><span className="day-focus-tag">{focus.urgent?<AlertTriangle size={14}/>:<CheckCircle2 size={14}/>} {focus.label}</span></div><h2>{focus.title}</h2>{focus.description&&<p>{focus.description}</p>}{focus.meta&&<div className="day-focus-meta">{focus.meta}</div>}<Button className="day-focus-action" onClick={focus.action}>{readonly&&task&&!issue&&!signal?'Visa aktivitet':focus.actionLabel}</Button></>
    :<><div className="day-focus-top"><span>{st.viewer?.name||'VÄLKOMMEN'}</span><Users size={22}/></div><h2>{canTeam?'Börja med teamets dag':'Din arbetsdag, på ett ställe'}</h2><p>{canTeam?'Se teamets aktiviteter, kundkontakter och order som behöver hjälp.':'Ditt konto behöver kopplas till din säljarprofil för att visa egna aktiviteter och resultat.'}</p>{canTeam?<Button className="day-focus-action" onClick={()=>onOwnerChange('all')}><Users size={17}/>Öppna teamets dag</Button>:<div className="day-focus-meta">Be Sebbe koppla ditt konto till rätt säljare.</div>}</>}
  </section>
  {!personal&&canTeam&&<div className="day-profile-link"><span>Vill du även ha egna uppgifter och mål?</span><button onClick={()=>onView('accounts')}>Koppla säljarprofil</button></div>}
  <div className="day-tools" aria-label="Snabbval" data-readonly={readonly}>
   {!readonly&&<><button className="day-tool-note" onClick={()=>onCreate('notes')}><span><FilePenLine size={21}/></span><b>Anteckna</b><small>Samtal eller möte</small></button><button className="day-tool-order" onClick={()=>onCreate('deal')}><span><Plus size={22}/></span><b>Ny offert/order</b><small>Börja med kunden</small></button></>}
   <button className="day-tool-search" onClick={()=>onCreate('search')}><span><Search size={21}/></span><b>Sök kund</b><small>Kontakt & historik</small></button>
  </div>
  {hasScope&&<div className="day-work-counts" aria-label="Dagens arbetsläge">
   <button onClick={()=>openSection('daily-tasks')}><CalendarDays size={18}/><span>Planerat idag</span><b>{todayTasks.length}</b></button>
   <button data-urgent={late.length>0} onClick={()=>openSection('daily-tasks')}><Clock3 size={18}/><span>Försenat</span><b>{late.length}</b></button>
   <button data-urgent={issues.length>0} onClick={()=>issues.length?openSection('daily-blocked'):onView('orders')}><Package size={18}/><span>Orderhinder</span><b>{issues.length}</b></button>
  </div>}
  <div className="daily-columns">
   <div className="day-primary">
    {hasScope&&<section className="panel day-task-panel" id="daily-tasks" tabIndex={-1}><div className="panel-head"><div><span className="day-section-label">KUNDKONTAKT & UPPFÖLJNING</span><h2>{team?'Teamets uppgifter idag':'Att göra idag'} <span className="count">{now.length}</span></h2></div>{!readonly&&<Button variant="ghost" size="sm" onClick={()=>onCreate('task')}><Plus size={16}/>Planera aktivitet</Button>}</div>{taskRows(now)}{!now.length&&<div className="day-empty"><CheckCircle2 size={21}/><div><b>Inget planerat till idag</b><p>{later.length?later.length+' aktiviteter finns under kommande sju dagar.':'Nya aktiviteter visas här när de planeras.'}</p></div></div>}{later.length>0&&<details className="day-upcoming"><summary>Kommande sju dagar <span>{later.length}</span></summary>{taskRows(later)}</details>}</section>}
    {signals.length>0&&<section className="panel day-blocked"><div className="panel-head"><h2><AlertTriangle size={19}/>Prioritera nu <span className="count">{signals.length}</span></h2></div>{signals.slice(0,6).map(s=><div className="daily-row" key={s.id}><div><b>{s.title}{team&&s.escalated?' · behöver chefsuppföljning':''}</b><p>{s.reason}</p><small>{cname(s.customerId)}{team?' · '+s.owner:''}</small></div><Button variant="outline" onClick={()=>handleSignal(s.id)}>{readonly?'Visa underlag':'Hantera'}</Button></div>)}</section>}
    {issues.length>0&&<section className="panel day-blocked" id="daily-blocked" tabIndex={-1}><div className="panel-head"><h2><AlertTriangle size={20}/>Order som behöver hjälp <span className="count">{issues.length}</span></h2></div>{issues.map(o=><div className="daily-row" key={o.id}><div><b>{st.deals.find(d=>d.id===o.dealId)?.title}</b><p>{o.production.issue}</p><small>{cname(o.customerId)} · hos kund {displayDate(o.deliveryDate)}</small></div><Button variant="outline" onClick={()=>{onView('orders');onOrder(o)}}>Öppna ordern</Button></div>)}</section>}
    <section className="panel daily-drafts"><div className="panel-head"><div><span className="day-section-label">BARA SYNLIGT FÖR DIG</span><h2><FilePenLine size={19}/>Fortsätt där du slutade{drafts.ready&&drafts.records.length>0&&<span className="count">{drafts.records.length}</span>}</h2></div></div>{!drafts.ready&&<DraftStatus id=""/>}{drafts.records.slice(0,showAllDrafts?undefined:6).map((d,index)=>{const receipt=d.kind==='receipt',prefix=draftListId+'-'+index;return <div className={'daily-row'+(receipt?' daily-receipt-draft':'')} key={d.id}><div><b id={receipt?prefix+'-title':undefined}>{d.title}</b><small>{{catalog:'Offert-/orderutkast',production:'Tryckunderlag',note:'Anteckning',followup:'Kunduppföljning',form:'Påbörjade uppgifter',plan:'Kundplan',prospecting:'Nykundsbearbetning',onboarding:'Onboarding',receipt:'Leveransbesked'}[d.kind]} · privat utkast</small>{receipt&&<ReceiptDraftPreview draft={d} titleId={prefix+'-title'} summaryId={prefix+'-summary'} identityId={prefix+'-identity'}/>}<DraftStatus id={d.id}/></div><div className="biz-buttons"><Button variant="outline" aria-labelledby={receipt?prefix+'-continue '+prefix+'-title':undefined} aria-describedby={receipt?prefix+'-summary '+prefix+'-identity':undefined} onClick={()=>onDraft(d)}>{receipt?<span id={prefix+'-continue'}>Fortsätt</span>:'Fortsätt'}</Button>{discardDraft===d.id?<><Button variant="outline" onClick={async()=>{if(await drafts.archive(d.id))setDiscardDraft('')}}>Ja, ta bort utkast</Button><Button variant="ghost" onClick={()=>setDiscardDraft('')}>Behåll</Button></>:<Button variant="ghost" onClick={()=>setDiscardDraft(d.id)}>Ta bort</Button>}</div></div>})}{drafts.records.length>6&&<Button variant="ghost" onClick={()=>setShowAllDrafts(!showAllDrafts)}>{showAllDrafts?'Visa färre':'Visa alla '+drafts.records.length+' utkast'}</Button>}{drafts.ready&&!drafts.records.length&&<p className="day-quiet-empty">Inga privata utkast just nu.</p>}</section>
   </div>
   {hasScope&&<div className="day-secondary">
    <section className="panel day-meetings"><div className="panel-head"><h2><CalendarDays size={19}/>Nästa möten</h2><Button variant="ghost" size="sm" onClick={()=>onView('calendar')}>Kalender</Button></div>{meetings.slice(0,5).map(m=><div className="daily-row" key={m.id}><div><small>{displayDate(m.date)} · {m.time}</small><b>{m.title}</b><small>{cname(m.customerId)}</small></div><Button size="sm" variant="outline" onClick={()=>onMeeting(m)}>{readonly?'Visa möte':'Förbered'}</Button></div>)}{!meetings.length&&<p className="day-quiet-empty">Inga planerade CRM-möten de närmaste sju dagarna.</p>}</section>
    <section className="panel day-contacts"><div className="panel-head"><h2><Phone size={18}/>Kunder att kontakta <span className="count">{customers.length}</span></h2></div>{customers.slice(0,5).map(c=><div className="daily-row" key={c.id}><div><b>{c.name}</b><small>{concerns(c,today,st)[0]}</small></div><Button size="sm" variant="outline" onClick={()=>onCustomer(c.id)}>Öppna kund</Button></div>)}{!customers.length&&<p className="day-quiet-empty">Inga aktuella uppföljningssignaler.</p>}{customers.length>5&&<Button variant="ghost" onClick={()=>onView('care')}>Visa alla {customers.length} kunder</Button>}</section>
    {hasResultScope?<section className="day-month-card" aria-label="Försäljning denna månad"><div className="day-month-heading"><span>{team?'TEAMETS':'DIN'} FÖRSÄLJNING</span><TrendingUp size={19}/></div><h2>{new Date(today+'T12:00:00').toLocaleDateString('sv-SE',{month:'long'})}</h2><strong>{money(stats.revenue)}</strong><div className="day-month-progress"><span>Mål {stats.target===null?'ej satt':money(stats.target)}</span><b>{percentage===null?'—':percentage+' %'}</b></div><Progress aria-label="Andel av månadsmålet" aria-valuetext={percentage===null?'Mål ej satt':percentage+' procent'} value={Math.min(100,Math.max(0,percentage??0))}/><p>Registrerade fakturor exkl. moms. Fortnox är inte anslutet.</p>{team&&stats.unattributedInvoices.length>0&&<p>{stats.unattributedInvoices.length} fakturor på {money(stats.unattributedRevenue)} ingår utan verifierad personansvarig.</p>}<Button variant="outline" onClick={()=>onView(team?'team':'overview')}>Öppna {team?'teamets':'mitt'} resultat</Button></section>:<section className="day-month-card" aria-label="Personligt resultat behöver kopplas"><h2>Ditt resultat behöver kopplas</h2><p>Dina aktiviteter visas från kundansvaret. Personliga försäljningssiffror kräver en uttrycklig koppling till din resultatprofil.</p><Button variant="outline" onClick={()=>onView(canTeam?'settings':'overview')}>{canTeam?'Koppla resultatprofil':'Öppna mitt resultat'}</Button></section>}
   </div>}
  </div>
  {hasScope&&<div id="daily-receipts" tabIndex={-1}><ReceiptQueue st={st} owner={owner} onReceipt={onReceipt} compact/></div>}
 </div>;
}
