'use client';
import {isLegacyProductionAssignment} from '@/lib/production-assignment';
import {productionIssueResponsibility,ownsProductionIssue} from '@/lib/production-issue-responsibility';
import {ProductionIssueResponsibilityHistory} from './production-issue-responsibility-dialog';
import {useEffect,useRef,useState} from 'react';
import {restoreHandoverFocus} from './handover-focus';
import {Camera,Check,ChevronRight,PackageCheck,Printer,RefreshCw,Truck,AlertTriangle} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './ui/sheet';
import {Tabs,TabsList,TabsTrigger} from './ui/tabs';
import {day,type State,type Order} from '@/lib/crm';
import {productionProgress,productionBasis,assignmentBasis,type MovementKind} from '@/lib/production-quantities';
import type {CustomerFile} from '@/lib/crm-files';
import {ProductionProgress,QuantityDialog} from './production-progress';
import {displayDate,type SaveAction} from './business-ui';

function nextWork(o:Order){const p=o.production,rows=productionProgress(p);if(p.status==='dispatched')return {label:p.issue?'Skickat · öppet hinder':'Skickat',kind:null,date:p.issue?'':p.dispatchedAt.slice(0,10)};if(p.status==='cancelled')return {label:'Avbrutet',kind:null,date:''};if(p.issue)return {label:'Hinder behöver lösas',kind:null,date:rows.some(r=>r.toReceive>0||r.toPrint>0)?p.printDeadline:p.dispatchDeadline};if(rows.some(r=>r.toPrint>0))return {label:'Redo för tryck',kind:'printed' as MovementKind,date:p.printDeadline};if(rows.some(r=>r.toDispatch>0))return {label:'Redo att skickas',kind:'dispatched' as MovementKind,date:p.dispatchDeadline};return {label:'Varor saknas',kind:'received' as MovementKind,date:p.printDeadline};}
const labels={received:'Registrera mottagna varor',printed:'Registrera färdigt tryck',dispatched:'Registrera utleverans',scrap_unprinted:'Kassera före tryck',scrap_printed:'Kassera efter tryck'};
const active=(o:Order)=>['submitted','printed'].includes(o.production.status);
const issueTime=(value:string)=>!value?'Tidpunkt saknas i underlaget':Number.isNaN(new Date(value).getTime())?value:new Date(value).toLocaleString('sv-SE');
const issueButton='h-auto min-h-11! min-w-0 max-w-full whitespace-normal break-words';
export function ProductionWorkspace({st,space,save,busy,refresh,selectedId,onSelect,onProductionAssignment,onProductionIssueResponsibility}:{st:State;space:string;save:SaveAction;busy:boolean;refresh:()=>Promise<void>;selectedId:string;onSelect:(id:string)=>void;onProductionAssignment?:(o:Order)=>void;onProductionIssueResponsibility?:(o:Order)=>void}){
 const workspace=useRef<HTMLElement|null>(null);
 const [tab,setTab]=useState('mine'),[search,setSearch]=useState('');
 const canClaim=['admin','production','print','warehouse'].includes(st.viewer?.role||'');
 const uid=st.viewer?.id||'',orders=st.orders.filter(o=>o.production.status!=='draft'),mine=orders.filter(o=>!!uid&&(active(o)&&o.production.assigneeId===uid||!!o.production.issue&&['submitted','printed','dispatched'].includes(o.production.status)&&ownsProductionIssue(o.production,{id:uid,memberId:st.viewer?.memberId}))),queue=orders.filter(active);
 const visible=(tab==='mine'?mine:tab==='queue'?queue:orders.filter(o=>!active(o))).filter(o=>(st.customers.find(c=>c.id===o.customerId)?.name+' '+st.deals.find(d=>d.id===o.dealId)?.title).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>tab==='done'?b.production.dispatchedAt.localeCompare(a.production.dispatchedAt):Number(!!b.production.issue)-Number(!!a.production.issue)||(nextWork(a).date||'9999').localeCompare(nextWork(b).date||'9999'));
 const selected=orders.find(o=>o.id===selectedId),scope=tab==='mine'?mine:queue,today=day();
 return <section ref={workspace} className="business-ui production-workspace">
 <div className="work-summary"><span><b>{scope.filter(o=>nextWork(o).date&&nextWork(o).date<today).length}</b> försenade</span><span><b>{scope.filter(o=>nextWork(o).date===today).length}</b> deadline idag</span><span><b>{scope.filter(o=>o.production.issue).length}</b> med hinder</span><Button variant="ghost" disabled={busy} onClick={refresh}><RefreshCw size={16}/>Uppdatera</Button></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="work-tabs"><TabsTrigger value="mine">Mitt arbete ({mine.length})</TabsTrigger><TabsTrigger value="queue">Gemensam kö ({queue.length})</TabsTrigger><TabsTrigger value="done">Avslutat</TabsTrigger></TabsList></Tabs>
 <p className="biz-hint">Mitt arbete visar jobb du håller ihop och öppna hinder du ansvarar för. Ett skickat jobb kan ha ett kvarstående hinder.</p>
 <Input aria-label="Sök arbetsorder" placeholder="Sök kund eller jobb…" value={search} onChange={e=>setSearch(e.target.value)}/>
 <div className="work-cards">{visible.map(o=>{const p=o.production,n=nextWork(o);return <article className="work-card" key={o.id} data-urgent={active(o)&&!!n.date&&n.date<today} data-blocked={!!p.issue}><div className="work-card-top"><span className="pill">{n.label}</span><small>{p.assigneeId===uid?'Ditt jobb':p.issue&&ownsProductionIssue(p,{id:uid,memberId:st.viewer?.memberId})?'Ditt hinder · Jobbansvar: '+(p.assigneeName||'Ingen har tagit jobbet'):p.assigneeName||'Ingen har tagit jobbet'}</small></div><h2>{st.customers.find(c=>c.id===o.customerId)?.name}</h2><p>{st.deals.find(d=>d.id===o.dealId)?.title||'Arbetsorder'}</p><div className="work-dates"><span>Tryck klart<b>{displayDate(p.printDeadline)}</b></span><span>Skickas senast<b>{displayDate(p.dispatchDeadline)}</b></span><span>Hos kunden<b>{displayDate(p.deliveryDate)}</b></span></div>{p.issue&&<p className="work-warning"><AlertTriangle size={16}/><span className="min-w-0 [overflow-wrap:anywhere]">{p.issue}</span></p>}<div className="work-card-actions"><Button data-production-work-open={o.id} onClick={()=>onSelect(o.id)}>Öppna jobb<ChevronRight size={16}/></Button>{canClaim&&active(o)&&!p.assigneeId&&!p.assigneeName&&<Button variant="outline" disabled={busy} onClick={async()=>{if(await save('production_claim',{orderId:o.id,expectedAssignment:assignmentBasis(p)},false)){setTab('mine');onSelect(o.id)}}}>Jag tar jobbet</Button>}</div></article>})}</div>
 {!visible.length&&<div className="biz-empty"><h2>{search?'Inga jobb matchar sökningen':tab==='mine'?'Inga egna jobb eller hinder just nu':tab==='queue'?'Inga aktiva arbetsorder':'Inga avslutade jobb ännu'}</h2><p>{tab==='mine'?(canClaim?'Välj ett jobb i den gemensamma kön och tryck ”Jag tar jobbet”.':'Dina öppna hinder visas här när du fått ansvaret. Jobbets produktionsansvar granskas separat av administratören.'):tab==='queue'?'Jobb visas här när säljaren lämnar en order till tryck och lager.':''}</p>{tab==='mine'&&<Button onClick={()=>setTab('queue')}>Öppna gemensam kö</Button>}</div>}
 {selected&&<WorkDetails key={space+selected.id} st={st} o={selected} space={space} save={save} busy={busy} refresh={refresh} onClose={()=>onSelect('')} returnFocus={()=>{const root=workspace.current;return root?Array.from(root.querySelectorAll<HTMLElement>('[data-production-work-open]')).find(button=>button.dataset.productionWorkOpen===selected.id)||root.querySelector<HTMLElement>('[role=tab][data-state=active]'):null}} onProductionAssignment={onProductionAssignment} onProductionIssueResponsibility={onProductionIssueResponsibility}/>}
 </section>;
}
function WorkDetails({st,o,space,save,busy,refresh,onClose,returnFocus,onProductionAssignment,onProductionIssueResponsibility}:{st:State;o:Order;space:string;save:SaveAction;busy:boolean;refresh:()=>Promise<void>;onClose:()=>void;returnFocus:()=>HTMLElement|null;onProductionAssignment?:(o:Order)=>void;onProductionIssueResponsibility?:(o:Order)=>void}){
 const [opener]=useState<HTMLElement|null>(()=>typeof document!=='undefined'&&document.activeElement instanceof HTMLElement&&document.activeElement!==document.body?document.activeElement:null);
 const [refreshing,setRefreshing]=useState(false),[movement,setMovement]=useState<MovementKind|null>(null),[issueOpen,setIssueOpen]=useState(false),[issue,setIssue]=useState(o.production.issue),[issueBasis,setIssueBasis]=useState(productionBasis(o.production)),[resolution,setResolution]=useState(''),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[files,setFiles]=useState<CustomerFile[]>([]),[fileError,setFileError]=useState(''),[discard,setDiscard]=useState(false);
 const [issueOriginal,setIssueOriginal]=useState(()=>({resolveOnly:o.production.status==='dispatched',message:o.production.issue,ownerName:o.production.issueOwnerName,responsibleName:productionIssueResponsibility(o.production).name,reportedAt:o.production.issueAt,customerName:st.customers.find(customer=>customer.id===o.customerId)?.name||'Kundkoppling saknas i underlaget',jobTitle:st.deals.find(deal=>deal.id===o.dealId)?.title||'Arbetsorder',workId:o.production.workId}));
 const p=o.production,role=st.viewer?.role||'',uid=st.viewer?.id||'',canPrint=['admin','production','print'].includes(role),canWarehouse=['admin','production','warehouse'].includes(role),n=nextWork(o),rows=productionProgress(p),locked=busy||uploading||refreshing;
 const canClaim=['admin','production','print','warehouse'].includes(role),canIssue=!p.issue||ownsProductionIssue(p,{id:uid,memberId:st.viewer?.memberId})||role==='admin',resolveOnly=issueOriginal.resolveOnly;
 const choices=(['received','printed','dispatched'] as MovementKind[]).filter(k=>(k==='printed'?canPrint:canWarehouse)&&rows.some(r=>k==='received'?r.toReceive>0:k==='printed'?r.toPrint>0:r.toDispatch>0));
 const primary=choices.includes(n.kind!)?n.kind:choices.find(k=>k==='received')||null;
 const fileUrl=(id:string,preview=false)=>'/api/crm/files?space='+space+'&id='+encodeURIComponent(id)+(preview?'&preview=1':'');
 useEffect(()=>{let stopped=false;fetch('/api/crm/files?space='+space+'&customerId='+encodeURIComponent(o.customerId)+'&orderId='+encodeURIComponent(o.id)).then(async r=>{const data:any=await r.json();if(!r.ok)throw Error(data.error);if(!stopped){setFiles(data);setFileError('')}}).catch(e=>{if(!stopped)setFileError(e.message)});return()=>{stopped=true}},[space,o.id,o.customerId,st.version]);
 const dirty=issueOpen&&(issue!==issueOriginal.message||!!resolution);
 useEffect(()=>{if(!dirty&&!uploading)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty,uploading]);
 const close=()=>{if(locked)return;if(dirty){setDiscard(true);return}onClose()};
 const sketch=files.find(f=>f.id===p.sketchFileId),photos=files.filter(f=>f.purpose==='production'&&f.workId===p.workId);
 function openIssue(){setIssue(p.issue);setIssueBasis(productionBasis(p));setIssueOriginal({resolveOnly:p.status==='dispatched',message:p.issue,ownerName:p.issueOwnerName,responsibleName:productionIssueResponsibility(p).name,reportedAt:p.issueAt,customerName:st.customers.find(customer=>customer.id===o.customerId)?.name||'Kundkoppling saknas i underlaget',jobTitle:st.deals.find(deal=>deal.id===o.dealId)?.title||'Arbetsorder',workId:p.workId});setResolution('');setError('');setIssueOpen(true)}
 async function upload(file:File){setUploading(true);setError('');try{const body=new FormData();Object.entries({space,customerId:o.customerId,orderId:o.id,workId:p.workId,purpose:'production',kind:'document',version:new Date().toISOString()}).forEach(([k,v])=>body.set(k,v));body.set('file',file);const r=await fetch('/api/crm/files',{method:'POST',body});const data:any=await r.json();if(!r.ok)throw Error(data.error);setFiles(old=>[data,...old.filter(f=>f.id!==data.id)]);await refresh()}catch(e){setError((e as Error).message)}finally{setUploading(false)}}
 return <><Sheet open onOpenChange={v=>{if(!v)close()}}><SheetContent className="crm-sheet work-sheet" onCloseAutoFocus={event=>restoreHandoverFocus(event,opener,returnFocus)}><SheetHeader className="min-w-0 [overflow-wrap:anywhere]"><SheetDescription>{st.customers.find(c=>c.id===o.customerId)?.name} · Säljare: {o.owner}</SheetDescription><SheetTitle className="min-w-0 [overflow-wrap:anywhere]">{st.deals.find(d=>d.id===o.dealId)?.title||'Arbetsorder'}</SheetTitle></SheetHeader><div className="sheet-body business-ui min-w-0 [overflow-wrap:anywhere] [&_button]:min-w-0 [&_button]:max-w-full">
 <Button variant="ghost" disabled={locked} onClick={async()=>{setRefreshing(true);try{await refresh()}finally{setRefreshing(false)}}}><RefreshCw size={16}/>{refreshing?'Uppdaterar…':'Uppdatera jobbet'}</Button>
 <div className="work-card-top"><span className="pill">{n.label}</span></div><section className="production-assignment-entry" aria-label="Produktionsansvar"><h3 tabIndex={-1} data-production-assignment-heading={o.id}>Produktionsansvar</h3><p><b>Håller ihop jobbet:</b> {p.assigneeId?(p.assigneeName||'Registrerad ansvarig utan namn'):p.assigneeName?p.assigneeName+' · äldre namn utan konto-ID':'Ingen har tagit jobbet'}.</p><p className="biz-hint">Orderansvar ligger kvar hos {o.owner||'orderansvarig'}. Registrerade moment behåller sina personer.</p>{role==='admin'&&active(o)&&onProductionAssignment&&<Button type="button" variant="outline" disabled={locked} onClick={()=>onProductionAssignment(o)}>{isLegacyProductionAssignment(p)?'Rätta äldre jobbansvar':p.assigneeId?'Byt produktionsansvar':'Tilldela produktionsansvar'}</Button>}{!active(o)&&<p className="biz-hint">Arbetsordern är avslutad och behåller sitt registrerade ansvar.</p>}</section>
 {canClaim&&active(o)&&<div className="biz-buttons">{!p.assigneeId&&p.assigneeName?<p className="biz-hint">Det äldre namnet saknar användaridentitet. Ansvarskopplingen behöver granskas före tilldelning.</p>:!p.assigneeId?<Button disabled={locked} onClick={()=>save('production_claim',{orderId:o.id,expectedAssignment:assignmentBasis(p)},false)}>Jag tar jobbet</Button>:(p.assigneeId===uid||role==='admin')?<Button variant="outline" disabled={locked} onClick={()=>{if(window.confirm('Lämna tillbaka jobbet till den gemensamma kön?'))void save('production_release',{orderId:o.id,expectedAssignment:assignmentBasis(p)},false)}}>Lämna tillbaka till kön</Button>:<p className="biz-hint">{p.assigneeName} håller ihop jobbet. Ni kan hjälpas åt med registreringarna.</p>}</div>}
 <div className={issueOpen?'work-dates grid-cols-1! md:grid-cols-3!':'work-dates'}><span>Tryck klart<b>{displayDate(p.printDeadline)}</b></span><span>Skickas senast<b>{displayDate(p.dispatchDeadline)}</b></span><span>Hos kunden<b>{displayDate(p.deliveryDate)}</b></span></div>
 {p.issue&&<section className="production-assignment-entry min-w-0 [overflow-wrap:anywhere]" aria-label="Öppet produktionshinder"><h3 tabIndex={-1} data-production-issue-responsibility-heading={o.id}>Öppet hinder</h3><div className="work-warning"><AlertTriangle size={20} aria-hidden="true"/><div className="min-w-0 [overflow-wrap:anywhere]"><b>Hinder: {p.issue}</b><p><b>Ansvarar för nästa steg:</b> {productionIssueResponsibility(p).name||'Ansvarig saknas i underlaget'}. {p.status==='dispatched'?'Jobbet är skickat. Det registrerade hindret behöver fortfarande följas upp.':'Tryck och utleverans väntar tills hindret är löst.'}</p></div></div><p className="biz-hint"><b>Rapporterat av:</b> {p.issueOwnerName||'Rapportör saknas i underlaget'}. <b>Registrerad rapporttid:</b> {issueTime(p.issueAt)}.</p>{role==='admin'&&['submitted','printed','dispatched'].includes(p.status)&&onProductionIssueResponsibility&&<Button type="button" variant="outline" disabled={locked||issueOpen} onClick={()=>onProductionIssueResponsibility(o)}>Byt hinderansvar</Button>}</section>}<ProductionIssueResponsibilityHistory production={p}/>
 {active(o)&&<div className="work-next"><h3>Nästa moment</h3>{primary?<Button className="work-primary" disabled={locked||(!!p.issue&&primary!=='received')} onClick={()=>setMovement(primary)}>{primary==='received'?<PackageCheck/>:primary==='printed'?<Printer/>:<Truck/>}{labels[primary]}</Button>:<p>{p.issue?'Lös hindret innan arbetet fortsätter.':'Inväntar nästa moment från kollegan.'}</p>}{choices.filter(k=>k!==primary).map(k=><Button key={k} variant="outline" disabled={locked||(!!p.issue&&k!=='received')} onClick={()=>setMovement(k)}>{labels[k]}</Button>)}<Button variant="ghost" disabled={locked||!canIssue} onClick={openIssue}><AlertTriangle size={16}/>{p.issue?'Hantera hinder':'Rapportera hinder'}</Button></div>}
 {p.status==='dispatched'&&!!p.issue&&role!=='reader'&&canIssue&&<div className="biz-buttons"><Button className={issueButton} variant="outline" disabled={locked||issueOpen} onClick={openIssue}><AlertTriangle size={16}/>Lös kvarstående hinder</Button></div>}
 {issueOpen&&<section className="work-issue min-w-0 [overflow-wrap:anywhere]" aria-label={resolveOnly?'Lös kvarstående hinder':issueOriginal.message?'Ändra hinderbeskrivning':'Rapportera hinder'}><h3 className="min-w-0"><span className="min-w-0 [overflow-wrap:anywhere]">{resolveOnly?'Lös kvarstående hinder':issueOriginal.message?'Ändra hinderbeskrivning':'Rapportera hinder'}</span></h3>
  <p className="biz-hint" aria-label="Jobb som hindret gäller"><b>{issueOriginal.customerName} · {issueOriginal.jobTitle}</b><br/>Order-ID: {o.id}. Arbetsreferens: {issueOriginal.workId||'saknas i underlaget'}.</p>
  {issueOriginal.message&&<section className="production-assignment-current min-w-0 [overflow-wrap:anywhere]" aria-label="Registrerat hinderunderlag"><h3 className="min-w-0"><span className="min-w-0 [overflow-wrap:anywhere]">Registrerat hinderunderlag · ligger kvar</span></h3><p className="whitespace-pre-wrap"><b>Hinder i det öppnade underlaget:</b> {issueOriginal.message}</p><p><b>Rapporterat av:</b> {issueOriginal.ownerName||'Rapportör saknas i underlaget'}.</p><p><b>Ansvarar för nästa steg i det öppnade underlaget:</b> {issueOriginal.responsibleName||'Ansvarig saknas i underlaget'}.</p><p><b>Registrerad rapporttid:</b> {issueTime(issueOriginal.reportedAt)}.</p><p>{resolveOnly?'Den sparade beskrivningen, rapportören och rapporttiden bevaras i lösningshistoriken. Jobbansvar, orderansvar och registrerade antal ligger kvar.':'Att spara beskrivningen byter ingen ansvarig och gör inte hindret löst. Jobbansvar, orderansvar och registrerade antal ligger kvar.'}</p></section>}
  {!resolveOnly&&<><label>{issueOriginal.message?'Beskrivning av hindret':'Vad hindrar jobbet?'}<Textarea className="field-sizing-fixed h-32 max-h-[40dvh] overflow-y-auto" onFocus={e=>e.currentTarget.scrollIntoView({block:'nearest',inline:'nearest'})} disabled={locked||!canIssue} value={issue} onChange={e=>setIssue(e.target.value)} placeholder="Exempel: tre plagg saknas, säljaren behöver kontakta leverantören."/></label><p>{issueOriginal.message?'Säljaren får en notis när du sparar.':'Ditt konto registreras som ansvarigt när du sparar. Säljaren får en notis.'}</p><div className="biz-buttons"><Button className={issueButton} disabled={locked||!canIssue||!issue.trim()} onClick={async()=>{setError('');if(await save('production_issue',{orderId:o.id,message:issue,expectedProduction:issueBasis},false))setIssueOpen(false);else setError('Beskrivningen kunde inte bekräftas. Din text finns kvar. Läs CRM:s felmeddelande och kontrollera aktuellt hinder innan du försöker igen.');}}>{issueOriginal.message?'Spara beskrivning':'Rapportera hinder'}</Button><Button className={issueButton} variant="ghost" disabled={locked} onClick={()=>{setIssue(p.issue);setIssueOpen(false)}}>Avbryt</Button></div></>}
  {issueOriginal.message&&<section className="mt-6 border-t border-amber-200 pt-5 min-w-0 [overflow-wrap:anywhere]" aria-label="Lös det registrerade hindret"><h3 className="min-w-0"><span className="min-w-0 [overflow-wrap:anywhere]">Hindret är löst?</span></h3><p>{resolveOnly?'Registrera lösningen först när hindret faktiskt är löst. Jobbet är redan skickat. Registrerade antal, produktionsmoment och tidigare leveranser ligger kvar. Säljaren får en notis när lösningen sparas.':'Registrera lösningen först när jobbet kan fortsätta. Åtgärden avslutar hindret i det öppnade underlaget; osparade ändringar av beskrivningen ingår inte.'}</p><label>Hur löstes hindret?<Textarea className="field-sizing-fixed h-32 max-h-[40dvh] overflow-y-auto" onFocus={e=>e.currentTarget.scrollIntoView({block:'nearest',inline:'nearest'})} disabled={locked||!canIssue} value={resolution} onChange={e=>setResolution(e.target.value)} placeholder={resolveOnly?'Beskriv den åtgärd som löste det registrerade hindret.':'Beskriv den åtgärd som gjorde att jobbet kan fortsätta.'}/></label><div className="biz-buttons"><Button className={issueButton} variant="outline" disabled={locked||!canIssue||!resolution.trim()} onClick={async()=>{setError('');if(await save('production_issue_resolve',{orderId:o.id,resolution,expectedProduction:issueBasis},false)){setIssue('');setIssueOpen(false)}else setError('Lösningen kunde inte bekräftas. Din text finns kvar. Läs CRM:s felmeddelande och kontrollera aktuellt hinder innan du försöker igen.');}}><Check size={16}/>Hindret är löst</Button>{resolveOnly&&<Button className={issueButton} variant="ghost" disabled={locked} onClick={()=>{setIssue(p.issue);setResolution('');setError('');setIssueOpen(false)}}>Avbryt</Button>}</div></section>}
  <p className="biz-hint">Texten är inget sparat privat utkast. Kopiera texten före omladdning.</p>
 </section>}
 <section className="work-instructions"><h3>Skiss & instruktion</h3><p className="work-instruction-text">{p.instructions||'Ingen separat instruktion.'}</p>{p.sketchFileId&&<><a className="work-file-link" href={fileUrl(p.sketchFileId)} target="_blank" rel="noreferrer">Öppna tryckskiss · {p.sketchVersion||'underlag'}</a>{sketch&&/\.(png|jpe?g|webp)$/i.test(sketch.name)&&<img className="work-sketch" src={fileUrl(sketch.id,true)} alt={'Tryckskiss, version '+p.sketchVersion}/>}</>}</section>
 <details className="biz-details" open><summary>Antal per artikel</summary><ProductionProgress production={p}/></details>
 <details className="biz-details"><summary>Leveransadress & kontakt</summary><p>{[p.deliveryAddress.street,p.deliveryAddress.postalCode,p.deliveryAddress.city,p.deliveryAddress.country,p.deliveryAddress.reference].filter(Boolean).join(', ')}</p><p>{st.customers.find(c=>c.id===o.customerId)?.contact} · {st.customers.find(c=>c.id===o.customerId)?.phone}</p><p>Skickat betyder att varorna lämnats till transportör eller hämtats. Säljaren följer upp kundens mottagande separat.</p></details>
 <section className="work-photos"><h3>Arbetsfoton</h3>{canClaim&&active(o)&&<label className="work-upload"><Camera size={18}/>{uploading?'Laddar upp…':'Lägg till foto'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={locked} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file)}}/></label>}{canClaim&&active(o)&&<p className="biz-hint">Fotot sparas direkt på arbetsordern. JPG, PNG eller WebP, högst 5 MB.</p>}{fileError&&<p className="error">{fileError}</p>}<div className="work-photo-grid">{photos.map(f=><a key={f.id} href={fileUrl(f.id)} target="_blank" rel="noreferrer"><img src={fileUrl(f.id,true)} alt={f.name}/><span>{f.uploadedBy} · {displayDate(f.at)}</span></a>)}</div>{!photos.length&&!fileError&&<p>Inga arbetsfoton ännu.</p>}</section>
 {active(o)&&<details className="biz-details"><summary>Avvikande antal / kassation</summary><p>Kassera bara varor som inte kan användas. Om kunden godtar färre varor behöver säljaren registrera den överenskommelsen på ordern.</p><div className="biz-buttons">{canWarehouse&&<Button variant="outline" disabled={locked||!rows.some(r=>r.toPrint>0)} onClick={()=>setMovement('scrap_unprinted')}>Kassera före tryck</Button>}{canPrint&&<Button variant="outline" disabled={locked||!rows.some(r=>r.toDispatch>0)} onClick={()=>setMovement('scrap_printed')}>Kassera efter tryck</Button>}</div></details>}
 {o.productionHistory.some(previous=>!!previous.issueResponsibility?.history.length||previous.issueResolutions.some(resolution=>!!resolution.responsibility?.history.length))&&<details className="biz-details"><summary>Hinderansvar i tidigare arbetsversioner</summary>{o.productionHistory.map((previous,index)=>(previous.issueResponsibility?.history.length||previous.issueResolutions.some(resolution=>!!resolution.responsibility?.history.length))?<section key={previous.workId+'-'+index}><h3>Arbetsversion {index+1} · arkiverad</h3><p className="biz-hint">Arbetsreferens: {previous.workId}.</p><ProductionIssueResponsibilityHistory production={previous} archived/></section>:null)}</details>}
 <details className="biz-details"><summary>Arbetsorderns historik</summary>{st.events.filter(e=>e.dealId===o.dealId&&e.kind==='production').slice().sort((a,b)=>b.at.localeCompare(a.at)).map(e=><p key={e.id}>{displayDate(e.at)} · {e.actor?.name||'Tidigare registrering'} · {e.text}</p>)}</details>
 {error&&<p className="error" role="alert">{error}</p>}{discard&&<div className="record-conflict"><p>{resolveOnly?'Du har en osparad lösning av hindret.':'Du har en osparad beskrivning av hindret.'}</p><Button variant="outline" onClick={()=>setDiscard(false)}>Fortsätt skriva</Button><Button variant="ghost" onClick={onClose}>Stäng utan att spara texten</Button></div>}<Button variant="outline" disabled={locked} onClick={close}>Stäng jobbet</Button>
 </div></SheetContent></Sheet>{movement&&<QuantityDialog key={o.id+movement} order={o} kind={movement} title={st.deals.find(d=>d.id===o.dealId)?.title||'Arbetsorder'} save={save} busy={locked} onClose={()=>setMovement(null)}/>}</>;
}
