'use client';
import {useState} from 'react';
import {PackageCheck,Printer,Truck,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {productionProgress,productionBasis,type Production,type MovementKind} from '@/lib/production-quantities';
import {variantLabel} from '@/lib/business';
import type {Order} from '@/lib/crm';
import {BusinessField as F,displayDate,type SaveAction} from './business-ui';

const captions={received:'Varumottagning',printed:'Färdigtryckta artiklar',dispatched:'Utleverans',scrap_unprinted:'Kassation före tryck',scrap_printed:'Kassation efter tryck'};
export function ProductionProgress({production:p}:{production:Production}){
 const rows=productionProgress(p);
 if(!rows.length)return null;
 return <div className="quantity-progress">{rows.map(r=><section className="quantity-row" key={r.line.id}><div className="quantity-title"><b>{r.line.description}</b><span>{r.line.article} · {variantLabel(r.line)||'Variant ej angiven'} · {r.line.unit||'st'}</span></div><dl className="quantity-counts"><div><dt>Beställt</dt><dd>{r.ordered}</dd></div>{r.reduction>0&&<div><dt>Godkänt antal</dt><dd>{r.target}</dd></div>}<div data-state="received"><dt>Mottaget</dt><dd>{r.received}</dd></div><div data-state="printed"><dt>Tryckt, godkänt</dt><dd>{r.usablePrinted}</dd></div><div data-state="dispatched"><dt>Skickat</dt><dd>{r.dispatched}</dd></div><div data-pending={r.remaining>0}><dt>Återstår</dt><dd>{r.remaining}</dd></div></dl>{r.scrapUnprinted+r.scrapPrinted>0&&<p className="biz-hint">Kasserat: {r.scrapUnprinted+r.scrapPrinted} {r.line.unit}. {r.toReceive>0?r.toReceive+' ersättningsvaror saknas.':'Varuförsörjningen är komplett.'}</p>}</section>)}<details className="biz-details movement-history"><summary>Registreringar & försändelser ({p.movements.length})</summary>{p.quantityMode==='legacy'&&<p>Antalen bygger på tidigare bekräftelser för hela ordern.</p>}{[...p.movements].reverse().map(m=><article key={m.id}><b>{captions[m.kind]}{m.legacy?' · tidigare helorderbekräftelse':''}</b><p>{/^\d{4}-/.test(m.at)?displayDate(m.at):m.at} · {m.by}</p>{m.entries.map(e=>{const l=p.lines.find(l=>l.id===e.lineId);return <p key={e.lineId}>{e.quantity} {l?.unit||'st'} · {l?.description||'Artikelrad'} · {l?variantLabel(l):e.lineId}</p>})}{m.reason&&<p>Orsak: {m.reason}</p>}{m.kind==='dispatched'&&<><p>{[m.recipient,m.address?.street,m.address?.postalCode,m.address?.city,m.address?.reference].filter(Boolean).join(', ')}</p><p>Spårning: {m.tracking||'Ej registrerad'}</p></>}</article>)}{p.quantityAdjustments.map(a=><article key={a.id}><b>Kundgodkänd minskning</b><p>{a.reason} · godkänt av {a.customerApprovedBy} {a.customerApprovedOn}</p>{a.entries.map(e=><p key={e.lineId}>{e.quantity} färre · {p.lines.find(l=>l.id===e.lineId)?.description}</p>)}<p>Registrerat av {a.recordedBy}</p></article>)}</details></div>;
}

export function QuantityDialog({order:o,title,kind,save,busy,onClose}:{order:Order;title:string;kind:MovementKind;save:SaveAction;busy:boolean;onClose:()=>void}){
 const [basis,setBasis]=useState(()=>productionBasis(o.production)),[values,setValues]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[tracking,setTracking]=useState(''),[recipient,setRecipient]=useState(''),[address,setAddress]=useState(()=>({...o.production.deliveryAddress})),[error,setError]=useState('');
 const rows=productionProgress(o.production),stale=basis!==productionBasis(o.production);
 const available=(r:typeof rows[number])=>kind==='received'?r.toReceive:kind==='printed'||kind==='scrap_unprinted'?r.toPrint:r.toDispatch;
 const entries=rows.filter(r=>Number(values[r.line.id])>0).map(r=>({lineId:r.line.id,quantity:Number(values[r.line.id])}));
 const invalid=rows.some(r=>{const n=Number(values[r.line.id]||0);return !Number.isFinite(n)||n<0||n>available(r)});
 const icon=kind==='received'?<PackageCheck size={18}/>:kind==='printed'?<Printer size={18}/>:<Truck size={18}/>;
 return <Sheet open onOpenChange={v=>{if(!v&&!busy)onClose()}}><SheetContent className="crm-sheet"><SheetHeader><SheetTitle>{captions[kind]}</SheetTitle><SheetDescription>{title} · Registrera bara de antal som har hanterats denna gång.</SheetDescription></SheetHeader><div className="sheet-body business-ui quantity-dialog">
 {stale&&<div className="record-conflict" role="alert"><b>Orderns antal har ändrats</b><p>En kollega har registrerat en händelse. Läs in aktuella antal och fyll i denna registrering igen. Adress och fraktreferens behålls.</p><Button disabled={busy} variant="outline" onClick={()=>{setBasis(productionBasis(o.production));setValues({});setError('')}}><RefreshCw size={16}/>Läs in aktuella antal</Button></div>}
 <fieldset disabled={busy||stale}><Button type="button" variant="outline" onClick={()=>setValues(Object.fromEntries(rows.map(r=>[r.line.id,available(r)>0?String(available(r)):''])))}>Fyll tillgängligt antal</Button>
 <div className="quantity-inputs">{rows.map(r=><div key={r.line.id} className="quantity-input-row"><div><b>{r.line.description}</b><p>{r.line.article} · {variantLabel(r.line)}</p><span>Tillgängligt att registrera: <b>{available(r)} {r.line.unit||'st'}</b></span></div><F label={'Antal '+(r.line.size||'')+' '+(r.line.color||'')}><Input type="number" min="0" step="any" max={available(r)} disabled={available(r)<=0} placeholder="0" value={values[r.line.id]||''} onChange={e=>setValues({...values,[r.line.id]:e.target.value})}/></F></div>)}</div>
 {kind.startsWith('scrap_')&&<><F label="Orsak till kassation *"><Input required value={message} onChange={e=>setMessage(e.target.value)}/></F><p className="biz-hint">Kasserade varor kan inte skickas. Kundens beställda antal gäller fortfarande och ersättningsvaror visas som saknade.</p></>}
 {kind==='dispatched'&&<><h3>Mottagare för denna försändelse</h3><F label="Person / avdelning"><Input value={recipient} onChange={e=>setRecipient(e.target.value)}/></F><div className="biz-grid">{(['street','postalCode','city','country','reference'] as const).map((key,i)=><F key={key} label={['Gatuadress *','Postnummer *','Ort *','Land','Leveransreferens'][i]}><Input value={address[key]} onChange={e=>setAddress({...address,[key]:e.target.value})}/></F>)}</div><F label="Spårningsnummer / fraktreferens"><Input value={tracking} onChange={e=>setTracking(e.target.value)}/></F><p className="biz-hint">Registrera när varorna lämnats till transportören eller hämtats. Resterande antal ligger kvar i arbetskön. Faktureringsuppgiften skapas efter sista utleveransen.</p></>}
 {invalid&&<p className="error" role="alert">Ange ett antal mellan noll och tillgängligt antal på varje rad.</p>}{error&&<p className="error" role="alert">{error}</p>}
 <div className="biz-buttons"><Button type="button" variant="outline" onClick={onClose}>Avbryt</Button><Button disabled={busy||stale||invalid||!entries.length||(kind.startsWith('scrap_')&&!message.trim())||(kind==='dispatched'&&(!address.street.trim()||!address.postalCode.trim()||!address.city.trim()))} onClick={async()=>{setError('');if(await save('production_'+kind,{orderId:o.id,expectedProduction:basis,entries,tracking,recipient,address,message},false))onClose();else setError('Registreringen sparades inte. Kontrollera meddelandet och underlaget innan du försöker igen.')}}>{icon}{busy?'Sparar…':'Registrera '+entries.length+(entries.length===1?' artikelrad':' artikelrader')}</Button></div>
 </fieldset></div></SheetContent></Sheet>;
}
