'use client';
import {useEffect,useState} from 'react';
import {Camera,Check,ChevronRight,PackageCheck,Printer,RefreshCw,Truck,AlertTriangle} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './ui/sheet';
import {Tabs,TabsList,TabsTrigger} from './ui/tabs';
import {day,type State,type Order} from '@/lib/crm';
import {productionProgress,assignmentBasis,type MovementKind} from '@/lib/production-quantities';
import type {CustomerFile} from '@/lib/crm-files';
import {ProductionProgress,QuantityDialog} from './production-progress';
import {displayDate,type SaveAction} from './business-ui';

function nextWork(o:Order){const p=o.production,rows=productionProgress(p);if(p.status==='dispatched')return {label:'Skickat',kind:null,date:p.dispatchedAt.slice(0,10)};if(p.status==='cancelled')return {label:'Avbrutet',kind:null,date:''};if(p.issue)return {label:'Hinder behöver lösas',kind:null,date:rows.some(r=>r.toReceive>0||r.toPrint>0)?p.printDeadline:p.dispatchDeadline};if(rows.some(r=>r.toPrint>0))return {label:'Redo för tryck',kind:'printed' as MovementKind,date:p.printDeadline};if(rows.some(r=>r.toDispatch>0))return {label:'Redo att skickas',kind:'dispatched' as MovementKind,date:p.dispatchDeadline};return {label:'Varor saknas',kind:'received' as MovementKind,date:p.printDeadline};}
const labels={received:'Registrera mottagna varor',printed:'Registrera färdigt tryck',dispatched:'Registrera utleverans',scrap_unprinted:'Kassera före tryck',scrap_printed:'Kassera efter tryck'};
const active=(o:Order)=>['submitted','printed'].includes(o.production.status);
export function ProductionWorkspace({st,space,save,busy,refresh,selectedId,onSelect}:{st:State;space:string;save:SaveAction;busy:boolean;refresh:()=>Promise<void>;selectedId:string;onSelect:(id:string)=>void}){
 const [tab,setTab]=useState('mine'),[search,setSearch]=useState('');
 const uid=st.viewer?.id||'',orders=st.orders.filter(o=>o.production.status!=='draft'),mine=orders.filter(o=>active(o)&&o.production.assigneeId===uid),queue=orders.filter(active);
 const visible=(tab==='mine'?mine:tab==='queue'?queue:orders.filter(o=>!active(o))).filter(o=>(st.customers.find(c=>c.id===o.customerId)?.name+' '+st.deals.find(d=>d.id===o.dealId)?.title).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>tab==='done'?b.production.dispatchedAt.localeCompare(a.production.dispatchedAt):Number(!!b.production.issue)-Number(!!a.production.issue)||(nextWork(a).date||'9999').localeCompare(nextWork(b).date||'9999'));
 const selected=orders.find(o=>o.id===selectedId),scope=tab==='mine'?mine:queue,today=day();
 return <section className="business-ui production-workspace">
 <div className="work-summary"><span><b>{scope.filter(o=>nextWork(o).date&&nextWork(o).date<today).length}</b> försenade</span><span><b>{scope.filter(o=>nextWork(o).date===today).length}</b> deadline idag</span><span><b>{scope.filter(o=>o.production.issue).length}</b> med hinder</span><Button variant="ghost" disabled={busy} onClick={refresh}><RefreshCw size={16}/>Uppdatera</Button></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="work-tabs"><TabsTrigger value="mine">Mitt arbete ({mine.length})</TabsTrigger><TabsTrigger value="queue">Gemensam kö ({queue.length})</TabsTrigger><TabsTrigger value="done">Avslutat</TabsTrigger></TabsList></Tabs>
 <Input aria-label="Sök arbetsorder" placeholder="Sök kund eller jobb…" value={search} onChange={e=>setSearch(e.target.value)}/>
 <div className="work-cards">{visible.map(o=>{const p=o.production,n=nextWork(o);return <article className="work-card" key={o.id} data-urgent={active(o)&&!!n.date&&n.date<today} data-blocked={!!p.issue}><div className="work-card-top"><span className="pill">{n.label}</span><small>{p.assigneeId===uid?'Ditt jobb':p.assigneeName||'Ingen har tagit jobbet'}</small></div><h2>{st.customers.find(c=>c.id===o.customerId)?.name}</h2><p>{st.deals.find(d=>d.id===o.dealId)?.title||'Arbetsorder'}</p><div className="work-dates"><span>Tryck klart<b>{displayDate(p.printDeadline)}</b></span><span>Skickas senast<b>{displayDate(p.dispatchDeadline)}</b></span><span>Hos kunden<b>{displayDate(p.deliveryDate)}</b></span></div>{p.issue&&<p className="work-warning"><AlertTriangle size={16}/>{p.issue}</p>}<div className="work-card-actions"><Button onClick={()=>onSelect(o.id)}>Öppna jobb<ChevronRight size={16}/></Button>{active(o)&&!p.assigneeId&&<Button variant="outline" disabled={busy} onClick={async()=>{if(await save('production_claim',{orderId:o.id,expectedAssignment:assignmentBasis(p)},false)){setTab('mine');onSelect(o.id)}}}>Jag tar jobbet</Button>}</div></article>})}</div>
 {!visible.length&&<div className="biz-empty"><h2>{search?'Inga jobb matchar sökningen':tab==='mine'?'Inga egna jobb just nu':tab==='queue'?'Inga aktiva arbetsorder':'Inga avslutade jobb ännu'}</h2><p>{tab==='mine'?'Välj ett jobb i den gemensamma kön och tryck ”Jag tar jobbet”.':tab==='queue'?'Jobb visas här när säljaren lämnar en order till tryck och lager.':''}</p>{tab==='mine'&&<Button onClick={()=>setTab('queue')}>Öppna gemensam kö</Button>}</div>}
 {selected&&<WorkDetails key={space+selected.id} st={st} o={selected} space={space} save={save} busy={busy} refresh={refresh} onClose={()=>onSelect('')}/>}
 </section>;
}
function WorkDetails({st,o,space,save,busy,refresh,onClose}:{st:State;o:Order;space:string;save:SaveAction;busy:boolean;refresh:()=>Promise<void>;onClose:()=>void}){
 const [refreshing,setRefreshing]=useState(false),[movement,setMovement]=useState<MovementKind|null>(null),[issueOpen,setIssueOpen]=useState(false),[issue,setIssue]=useState(o.production.issue),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[files,setFiles]=useState<CustomerFile[]>([]),[fileError,setFileError]=useState(''),[discard,setDiscard]=useState(false);
 const p=o.production,role=st.viewer?.role||'',uid=st.viewer?.id||'',canPrint=['admin','production','print'].includes(role),canWarehouse=['admin','production','warehouse'].includes(role),n=nextWork(o),rows=productionProgress(p),locked=busy||uploading||refreshing;
 const canIssue=!p.issue||p.issueOwnerId===uid||role==='admin';
 const choices=(['received','printed','dispatched'] as MovementKind[]).filter(k=>(k==='printed'?canPrint:canWarehouse)&&rows.some(r=>k==='received'?r.toReceive>0:k==='printed'?r.toPrint>0:r.toDispatch>0));
 const primary=choices.includes(n.kind!)?n.kind:choices.find(k=>k==='received')||null;
 const fileUrl=(id:string,preview=false)=>'/api/crm/files?space='+space+'&id='+encodeURIComponent(id)+(preview?'&preview=1':'');
 useEffect(()=>{let stopped=false;fetch('/api/crm/files?space='+space+'&customerId='+encodeURIComponent(o.customerId)+'&orderId='+encodeURIComponent(o.id)).then(async r=>{const data:any=await r.json();if(!r.ok)throw Error(data.error);if(!stopped){setFiles(data);setFileError('')}}).catch(e=>{if(!stopped)setFileError(e.message)});return()=>{stopped=true}},[space,o.id,o.customerId,st.version]);
 const dirty=issueOpen&&issue!==p.issue;
 useEffect(()=>{if(!dirty&&!uploading)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty,uploading]);
 const close=()=>{if(locked)return;if(dirty){setDiscard(true);return}onClose()};
 const sketch=files.find(f=>f.id===p.sketchFileId),photos=files.filter(f=>f.purpose==='production'&&f.workId===p.workId);
 async function upload(file:File){setUploading(true);setError('');try{const body=new FormData();Object.entries({space,customerId:o.customerId,orderId:o.id,workId:p.workId,purpose:'production',kind:'document',version:new Date().toISOString()}).forEach(([k,v])=>body.set(k,v));body.set('file',file);const r=await fetch('/api/crm/files',{method:'POST',body});const data:any=await r.json();if(!r.ok)throw Error(data.error);setFiles(old=>[data,...old.filter(f=>f.id!==data.id)]);await refresh()}catch(e){setError((e as Error).message)}finally{setUploading(false)}}
 return <><Sheet open onOpenChange={v=>{if(!v)close()}}><SheetContent className="crm-sheet work-sheet"><SheetHeader><SheetDescription>{st.customers.find(c=>c.id===o.customerId)?.name} · Säljare: {o.owner}</SheetDescription><SheetTitle>{st.deals.find(d=>d.id===o.dealId)?.title||'Arbetsorder'}</SheetTitle></SheetHeader><div className="sheet-body business-ui">
 <Button variant="ghost" disabled={locked} onClick={async()=>{setRefreshing(true);try{await refresh()}finally{setRefreshing(false)}}}><RefreshCw size={16}/>{refreshing?'Uppdaterar…':'Uppdatera jobbet'}</Button>
 <div className="work-card-top"><span className="pill">{n.label}</span><b>{p.assigneeName||'Ingen ansvarig ännu'}</b></div>
 {active(o)&&<div className="biz-buttons">{!p.assigneeId?<Button disabled={locked} onClick={()=>save('production_claim',{orderId:o.id,expectedAssignment:assignmentBasis(p)},false)}>Jag tar jobbet</Button>:(p.assigneeId===uid||role==='admin')?<Button variant="outline" disabled={locked} onClick={()=>{if(window.confirm('Lämna tillbaka jobbet till den gemensamma kön?'))void save('production_release',{orderId:o.id,expectedAssignment:assignmentBasis(p)},false)}}>Lämna tillbaka till kön</Button>:<p className="biz-hint">{p.assigneeName} håller ihop jobbet. Ni kan hjälpas åt med registreringarna.</p>}</div>}
 <div className="work-dates"><span>Tryck klart<b>{displayDate(p.printDeadline)}</b></span><span>Skickas senast<b>{displayDate(p.dispatchDeadline)}</b></span><span>Hos kunden<b>{displayDate(p.deliveryDate)}</b></span></div>
 {p.issue&&<div className="work-warning" role="status"><AlertTriangle size={20}/><div><b>Hinder: {p.issue}</b><p>Följs upp av {p.issueOwnerName||'ansvarig medarbetare'}. Tryck och utleverans väntar tills hindret är löst.</p></div></div>}
 {active(o)&&<div className="work-next"><h3>Nästa moment</h3>{primary?<Button className="work-primary" disabled={locked||(!!p.issue&&primary!=='received')} onClick={()=>setMovement(primary)}>{primary==='received'?<PackageCheck/>:primary==='printed'?<Printer/>:<Truck/>}{labels[primary]}</Button>:<p>{p.issue?'Lös hindret innan arbetet fortsätter.':'Inväntar nästa moment från kollegan.'}</p>}{choices.filter(k=>k!==primary).map(k=><Button key={k} variant="outline" disabled={locked||(!!p.issue&&k!=='received')} onClick={()=>setMovement(k)}>{labels[k]}</Button>)}<Button variant="ghost" disabled={locked||!canIssue} onClick={()=>{setIssue(p.issue);setIssueOpen(true)}}><AlertTriangle size={16}/>{p.issue?'Hantera hinder':'Rapportera hinder'}</Button></div>}
 {issueOpen&&<section className="work-issue"><h3>{p.issue?'Hantera hinder':'Vad hindrar jobbet?'}</h3><label>Beskriv vad som behöver lösas<Textarea disabled={locked||!canIssue} value={issue} onChange={e=>setIssue(e.target.value)} placeholder="Exempel: tre plagg saknas, säljaren behöver kontakta leverantören."/></label><p>Säljaren får en notis när du sparar.</p><div className="biz-buttons"><Button disabled={locked||!canIssue||!issue.trim()} onClick={async()=>{setError('');if(await save('production_issue',{orderId:o.id,message:issue},false))setIssueOpen(false);else setError('Hindret sparades inte. Din text finns kvar.')}}>Spara hinder</Button>{p.issue&&<Button variant="outline" disabled={locked||!canIssue} onClick={async()=>{if(window.confirm('Är hindret löst så att arbetet kan fortsätta?')&&await save('production_issue',{orderId:o.id,message:''},false)){setIssue('');setIssueOpen(false)}}}><Check size={16}/>Hindret är löst</Button>}<Button variant="ghost" disabled={locked} onClick={()=>{setIssue(p.issue);setIssueOpen(false)}}>Avbryt</Button></div></section>}
 <section className="work-instructions"><h3>Skiss & instruktion</h3><p className="work-instruction-text">{p.instructions||'Ingen separat instruktion.'}</p>{p.sketchFileId&&<><a className="work-file-link" href={fileUrl(p.sketchFileId)} target="_blank" rel="noreferrer">Öppna tryckskiss · {p.sketchVersion||'underlag'}</a>{sketch&&/\.(png|jpe?g|webp)$/i.test(sketch.name)&&<img className="work-sketch" src={fileUrl(sketch.id,true)} alt={'Tryckskiss, version '+p.sketchVersion}/>}</>}</section>
 <details className="biz-details" open><summary>Antal per artikel</summary><ProductionProgress production={p}/></details>
 <details className="biz-details"><summary>Leveransadress & kontakt</summary><p>{[p.deliveryAddress.street,p.deliveryAddress.postalCode,p.deliveryAddress.city,p.deliveryAddress.country,p.deliveryAddress.reference].filter(Boolean).join(', ')}</p><p>{st.customers.find(c=>c.id===o.customerId)?.contact} · {st.customers.find(c=>c.id===o.customerId)?.phone}</p><p>Skickat betyder att varorna lämnats till transportör eller hämtats. Säljaren följer upp kundens mottagande separat.</p></details>
 <section className="work-photos"><h3>Arbetsfoton</h3>{active(o)&&<label className="work-upload"><Camera size={18}/>{uploading?'Laddar upp…':'Lägg till foto'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={locked} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file)}}/></label>}{active(o)&&<p className="biz-hint">Fotot sparas direkt på arbetsordern. JPG, PNG eller WebP, högst 5 MB.</p>}{fileError&&<p className="error">{fileError}</p>}<div className="work-photo-grid">{photos.map(f=><a key={f.id} href={fileUrl(f.id)} target="_blank" rel="noreferrer"><img src={fileUrl(f.id,true)} alt={f.name}/><span>{f.uploadedBy} · {displayDate(f.at)}</span></a>)}</div>{!photos.length&&!fileError&&<p>Inga arbetsfoton ännu.</p>}</section>
 {active(o)&&<details className="biz-details"><summary>Avvikande antal / kassation</summary><p>Kassera bara varor som inte kan användas. Om kunden godtar färre varor behöver säljaren registrera den överenskommelsen på ordern.</p><div className="biz-buttons">{canWarehouse&&<Button variant="outline" disabled={locked||!rows.some(r=>r.toPrint>0)} onClick={()=>setMovement('scrap_unprinted')}>Kassera före tryck</Button>}{canPrint&&<Button variant="outline" disabled={locked||!rows.some(r=>r.toDispatch>0)} onClick={()=>setMovement('scrap_printed')}>Kassera efter tryck</Button>}</div></details>}
 <details className="biz-details"><summary>Arbetsorderns historik</summary>{st.events.filter(e=>e.dealId===o.dealId&&e.kind==='production').slice().sort((a,b)=>b.at.localeCompare(a.at)).map(e=><p key={e.id}>{displayDate(e.at)} · {e.text}</p>)}</details>
 {error&&<p className="error" role="alert">{error}</p>}{discard&&<div className="record-conflict"><p>Du har en osparad beskrivning av hindret.</p><Button variant="outline" onClick={()=>setDiscard(false)}>Fortsätt skriva</Button><Button variant="ghost" onClick={onClose}>Stäng utan att spara texten</Button></div>}<Button variant="outline" disabled={locked} onClick={close}>Stäng jobbet</Button>
 </div></SheetContent></Sheet>{movement&&<QuantityDialog key={o.id+movement} order={o} kind={movement} title={st.deals.find(d=>d.id===o.dealId)?.title||'Arbetsorder'} save={save} busy={locked} onClose={()=>setMovement(null)}/>}</>;
}
