'use client';
import { Plus,Trash2,Calculator } from 'lucide-react';
import { Input } from '@/components/ui/input';import { Button } from '@/components/ui/button';import { Checkbox } from '@/components/ui/checkbox';
import { calculateQuote,LineSchema,variantLabel,type QuoteLine } from '@/lib/business';import type { Deal,Customer } from '@/lib/crm';
import { BusinessField as F,Pick,money,displayDate } from './business-ui';
const kinds=[{id:'product',label:'Produkt'},{id:'marking',label:'Tryck / brodyr'},{id:'setup',label:'Startkostnad'},{id:'freight',label:'Frakt'},{id:'other',label:'Övrigt'}];
export function QuoteEditor({deal:d,customer,onChange}:{deal:Deal;customer?:Customer;onChange:(key:string,v:unknown)=>void}){
 const lines=d.lines||[],total=lines.length?calculateQuote(lines):{value:d.value,cost:d.cost};
 const change=(next:QuoteLine[])=>{onChange('lines',next);onChange('priceChecked',false);if(next.length){const t=calculateQuote(next);onChange('value',t.value);onChange('cost',t.cost)}};
 const patch=(i:number,key:keyof QuoteLine,value:unknown)=>change(lines.map((l,n)=>n===i?{...l,[key]:value,...(['color','size','article','variant'].includes(key)?{variantId:''}:{})}:l));
 const add=()=>change([...lines,{id:crypto.randomUUID(),sourceId:'',productUrl:'',kind:'product',description:'',article:'',variant:'',variantId:'',color:'',size:'',unit:'st',quantity:1,unitPrice:0,unitCost:null}]);
 return <section className="business-ui quote-editor"><div className="biz-head"><h3><Calculator size={19}/>Offertkalkyl</h3><Button type="button" variant="outline" size="sm" onClick={add}><Plus size={15}/>Kalkylrad</Button></div>{!lines.length&&<p className="biz-hint">Använd totalsummorna nedan eller lägg till kalkylrader. Raderna räknar då fram summorna automatiskt. Använd en rad per färg och storlek.</p>}{customer&&customer.products.length>0&&<F label="Lägg in från kundens sortiment"><Pick label="Produkt från kundsortiment" value="" items={[{id:'',label:'Välj produkt'},...customer.products.map(p=>({id:p.id,label:p.description}))]} onChange={id=>{const p=customer.products.find(p=>p.id===id);if(p)change([...lines,{id:crypto.randomUUID(),sourceId:'',productUrl:'',kind:'product',description:p.description,article:p.article,variant:[p.variant,p.marking].filter(Boolean).join(' · '),variantId:p.variantId,color:p.color,size:p.size,unit:p.unit,quantity:1,unitPrice:0,unitCost:null}])}}/></F>}
 {lines.map((l,i)=><fieldset className="quote-line" key={l.id||i}><legend>Rad {i+1}</legend><div className="biz-grid"><F label="Typ"><Pick label={'Typ rad '+(i+1)} value={l.kind} onChange={v=>patch(i,'kind',v)} items={kinds}/></F><F label="Benämning *"><Input required value={l.description} onChange={e=>patch(i,'description',e.target.value)}/></F><F label="Artikelnummer"><Input value={l.article} onChange={e=>patch(i,'article',e.target.value)}/></F><F label="Färg"><Input value={l.color||''} onChange={e=>patch(i,'color',e.target.value)}/></F><F label="Storlek"><Input value={l.size||''} onChange={e=>patch(i,'size',e.target.value)}/></F><F label="Övrig variant / märkning"><Input value={l.variant} onChange={e=>patch(i,'variant',e.target.value)}/></F></div><div className="quote-numbers"><F label="Antal *"><Input type="number" min="0.01" step="any" value={l.quantity} onChange={e=>patch(i,'quantity',Number(e.target.value))}/></F><F label="Pris / st exkl. moms"><Input type="number" min="0" step="0.01" value={l.unitPrice} onChange={e=>patch(i,'unitPrice',Number(e.target.value))}/></F><F label="Kostnad / st"><Input type="number" min="0" step="0.01" placeholder="Okänd" value={l.unitCost??''} onChange={e=>patch(i,'unitCost',e.target.value===''?null:Number(e.target.value))}/></F></div><div className="biz-head"><span>Radbelopp {money(l.quantity*l.unitPrice)}</span><Button type="button" variant="ghost" size="sm" aria-label={'Ta bort kalkylrad '+(i+1)} onClick={()=>change(lines.filter((_,n)=>n!==i))}><Trash2 size={16}/></Button></div></fieldset>)}{lines.length>0&&<div className="quote-totals"><div><span>Offert exkl. moms</span><b>{money(total.value)}</b></div><div><span>Direkta kostnader</span><b>{money(total.cost)}</b></div><div><span>Bruttovinst</span><b>{total.cost==null?'Kostnad saknas':money(total.value!-total.cost)}</b></div></div>}
 {d.sourceDealId&&<div className="biz-callout"><b>Återbeställning – tidigare underlag</b><p>Kontrollera dagens priser, antal, lagerstatus och leveranstid.</p>{d.repeatRecipe&&<p>Tidigare skiss och tryckinstruktioner följer med till orderberedningen. Kundgodkännande och leverantörsbekräftelse behöver registreras på nytt.</p>}<label className="check-field"><Checkbox checked={d.priceChecked} onCheckedChange={v=>onChange('priceChecked',v===true)}/>Priser och leveransförutsättningar är kontrollerade för denna beställning</label></div>}
 <div className="biz-grid"><F label="Korrektur godkänt senast"><Input type="date" value={d.proofDeadline||''} onChange={e=>onChange('proofDeadline',e.target.value)}/></F><F label="Beställ hos leverantör senast"><Input type="date" value={d.orderDeadline||''} onChange={e=>onChange('orderDeadline',e.target.value)}/></F></div>
 {!!d.quotes?.length&&<details className="biz-details"><summary>Offertversioner ({d.quotes.length})</summary>{[...d.quotes].reverse().map(q=><details className="quote-version" key={q.version}><summary>Version {q.version} · {q.reference} · {money(q.value)}<small>{displayDate(q.at)} · leverans {displayDate(q.deliveryDate)}</small></summary><p>Kostnad {money(q.cost)} · korrektur {displayDate(q.proofDeadline)} · beställning {displayDate(q.orderDeadline)}</p>{q.lines.map((l,i)=><p key={i}>{l.quantity} × {l.description} · {l.article} · {variantLabel(l)} · {money(l.unitPrice)} / st</p>)}</details>)}</details>}
 </section>
}
