'use client';
import {useState,useMemo} from 'react';import {Input} from '@/components/ui/input';import {Button} from '@/components/ui/button';import {Table,TableHead,TableHeader,TableBody,TableCell,TableRow} from '@/components/ui/table';import {parseCSV} from '@/lib/business';import {BusinessField as F,Pick} from './business-ui';
export function RecordImporter({fields,parse,onImport,busy,maxRows=200}:{fields:{id:string;label:string;aliases?:string[]}[];parse:(record:Record<string,string>)=>unknown;onImport:(rows:any[])=>Promise<boolean>;busy:boolean;maxRows?:number}){
 const [rows,setRows]=useState<string[][]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[error,setError]=useState('');
 const preview=useMemo(()=>rows.slice(1).map((row,i)=>{const record=Object.fromEntries(fields.map(f=>[f.id,mapping[f.id]!==''&&mapping[f.id]!==undefined?row[Number(mapping[f.id])]||'':'']));try{return {row:i+2,data:parse(record),error:'',label:Object.values(record).filter(Boolean).slice(0,3).join(' · ')}}catch(e){return {row:i+2,data:null,error:e instanceof Error?e.message:'Kontrollera raden',label:Object.values(record).filter(Boolean).slice(0,3).join(' · ')}}}),[rows,mapping,fields,parse]);
 const valid=preview.filter(r=>r.data!==null);
 return <div className="business-ui"><F label={'CSV-fil med rubrikrad, högst '+maxRows+' rader'}><Input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>2000000)throw Error('Välj en fil på högst 2 MB.');const data=parseCSV(await f.text());if(data.length<2||data.length>maxRows+1)throw Error('Välj 1–'+maxRows+' datarader med en rubrikrad.');setRows(data);const normalize=(v:string)=>v.toLowerCase().replace(/[^a-zåäö0-9]/g,'');setMapping(Object.fromEntries(fields.map(field=>{const accepted=[field.id,field.label,...field.aliases||[]].map(normalize);const index=data[0].findIndex(h=>accepted.includes(normalize(h)));return [field.id,index<0?'':String(index)]})));setError('')}catch(e){setError((e as Error).message)}}}/></F>{rows.length>0&&<><div className="biz-grid">{fields.map(f=><F label={f.label} key={f.id}><Pick label={'Kolumn '+f.label} value={mapping[f.id]||''} items={[{id:'',label:'Ingen kolumn'},...rows[0].map((h,i)=>({id:String(i),label:h||'Kolumn '+(i+1)}))]} onChange={v=>setMapping({...mapping,[f.id]:v})}/></F>)}</div><Table><TableHeader><TableRow><TableHead>Rad</TableHead><TableHead>Innehåll</TableHead><TableHead>Kontroll</TableHead></TableRow></TableHeader><TableBody>{preview.slice(0,20).map(r=><TableRow key={r.row}><TableCell>{r.row}</TableCell><TableCell>{r.label}</TableCell><TableCell>{r.error||'Redo'}</TableCell></TableRow>)}</TableBody></Table><p className="biz-hint">{valid.length} av {preview.length} rader är klara. De första 20 visas. Rader med fel hoppas över.</p><Button disabled={busy||!valid.length} onClick={async()=>{if(await onImport(valid.map(r=>r.data)))setRows([])}}>Importera {valid.length} rader</Button></>}{error&&<p className="error">{error}</p>}</div>
}
export const csvNumber=(v:string)=>v.trim()?Number(v.replace(/\s/g,'').replace(',','.')):null;
