'use client';
import {useId,useRef,useState} from 'react';
import {UserRound,Users,Target,TrendingUp,ClipboardList,HeartHandshake,Package,CalendarDays,AlertTriangle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {type State,type Task,PIPELINE,day,concerns} from '@/lib/crm';
import {personalResultScope,resultOperationalOwner,resultTaskScope,salesMetrics} from '@/lib/sales-dashboard';
import {sellerProfileById} from '@/lib/seller-profiles';
import {money,displayDate} from './business-ui';
import {TeamDashboard} from './team-dashboard';
import {SalesTrend} from './sales-trend';
function GoalRing({percentage}:{percentage:number|null}){
 const circumference=2*Math.PI*29;
 return <span className="result-goal-ring" aria-hidden="true"><svg viewBox="0 0 72 72"><circle className="ring-track" cx="36" cy="36" r="29"/><circle className="ring-value" cx="36" cy="36" r="29" strokeDasharray={circumference} strokeDashoffset={circumference*(1-Math.min(100,percentage??0)/100)}/></svg><b>{percentage===null?'—':(percentage>999?'999%+':percentage+'%')}<small>av målet</small></b></span>;
}
const attainment=(value:number,target:number|null)=>target!==null&&target>0?Math.round(value/target*100):null;
const remaining=(value:number,target:number|null)=>target===null?'Mål ej satt':value>=target?'Målet uppnått':money(target-value)+' kvar';
export function SalesDashboard({st,mode,month,onMonth,onMode,onView,onCustomer,onTask}:{st:State;mode:'personal'|'team';month:string;onMonth:(v:string)=>void;onMode:(v:'personal'|'team')=>void;onView:(v:string,owner:string)=>void;onCustomer:(id:string)=>void;onTask:(t:Task)=>void}){
 const profileDiagnosticId=useId(),invoiceDetails=useRef<HTMLDetailsElement>(null),[invoicePeriod,setInvoicePeriod]=useState<'month'|'year'>('month');
 const showInvoices=(period:'month'|'year')=>{setInvoicePeriod(period);if(invoiceDetails.current){invoiceDetails.current.open=true;invoiceDetails.current.querySelector('summary')?.focus({preventScroll:true});invoiceDetails.current.scrollIntoView({behavior:'smooth',block:'start'})}};
 const personal=personalResultScope(st),team=mode==='team',canTeam=st.viewer?.role==='admin',owner=team?'all':personal;
 const stats=salesMetrics(st,month,owner,team?'profile':'personal'),taskScope=resultTaskScope(st,owner,team?'profile':'personal'),linkedProfile=taskScope.profileId?sellerProfileById(st.settings,taskScope.profileId):undefined,name=(st.settings.sellerProfilesInitialized?sellerProfileById(st.settings,personal)?.displayName:undefined)||st.viewer?.name||'Mitt konto',today=day(),year=month.slice(0,4);
 const risk=stats.customers.filter(c=>concerns(c,today,st).length),due=stats.tasks.filter(t=>t.due<=today),late=due.filter(t=>t.due<today),issues=stats.orders.filter(o=>['submitted','printed'].includes(o.production.status)&&o.production.issue);
 const go=(view:string)=>onView(view,resultOperationalOwner(st,owner)),monthLabel=new Date(month+'-01T12:00:00').toLocaleDateString('sv-SE',{month:'long',year:'numeric'});
 const invoiceRows=invoicePeriod==='year'?stats.yearInvoices:stats.invoices;
 const monthPct=attainment(stats.revenue,stats.target),yearPct=attainment(stats.yearRevenue,stats.yearTarget),coverage=stats.invoices.length?stats.known.length/stats.invoices.length*100:0;
 return <div className="business-ui sales-dashboard visual-results">
  <div className="sales-scope"><Tabs value={mode} onValueChange={value=>onMode(value as 'personal'|'team')}><TabsList><TabsTrigger value="personal"><UserRound size={16}/>Mitt resultat</TabsTrigger>{canTeam&&<TabsTrigger value="team"><Users size={16}/>Teamets resultat</TabsTrigger>}</TabsList></Tabs><label>Rapportmånad<Input type="month" aria-label="Rapportmånad" value={month} onChange={event=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(event.target.value))onMonth(event.target.value)}}/></label></div>
  {!team&&!personal?<section className="panel padded personal-unmapped"><UserRound size={30}/><h2>{name}</h2><p>Ditt konto är inte kopplat till en egen resultatprofil. Därför visar vi inga personliga försäljningssiffror här.</p>{canTeam?<><p>Koppla rätt person till resultatprofilen under Mål & inställningar. Teamets resultat kan du redan se.</p><div className="biz-buttons"><Button onClick={()=>onMode('team')}>Öppna teamets resultat</Button><Button variant="outline" onClick={()=>go('settings')}>Resultatprofiler & mål</Button></div></>:<p>Be en administratör kontrollera din konto- och profilkoppling i Mål & inställningar. Kundansvar och historiskt resultat har separata kopplingar.</p>}</section>:<>
   <div className="result-identity"><span className="result-avatar">{team?<Users size={22}/>:name.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><div><h2>{team?'Magnussons · hela teamet':name}</h2><p>{monthLabel} · fakturerad försäljning exkl. moms</p></div><Button variant="outline" onClick={()=>go('today')}>Till {team?'teamets':'min'} arbetsdag</Button></div>
   <div className="result-kpis">
    <button className="result-kpi result-kpi-primary" onClick={()=>showInvoices('month')}><span className="result-kpi-label">Försäljning · {monthLabel}<TrendingUp size={18}/></span><div className="result-kpi-value"><strong>{money(stats.revenue)}</strong><GoalRing percentage={monthPct}/></div><span className="result-kpi-context">Mål {stats.target===null?'ej satt':money(stats.target)}</span><Progress aria-label="Andel av månadsmålet" aria-valuetext={monthPct===null?'Mål ej satt':monthPct+' procent'} value={Math.min(100,monthPct??0)}/><span className="result-kpi-foot">{remaining(stats.revenue,stats.target)}<span>{stats.invoices.length} fakturor</span></span></button>
    <button className="result-kpi" onClick={()=>showInvoices('year')}><span className="result-kpi-label">Försäljning {year}<CalendarDays size={18}/></span><div className="result-kpi-value"><strong>{money(stats.yearRevenue)}</strong></div><span className="result-kpi-context">Årsmål {stats.yearTarget===null?'ej satt':money(stats.yearTarget)}</span><Progress aria-label="Andel av årsmålet" aria-valuetext={yearPct===null?'Mål ej satt':yearPct+' procent'} value={Math.min(100,yearPct??0)}/><span className="result-kpi-foot">{yearPct===null?'—':yearPct+' % av målet'}<span>{remaining(stats.yearRevenue,stats.yearTarget)}</span></span></button>
    <button className="result-kpi result-kpi-margin" onClick={()=>showInvoices('month')}><span className="result-kpi-label">Marginal<TrendingUp size={18}/></span><div className="result-kpi-value"><strong>{stats.margin===null?'—':stats.margin.toLocaleString('sv-SE',{maximumFractionDigits:1})+' %'}</strong></div><span className="result-kpi-context">På fakturor med registrerad kostnad</span><Progress aria-label="Andel fakturor med kostnadsunderlag" value={coverage}/><span className="result-kpi-foot">{stats.known.length} av {stats.invoices.length} har kostnad<span>{stats.known.length<stats.invoices.length?'Ofullständigt underlag':stats.invoices.length?'Fullständigt underlag':'Inga fakturor ännu'}</span></span></button>
    <button className="result-kpi result-kpi-prospects" onClick={()=>go('prospects')}><span className="result-kpi-label">Nya kvalificerade prospects<Target size={18}/></span><div className="result-kpi-value"><strong>{stats.qualified}</strong><span className="result-number-unit">företag</span></div><span className="result-kpi-context">Första bekräftade behov · {monthLabel}</span>{stats.qualifiedTarget!==null&&<Progress aria-label="Andel av kvalificeringsmålet" value={stats.qualifiedTarget>0?Math.min(100,stats.qualified/stats.qualifiedTarget*100):0}/>}<span className="result-kpi-foot">{stats.qualifiedTarget===null?'Kvalificeringsmål ej satt':'Mål '+stats.qualifiedTarget+' företag'}<span>Öppna bearbetningen</span></span></button>
   </div>
   <p className="result-source-note">Manuellt registrerade fakturor · Fortnox är inte anslutet.</p>
   {team&&(stats.yearUnattributedInvoices.length>0||stats.unattributedQualified>0)&&<p className="biz-callout" role="status">{stats.yearUnattributedInvoices.length} fakturor på {money(stats.yearUnattributedRevenue)} under {year} saknar verifierad resultatansvarig. I {monthLabel} gäller det {stats.unattributedInvoices.length} fakturor på {money(stats.unattributedRevenue)} och {stats.unattributedQualified} kvalificerade prospects. Beloppen ingår i teamets resultat och har inte tilldelats en person.</p>}
   <div className="result-main-grid"><SalesTrend st={st} owner={owner} month={month} onMonth={onMonth}/>
    <section className="panel result-next" data-profile-diagnostic={taskScope.diagnostic||undefined}><div className="result-panel-heading"><div><span className="result-kicker">NÄSTA HANDLING</span><h2>Kräver uppmärksamhet</h2></div><span className="result-live-caption">Just nu</span></div>
     {!team&&taskScope.diagnostic&&<section className="day-profile-notice result-task-notice mx-5 mb-3 min-w-0 rounded-md border border-[#e5cfaa] bg-[#fff9ef] px-4 py-3" role="status" aria-labelledby={profileDiagnosticId} data-profile-diagnostic={taskScope.diagnostic}>
      <h3 id={profileDiagnosticId} className="flex items-start gap-2 font-semibold leading-normal text-[#684716] [overflow-wrap:anywhere]"><AlertTriangle size={20} aria-hidden="true" className="mt-0.5 shrink-0"/>{taskScope.diagnostic==='operational-missing'?'Kundansvar saknas':taskScope.diagnostic==='missing'?'Dina aktiviteter behöver en kontokoppling':'Kontokopplingen behöver kontrolleras'}</h3>
      <p>{taskScope.diagnostic==='operational-missing'?'Ditt konto är kopplat till en säljarprofil, men har inget giltigt kundansvar. Dina profilkopplade uppgifter visas. Äldre uppgifter utan profilansvar kan saknas här.':taskScope.diagnostic==='missing'?'Ditt konto saknar koppling till en säljarprofil. Uppgifter med profilansvar kan därför saknas här.':'Ditt kundansvar och den säljarprofil som är kopplad till kontot hör till olika ansvar. Profilkopplade uppgifter följer profilen; äldre uppgifter utan profilansvar följer kundansvaret.'}</p>
      {taskScope.diagnostic==='operational-missing'&&<p>Kopplad profil: <b>{linkedProfile!.displayName}</b>.</p>}
      {taskScope.diagnostic==='mismatch'&&<p>Kundansvar: <b>{taskScope.legacyOwner}</b>. Kopplad profil: <b>{linkedProfile!.displayName}</b> · ansvar: <b>{linkedProfile!.legacyOwnerName}</b>.</p>}
      <p>Synligt urval: aktivitetsantalet gäller bara det som kan kopplas i detta urval. Arbetslistan kan vara ofullständig.</p>
      {canTeam?<Button type="button" variant="outline" onClick={()=>go(taskScope.diagnostic==='operational-missing'?'accounts':'settings')}>{taskScope.diagnostic==='operational-missing'?'Öppna Konton & roller':'Öppna Mål & inställningar'}</Button>:<p>{taskScope.diagnostic==='operational-missing'?'Be en administratör kontrollera ditt kundansvar i Konton & roller.':'Be en administratör kontrollera din konto- och profilkoppling i Mål & inställningar.'}</p>}
     </section>}
     <button className="result-attention" onClick={()=>go('today')} data-urgent={late.length>0}><ClipboardList size={20}/><span><b>{due.length} aktiviteter att hantera{taskScope.diagnostic?' · synligt urval':''}</b><small>{taskScope.diagnostic?(late.length?late.length+' försenade i urvalet':due.length?'Planerade till idag i urvalet':'Inga aktiviteter visas till idag. Listan kan vara ofullständig.'):late.length?late.length+' försenade':due.length?'Planerade till idag':'Inget försenat eller planerat idag'}</small></span></button>
     <button className="result-attention" onClick={()=>go('care')}><HeartHandshake size={20}/><span><b>{risk.length} kunder behöver kontakt</b><small>Avstämning, återköp eller relationsrisk</small></span></button>
     <button className="result-attention" onClick={()=>go('orders')} data-urgent={issues.length>0}><Package size={20}/><span><b>{issues.length} order har ett hinder</b><small>Hjälp tryck och lager vidare</small></span></button>
     {due.slice(0,3).map(task=><button className="result-next-task" key={task.id} onClick={()=>onTask(task)}><span>{task.kind==='quote'?'Följ upp offert':task.kind==='invoice_ready'?'Registrera faktura':'Hantera aktivitet'}</span><b>{task.title}</b><small>{st.customers.find(customer=>customer.id===task.customerId)?.name} · {task.due===today?'Idag':displayDate(task.due)}</small></button>)}
     <Button variant="outline" onClick={()=>go('today')}>Öppna {team?'teamets uppgifter':'Min dag'}</Button>
    </section>
   </div>
   {team&&<TeamDashboard st={st} month={month} onCustomer={onCustomer}/>}
   <section className="panel result-pipeline"><div className="result-panel-heading"><div><span className="result-kicker">ÖPPNA AFFÄRER JUST NU</span><h2>{money(stats.pipeline)} i offertvärde</h2><p>{stats.open.length} pågående affärer{stats.unpriced?' · '+stats.unpriced+' saknar värde':''}</p></div><Button variant="outline" onClick={()=>go('deals')}>Öppna affärstavlan</Button></div><div className="result-stage-grid">{PIPELINE.map(stage=>{const list=stats.open.filter(deal=>deal.stage===stage.id);return <button key={stage.id} onClick={()=>go('deals')}><span>{stage.short}<b>{list.length}</b></span><Progress aria-label={stage.label+': '+list.length+' affärer'} value={stats.open.length?list.length/stats.open.length*100:0}/><small>{money(list.reduce((sum,deal)=>sum+(deal.value||0),0))}</small></button>})}</div><p className="result-chart-note">Oviktat offertvärde. Det är inte fakturerad försäljning.</p></section>
   <details ref={invoiceDetails} className="panel result-data-table result-invoices"><summary>Visa fakturaunderlag</summary><div><Tabs value={invoicePeriod} onValueChange={value=>setInvoicePeriod(value as 'month'|'year')}><TabsList><TabsTrigger value="month">{monthLabel}</TabsTrigger><TabsTrigger value="year">Hela {year}</TabsTrigger></TabsList></Tabs><table><caption>{invoiceRows.length} registrerade fakturor · ansvar vid fakturaregistrering · exkl. moms</caption><thead><tr><th>Kund</th><th>Fakturareferens</th><th>Resultatansvarig</th><th>Datum</th><th>Fakturerat</th><th>Kostnad</th></tr></thead><tbody>{invoiceRows.slice(0,50).sort((a,b)=>b.invoiceDate.localeCompare(a.invoiceDate)).map(order=><tr key={order.id}><th scope="row"><button data-customer-id={order.customerId} onClick={()=>onCustomer(order.customerId)}>{st.customers.find(customer=>customer.id===order.customerId)?.name||'Kund'}</button></th><td>{order.invoiceRef||'Saknas'}</td><td>{st.settings.sellerProfilesInitialized?(sellerProfileById(st.settings,order.invoiceOwnerId)?.displayName||'Ej verifierad'):(order.invoiceOwner||order.owner)}</td><td>{displayDate(order.invoiceDate)}</td><td>{money(order.invoiceValue)}</td><td>{order.actualCost===null?'Okänd':money(order.actualCost)}</td></tr>)}</tbody></table>{!invoiceRows.length&&<p>Inga registrerade fakturor i perioden.</p>}{invoiceRows.length>50&&<p>Här visas de första 50 fakturorna. Samtliga ingår i resultatet.</p>}</div></details>
   <details className="result-definitions"><summary>Så räknas resultatet</summary><p>Försäljning räknas på fakturadatum och det ansvar som sparades när fakturan registrerades. Ett senare byte av orderansvarig flyttar inte resultatet. Årskortet visar hela kalenderåret.</p>{st.settings.sellerProfilesInitialized&&<p>Resultatet följer en stabil profil och en uttrycklig kontokoppling. Visningsnamn kan ändras utan att historiken flyttas. Äldre fakturor eller kvalificeringar utan verifierat ansvar ingår i teamet och tilldelas ingen person automatiskt.</p>}<p>Marginal = (fakturerat − registrerad kostnad) / fakturerat, enbart för fakturor med kostnad. Saknad kostnad ger okänd marginal. {stats.profit===null?'Bruttovinst saknas.':'Känd bruttovinst i rapportmånaden: '+money(stats.profit)+'.'}</p><p>Prospects räknas när ett behov kvalificeras för första gången. Importerade företag och obesvarade kontaktförsök räknas inte som kvalificeringar.</p>{!team&&stats.yearTargetSource==='months'&&<p>Årsmålet är summan av tolv satta månadsmål.</p>}{!team&&stats.yearTarget===null&&<p>{stats.configuredMonths} av tolv månadsmål finns. Ange ett årsmål under Mål & inställningar.</p>}</details>
  </>}
 </div>;
}
