'use client';
import {ArrowRight,UserRound,Users,Target,TrendingUp,Kanban,ClipboardList,CalendarDays,HeartHandshake} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Progress} from '@/components/ui/progress';import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {type State,type Task,PIPELINE,day,concerns} from '@/lib/crm';import {personalOwner,salesMetrics} from '@/lib/sales-dashboard';import {money,displayDate} from './business-ui';import {TeamDashboard} from './team-dashboard';
export function SalesDashboard({st,mode,month,onMonth,onMode,onView,onCustomer,onTask}:{st:State;mode:'personal'|'team';month:string;onMonth:(v:string)=>void;onMode:(v:'personal'|'team')=>void;onView:(v:string,owner:string)=>void;onCustomer:(id:string)=>void;onTask:(t:Task)=>void}){
 const personal=personalOwner(st),team=mode==='team',canTeam=st.viewer?.role==='admin',owner=team?'all':personal,stats=salesMetrics(st,month,owner),name=st.viewer?.name||'Mitt konto',year=month.slice(0,4),today=day(),risk=stats.customers.filter(c=>concerns(c,day(),st).length),due=stats.tasks.filter(t=>t.due<=today),go=(v:string)=>onView(v,owner),monthLabel=new Date(month+'-01T12:00:00').toLocaleDateString('sv-SE',{month:'long',year:'numeric'});
 const attainment=(value:number,target:number|null)=>target!==null&&target>0?Math.round(value/target*100):null;
 const monthPct=attainment(stats.revenue,stats.target),yearPct=attainment(stats.yearRevenue,stats.yearTarget);
 return <div className="business-ui sales-dashboard"><div className="sales-scope"><Tabs value={mode} onValueChange={v=>onMode(v as 'personal'|'team')}><TabsList><TabsTrigger value="personal"><UserRound size={16}/>Mitt resultat</TabsTrigger>{canTeam&&<TabsTrigger value="team"><Users size={16}/>Teamets resultat</TabsTrigger>}</TabsList></Tabs><label>Rapportmånad<Input type="month" aria-label="Rapportmånad" value={month} onChange={e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value))onMonth(e.target.value)}}/></label></div>
 {!team&&!personal?<section className="panel padded personal-unmapped"><UserRound size={30}/><h2>{name}</h2><p>Ditt konto är inte kopplat till en egen säljarprofil. Därför visar vi inga personliga försäljningssiffror här.</p>{canTeam?<><p>Som administratör kan du öppna teamets resultat. Om du också säljer behöver kontot kopplas till din egen kundportfölj under Konton & roller.</p><div className="biz-buttons"><Button onClick={()=>onMode('team')}>Öppna teamets resultat</Button><Button variant="outline" onClick={()=>go('accounts')}>Konton & roller</Button></div></>:<p>Be Sebbe koppla ditt konto till rätt ansvarig säljare. Dina kunder, mål och aktiviteter visas därefter automatiskt.</p>}</section>:<>
 <div className={'sales-identity '+(team?'team':'personal')}><span className="sales-avatar">{team?<Users size={30}/>:name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div><span className="biz-kicker">{team?'HELA TEAMETS FÖRSÄLJNING':'DIN FÖRSÄLJNING'}</span><h2>{team?'Magnussons':name}</h2><p>{team?st.settings.owners.length+' ansvariga · gemensamma mål och resultat':'Kundportfölj: '+personal+' · dina mål, affärer och kundlöften'}</p></div><Button variant="outline" onClick={()=>go('today')}>Till {team?'teamets':'min'} arbetsdag <ArrowRight size={16}/></Button></div>
 <div className="sales-targets"><section className="sales-target month-target"><span>{team?'TEAMETS':'DIN'} MÅNAD · {monthLabel}</span><strong>{money(stats.revenue)}</strong><p>Fakturerad försäljning</p><div className="sales-target-line"><span>Mål</span><b>{stats.target===null?'Ej satt':money(stats.target)}</b></div><Progress value={monthPct===null?0:Math.min(100,monthPct)}/><div className="sales-target-line"><span>{monthPct===null?'Måluppfyllelse —':monthPct+' % av målet'}</span><b>{stats.target===null?'':stats.revenue>=stats.target?'Målet uppnått':money(stats.target-stats.revenue)+' kvar'}</b></div></section><section className="sales-target year-target"><span>{team?'TEAMETS':'DITT'} HELÅR · {year}</span><strong>{money(stats.yearRevenue)}</strong><p>Fakturerad försäljning under kalenderåret</p><div className="sales-target-line"><span>Årsmål</span><b>{stats.yearTarget===null?'Ej satt':money(stats.yearTarget)}</b></div><Progress value={yearPct===null?0:Math.min(100,yearPct)}/><div className="sales-target-line"><span>{yearPct===null?'Måluppfyllelse —':yearPct+' % av årsmålet'}</span><b>{stats.yearTarget===null?'':stats.yearRevenue>=stats.yearTarget?'Målet uppnått':money(stats.yearTarget-stats.yearRevenue)+' kvar'}</b></div>{!team&&stats.yearTargetSource==='months'&&<small>Årsmål summerat från 12 satta månadsmål.</small>}{!team&&stats.yearTarget===null&&<small>{stats.configuredMonths} av 12 månadsmål satta. Ett eget årsmål kan anges under Mål & inställningar.</small>}</section></div>
 <p className="sales-data-note">Försäljningen bygger på registrerade fakturor. {team?'Företagets mål anges separat från säljarnas mål.':'Här räknas enbart order där du är ansvarig.'}</p>
 <div className="daily-metrics sales-metrics"><button onClick={()=>go('orders')}><TrendingUp/><b>{stats.margin===null?'—':stats.margin.toLocaleString('sv-SE',{maximumFractionDigits:1})+' %'}</b><span>Bruttomarginal · {monthLabel}</span><small>{stats.known.length} av {stats.invoices.length} fakturor har kostnad. {stats.profit===null?'Bruttovinst saknas.':(stats.known.length<stats.invoices.length?'Känd':'Total')+' bruttovinst '+money(stats.profit)+'.'}</small></button><button onClick={()=>go('deals')}><Kanban/><b>{money(stats.pipeline)}</b><span>{stats.open.length} öppna affärer just nu</span><small>Oviktat ordervärde.{stats.unpriced?' '+stats.unpriced+' affärer saknar värde.':''}</small></button><button onClick={()=>go('prospects')}><Target/><b>{stats.qualified}</b><span>Kvalificerade prospekt · {monthLabel}</span><small>{team?'Första bekräftade behovet.':stats.qualifiedTarget===null?'Kvalificeringsmål saknas.':'Mål '+stats.qualifiedTarget+' kvalificerade.'} {stats.repeat} fakturerade återköpsorder.</small></button><button onClick={()=>go('today')}><ClipboardList/><b>{due.length}</b><span>Aktiviteter idag eller försenade</span><small>{risk.length} kunder behöver kontakt.</small></button></div>
 <section className="panel"><div className="panel-head"><h2>{team?'Teamets affärsläge':'Mina affärer – steg för steg'}</h2><Button size="sm" variant="outline" onClick={()=>go('deals')}>Öppna affärstavlan</Button></div><div className="pipeline-summary">{PIPELINE.map((p,i)=>{const list=stats.open.filter(d=>d.stage===p.id);return <button key={p.id} data-stage={p.id} onClick={()=>go('deals')}><span className="stage-number">0{i+1}</span><b>{p.short}</b><strong>{list.length}</strong><small>{money(list.reduce((n,d)=>n+(d.value||0),0))}</small><div className="summary-bar" style={{height:Math.max(5,Math.min(45,list.length*16))}}/></button>})}</div></section>{team&&<TeamDashboard st={st} month={month} onCustomer={onCustomer}/>}</>}
 </div>
}
