'use client';
import {useEffect,useState} from 'react';import {toast} from 'sonner';import {UserRound,Users,ShieldCheck} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Input} from '@/components/ui/input';import {Button} from '@/components/ui/button';import {Checkbox} from '@/components/ui/checkbox';import {type State} from '@/lib/crm';import {BusinessField as F,Pick} from './business-ui';
type Account={email:string;name:string;role:'admin'|'seller'|'reader'|'print'|'warehouse'|'production';owner:string;active:boolean;connected?:number};
type Profile='manager'|Account['role'];
const profileOf=(a:Account):Profile=>a.role==='admin'&&a.owner?'manager':a.role;
const roleLabel=(a:Account)=>({manager:'Ledning & säljare',admin:'Administratör',seller:'Säljare',reader:'Läsare',print:'Tryck',warehouse:'Lager',production:'Tryck & leverans'})[profileOf(a)];
export function TeamAccounts({st,refresh}:{st:State;refresh:()=>Promise<void>}){
 const [accounts,setAccounts]=useState<Account[]>([]),[edit,setEdit]=useState<Account|null>(null),[profile,setProfile]=useState<Profile>('seller'),[existing,setExisting]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 async function load(){try{const r=await fetch('/api/crm/members'),data:any=await r.json();if(!r.ok)throw Error(data.error);setAccounts(data.map((a:any)=>({...a,active:!!a.active})));setLoaded(true);setError('')}catch(e){setError((e as Error).message)}}useEffect(()=>{void load()},[]);
 function open(a:Account,isExisting=false){setEdit({...a});setExisting(isExisting);setProfile(profileOf(a));setError('')}
 async function save(){if(!edit||busy)return;if(['seller','manager'].includes(profile)&&!edit.owner){setError('Välj vilken säljarprofil kontot ska kopplas till.');return;}setBusy(true);try{const r=await fetch('/api/crm/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)}),data:any=await r.json();if(!r.ok)throw Error(data.error);setEdit(null);await load();await refresh();toast.success('Det personliga CRM-kontot är sparat.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="business-ui accounts-workspace"><div className="panel padded"><div className="biz-head"><div><span className="biz-kicker">PERSONLIG INLOGGNING</span><h2><Users size={22}/>Ett konto per person</h2><p>Inloggningsadressen identifierar personen. Säljarprofilen kopplar kontot till rätt kunder, affärer, mål och aktiviteter.</p></div><Button variant="outline" onClick={()=>open({email:'',name:'',role:'seller',owner:'',active:true})}>Förbered nytt konto</Button></div><div className="account-role-guide"><div><UserRound/><b>Säljare</b><p>Öppnar Min dashboard med sin egen försäljning och Min dag med sina aktiviteter.</p></div><div><ShieldCheck/><b>Ledning & säljare</b><p>För Sebbe och Pelle: personlig dashboard, teamets dashboard och full CRM-administration.</p></div><div><Users/><b>Tryck & lager</b><p>Öppnar avdelningens arbetskö med order, underlag och deadlines.</p></div></div><p className="biz-hint">Personliga vyer väljer rätt urval. Säljteamets kundregister är gemensamt; detta spärrar inte säljare från varandras kunduppgifter. Egna utkast och personlig Outlook-korrespondens har separat åtkomst.</p></div>
 <section className="panel padded"><h2>Säljarprofiler och kontokoppling</h2><p className="biz-hint">En säljarprofil är inte ett inloggningskonto. Här syns vilka kopplingar som är klara.</p>{loaded?<div className="account-roster">{st.settings.owners.map(owner=>{const a=accounts.find(a=>a.owner===owner&&a.active);return <article key={owner}><span className="account-avatar">{owner.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><h3>{owner}</h3><p>{a?roleLabel(a):'Personligt konto saknas'}</p><small>{a?.email||'Inloggningsadress behöver anges'}</small><span className={'pill '+(a?.connected?'green':'amber')}>{a?a.connected?'Har loggat in':'Inväntar första inloggning':'Säljarprofil utan konto'}</span><Button variant="outline" onClick={()=>a?open(a,true):open({name:owner,email:'',role:owner==='Pelle Peolin'?'admin':'seller',owner,active:true})}>{a?'Ändra koppling':'Förbered konto'}</Button></article>})}</div>:<p>Hämtar kontokopplingar…</p>}</section>
 <section className="panel padded"><h2>Registrerade CRM-konton</h2>{accounts.map(a=><div className="biz-repeat" key={a.email}><div><b>{a.name}</b><small>{a.email}</small><small>{roleLabel(a)} · {a.active?'Aktivt':'Inaktiverat'}{a.owner?' · Kundportfölj: '+a.owner:' · Ingen personlig säljarprofil'}</small></div><Button variant="outline" size="sm" onClick={()=>open(a,true)}>Ändra</Button></div>)}<p className="biz-hint">Att spara ett CRM-konto skickar ingen inbjudan. Tillgång till sidan tilldelas separat när ni är redo att släppa in personen.</p></section>
 <Sheet open={!!edit} onOpenChange={v=>{if(!v&&!busy)setEdit(null)}}><SheetContent className="crm-sheet"><SheetHeader><SheetTitle>{existing?'Ändra personligt konto':'Förbered personligt konto'}</SheetTitle><SheetDescription>Koppla personens inloggning till rätt roll och säljarprofil.</SheetDescription></SheetHeader>{edit&&<div className="sheet-body business-ui account-editor"><fieldset disabled={busy}><div className="biz-grid"><F label="Namn"><Input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></F><F label="Personlig inloggningsadress"><Input type="email" disabled={existing} value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})} placeholder="förnamn.efternamn@magnussonsreklam.se"/></F><F label="Roll och arbetsvy"><Pick label="Roll och arbetsvy" value={profile} onChange={v=>{const p=v as Profile;setProfile(p);setEdit({...edit,role:p==='manager'?'admin':p,owner:['manager','seller'].includes(p)?edit.owner:''})}} items={[{id:'seller',label:'Säljare – personlig dashboard'},{id:'manager',label:'Ledning & säljare – egen + team'},{id:'admin',label:'Administratör – utan egen portfölj'},{id:'reader',label:'Läsare'},{id:'production',label:'Tryck & leverans – gemensam arbetsvy'},{id:'print',label:'Tryck'},{id:'warehouse',label:'Lager'}]}/></F>{['manager','seller','reader'].includes(profile)&&<F label="Kopplad säljarprofil"><Pick label="Koppla konto till säljare" value={edit.owner} onChange={v=>setEdit({...edit,owner:v})} items={[{id:'',label:'Välj säljarprofil'},...st.settings.owners.map(o=>({id:o,label:o}))]}/></F>}</div><label className="check-field"><Checkbox checked={edit.active} onCheckedChange={v=>setEdit({...edit,active:v===true})}/>Kontot är aktivt</label><div className="biz-callout"><b>Så öppnas kontot</b><p>{profile==='manager'?'Egen försäljning visas först. Personen kan växla till hela teamet och administrera CRM-systemet.':profile==='seller'?'Egna mål, egen försäljning och egna aktiviteter visas först.':profile==='admin'?'Personen administrerar systemet och kan öppna teamets dashboard. Inga personliga säljsiffror visas utan säljarprofil.':profile==='production'?'Personen öppnar Min produktion med eget arbete och gemensam kö. Kan registrera varor, tryck och utleverans.':profile==='print'||profile==='warehouse'?'Personen öppnar avdelningens arbetskö.':'Kontot får läsbehörighet.'}</p></div><div className="biz-buttons"><Button disabled={!edit.email.trim()||!edit.name.trim()} onClick={save}>Spara CRM-konto</Button><Button variant="ghost" onClick={()=>setEdit(null)}>Stäng</Button></div></fieldset>{error&&<p className="error" role="alert">{error}</p>}</div>}</SheetContent></Sheet>{error&&!edit&&<p className="error" role="alert">{error}</p>}
 </section>
}
