'use client';
import { useState } from 'react';
import { Target } from 'lucide-react';
import { Button } from '@/components/ui/button';import { Input } from '@/components/ui/input';import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import {teamSalesRows} from '@/lib/sales-dashboard';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import { type State } from '@/lib/crm';
import { BusinessField as F,money,type SaveAction } from './business-ui';
export function TeamDashboard({st,month,onCustomer}:{st:State;month:string;onCustomer:(id:string)=>void}){
 const [sort,setSort]=useState<'goal'|'revenue'|'qualified'>('goal'),[ranked,setRanked]=useState(false);
 const rows=teamSalesRows(st,month).sort((a,b)=>sort==='revenue'?b.revenue-a.revenue:sort==='qualified'?b.qualified-a.qualified:(b.attainment??-1)-(a.attainment??-1));
 const watched=st.customers.filter(c=>c.status!=='prospect'&&c.status!=='closed'&&(!c.plan.nextAction||!c.nextReview));
 const score=(row:typeof rows[number])=>sort==='goal'?row.attainment:sort==='revenue'?row.revenue:row.qualified;
 const place=(row:typeof rows[number])=>{const value=score(row);return value===null?'—':1+rows.filter(other=>{const otherValue=score(other);return otherValue!==null&&otherValue>value}).length};
 return <section className="business-ui team-score panel result-team">
  <div className="result-panel-heading"><div><span className="result-kicker">GEMENSAM UPPFÖLJNING</span><h2>Teamets resultat</h2><p>Fakturerat och första kvalificeringar · {month}</p></div><label className="result-rank-toggle"><Switch checked={ranked} onCheckedChange={setRanked} aria-label="Visa placeringar"/>Visa placeringar</label></div>
  <div className="result-team-sort" aria-label="Sortera teamets resultat">{([{id:'goal',label:'Mot mål'},{id:'revenue',label:'Försäljning'},{id:'qualified',label:'Prospects'}] as const).map(item=><Button key={item.id} size="sm" variant={sort===item.id?'default':'ghost'} aria-pressed={sort===item.id} onClick={()=>setSort(item.id)}>{item.label}</Button>)}</div>
  <div className="result-team-list">{rows.map(row=><article key={row.owner}>
   {ranked&&<span className="result-rank">{place(row)}</span>}<span className="result-avatar">{row.owner.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><div className="result-seller"><b>{row.owner}</b><span>{money(row.revenue)} <small>av {row.goal?.revenue==null?'mål ej satt':money(row.goal.revenue)}</small></span><Progress aria-label={row.owner+'s måluppfyllelse'} value={Math.min(100,(row.attainment??0)*100)}/></div><div className="result-team-percent"><b>{row.attainment===null?'—':Math.round(row.attainment*100)+' %'}</b><small>av målet</small></div><div className="result-team-prospects"><b>{row.qualified}</b><small>kvalificerade</small></div>
  </article>)}</div>
  <details className="result-team-details"><summary>Visa marginal och fler mått</summary><Table><TableHeader><TableRow>{['Ansvarig','Marginal','Kostnadsunderlag','Bruttovinst / mål','Kvalificerade / mål','Återköpsorder','Försenade aktiviteter'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.owner}><TableCell>{row.owner}</TableCell><TableCell>{row.margin===null?'—':row.margin.toLocaleString('sv-SE',{maximumFractionDigits:1})+' %'}</TableCell><TableCell>{row.known} / {row.invoices} fakturor</TableCell><TableCell>{money(row.profit)}<small>{money(row.goal?.grossProfit)}</small></TableCell><TableCell>{row.qualified} / {row.goal?.qualified??'—'}</TableCell><TableCell>{row.repeat}</TableCell><TableCell>{row.late}</TableCell></TableRow>)}</TableBody></Table></details>
  <p className="result-chart-note">Jämför måluppfyllelse när kundportföljerna skiljer sig. Saknade mål ger ingen placering i jämförelsen mot mål. Samma resultatregler som i Mitt resultat används.</p>
  <div className="team-care"><b>{watched.length} befintliga kunder saknar fullständig kundplan</b>{watched.slice(0,4).map(customer=><Button size="sm" key={customer.id} variant="outline" onClick={()=>onCustomer(customer.id)}>{customer.name.replace(' · exempel','')}</Button>)}</div>
 </section>;
}
export function SellerGoals({st,month,save,busy}:{st:State;month:string;save:SaveAction;busy:boolean}){const [draft,setDraft]=useState(st.settings.sellerGoals),[annual,setAnnual]=useState(st.settings.sellerAnnualGoals),[basis,setBasis]=useState(JSON.stringify([st.settings.sellerGoals,st.settings.sellerAnnualGoals]));const year=month.slice(0,4),changed=basis!==JSON.stringify([st.settings.sellerGoals,st.settings.sellerAnnualGoals]);return <section className="business-ui panel padded"><h2><Target size={20}/>Säljarmål · {month}</h2><p className="biz-hint">Lämna tomt när mål ännu inte är överenskommet. Personliga månads- och årsmål visas på säljarens dashboard. Teambudgeten anges separat.</p>{st.settings.owners.map(owner=><fieldset className="biz-group" key={owner}><legend>{owner}</legend><div className="biz-grid">{(['revenue','grossProfit','qualified'] as const).map((k,i)=><F key={k} label={['Försäljningsmål, kr','Bruttovinstmål, kr','Nya kvalificerade prospects'][i]}><Input type="number" min={0} step={k==='qualified'?1:'0.01'} value={draft[owner]?.[month]?.[k]??''} onChange={e=>setDraft({...draft,[owner]:{...draft[owner],[month]:{...(draft[owner]?.[month]||{revenue:null,grossProfit:null,qualified:null}),[k]:e.target.value===''?null:Number(e.target.value)}}})}/></F>)}<F label={'Personligt årsmål '+year+', kr'}><Input type="number" min={0} step="0.01" value={annual[owner]?.[year]??''} onChange={e=>{const values={...annual[owner]};if(e.target.value==='')delete values[year];else values[year]=Number(e.target.value);setAnnual({...annual,[owner]:values})}}/></F></div></fieldset>)}<p className="biz-hint">Lämna årsmålet tomt för att använda summan av tolv kompletta månadsmål.</p>{changed&&<div className="biz-callout">Målen har ändrats sedan du öppnade dem. Läs in aktuella mål innan du sparar.<Button variant="outline" onClick={()=>{setDraft(st.settings.sellerGoals);setAnnual(st.settings.sellerAnnualGoals);setBasis(JSON.stringify([st.settings.sellerGoals,st.settings.sellerAnnualGoals]))}}>Läs in aktuella mål</Button></div>}<Button disabled={busy||changed} onClick={async()=>{if(await save('settings',{...st.settings,sellerGoals:draft,sellerAnnualGoals:annual},false))setBasis(JSON.stringify([draft,annual]))}}>Spara säljarmål</Button></section>}
