'use client';
import { useState } from 'react';
import { Trophy,Target } from 'lucide-react';
import { Button } from '@/components/ui/button';import { Input } from '@/components/ui/input';import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import {swedishMonth} from '@/lib/sales-dashboard';
import { day,type State } from '@/lib/crm';
import { BusinessField as F,money,type SaveAction } from './business-ui';
export function TeamDashboard({st,month,onCustomer}:{st:State;month:string;onCustomer:(id:string)=>void}){
 const [sort,setSort]=useState<'goal'|'profit'|'qualified'>('goal');
 const rows=st.settings.owners.map(owner=>{const orders=st.orders.filter(o=>o.owner===owner&&o.invoiceDate.startsWith(month)&&o.invoiceValue!==null),known=orders.filter(o=>o.actualCost!==null);const revenue=orders.reduce((sum,o)=>sum+o.invoiceValue!,0),profit=known.reduce((sum,o)=>sum+o.invoiceValue!-o.actualCost!,0),qualified=st.customers.filter(c=>(c.prospecting.qualifiedOwner||c.owner)===owner&&swedishMonth(c.prospecting.qualifiedAt)===month).length,goal=st.settings.sellerGoals[owner]?.[month];const repeat=orders.filter(o=>st.deals.find(d=>d.id===o.dealId)?.type==='repeat').length;return {owner,revenue,profit:known.length?profit:null,coverage:known.length+'/'+orders.length,qualified,goal,attainment:goal?.revenue?revenue/goal.revenue:null,repeat,late:st.tasks.filter(t=>t.owner===owner&&!t.done&&t.due<day()).length}}).sort((a,b)=>sort==='profit'?(b.profit??-Infinity)-(a.profit??-Infinity):sort==='qualified'?b.qualified-a.qualified:(b.attainment??-1)-(a.attainment??-1));
 const watched=st.customers.filter(c=>c.status!=='prospect'&&c.status!=='closed'&&(!c.plan.nextAction||!c.nextReview));
 return <section className="business-ui team-score panel"><div className="panel-head"><div><span className="biz-kicker">GEMENSAM UPPFÖLJNING</span><h2><Trophy size={22}/>Teamets måltavla</h2><p>{month} · fakturerat resultat, manuellt registrerat</p></div><div className="biz-buttons">{([{id:'goal',label:'Mot mål'},{id:'profit',label:'Bruttovinst'},{id:'qualified',label:'Kvalificering'}] as const).map(s=><Button key={s.id} size="sm" variant={sort===s.id?'default':'outline'} onClick={()=>setSort(s.id)}>{s.label}</Button>)}</div></div><Table><TableHeader><TableRow>{['Ansvarig','Försäljning / mål','Måluppfyllelse','Bruttovinst / mål','Kostnadsunderlag','Kvalificerade / mål','Återköpsorder','Försenade aktiviteter'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.owner}><TableCell><b>{r.owner}</b></TableCell><TableCell>{money(r.revenue)}<small>{money(r.goal?.revenue)}</small></TableCell><TableCell><span className="score-pill">{r.attainment===null?(r.goal?.revenue==null?'Mål saknas':'—'):Math.round(r.attainment*100)+' %'}</span></TableCell><TableCell>{money(r.profit)}<small>{money(r.goal?.grossProfit)}</small></TableCell><TableCell>{r.coverage} fakturor</TableCell><TableCell>{r.qualified} / {r.goal?.qualified??'—'}</TableCell><TableCell>{r.repeat}</TableCell><TableCell className={r.late?'late':''}>{r.late}</TableCell></TableRow>)}</TableBody></Table><p className="biz-hint padded">Kvalificering räknas vid första bekräftade behovet och finns kvar när kunden köper. Äldre kvalificeringar utan datum ingår inte. Bruttovinst bygger på fakturor med registrerad kostnad. Jämför måluppfyllelse när kundportföljerna skiljer sig.</p><div className="team-care"><b>{watched.length} befintliga kunder saknar nästa kundavstämning eller aktivitet</b>{watched.slice(0,4).map(c=><Button size="sm" key={c.id} variant="outline" onClick={()=>onCustomer(c.id)}>{c.name.replace(' · exempel','')}</Button>)}</div></section>
}
export function SellerGoals({st,month,save,busy}:{st:State;month:string;save:SaveAction;busy:boolean}){const [draft,setDraft]=useState(st.settings.sellerGoals),[annual,setAnnual]=useState(st.settings.sellerAnnualGoals),[basis,setBasis]=useState(JSON.stringify([st.settings.sellerGoals,st.settings.sellerAnnualGoals]));const year=month.slice(0,4),changed=basis!==JSON.stringify([st.settings.sellerGoals,st.settings.sellerAnnualGoals]);return <section className="business-ui panel padded"><h2><Target size={20}/>Säljarmål · {month}</h2><p className="biz-hint">Lämna tomt när mål ännu inte är överenskommet. Personliga månads- och årsmål visas på säljarens dashboard. Teambudgeten anges separat.</p>{st.settings.owners.map(owner=><fieldset className="biz-group" key={owner}><legend>{owner}</legend><div className="biz-grid">{(['revenue','grossProfit','qualified'] as const).map((k,i)=><F key={k} label={['Försäljningsmål, kr','Bruttovinstmål, kr','Nya kvalificerade prospects'][i]}><Input type="number" min={0} step={k==='qualified'?1:'0.01'} value={draft[owner]?.[month]?.[k]??''} onChange={e=>setDraft({...draft,[owner]:{...draft[owner],[month]:{...(draft[owner]?.[month]||{revenue:null,grossProfit:null,qualified:null}),[k]:e.target.value===''?null:Number(e.target.value)}}})}/></F>)}<F label={'Personligt årsmål '+year+', kr'}><Input type="number" min={0} step="0.01" value={annual[owner]?.[year]??''} onChange={e=>{const values={...annual[owner]};if(e.target.value==='')delete values[year];else values[year]=Number(e.target.value);setAnnual({...annual,[owner]:values})}}/></F></div></fieldset>)}<p className="biz-hint">Lämna årsmålet tomt för att använda summan av tolv kompletta månadsmål.</p>{changed&&<div className="biz-callout">Målen har ändrats sedan du öppnade dem. Läs in aktuella mål innan du sparar.<Button variant="outline" onClick={()=>{setDraft(st.settings.sellerGoals);setAnnual(st.settings.sellerAnnualGoals);setBasis(JSON.stringify([st.settings.sellerGoals,st.settings.sellerAnnualGoals]))}}>Läs in aktuella mål</Button></div>}<Button disabled={busy||changed} onClick={async()=>{if(await save('settings',{...st.settings,sellerGoals:draft,sellerAnnualGoals:annual},false))setBasis(JSON.stringify([draft,annual]))}}>Spara säljarmål</Button></section>}
