'use client';
import {useEffect,useId,useRef,useState,type FocusEvent} from 'react';
import {restoreHandoverFocus} from './handover-focus';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {CATEGORIES,day,plusDays,type State} from '@/lib/crm';
import {recordBasis} from '@/lib/record-conflicts';
import {validDate} from '@/lib/business';
import {yearNeedEditContext,type YearNeedEditContext} from '@/lib/yearwheel-responsibility';
import {YearNeedDraftEnvelopeSchema,yearNeedDraftValues,createYearNeedDraftEnvelope,yearNeedDraftServerVersion,adoptYearNeedDraftContext,isYearNeedDraft,type YearNeedDraftEnvelope,type YearNeedDraftValues} from '@/lib/year-need-drafts';
import {BusinessField as F,Pick,displayDate} from './business-ui';
import {useDrafts,DraftStatus} from './draft-workspace';
import {YearNeedDraftPreview,YearNeedSnapshot,YearNeedContextSnapshot,needStatuses,needIntervals} from './year-need-draft-preview';

export type YearNeedDraftRequest={customerId:string;needId:string;draftId?:string};
export type YearNeedPublish=(data:unknown,onFailure:(status:number,message?:string)=>void)=>Promise<boolean>;
type Attempt={data:{customerId:string;need:YearNeedDraftValues;expectedContext:string;draft:{id:string;revision:number}}};
const title=(values:YearNeedDraftValues)=>('Årshjul · '+(values.title.trim()||'Påbörjat kundbehov')).slice(0,200);
const identity=(st:State)=>JSON.stringify([st.viewer?.id||'',st.viewer?.memberId||'',st.viewer?.role||'']);
function capture(st:State,request:YearNeedDraftRequest):YearNeedDraftEnvelope|null{
 if(request.draftId)return null;
 try{
  const customer=st.customers.find(c=>c.id===request.customerId),need=customer?.yearNeeds.find(n=>n.id===request.needId);
  if(!customer||request.needId&&!need)return null;
  const values:YearNeedDraftValues=need?yearNeedDraftValues(need):{id:'',title:'',category:'',due:plusDays(day(),60),leadDays:'30',owner:st.settings.sellerProfilesInitialized?'':customer.owner,ownerProfileId:'',responsibilityTransfers:[],intervalMonths:'0',notes:'',status:'planned',completedAt:'',dealId:''};
  return createYearNeedDraftEnvelope(st,request.customerId,values,crypto.randomUUID());
 }catch{return null;}
}

export function YearNeedEditor({st,request,busy,publish,refresh,onClose,returnFocus}:{st:State;request:YearNeedDraftRequest;busy:boolean;publish:YearNeedPublish;refresh:()=>Promise<State>;onClose:()=>void;returnFocus?:()=>HTMLElement|null}){
 const w=useDrafts(),enabled=['admin','seller'].includes(st.viewer?.role||''),profileDescriptionId=useId();
 const opener=useRef<HTMLElement|null>(typeof document==='undefined'?null:document.activeElement instanceof HTMLElement?document.activeElement:null);
 // Capture the whole CRM basis before the asynchronous private workspace load.
 const opening=useRef<YearNeedDraftEnvelope|null>(capture(st,request)),openingIdentity=useRef(identity(st));
 const initialized=useRef(false),lock=useRef(false),alive=useRef(true),ws=useRef(w),state=useRef(st),retryAttempt=useRef<Attempt|null>(null);
 const panel=useRef<HTMLDivElement>(null),status=useRef<HTMLDivElement>(null),footer=useRef<HTMLDivElement>(null),privateDetails=useRef<HTMLDivElement>(null),sharedDetails=useRef<HTMLDivElement>(null);
 const [activeId,setActiveId]=useState(request.draftId||''),[operation,setOperation]=useState(''),[failure,setFailure]=useState(''),[crmMessage,setCrmMessage]=useState(''),[choices,setChoices]=useState<string[]>([]),[retry,setRetry]=useState<Attempt|null>(null),[discard,setDiscard]=useState(false);
 const [fetched,setFetched]=useState<State|null>(null),[reviewedContext,setReviewedContext]=useState<YearNeedEditContext|null>(null),[sharedChoice,setSharedChoice]=useState(''),[privateChoice,setPrivateChoice]=useState('');
 const latest=fetched&&fetched.version>st.version&&identity(fetched)===identity(st)?fetched:st;ws.current=w;state.current=latest;
 const local=enabled?w.records.find(d=>d.id===activeId&&isYearNeedDraft(d.kind,d.context)):undefined;
 const parsed=local?YearNeedDraftEnvelopeSchema.safeParse(local.data):null;
 const envelope=parsed?.success&&parsed.data.draftId===local?.id&&parsed.data.customerId===request.customerId&&parsed.data.base.id===request.needId?parsed.data:undefined,values=envelope?.values;
 const context=yearNeedEditContext(latest,envelope?.customerId||request.customerId,envelope?.base.id||request.needId),basis=recordBasis(context);
 const missing=!!envelope&&(!context.customer||!!envelope.base.id&&!context.need),conflict=!!envelope&&envelope.expectedContext!==basis,privateConflict=local?.status==='conflict',locked=busy||!!operation;
 const server=privateConflict?yearNeedDraftServerVersion(local.server,activeId,request.customerId,request.needId):null;
 const choiceBasis=recordBasis({id:local?.id,generation:local?.generation,data:local?.data,server:local?.server}),sharedBasis=recordBasis({id:local?.id,generation:local?.generation,data:local?.data,basis,reviewedContext});
 const initializedProfiles=envelope?.context.initialized,activeProfiles=envelope?.context.profiles.filter(p=>p.active&&envelope.context.owners.includes(p.legacyOwnerName))||[];
 const selectedProfile=activeProfiles.find(p=>p.id===values?.ownerProfileId),actualProfile=latest.settings.sellerProfiles.find(p=>p.id===values?.ownerProfileId&&p.active&&latest.settings.owners.includes(p.legacyOwnerName)&&p.legacyOwnerName===values.owner);
 const responsibilityBlocked=!!envelope&&!envelope.base.id&&!!initializedProfiles&&!actualProfile;
 const usableDue=!!values?.due&&validDate.safeParse(values.due).success;
 const lead=values&&/^\d+$/.test(values.leadDays)&&Number(values.leadDays)<=730?Number(values.leadDays):null;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 useEffect(()=>{retryAttempt.current=null;setRetry(null);setSharedChoice('');setReviewedContext(null);setDiscard(false)},[local?.generation]);
 useEffect(()=>setPrivateChoice(''),[choiceBasis]);
 useEffect(()=>setSharedChoice(''),[sharedBasis]);
 useEffect(()=>{
  const node=panel.current,actions=footer.current,banner=status.current;if(!node||!actions||!banner)return;
  const measure=()=>{const height=actions.getBoundingClientRect().height,top=banner.getBoundingClientRect().height;node.style.setProperty('--yearwheel-footer-height',height+'px');node.dataset.draftFlow=height+top>Math.min(window.innerHeight,node.getBoundingClientRect().height)/2?'true':'false'};
  measure();const observer=typeof ResizeObserver==='undefined'?null:new ResizeObserver(measure);observer?.observe(actions);observer?.observe(banner);window.addEventListener('resize',measure);
  return()=>{observer?.disconnect();window.removeEventListener('resize',measure);node.style.removeProperty('--yearwheel-footer-height');delete node.dataset.draftFlow};
 },[enabled]);
 function currentEnvelope(){const d=ws.current.get(activeId);if(!d||!isYearNeedDraft(d.kind,d.context))return null;const e=YearNeedDraftEnvelopeSchema.safeParse(d.data);return e.success&&e.data.draftId===d.id&&e.data.customerId===request.customerId&&e.data.base.id===request.needId?{record:d,envelope:e.data}:null}
 function clearAttempt(){retryAttempt.current=null;setRetry(null)}
 function reveal(node:HTMLElement|null){if(!node?.isConnected)return;node.focus({preventScroll:true});node.scrollIntoView({block:'start',behavior:'instant'})}
 function notice(message:string){if(!alive.current)return;setFailure(message);requestAnimationFrame(()=>{if(alive.current)reveal(status.current)})}
 function create(){
  if(lock.current||busy||!enabled||!ws.current.ready)return;
  if(!opening.current||openingIdentity.current!==identity(state.current)){notice('Kunden, behovet eller kontots ursprungliga underlag kunde inte läsas. Inget utkast har skapats.');return}
  const id=crypto.randomUUID(),e={...structuredClone(opening.current),draftId:id};
  const created=ws.current.create('form','year_need',e,title(e.values),id);if(created){setChoices([]);setActiveId(created)}else notice('Ditt privata utkast kunde inte öppnas. Försök hämta utkasten igen.');
 }
 async function resume(id:string){if(lock.current||busy||!enabled)return;lock.current=true;setOperation('open');setActiveId(id);setChoices([]);try{await ws.current.reconcile(id);if(alive.current&&!ws.current.get(id))setFailure('Det valda utkastet saknas eller är avslutat. Inget annat utkast har öppnats.')}finally{lock.current=false;if(alive.current)setOperation('')}}
 useEffect(()=>{
  if(initialized.current||!w.ready||!enabled||busy)return;initialized.current=true;
  if(request.draftId){void resume(request.draftId);return}
  const existing=w.records.filter(d=>{if(!isYearNeedDraft(d.kind,d.context))return false;const e=YearNeedDraftEnvelopeSchema.safeParse(d.data);return e.success&&e.data.draftId===d.id&&e.data.customerId===request.customerId&&e.data.base.id===request.needId});
  if(existing.length){setChoices(existing.map(d=>d.id));return}create();
 },[w.ready,enabled,busy,request]);
 function update<K extends keyof YearNeedDraftValues>(key:K,value:YearNeedDraftValues[K]){
  if(locked||lock.current||!enabled)return;const saved=currentEnvelope();if(!saved||saved.record.status==='conflict')return;
  const next={...saved.envelope.values,[key]:value};ws.current.update(activeId,{...saved.envelope,values:next},title(next));clearAttempt();setFailure('');setCrmMessage('');setReviewedContext(null);setSharedChoice('');
 }
 async function copy(){const d=ws.current.get(activeId);if(!d)return;try{await navigator.clipboard.writeText(JSON.stringify(d.data,null,2));setFailure('Hela ditt öppna underlag är kopierat.')}catch{setFailure('Kunde inte kopiera. Markera texten under hela det bevarade underlaget och kopiera den.')}}
 async function close(){if(lock.current||busy)return;if(!enabled||!activeId){onClose();return}lock.current=true;setOperation('close');setFailure('');try{if(!await ws.current.flush(activeId)){notice('Utkastet kunde inte sparas privat. Dina uppgifter finns kvar här. Försök igen eller behåll dem uttryckligen på denna enhet.');return}if(alive.current)onClose()}finally{lock.current=false;if(alive.current)setOperation('')}}
 function closeLocally(){if(lock.current||busy||!enabled)return;if(!ws.current.hasLocalCopy(activeId)){notice('En oförändrad lokal reservkopia kunde inte återläsas. Panelen är kvar. Kopiera underlaget innan du lämnar sidan.');return}onClose()}
 async function fetchCurrent(){
  if(lock.current||busy||!enabled)return;lock.current=true;setOperation('refresh');setFailure('');const started=identity(state.current);
  try{const fresh=await refresh();if(!alive.current)return;if(identity(fresh)!==started){notice('Kontot eller arbetsytan ändrades. Dina ursprungliga uppgifter har inte flyttats till ett annat konto.');return}setFetched(structuredClone(fresh));setReviewedContext(null);setSharedChoice('');setFailure('Aktuella CRM-uppgifter är hämtade. Ditt privata utkast och dess tidigare underlag är oförändrade tills du uttryckligen granskar och väljer det nya underlaget.')}catch(e){notice((e as Error).message||'Aktuella uppgifter kunde inte hämtas. Ditt privata utkast finns kvar.')}finally{lock.current=false;if(alive.current)setOperation('')}
 }
 async function submit(){
  if(lock.current||busy||!enabled||!envelope||!retryAttempt.current&&(conflict||missing||privateConflict||responsibilityBlocked))return;
  lock.current=true;setOperation('publish');setFailure('');setCrmMessage('');
  try{
   let attempt=retryAttempt.current;
   if(!attempt){
    if(!await ws.current.reconcile(activeId)){notice('Det privata utkastet behöver granskas. Dina öppna uppgifter finns kvar.');return}
    const reference=await ws.current.flush(activeId);if(!alive.current)return;if(!reference){notice('Utkastet kunde inte sparas privat. Behov och påminnelse har inte ändrats av detta försök.');return}
    const saved=currentEnvelope();if(!saved||saved.record.status!=='saved'||saved.record.revision!==reference.revision){notice('Utkastet hann ändras. Kontrollera den sparade versionen.');return}
    const currentContext=yearNeedEditContext(state.current,saved.envelope.customerId,saved.envelope.base.id);
    if(recordBasis(currentContext)!==saved.envelope.expectedContext||!currentContext.customer||saved.envelope.base.id&&!currentContext.need){notice('Kunden, behovet eller ansvarskopplingen har ändrats. Granska det aktuella underlaget först.');return}
    attempt={data:{customerId:saved.envelope.customerId,need:structuredClone(saved.envelope.values),expectedContext:saved.envelope.expectedContext,draft:reference}};retryAttempt.current=attempt;setRetry(attempt);
   }
   let code=0;
   const ok=await publish(attempt.data,(status,message)=>{code=status;if(alive.current)setCrmMessage(message||'Ingen bekräftad sparning av behov och påminnelse. Dina uppgifter finns kvar.')});
   if(!alive.current)return;
   if(ok){ws.current.consume(activeId);clearAttempt();onClose();return}
   if(code>0&&code<500){clearAttempt();if(code===409)await ws.current.reconcile(activeId)}
   if(!code||code>=500)setCrmMessage('Sparningen av behov och påminnelse kunde inte bekräftas. Den kan redan ha lyckats. Försök samma sparning igen; uppgifterna och begäran behålls.');
  }finally{lock.current=false;if(alive.current)setOperation('')}
 }
 function choosePrivate(useServer:boolean){
  if(locked||lock.current||privateChoice!==choiceBasis)return;const saved=currentEnvelope();if(!saved||saved.record.status!=='conflict'||recordBasis({id:saved.record.id,generation:saved.record.generation,data:saved.record.data,server:saved.record.server})!==choiceBasis)return;
  const version=yearNeedDraftServerVersion(saved.record.server,activeId,request.customerId,request.needId);
  if(saved.record.server&&!version||version?.archived||useServer&&!version){notice('Den privata serverversionen är inte ett giltigt aktivt utkast. Dina uppgifter finns kvar för kopiering.');return}
  ws.current.resolve(activeId,useServer);clearAttempt();setFailure(useServer?'Den visade serverversionen är vald. CRM är oförändrat.':'Dina öppna uppgifter är valda för en ny privat sparversion. CRM är oförändrat.');setPrivateChoice('');
 }
 function adoptShared(){
  if(locked||lock.current||sharedChoice!==sharedBasis||!reviewedContext)return;const saved=currentEnvelope(),actual=yearNeedEditContext(state.current,request.customerId,request.needId);
  if(!saved||saved.record.status==='conflict'||recordBasis(actual)!==recordBasis(reviewedContext)||recordBasis({id:saved.record.id,generation:saved.record.generation,data:saved.record.data,basis:recordBasis(actual),reviewedContext})!==sharedBasis){notice('Underlaget hann ändras. Granska det aktuella behovet igen.');return}
  try{ws.current.update(activeId,adoptYearNeedDraftContext(saved.envelope,state.current));clearAttempt();setReviewedContext(null);setSharedChoice('');setFailure('Det granskade underlaget används. Din behovstext och dina innehållsfält bevaras privat. Registrerat ansvar, historik och affärskoppling följer det granskade behovet. CRM är oförändrat.')}catch(e){notice((e as Error).message||'Underlaget kunde inte användas. Dina uppgifter finns kvar.')}
 }
 async function remove(){if(lock.current||busy||!enabled)return;lock.current=true;setOperation('archive');try{if(await ws.current.archive(activeId)){if(alive.current)onClose()}else notice('Utkastet kunde inte tas bort. Dina uppgifter finns kvar.')}finally{lock.current=false;if(alive.current)setOperation('')}}
 function focusIn(e:FocusEvent<HTMLDivElement>){const target=e.target as HTMLElement;requestAnimationFrame(()=>{const scroller=panel.current;if(!alive.current||document.activeElement!==target||!scroller||!target.isConnected||!scroller.contains(target))return;const p=scroller.getBoundingClientRect(),top=status.current?.getBoundingClientRect(),bottom=footer.current?.getBoundingClientRect(),r=target.getBoundingClientRect();const low=Math.max(p.top+8,top&&getComputedStyle(status.current!).position==='sticky'?top.bottom+8:p.top+8),high=Math.min(p.bottom-8,bottom&&getComputedStyle(footer.current!).position==='sticky'?bottom.top-8:p.bottom-8);if(high<=low)return;if(r.top<low)scroller.scrollTop-=low-r.top;else if(r.bottom>high)scroller.scrollTop+=r.bottom-high})}
 const statusText=!w.ready?w.error?'Ditt privata utkast kunde inte hämtas':'Hämtar ditt privata utkast…':!local?'Välj eller öppna ett privat utkast':!envelope?'Det bevarade underlaget kunde inte läsas':local.status==='saved'?'Privat utkast sparat':local.status==='saving'?'Sparar privat utkast…':local.status==='pending'?'Privata ändringar väntar på sparning':privateConflict?'Granska privata utkastversioner':'Det privata utkastet kunde inte sparas';
 return <Sheet open onOpenChange={v=>{if(!v&&!locked)void close()}}><SheetContent onCloseAutoFocus={e=>{if(returnFocus)restoreHandoverFocus(e,opener.current,returnFocus)}} ref={panel} className="crm-sheet event-draft-editor yearwheel-editor year-need-editor" showCloseButton={!locked} onFocusCapture={focusIn} onEscapeKeyDown={e=>{if(locked)e.preventDefault()}} onPointerDownOutside={e=>{if(locked)e.preventDefault()}}><SheetHeader><SheetTitle>Planera kundens behov</SheetTitle><SheetDescription>Privat utkast · bara synligt för dig. Dina ändringar blir synliga för teamet först när du väljer Spara behov och påminnelse.</SheetDescription></SheetHeader>
 {!enabled?<div className="sheet-body"><p role="alert">Privata behovsutkast kräver sälj- eller administratörsbehörighet.</p><Button onClick={onClose}>Stäng</Button></div>:<><div ref={status} tabIndex={-1} className="event-draft-status" aria-label="Sparstatus för kundens behov"><div role="status" aria-live="polite" aria-atomic="true"><strong>{statusText}</strong><span>{operation==='publish'?'Kontrollerar sparning av behov och påminnelse…':crmMessage||failure||'Utkastet ändrar inte teamets årshjul eller aktivitetslista.'}</span></div><div className="event-draft-actions">{!w.ready&&w.error&&<Button variant="outline" disabled={locked} onClick={w.retry}>Hämta utkast igen</Button>}{local?.status==='error'&&<Button variant="outline" disabled={locked} onClick={()=>void w.flush(activeId)}>Försök spara utkast</Button>}{privateConflict&&<Button variant="outline" disabled={locked} onClick={()=>reveal(privateDetails.current)}>Granska utkastversioner</Button>}{envelope&&!privateConflict&&!conflict&&!missing&&<Button variant="outline" disabled={locked} onClick={()=>void fetchCurrent()}>Hämta aktuellt CRM-underlag</Button>}{conflict&&!privateConflict&&<Button variant="outline" disabled={locked} onClick={()=>reveal(sharedDetails.current)}>Granska CRM-underlaget</Button>}</div></div>
 <div className="sheet-body business-ui">{!activeId&&choices.length>0&&<section className="event-draft-card"><h3>Fortsätt ett privat behovsutkast</h3><p>Välj rätt kund, behov och datum. Ett annat utkast öppnas aldrig automatiskt.</p>{choices.map(id=>{const d=w.records.find(d=>d.id===id);return d?<article className="event-draft-card" key={id}><h4>{d.title}</h4><YearNeedDraftPreview draft={d}/><Button disabled={locked} onClick={()=>void resume(id)}>Fortsätt detta utkast</Button></article>:null})}<Button variant="outline" disabled={locked} onClick={create}>Börja på ett nytt behovsutkast</Button></section>}
 {local&&<><DraftStatus id={activeId} allowActions={false}/><details className="event-draft-raw"><summary>Visa hela mitt bevarade underlag</summary><pre>{JSON.stringify(local.data,null,2)}</pre><Button variant="outline" disabled={locked} onClick={()=>void copy()}>Kopiera hela mitt underlag</Button></details>{!envelope&&<p role="alert">Formatet eller kund- och behovskopplingen stämmer inte. Uppgifterna har inte ersatts; kopiera underlaget för återhämtning.</p>}</>}
 {envelope&&<><div className="year-need-customer-context"><span>Kund</span><b>{envelope.context.customer?.name||'Kunden saknas i det ursprungliga underlaget'}</b><small>{envelope.base.id?'Ändring av befintligt behov':'Nytt behov'}</small><details><summary>Visa kund- och behovsreferens</summary><p>Kund: {envelope.customerId}</p><p>Behov: {envelope.base.id||'Nytt behov'}</p></details></div><fieldset disabled={locked||privateConflict} className="event-draft-fields"><F label="Behov *"><Input maxLength={200} value={values!.title} onChange={e=>update('title',e.target.value)} placeholder="Arbetskläder till höststarten"/></F><F label="Produktområde"><Pick label="Produktområde" value={values!.category} items={[{id:'',label:'Välj område'},...CATEGORIES.map(c=>({id:c,label:c}))]} onChange={v=>update('category',v)}/></F><div className="biz-grid"><F label="Behövs hos kunden *"><Input type="date" value={values!.due} onChange={e=>update('due',e.target.value)}/>{!usableDue&&values!.due&&<small>Bevarat angivet datum: {values!.due}</small>}</F><F label="Kontakta så många dagar före"><Input type="text" inputMode="numeric" maxLength={100} value={values!.leadDays} onChange={e=>update('leadDays',e.target.value)} aria-describedby={profileDescriptionId+'-lead'}/></F></div><p id={profileDescriptionId+'-lead'} className="biz-callout">{lead!==null&&usableDue?'Kontakta senast '+displayDate(plusDays(values!.due,-lead))+'. Räkna in offert, korrektur och leverantörens ledtid.':'Ange leveransdatum och ett helt antal dagar mellan 0 och 730 före sparning i CRM. Ofärdiga uppgifter kan sparas privat.'}</p><F label="Upprepning"><Pick label="Upprepning" value={values!.intervalMonths} items={needIntervals.some(i=>i.id===values!.intervalMonths)?needIntervals:[...needIntervals,{id:values!.intervalMonths,label:'Bevarat värde: '+(values!.intervalMonths||'tomt')}]} onChange={v=>update('intervalMonths',v)}/></F>
 {envelope.base.id?<div className="yearwheel-responsibility"><p><b>Behovsansvarig i utkastet:</b> {values!.owner||'Ansvar saknas'}</p><p className="biz-hint">Registrerat ansvar och historik behålls när du ändrar innehållet. Administratören granskar ansvarsbyte på behovskortet. Ändrat CRM-underlag jämförs separat.</p>{values!.ownerProfileId&&<details><summary>Visa registrerad ansvarskoppling</summary><p>Profil-ID: {values!.ownerProfileId}</p></details>}</div>:initializedProfiles?<><F label="Ansvarig för det nya behovet *"><Select value={values!.ownerProfileId||'_none'} onValueChange={v=>{const p=activeProfiles.find(p=>p.id===v),saved=currentEnvelope();if(!saved||locked||lock.current||!enabled||saved.record.status==='conflict')return;const next={...saved.envelope.values,ownerProfileId:p?.id||'',owner:p?.legacyOwnerName||''};ws.current.update(activeId,{...saved.envelope,values:next},title(next));clearAttempt();setFailure('');setReviewedContext(null);setSharedChoice('')}}><SelectTrigger className="yearwheel-profile-choice" aria-label="Ansvarig för behov" aria-describedby={profileDescriptionId}><SelectValue><span className="yearwheel-profile-label">{selectedProfile?.displayName||values!.owner||'Välj ansvarig'}</span></SelectValue></SelectTrigger><SelectContent className="yearwheel-responsibility-options"><SelectItem value="_none">Välj ansvarig</SelectItem>{activeProfiles.map(p=><SelectItem key={p.id} value={p.id}>{p.displayName+(p.displayName===p.legacyOwnerName?'':' · '+p.legacyOwnerName)}</SelectItem>)}</SelectContent></Select></F><p id={profileDescriptionId} className="biz-hint">{selectedProfile?<><b>Vald ansvarig:</b> {selectedProfile.displayName}. Ansvarskoppling: {selectedProfile.legacyOwnerName}.</>:'Välj en aktiv granskad säljarprofil innan du sparar behov och påminnelse. Ett ofärdigt val kan sparas privat.'}</p>{selectedProfile&&<details><summary>Visa vald profilreferens</summary><p>Profil-ID: {selectedProfile.id}</p></details>}{responsibilityBlocked&&<p className="biz-callout">Behovet saknar en giltig aktiv ansvarskoppling i aktuellt CRM. Granska ändrat underlag eller be administratören kontrollera Konton & roller.</p>}</>:<F label="Ansvarig"><Pick label="Ansvarig för behov" value={values!.owner} items={envelope.context.owners.map(o=>({id:o,label:o}))} onChange={v=>update('owner',v)}/></F>}
 <F label="Omfattning, anledning och förberedelser"><Textarea rows={4} maxLength={4000} value={values!.notes} onChange={e=>update('notes',e.target.value)}/></F><F label="Status"><Pick label="Behovsstatus" value={values!.status} items={needStatuses} onChange={v=>update('status',v as YearNeedDraftValues['status'])}/></F></fieldset>
 {privateConflict&&<section ref={privateDetails} tabIndex={-1} className="event-draft-card"><h3>En annan privat version finns</h3><p>Jämför hela underlaget innan du väljer. Behov och påminnelse i CRM ändras inte av valet.</p><div className="event-draft-comparison"><section><h4>Mitt öppna underlag</h4><YearNeedSnapshot values={values!}/><YearNeedContextSnapshot context={envelope.context}/></section><section><h4>Sparad privat serverversion</h4>{server?<><YearNeedDraftPreview draft={server}/>{server.archived&&<p>Serverutkastet är avslutat. Det betyder inte att behovet har sparats i CRM. Ditt öppna underlag finns kvar för kopiering.</p>}</>:<><p>{local.server?'Serverversionens format eller koppling kunde inte läsas.':'Ingen privat serverversion hittades.'}</p>{local.server&&<pre>{JSON.stringify(local.server.data,null,2)}</pre>}</>}</section></div>{!server?.archived&&(!local.server||server)&&<><label className="event-draft-choice"><Checkbox disabled={locked} checked={privateChoice===choiceBasis} onCheckedChange={v=>setPrivateChoice(v===true?choiceBasis:'')}/><span>Jag har jämfört de privata versionerna och vill välja underlag.</span></label><div className="event-draft-actions">{server&&<Button variant="outline" disabled={locked||privateChoice!==choiceBasis} onClick={()=>choosePrivate(true)}>Använd den visade serverversionen</Button>}<Button disabled={locked||privateChoice!==choiceBasis} onClick={()=>choosePrivate(false)}>Spara mina uppgifter som ny utkastversion</Button></div></>}</section>}
 {(conflict||missing)&&!privateConflict&&<section ref={sharedDetails} tabIndex={-1} className="event-draft-card"><h3>{missing?'Kunden eller behovet finns inte längre':'CRM-underlaget har ändrats'}</h3><p>Ditt privata underlag finns kvar. Dina innehållsfält bevaras när du uttryckligen använder granskat underlag. Ett befintligt behov får det registrerade ansvaret, historiken och affärskopplingen från den granskade versionen. För nya behov behålls ditt eget ansvarsval och måste fortfarande vara giltigt.</p><div className="event-draft-comparison"><section><h4>Ursprungligt CRM-underlag</h4><YearNeedContextSnapshot context={envelope.context}/><YearNeedSnapshot values={envelope.base}/></section><section><h4>Mina föreslagna uppgifter</h4><YearNeedSnapshot values={values!}/></section></div><Button variant="outline" disabled={locked} onClick={()=>void fetchCurrent()}>Hämta aktuellt CRM-underlag</Button>{!missing&&<><Button variant="outline" disabled={locked} onClick={()=>{setReviewedContext(structuredClone(context));setSharedChoice('')}}>Granska aktuellt CRM-underlag</Button>{reviewedContext&&recordBasis(reviewedContext)===basis&&<><h4>Aktuellt CRM-underlag</h4><YearNeedContextSnapshot context={reviewedContext}/>{reviewedContext.need&&<YearNeedSnapshot values={yearNeedDraftValues(reviewedContext.need)}/>}<label className="event-draft-choice"><Checkbox disabled={locked} checked={sharedChoice===sharedBasis} onCheckedChange={v=>setSharedChoice(v===true?sharedBasis:'')}/><span>Jag har jämfört mina innehållsfält, kunden och ansvarskopplingen med det aktuella underlaget.</span></label><Button disabled={locked||sharedChoice!==sharedBasis} onClick={adoptShared}>Använd aktuellt underlag och behåll mina uppgifter</Button></>}</>}</section>}
 <div className="event-draft-actions"><Button variant="ghost" disabled={locked||privateConflict} onClick={()=>setDiscard(true)}>Ta bort privat utkast</Button>{discard&&<><p>Detta tar bort det privata utkastet. Det ändrar inte behov eller påminnelse i CRM och återställer inte en tidigare obekräftad CRM-sparning.</p><Button variant="outline" disabled={locked||privateConflict} onClick={()=>void remove()}>Ja, ta bort utkast</Button><Button variant="ghost" disabled={locked} onClick={()=>setDiscard(false)}>Behåll utkast</Button></>}</div></>}
 {(local?.status==='error'||privateConflict||local&&!envelope)&&<section className="event-draft-card"><p>Du kan behålla en återläst lokal reservkopia. Den skyddar inte mot rensad enhetslagring och är ingen bekräftad serversparning.</p><Button variant="outline" disabled={locked} onClick={closeLocally}>Stäng och behåll på denna enhet</Button></section>}
 {(failure||crmMessage)&&<div className="event-draft-message" role="alert">{crmMessage||failure}</div>}
 <div ref={footer} className="event-draft-footer"><Button variant="outline" disabled={locked} onClick={()=>void close()}>Spara utkast & stäng</Button><Button disabled={locked||!envelope||!retry&&(conflict||missing||privateConflict||responsibilityBlocked)} onClick={()=>void submit()}>{operation==='publish'?'Sparar behov och påminnelse…':retry?'Försök samma CRM-sparning igen':'Spara behov och påminnelse'}</Button></div></div></>}
 </SheetContent></Sheet>;
}
