'use client';

import {useEffect,useId,useRef,useState} from 'react';
import {Plus,CalendarDays,ArrowUpRight,Check,ArrowRightLeft,Search} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {day,plusDays,type Customer,type State} from '@/lib/crm';
import {personalSellerId} from '@/lib/seller-profiles';
import {yearwheelResponsibleProfile,yearwheelOwnerLabel} from '@/lib/yearwheel-responsibility';
import {YearNeedDraftEnvelopeSchema,isYearNeedDraft} from '@/lib/year-need-drafts';
import {BusinessField as F,displayDate} from './business-ui';
import {useDrafts,DraftStatus} from './draft-workspace';
import {YearNeedEditor,type YearNeedDraftRequest} from './year-need-editor';
import {YearNeedDraftPreview} from './year-need-draft-preview';
import {YearwheelResponsibilityDialog,type YearwheelResponsibilitySave} from './yearwheel-responsibility-dialog';

type Props={st:State;customers:Customer[];space:string;save:YearwheelResponsibilitySave;busy:boolean;refresh:()=>Promise<State>;onCustomer:(id:string)=>void;compact?:boolean;resumeDraftId?:string;onResumeClosed?:()=>void};
export function YearWheel({st,customers,space,save,busy,refresh,onCustomer,compact=false,resumeDraftId,onResumeClosed}:Props){
 const w=useDrafts(),[request,setRequest]=useState<(YearNeedDraftRequest&{token:string})|null>(null),[chooseCustomer,setChooseCustomer]=useState(false),[customerChoice,setCustomerChoice]=useState('');
 const [year,setYear]=useState(day().slice(0,4)),[showAll,setShowAll]=useState(false),[scope,setScope]=useState<'mine'|'team'>('mine'),[search,setSearch]=useState(''),[transfer,setTransfer]=useState<{customerId:string;needId:string}|null>(null);
 const heading=useRef<HTMLHeadingElement>(null),customerDescriptionId=useId();
 const identity=JSON.stringify([space,st.viewer?.id||'',st.viewer?.memberId||'',st.viewer?.role||'']);
 const writable=['admin','seller'].includes(st.viewer?.role||''),admin=st.viewer?.role==='admin',initialized=st.settings.sellerProfilesInitialized,personal=personalSellerId(st);
 const drafts=writable?w.records.filter(d=>{if(!isYearNeedDraft(d.kind,d.context))return false;if(!compact)return true;const p=YearNeedDraftEnvelopeSchema.safeParse(d.data);return p.success&&customers.some(c=>c.id===p.data.customerId)}):[];
 function openEdit(customerId:string,needId:string){setRequest({customerId,needId,token:crypto.randomUUID()})}
 function openDraft(id:string){const d=w.get(id),p=d&&YearNeedDraftEnvelopeSchema.safeParse(d.data);setRequest({customerId:p&&p.success?p.data.customerId:'',needId:p&&p.success?p.data.base.id:'',draftId:id,token:crypto.randomUUID()})}
 function create(){if(compact&&customers.length===1){openEdit(customers[0].id,'');return}setCustomerChoice('');setChooseCustomer(true)}
 useEffect(()=>{if(resumeDraftId&&writable&&w.ready)openDraft(resumeDraftId)},[resumeDraftId,writable,w.ready]);
 const all=customers.flatMap(customer=>customer.yearNeeds.map(need=>({need,customer}))).filter(({need,customer})=>{
  const own=initialized?!!personal&&yearwheelResponsibleProfile(st,need)?.id===personal:!!personal&&need.owner===personal;
  return (compact||scope==='team'||own)&&(showAll||need.status==='planned')&&(compact||[customer.name,customer.contact,need.title,need.notes,yearwheelOwnerLabel(st,need)].join(' ').toLocaleLowerCase('sv').includes(search.toLocaleLowerCase('sv')));
 }).sort((a,b)=>a.need.due.localeCompare(b.need.due)||a.need.id.localeCompare(b.need.id));
 const list=compact?all:all.filter(({need})=>need.due.startsWith(year));
 const contactNow=list.filter(({need})=>need.status==='planned'&&plusDays(need.due,-need.leadDays)<=day()).length;
 function responsibilityText(need:Customer['yearNeeds'][number]){const profile=yearwheelResponsibleProfile(st,need);if(!initialized)return 'Äldre ansvar · säljarprofiler är inte granskade';if(!profile)return 'Ansvarskoppling behöver granskas';return (need.ownerProfileId?'Förankrat i säljarprofil':'Äldre ansvar · behöver förankras')+(profile.active?'':' · inaktiv profil');}
 return <section className={'business-ui yearwheel '+(compact?'biz-section':'')}>
  <div className="biz-head"><div><span className="biz-kicker">FRAMFÖRHÅLLNING</span><h2 className="yearwheel-heading" ref={heading} tabIndex={-1}><CalendarDays aria-hidden="true" size={22}/>{compact?'Kundens årshjul':scope==='mine'?'Mina behov':'Teamets behov'}</h2><p>Planera kontakten utifrån när kunden behöver leveransen.</p></div>{writable&&<Button onClick={create} disabled={!customers.length||busy}><Plus aria-hidden="true" size={16}/>Nytt behov</Button>}</div>
  {!compact&&<><div className="yearwheel-scope" aria-label="Urval av årshjulsbehov"><Button variant={scope==='mine'?'default':'outline'} aria-pressed={scope==='mine'} onClick={()=>setScope('mine')}>Mina behov</Button><Button variant={scope==='team'?'default':'outline'} aria-pressed={scope==='team'} onClick={()=>setScope('team')}>Teamets behov</Button></div><p className="biz-hint">{scope==='mine'?'Urvalet följer behovets ansvar, även när kundrelationen tillhör någon annan.':'Här visas teamets behov oavsett kundansvarig.'} Äldre behov följer sin registrerade ansvarskoppling tills den har granskats.</p>{scope==='mine'&&!personal&&<p className="biz-callout" role="status">Ditt konto saknar en granskad säljarprofil. Visa Teamets behov; administratören kan kontrollera kontokopplingen under Konton & roller.</p>}<div className="yearwheel-toolbar"><F label="Sök kund eller behov"><span className="yearwheel-search"><Search aria-hidden="true" size={16}/><Input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Kund, inköp eller förberedelser…" aria-label="Sök kund eller behov"/></span></F><F label="År"><Input type="number" min={2000} max={2100} value={year} onChange={event=>setYear(event.target.value)} aria-label="År för årshjul"/></F><Button variant="outline" aria-pressed={showAll} onClick={()=>setShowAll(!showAll)}>{showAll?'Visa planerade':'Visa även hanterade'}</Button></div><p className="yearwheel-contact" role="status"><b>{contactNow}</b> behov behöver kontakt nu i urvalet för {year}.</p><div className="year-months" aria-label={'Behov per månad '+year}>{Array.from({length:12},(_,index)=>{const month=year+'-'+String(index+1).padStart(2,'0'),items=list.filter(({need})=>need.due.startsWith(month));return <div key={month} className={month===day().slice(0,7)?'current':''}><span>{new Date(2026,index,1).toLocaleDateString('sv-SE',{month:'short'})}</span><b>{items.filter(({need})=>need.status==='planned').length}</b>{items.slice(0,2).map(({need,customer})=><div className="yearwheel-month-need" key={JSON.stringify([customer.id,need.id])}><p>{customer.name.replace(' · exempel','')}</p><small>{need.title}</small><button data-customer-id={customer.id} onClick={()=>onCustomer(customer.id)} aria-label={'Öppna kundkort för '+customer.name+' · '+need.title}>Öppna kundkort <ArrowUpRight aria-hidden="true" size={14}/></button></div>)}</div>;})}</div></>}
  {writable&&<section className="event-draft-list year-need-draft-list"><h3>Mina privata behovsutkast</h3><p>Bara synliga för dig. Dina utkast ändrar behov och påminnelser först när du sparar dem i CRM.</p>{!w.ready&&<DraftStatus id=""/>}{drafts.map(d=><article className="event-draft-card" key={d.id}><h4>{d.title}</h4><YearNeedDraftPreview draft={d}/><DraftStatus id={d.id} allowActions={false}/><Button variant="outline" disabled={busy} onClick={()=>openDraft(d.id)}>Fortsätt detta behovsutkast</Button></article>)}{w.ready&&!drafts.length&&<p>Inga privata behovsutkast just nu.</p>}</section>}
  <div className="need-list">{list.map(({need,customer})=><article key={JSON.stringify([customer.id,need.id])} className="need-card" data-customer-id={customer.id} data-need-id={need.id} data-due={need.status==='planned'&&plusDays(need.due,-need.leadDays)<=day()}><div className="biz-head"><div><span className="pill">{need.category||'Inköpsbehov'}</span><h3>{need.title}</h3>{!compact&&<div className="yearwheel-customer"><p>{customer.name.replace(' · exempel','')}</p><button className="text-link" data-customer-id={customer.id} onClick={()=>onCustomer(customer.id)} aria-label={'Öppna kundkort för '+customer.name}>Öppna kundkort <ArrowUpRight aria-hidden="true" size={14}/></button></div>}</div><span className="pill">{need.status==='planned'?'Planerat':need.status==='done'?'Hanterat':'Avslutat'}</span></div><div className="biz-grid"><div><small>Kontakta senast</small><b>{displayDate(plusDays(need.due,-need.leadDays))}</b></div><div><small>Kundens leveransbehov</small><b>{displayDate(need.due)}</b></div></div><div className="yearwheel-responsibility"><p><b>Behovsansvarig:</b> {yearwheelOwnerLabel(st,need)||'Ansvar saknas'}</p><p className="biz-hint">{responsibilityText(need)}</p>{admin&&initialized&&need.status==='planned'&&<Button variant="outline" onClick={()=>setTransfer({customerId:customer.id,needId:need.id})} disabled={busy}><ArrowRightLeft aria-hidden="true" size={16}/>{need.ownerProfileId?'Byt behovsansvar':'Förankra behovsansvar'}</Button>}</div>{initialized&&need.status==='planned'&&!need.dealId&&(!yearwheelResponsibleProfile(st,need)?.active||!st.settings.owners.includes(need.owner))&&<p className="biz-hint">Behovsansvaret behöver kopplas till en aktiv profil innan en affär skapas. Administratören granskar behovsansvaret.</p>}<p>{need.intervalMonths?`Upprepas var ${need.intervalMonths}:e månad`:'Engångsbehov'}</p>{need.notes&&<p className="whitespace-pre-wrap">{need.notes}</p>}{writable&&<div className="biz-buttons"><Button size="sm" variant="outline" onClick={()=>openEdit(customer.id,need.id)} disabled={busy}>Ändra behov</Button>{need.status==='planned'&&<><Button size="sm" variant="outline" disabled={busy||!!need.dealId||initialized&&(!yearwheelResponsibleProfile(st,need)?.active||!st.settings.owners.includes(need.owner))} onClick={()=>save('need_deal',{customerId:customer.id,id:need.id},false)}>{need.dealId?'Affär skapad':'Skapa affär'}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>save('complete_need',{customerId:customer.id,id:need.id},false)}><Check aria-hidden="true" size={14}/>{need.intervalMonths?'Hanterat – planera nästa':'Markera hanterat'}</Button></>}</div>}</article>)}</div>
  {!list.length&&<div className="biz-empty">{compact?'Inga planerade behov för kunden.':scope==='mine'?'Inga behov i ditt urval för '+year+'.':'Inga behov i teamets urval för '+year+'.'} {writable?'Lägg till nästa klädbeställning eller mässa.':'Välj ett annat år eller visa även hanterade behov.'}</div>}
  <Sheet open={chooseCustomer} onOpenChange={setChooseCustomer}><SheetContent className="crm-sheet year-need-customer-picker"><SheetHeader><SheetTitle>Vilken kund gäller behovet?</SheetTitle><SheetDescription>Välj kunden innan du börjar. Ditt privata utkast behåller denna kundkoppling.</SheetDescription></SheetHeader><div className="sheet-body business-ui"><F label="Kund"><Select value={customerChoice||'_none'} onValueChange={v=>setCustomerChoice(v==='_none'?'':v)}><SelectTrigger className="yearwheel-profile-choice" aria-label="Kund för nytt behov" aria-describedby={customerDescriptionId}><SelectValue><span className="yearwheel-profile-label">{customers.find(c=>c.id===customerChoice)?.name||'Välj kund'}</span></SelectValue></SelectTrigger><SelectContent className="yearwheel-responsibility-options"><SelectItem value="_none">Välj kund</SelectItem>{customers.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></F><p id={customerDescriptionId} className="biz-callout"><b>{customerChoice?'Vald kund:':'Kundval:'}</b> {customers.find(c=>c.id===customerChoice)?.name||'Välj kunden som behovet gäller.'}</p><Button disabled={busy||!customers.some(c=>c.id===customerChoice)} onClick={()=>{if(!customers.some(c=>c.id===customerChoice))return;setChooseCustomer(false);openEdit(customerChoice,'')}}>Börja planera kundens behov</Button></div></SheetContent></Sheet>
  {request&&<YearNeedEditor key={identity+request.token} st={st} request={request} busy={busy} refresh={refresh} publish={(data,onFailure)=>save('year_need',data,false,onFailure)} onClose={()=>{setRequest(null);onResumeClosed?.()}} returnFocus={()=>heading.current}/>}
  {transfer&&<YearwheelResponsibilityDialog key={identity+transfer.customerId+transfer.needId} st={st} space={space} customerId={transfer.customerId} needId={transfer.needId} save={save} busy={busy} refresh={refresh} onClose={()=>setTransfer(null)}/>}
 </section>;
}
