'use client';
import type {DraftRecord} from '@/lib/drafts';
import {YearwheelResponsibilityDraftEnvelopeSchema,yearwheelResponsibilityDraftSnapshot,yearwheelResponsibilityDraftContext,type YearwheelResponsibilityDraftValues} from '@/lib/yearwheel-responsibility-drafts';
import {displayDate} from './business-ui';

type Context=ReturnType<typeof yearwheelResponsibilityDraftContext>;
const profileName=(profile:{displayName:string;legacyOwnerName:string})=>profile.displayName+(profile.displayName===profile.legacyOwnerName?'':' · '+profile.legacyOwnerName);
export function YearwheelResponsibilityIntentSnapshot({values,context}:{values:YearwheelResponsibilityDraftValues;context:Context}){
 const target=context.profiles.find(p=>p.id===values.targetProfileId),selected=context.tasks.filter(task=>values.selectedTaskIds.includes(task.id)),unknown=values.selectedTaskIds.filter(id=>!context.tasks.some(task=>task.id===id));
 return <div className="event-draft-snapshot yearwheel-handover-snapshot"><dl><div><dt>Föreslagen ansvarig</dt><dd>{target?profileName(target):values.targetProfileId?'Den valda profilen finns inte i underlaget':'Inte vald'}</dd></div><div><dt>Angiven orsak</dt><dd className="whitespace-pre-wrap">{values.reason||'Inte angiven'}</dd></div><div><dt>Valda uppgifter</dt><dd>{values.selectedTaskIds.length} uppgifter</dd></div></dl>{selected.map(task=><article className="revision-card" key={task.id}><b>{task.title}</b><p>{displayDate(task.due)} · {task.owner} → {target?profileName(target):'inte vald'}</p></article>)}{!!unknown.length&&<p>Valda uppgifter utan motsvarande rad: {unknown.join(', ')}.</p>}<details><summary>Visa exakta föreslagna val</summary><pre>{JSON.stringify(values,null,2)}</pre></details></div>;
}
export function YearwheelResponsibilityContextSnapshot({context}:{context:Context}){
 const need=context.need,profile=context.profiles.find(p=>need?.ownerProfileId?p.id===need.ownerProfileId:p.legacyOwnerName===need?.owner);
 return <div className="event-draft-snapshot yearwheel-handover-snapshot"><dl><div><dt>Kund</dt><dd>{context.customer?.name||'Kunden saknas'}</dd></div><div><dt>Inköpsbehov</dt><dd>{need?.title||'Behovet saknas'}</dd></div><div><dt>Registrerat behovsansvar</dt><dd>{profile?profileName(profile):need?.owner||'Saknas'}</dd></div><div><dt>Behövs hos kunden</dt><dd>{displayDate(need?.due||'')}</dd></div><div><dt>Behovets status</dt><dd>{need?.status==='planned'?'Planerat':need?.status==='done'?'Hanterat':need?.status==='cancelled'?'Avslutat':'Saknas'}</dd></div><div><dt>Omfattning och förberedelser</dt><dd className="whitespace-pre-wrap">{need?.notes||'Ingen anteckning'}</dd></div><div><dt>Uppgifter i granskningsunderlaget</dt><dd>{context.tasks.length}</dd></div></dl>{context.tasks.map(task=><article className="revision-card" key={task.id}><b>{task.title}</b><p>{displayDate(task.due)} · {task.owner} · {task.done?'Avslutad':'Öppen'}</p><small>{task.kind}{task.dealId?' · affärs-/orderkopplad':''}</small></article>)}<details><summary>Visa hela kund-, behovs-, profil- och uppgiftsunderlaget</summary><pre>{JSON.stringify(context,null,2)}</pre></details></div>;
}
// Reading a preview never replaces a local version or adopts CRM data.
export function YearwheelResponsibilityDraftPreview({draft,summaryId,identityId}:{draft:Pick<DraftRecord,'id'|'data'|'updatedAt'>;summaryId?:string;identityId?:string}){
 const parsed=YearwheelResponsibilityDraftEnvelopeSchema.safeParse(draft.data),envelope=parsed.success&&parsed.data.draftId===draft.id?parsed.data:null;
 const snapshot=envelope?yearwheelResponsibilityDraftSnapshot(envelope.context):null,target=envelope?.context.profiles.find(p=>p.id===envelope.values.targetProfileId);
 return <div className="event-draft-preview yearwheel-handover-draft-preview"><p id={summaryId}>{envelope?(envelope.context.customer.name+' · '+envelope.context.need.title+' · '+(target?profileName(target):'ansvarig inte vald')+' · '+envelope.values.selectedTaskIds.length+' valda uppgifter'):'Utkastets format kunde inte läsas. Öppna för att kopiera det bevarade underlaget.'}</p>{envelope?.values.reason&&<p className="yearwheel-handover-reason-summary">{envelope.values.reason}</p>}<details><summary>Visa hela överlämningsutkastet</summary>{envelope&&<><YearwheelResponsibilityIntentSnapshot values={envelope.values} context={envelope.context}/><YearwheelResponsibilityContextSnapshot context={envelope.context}/>{snapshot?.blockedReason&&<p>{snapshot.blockedReason}</p>}</>}<dl id={identityId}><div><dt>Ändrat · originaltid</dt><dd>{draft.updatedAt}</dd></div><div><dt>Privat utkastreferens</dt><dd>{draft.id}</dd></div><div><dt>Kund och behov · referenser</dt><dd>{envelope?envelope.customerId+' · '+envelope.needId:'Kopplingen kunde inte läsas'}</dd></div></dl><details><summary>Visa hela det bevarade underlaget</summary><pre>{JSON.stringify(draft.data,null,2)}</pre></details></details></div>;
}
