'use client';
import { useState } from 'react';
import { Plus,CalendarDays,ArrowUpRight,Check } from 'lucide-react';
import { Input } from '@/components/ui/input';import { Textarea } from '@/components/ui/textarea';import { Button } from '@/components/ui/button';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { CATEGORIES,day,plusDays,type Customer,type State } from '@/lib/crm';
import { NeedSchema,type Need } from '@/lib/business';
import { BusinessField as F,Pick,displayDate,type SaveAction } from './business-ui';
export function YearWheel({st,customers,save,busy,onCustomer,compact=false}:{st:State;customers:Customer[];save:SaveAction;busy:boolean;onCustomer:(id:string)=>void;compact?:boolean}){
 const [edit,setEdit]=useState<{customerId:string;need:Need}|null>(null),[year,setYear]=useState(day().slice(0,4)),[showAll,setShowAll]=useState(false);
 const writable=st.viewer?.role!=='reader';const all=customers.flatMap(c=>c.yearNeeds.map(n=>({...n,customerId:c.id,customer:c.name}))).filter(n=>showAll||n.status==='planned').sort((a,b)=>a.due.localeCompare(b.due));const list=compact?all:all.filter(n=>n.due.startsWith(year));
 const set=(key:keyof Need,value:unknown)=>setEdit(e=>e?{...e,need:{...e.need,[key]:value}}:e);
 function create(){const c=customers[0];if(c)setEdit({customerId:c.id,need:NeedSchema.parse({title:'Nytt inköpsbehov',due:plusDays(day(),60),owner:c.owner})})}
 return <section className={'business-ui '+(compact?'biz-section':'')}><div className="biz-head"><div><span className="biz-kicker">FRAMFÖRHÅLLNING</span><h2><CalendarDays size={22}/>Kundernas årshjul</h2><p>Planera kontakten utifrån när kunden behöver leveransen.</p></div>{writable&&<Button onClick={create} disabled={!customers.length}><Plus size={16}/>Nytt behov</Button>}</div>{!compact&&<div className="biz-toolbar"><F label="År"><Input type="number" min={2000} max={2100} value={year} onChange={e=>setYear(e.target.value)}/></F><Button variant="outline" onClick={()=>setShowAll(!showAll)}>{showAll?'Visa planerade':'Visa även hanterade'}</Button><span>{all.filter(n=>n.status==='planned'&&plusDays(n.due,-n.leadDays)<=day()).length} behov behöver kontakt nu</span></div>}
 {!compact&&<div className="year-months">{Array.from({length:12},(_,i)=>{const month=year+'-'+String(i+1).padStart(2,'0'),items=list.filter(n=>n.due.startsWith(month));return <div key={month} className={month===day().slice(0,7)?'current':''}><span>{new Date(2026,i,1).toLocaleDateString('sv-SE',{month:'short'})}</span><b>{items.filter(n=>n.status==='planned').length}</b>{items.slice(0,2).map(n=><button key={n.id} onClick={()=>onCustomer(n.customerId)}>{n.customer.replace(' · exempel','')}<small>{n.title}</small></button>)}</div>})}</div>}
 <div className="need-list">{list.map(n=><article key={n.id} className="need-card" data-due={n.status==='planned'&&plusDays(n.due,-n.leadDays)<=day()}><div className="biz-head"><div><span className="pill">{n.category||'Inköpsbehov'}</span><h3>{n.title}</h3>{!compact&&<button className="text-link" onClick={()=>onCustomer(n.customerId)}>{n.customer.replace(' · exempel','')} <ArrowUpRight size={14}/></button>}</div><span className="pill">{n.status==='planned'?'Planerat':n.status==='done'?'Hanterat':'Avslutat'}</span></div><div className="biz-grid"><div><small>Kontakta senast</small><b>{displayDate(plusDays(n.due,-n.leadDays))}</b></div><div><small>Kundens leveransbehov</small><b>{displayDate(n.due)}</b></div></div><p>{n.owner} · {n.intervalMonths?`Var ${n.intervalMonths}:e månad`:'Engångsbehov'}</p>{n.notes&&<p>{n.notes}</p>}{writable&&<div className="biz-buttons"><Button size="sm" variant="outline" onClick={()=>setEdit({customerId:n.customerId,need:n})}>Ändra behov</Button>{n.status==='planned'&&<><Button size="sm" variant="outline" disabled={busy||!!n.dealId} onClick={()=>save('need_deal',{customerId:n.customerId,id:n.id},false)}>{n.dealId?'Affär skapad':'Skapa affär'}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>save('complete_need',{customerId:n.customerId,id:n.id},false)}><Check size={14}/>{n.intervalMonths?'Hanterat – planera nästa':'Markera hanterat'}</Button></>}</div>}</article>)}</div>{!list.length&&<div className="biz-empty">Inga behov planerade {compact?'för kunden':'för '+year}. Lägg till exempelvis nästa klädbeställning eller mässa.</div>}
 <Sheet open={!!edit} onOpenChange={v=>{if(!v&&!busy)setEdit(null)}}><SheetContent className="crm-sheet"><SheetHeader><SheetTitle>Planera kundens behov</SheetTitle><SheetDescription>Påminnelsen skapas direkt i teamets aktivitetslista.</SheetDescription></SheetHeader>{edit&&<form className="sheet-body business-ui" onSubmit={async e=>{e.preventDefault();if(await save('year_need',edit,false))setEdit(null)}}><F label="Kund"><Pick label="Kund för behov" value={edit.customerId} onChange={v=>setEdit({...edit,customerId:v,need:{...edit.need,owner:st.customers.find(c=>c.id===v)?.owner||edit.need.owner}})} items={(edit.need.id?st.customers.filter(c=>c.id===edit.customerId):customers).map(c=>({id:c.id,label:c.name}))}/></F><F label="Behov *"><Input required value={edit.need.title} onChange={e=>set('title',e.target.value)} placeholder="Arbetskläder till höststarten"/></F><F label="Produktområde"><Pick label="Produktområde" value={edit.need.category} items={[{id:'',label:'Välj område'},...CATEGORIES.map(c=>({id:c,label:c}))]} onChange={v=>set('category',v)}/></F><div className="biz-grid"><F label="Behövs hos kunden *"><Input required type="date" value={edit.need.due} onChange={e=>set('due',e.target.value)}/></F><F label="Kontakta så många dagar före"><Input type="number" min={0} max={730} value={edit.need.leadDays} onChange={e=>set('leadDays',Number(e.target.value))}/></F></div><div className="biz-callout">Kontakta senast {displayDate(plusDays(edit.need.due||day(),edit.need.leadDays?-edit.need.leadDays:0))}. Räkna in offert, korrektur och leverantörens ledtid.</div><F label="Upprepning"><Pick label="Upprepning" value={String(edit.need.intervalMonths)} items={[{id:'0',label:'Engångsbehov'},{id:'1',label:'Varje månad'},{id:'3',label:'Var tredje månad'},{id:'6',label:'Var sjätte månad'},{id:'12',label:'Varje år'},{id:'24',label:'Vartannat år'}]} onChange={v=>set('intervalMonths',Number(v))}/></F><F label="Ansvarig"><Pick label="Ansvarig för behov" value={edit.need.owner} onChange={v=>set('owner',v)} items={st.settings.owners.map(o=>({id:o,label:o}))}/></F><F label="Omfattning, anledning och förberedelser"><Textarea value={edit.need.notes} onChange={e=>set('notes',e.target.value)}/></F><F label="Status"><Pick label="Behovsstatus" value={edit.need.status} onChange={v=>set('status',v)} items={[{id:'planned',label:'Planerat'},{id:'done',label:'Hanterat'},{id:'cancelled',label:'Avslutat'}]}/></F><Button type="submit" disabled={busy}>Spara behov och påminnelse</Button></form>}</SheetContent></Sheet>
 </section>
}
