import {OrderRevisionSchema,PendingAmendmentSchema} from './business';
import {DirectShipmentSchema,deliveryVerified,latestDispatch} from './direct-delivery';
import {canFollowUp,protectedFollowUp,FollowUpSchema,followupBasis} from './follow-up';
import {normalizeProduction} from './production-quantities';
import {RoleSchema,ProductionSchema,ArticleSchema,NoticeSchema,LeadSchema,CompanyEventSchema,SourceSchema,operations,type Role,type Article,type Notice,type Lead,type CompanyEvent} from './operations';
import {ensureReceiptTasks} from './order-work';
import {applyOperations} from './crm-operations';
import {SellerProfileSchema,SellerProfilesInitSchema,SellerProfileInputSchema,initializeSellerProfiles,saveSellerProfile,sellerProfileForOwner,validateSellerProfileReferences,protectSellerSettings} from './seller-profiles';
import {sellerProfilesBasis} from './record-conflicts';
import {SellerProfileRetireSchema,retireSellerProfile,protectRetiredSellerResponsibilities,snapshotRetiredSellerResponsibilities} from './seller-profile-retirement';
import {RuleError} from './crm-errors';
import {CommercialResponsibilityHistorySchema,CommercialResponsibilityTransferSchema,transferCommercialResponsibility,validateCommercialResponsibilityReferences} from './commercial-responsibility';
import {CustomerResponsibilityHistorySchema,CustomerResponsibilityTransferSchema,transferCustomerResponsibility,validateCustomerResponsibilityReferences} from './customer-responsibility';
import {CustomerReopenSchema,reopenCustomer} from './customer-reopen';
import {TaskResponsibilityHistorySchema,TaskResponsibilityTransferSchema,protectTaskResponsibility,assignTaskResponsibilities,validateTaskResponsibilityReferences,transferTaskResponsibility,recordTaskBundleTransfers} from './task-responsibility';
import {MeetingResponsibilityHistorySchema,MeetingResponsibilityTransferSchema,protectMeetingResponsibility,validateMeetingResponsibilityReferences,transferMeetingResponsibility} from './meeting-responsibility';
import {OnboardingResponsibilityHistorySchema,OnboardingResponsibilityTransferSchema,protectOnboardingResponsibility,validateOnboardingResponsibilityReferences,transferOnboardingResponsibility} from './onboarding-responsibility';
import {IssueResponsibilityHistorySchema,IssueResponsibilityTransferSchema,protectIssueResponsibility,validateIssueResponsibilityReferences,transferIssueResponsibility} from './issue-responsibility';
import {YearwheelResponsibilityTransferSchema,protectYearwheelResponsibility,validateYearwheelResponsibilityReferences,transferYearwheelResponsibility,yearNeedEditBasis,yearwheelResponsibleProfile} from './yearwheel-responsibility';
export {RuleError} from './crm-errors';
import { z } from 'zod';
import { AddressSchema,SiteSchema,NeedSchema,LineSchema,ProductSchema,QuoteSnapshotSchema,GoalSchema,calculateQuote,addMonths } from './business';
export const PIPELINE=[
 {id:'identified',label:'Affär identifierad',short:'Identifierad',goal:'Ett konkret inköpsbehov att undersöka.',checks:['Kund och ansvarig','Kontaktanledning','Nästa aktivitet med datum'],help:'En köpt lista är inte pipeline. Skapa en affär när det finns en konkret möjlighet.'},
 {id:'contact',label:'Dialog pågår',short:'Dialog',goal:'Rätt kontakt är nådd och dialogen har börjat.',checks:['Kontaktperson bekräftad','Relevant nästa steg'],help:'Obesvarade samtal är aktiviteter. De flyttar inte affären framåt.'},
 {id:'needs',label:'Behov kartlagt',short:'Behov',goal:'Vad, varför, vem och när är känt.',checks:['Behov och användning','Beslutsfattare','Önskad leveransdag'],help:'Fånga målgrupp, antal, budget, återköpsmönster och beslutsväg.'},
 {id:'solution',label:'Lösning & prov',short:'Lösning',goal:'Sortiment och utförande matchar behovet.',checks:['Lösningsförslag','Storlekar, märkning och prov vid behov'],help:'Provplagg och skisser är kontrollpunkter. En återbeställning kan gå vidare direkt när kraven är uppfyllda.'},
 {id:'costing',label:'Offert förbereds',short:'Kalkyl',goal:'Pris, kostnad och leveranstid är genomarbetade.',checks:['Ordervärde exkl. moms','Direkta kostnader kalkylerade','Leveransförutsättningar'],help:'Ta med inköp, märkning, frakt och andra direkta kostnader. Saknad kostnad är inte noll.'},
 {id:'quoted',label:'Offert skickad',short:'Offert',goal:'Kunden har ett dokumenterat erbjudande.',checks:['Offertreferens','Beslutsdatum','Nästa uppföljning'],help:'En uppföljningsuppgift skapas automatiskt. Ange den verkliga offertreferensen.'},
 {id:'decision',label:'Beslut & förankring',short:'Beslut',goal:'Beslutsvägen och kvarvarande frågor är kända.',checks:['Beslutsfattare och datum','Sista hinder dokumenterat'],help:'Ett positivt samtal är inte en order. Vunnen kräver bekräftat kundbeslut.'}
] as const;
export const OUTCOMES=[{id:'won',label:'Vunnen'},{id:'paused',label:'Pausad'},{id:'lost',label:'Förlorad'}];
export const RELATIONS=[{id:'prospect',label:'Prospekt'},{id:'onboarding',label:'Ny kund'},{id:'active',label:'Aktiv kund'},{id:'growth',label:'Utveckling'},{id:'risk',label:'Behöver omsorg'},{id:'dormant',label:'Vilande'},{id:'closed',label:'Avslutad'}];
export const DELIVERY=[{id:'handover',label:'Orderunderlag'},{id:'approval',label:'Korrektur & godkännande'},{id:'supplier',label:'Leverantör bekräftad'},{id:'production',label:'Produktion'},{id:'shipping',label:'Leverans pågår'},{id:'delivered',label:'Levererad'},{id:'followed',label:'Uppföljd'}];
export const CATEGORIES=['Arbetskläder','Profilkläder','Företagsgåvor','Giveaways','Föreningskläder','Exponering'];
const s=z.string().trim().max(4000),required=s.min(1,'Fyll i obligatoriska uppgifter.'),id=s.max(100);
const date=z.string().refine(x=>x===''||(/^\d{4}-\d{2}-\d{2}$/.test(x)&&!Number.isNaN(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x),'Välj ett giltigt datum.');
const money=z.number().finite().min(0).max(1e9);
export const PROSPECT_STAGES=[{id:'selected',label:'Utvalt företag'},{id:'contact',label:'Kontakt etablerad'},{id:'qualified',label:'Behov bekräftat'},{id:'paused',label:'Pausad'},{id:'not_relevant',label:'Inte relevant'}];
export const ONBOARDING_CHECKS=[{id:'contacts',label:'Kontaktvägar och beställningssätt bekräftade'},{id:'billing',label:'Fakturauppgifter kontrollerade'},{id:'handover',label:'Kundlöfte och orderunderlag överlämnade'},{id:'artwork',label:'Logotyper, storlekar och nödvändiga godkännanden säkrade'},{id:'experience',label:'Första leveransen följd upp med kunden'}] as const;
export const ProspectSchema=z.object({stage:z.enum(['selected','contact','qualified','paused','not_relevant']).default('selected'),reason:s.default(''),nextAction:s.default(''),nextDate:date.default(''),need:s.default(''),scope:s.default(''),timing:date.default(''),outcomeReason:s.default(''),convertedDealId:s.default(''),qualifiedAt:s.default(''),qualifiedOwner:s.default(''),qualifiedOwnerId:z.union([z.literal(''),z.string().uuid()]).default('')});
export const OnboardingSchema=z.object({ownerProfileId:z.union([z.literal(''),z.string().uuid()]).default(''),responsibilityTransfers:z.array(OnboardingResponsibilityHistorySchema).max(1000).default([]),owner:s.default(''),due:date.default(''),dealId:s.default(''),startedAt:s.default(''),completedAt:s.default(''),checks:z.object({contacts:z.boolean().default(false),billing:z.boolean().default(false),handover:z.boolean().default(false),artwork:z.boolean().default(false),experience:z.boolean().default(false)}).default({}),feedback:s.default(''),nextNeed:s.default('')});
export const PlanSchema=z.object({issueOwnerProfileId:z.union([z.literal(''),z.string().uuid()]).default(''),issueResponsibilityTransfers:z.array(IssueResponsibilityHistorySchema).max(1000).default([]),goal:s.default(''),ordering:s.default(''),contacts:z.array(z.object({name:required,role:required,email:z.union([z.literal(''),z.string().email()]).default(''),phone:s.default('')})).max(20).default([]),nextNeed:s.default(''),nextNeedDate:date.default(''),nextAction:s.default(''),nextDate:date.default(''),issue:s.default(''),issueAction:s.default(''),issueOwner:s.default(''),issueDue:date.default(''),issueStatus:z.enum(['none','open','resolved']).default('none'),lastReview:s.default('')});
export const CustomerSchema=z.object({ownerProfileId:z.union([z.literal(''),z.string().uuid()]).default(''),responsibilityTransfers:z.array(CustomerResponsibilityHistorySchema).max(1000).default([]),id:id.default(''),name:required.max(200),organizationNumber:s.max(30).default(''),fortnoxNumber:s.max(100).default(''),website:s.default(''),billingEmail:z.union([z.literal(''),z.string().email()]).default(''),billingAddress:AddressSchema.default({}),deliveryAddress:AddressSchema.default({}),sites:z.array(SiteSchema).max(50).default([]),yearNeeds:z.array(NeedSchema).max(100).default([]),products:z.array(ProductSchema).max(100).default([]),contact:s.default(''),email:z.union([z.literal(''),z.string().email('Ogiltig e-postadress.')]).default(''),phone:s.default(''),owner:required,segment:s.default(''),status:z.enum(['prospect','onboarding','active','growth','risk','dormant','closed']).default('prospect'),lastContact:date.default(''),nextReview:date.default(''),expectedOrder:date.default(''),reviewDays:z.number().int().min(7).max(730).default(90),need:s.default(''),decisionMaker:s.default(''),categories:z.array(s).max(6).default([]),source:s.default(''),riskReason:s.default(''),createdAt:s.default(''),prospecting:ProspectSchema.default({}),onboarding:OnboardingSchema.default({}),plan:PlanSchema.default({})});
export const RepeatRecipeSchema=z.object({sourceOrderId:required,sourceWorkId:s.default(''),instructions:s,sketchFileId:s,sketchVersion:s});
export const DealSchema=z.object({ownerProfileId:z.union([z.literal(''),z.string().uuid()]).default(''),responsibilityTransfers:z.array(CommercialResponsibilityHistorySchema).max(1000).default([]),repeatRecipe:RepeatRecipeSchema.nullable().default(null),id:id.default(''),customerId:required,owner:required,title:required.max(200),stage:z.enum(['identified','contact','needs','solution','costing','quoted','decision','won','paused','lost']).default('identified'),category:s.default('Profilkläder'),type:z.enum(['new','repeat','expansion']).default('new'),value:money.nullable().default(null),cost:money.nullable().default(null),lines:z.array(LineSchema).max(100).default([]),proofDeadline:date.default(''),orderDeadline:date.default(''),sourceDealId:s.default(''),priceChecked:z.boolean().default(false),priceCheckedAt:s.default(''),quotes:z.array(QuoteSnapshotSchema).max(100).default([]),need:s.default(''),decisionMaker:s.default(''),solution:s.default(''),quoteRef:s.default(''),decisionDate:date.default(''),deliveryDate:date.default(''),nextAction:s.default(''),nextDate:date.default(''),reason:s.default(''),confirmed:z.boolean().default(false),createdAt:s.default(''),stageAt:s.default(''),wonAt:s.default('')});
export const OrderSchema=z.object({ownerProfileId:z.union([z.literal(''),z.string().uuid()]).default(''),responsibilityTransfers:z.array(CommercialResponsibilityHistorySchema).max(1000).default([]),invoiceOwner:s.default(''),invoiceOwnerId:z.union([z.literal(''),z.string().uuid()]).default(''),invoiceOwnerSource:z.enum(['recorded','legacy_recorded','legacy_fallback']).default('legacy_recorded'),directShipments:z.array(DirectShipmentSchema).max(1000).default([]),commercialVersion:z.number().int().positive().default(1),commercialValue:money.nullable().default(null),pendingAmendment:PendingAmendmentSchema.nullable().default(null),revisions:z.array(OrderRevisionSchema).max(100).default([]),shippingAddress:AddressSchema.nullable().default(null),receivedBy:s.default(''),receiptNote:s.default(''),deliveryIssue:s.default(''),deliveryNextCheck:date.default(''),production:ProductionSchema.default({}),productionHistory:z.array(ProductionSchema).max(100).default([]),id:required,customerId:required,dealId:required,owner:required,stage:z.enum(['handover','approval','supplier','production','shipping','delivered','followed']),proofRequired:z.boolean(),proofApproved:z.boolean(),proofFileId:s.default(''),proofVersion:s.default(''),approvedBy:s.default(''),approvedDate:date.default(''),supplierConfirmed:z.boolean(),deliveryDate:date,deliveredDate:date,invoiceDate:date,invoiceRef:s,invoiceValue:money.nullable(),actualCost:money.nullable(),notes:s});
export const TaskSchema=z.object({id:id.default(''),ownerProfileId:z.union([z.literal(''),z.string().uuid()]).default(''),responsibilityTransfers:z.array(TaskResponsibilityHistorySchema).max(1000).default([]),customerId:required,dealId:s.default(''),owner:required,title:required.max(240),due:date.refine(Boolean,'Välj förfallodatum.'),done:z.boolean().default(false),kind:s.default('manual'),doneAt:s.default('')});
export const MeetingSchema=z.object({id:id.default(''),ownerProfileId:z.union([z.literal(''),z.string().uuid()]).default(''),responsibilityTransfers:z.array(MeetingResponsibilityHistorySchema).max(1000).default([]),customerId:required,title:required.max(200),owner:required,date:date.refine(Boolean,'Välj mötesdatum.'),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),duration:z.number().int().min(15).max(480),location:s.default(''),notes:s.default(''),status:z.enum(['planned','done','cancelled']).default('planned')});
export const SettingsSchema=z.object({sellerProfiles:z.array(SellerProfileSchema).max(1000).default([]),sellerProfilesInitialized:z.boolean().default(false),sellerGoalsById:z.record(z.string().uuid(),z.record(z.string().regex(/^\d{4}-\d{2}$/),GoalSchema)).default({}),sellerAnnualGoalsById:z.record(z.string().uuid(),z.record(z.string().regex(/^\d{4}$/),money)).default({}),owners:z.array(required.max(150)).min(1).max(30),budgets:z.record(z.string().regex(/^\d{4}-\d{2}$/),money),sellerGoals:z.record(z.string(),z.record(z.string().regex(/^\d{4}-\d{2}$/),GoalSchema)).default({}),sellerAnnualGoals:z.record(z.string(),z.record(z.string().regex(/^\d{4}$/),money)).default({}),followupDays:z.number().int().min(1).max(90),reviewDays:z.number().int().min(7).max(730),catalogSources:z.array(SourceSchema).max(20).default([{id:'current',name:'Nuvarande webbshop',url:'https://www.magnussonsreklam.se',active:true}]),annualBudgets:z.record(z.string().regex(/^\d{4}$/),money).default({})});
export type Customer=z.infer<typeof CustomerSchema>;export type Deal=z.infer<typeof DealSchema>;export type Order=z.infer<typeof OrderSchema>;export type Task=z.infer<typeof TaskSchema>;export type Meeting=z.infer<typeof MeetingSchema>;export type Settings=z.infer<typeof SettingsSchema>;
export const CustomerNoteSchema=z.object({customerId:required,title:z.string().trim().max(160).default(''),text:z.string().max(50000,'Anteckningen får innehålla högst 50 000 tecken.').refine(v=>v.trim().length>0,'Skriv en anteckning.'),meetingDate:date.default(''),sourceFiles:z.array(z.string().max(200)).max(10).default([]),contact:z.boolean().default(false),nextAction:s.max(240).default(''),nextDate:date.default(''),owner:s.default('')});
export type Event={id:string;customerId:string;dealId:string;text:string;at:string;kind:string;actor?:{id:string;name:string};note?:{title:string;meetingDate:string;sourceFiles:string[]}};
export type State={viewer?:{id:string;memberId?:string;name:string;email:string;role:Role;owner:string};version:number;articles:Article[];notices:Notice[];leads:Lead[];companyEvents:CompanyEvent[];customers:Customer[];deals:Deal[];orders:Order[];tasks:Task[];meetings:Meeting[];events:Event[];settings:Settings};
export const day=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const plusDays=(v:string,n:number)=>{const d=new Date(v+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export const label=(list:readonly {id:string;label:string}[],key:string)=>list.find(x=>x.id===key)?.label??key;
export const margin=(value:number|null,cost:number|null)=>value&&cost!==null?100*(value-cost)/value:null;
export const isOpen=(d:Deal)=>!['won','lost','paused'].includes(d.stage);
export function concerns(c:Customer,today=day(),st?:State){const r:string[]=[];if(c.status==='closed'||c.status==='prospect')return r;if(c.plan?.issueStatus==='open')r.push('Öppet kundärende: '+c.plan.issue);if(c.plan?.nextNeedDate&&plusDays(c.plan.nextNeedDate,-14)<=today)r.push('Planera inför nästa inköpsbehov');if(c.status==='risk')r.push(c.riskReason||'Manuellt markerad för omsorg');if(c.nextReview&&c.nextReview<today)r.push('Kunduppföljning försenad');if(c.expectedOrder&&c.expectedOrder<today)r.push('Förväntat återköp behöver stämmas av');if(c.lastContact&&plusDays(c.lastContact,c.reviewDays)<today)r.push('Länge sedan senaste kontakt');if(['active','growth','risk'].includes(c.status)){if(st&&!st.tasks.some(t=>t.customerId===c.id&&!t.done)&&!st.meetings.some(m=>m.customerId===c.id&&m.status==='planned'&&m.date>=today))r.push('Aktiv kund utan planerad aktivitet');else if(!st&&!c.nextReview&&!c.plan.nextDate)r.push('Nästa kundkontakt saknas');}return r;}
export function emptyState():State{return{version:0,articles:[],notices:[],leads:[],companyEvents:[],customers:[],deals:[],orders:[],tasks:[],meetings:[],events:[],settings:SettingsSchema.parse({owners:['Sebastian Hansson','Erik Lindberg','Pelle Peolin','Sanna Timonen'],budgets:{},sellerGoals:{},followupDays:14,reviewDays:90})};}
export function seedState():State{
 const st=emptyState(),today=day();st.settings.budgets[today.slice(0,7)]=250000;
 const names=['Nordskåne Montage · exempel','Atlas Teknik · exempel','Björkdalens Golf · exempel','Hamnstadens Hotell · exempel','Forma Studio · exempel','Sydkustens Logistik · exempel','Höjdens IF · exempel','Park & Plats · exempel'];
 st.customers=names.map((name,i)=>CustomerSchema.parse({id:'c'+i,name,contact:['Anna Exempel','Johan Exempel','Sara Exempel'][i%3],owner:st.settings.owners[i%4],segment:['Bygg & installation','Industri','Förening','Besöksnäring'][i%4],status:i===0?'risk':i===3?'onboarding':i<5?'active':'prospect',lastContact:plusDays(today,i===0?-100:-12),nextReview:plusDays(today,i===0?-3:14+i),expectedOrder:i===1?plusDays(today,-2):'',need:['Nya arbetskläder inför hösten. Storleksprovning på plats.','Återkommande personalgåvor och mässmaterial.','Profilkläder till nya medarbetare.'][i%3],categories:i%2?['Profilkläder']:['Arbetskläder'],source:i%2?'Referens':'Befintlig relation',riskReason:i===0?'Kontaktpersonen har slutat. Ny inköpare behöver identifieras.':'',createdAt:plusDays(today,-120)}));
 const titles=['Arbetskläder till montörerna','Ny profilkollektion','Klubbkollektion inför säsongen','Välkomstpaket för personal','Mässa: kläder & exponering','Jackor till transportteamet','Julgåva till funktionärerna'];
 st.deals=PIPELINE.map((p,i)=>DealSchema.parse({id:'d'+i,customerId:'c'+i,owner:st.customers[i].owner,title:titles[i],stage:p.id,category:CATEGORIES[i%6],type:i%2?'expansion':'new',value:[48000,92000,34000,67000,125000,58000,23000][i],cost:[30000,58000,21000,43000,81000,37000,14500][i],need:st.customers[i].need,decisionMaker:st.customers[i].contact,solution:'Utvalt sortiment med logotyp. Prov och storlekar stäms av före beställning.',quoteRef:i>4?'OFF-EXEMPEL-'+i:'',decisionDate:plusDays(today,7),deliveryDate:plusDays(today,35),nextAction:['Identifiera ny inköpare','Boka behovsmöte','Bekräfta antal och storlekar','Stäm av provplagg','Kontrollera leverantörens pris','Följ upp offerten','Stäm av beslut'][i],nextDate:plusDays(today,i===5?-2:i%3),createdAt:plusDays(today,-20),stageAt:plusDays(today,-i-1)}));
 const won=DealSchema.parse({...st.deals[3],id:'dw',title:'Första leveransen av profilkläder',stage:'won',confirmed:true,value:72000,cost:45000,wonAt:plusDays(today,-8),nextAction:'',nextDate:''});st.deals.push(won);
 st.orders.push(OrderSchema.parse({id:'ow',customerId:'c3',dealId:'dw',owner:won.owner,stage:'delivered',proofRequired:true,proofApproved:true,supplierConfirmed:true,deliveryDate:plusDays(today,-3),deliveredDate:plusDays(today,-3),invoiceDate:today,invoiceRef:'DEMO-1001',invoiceValue:72000,actualCost:45800,notes:'Exempel: kontrollera passform efter första leveransen.'}));
 st.tasks=[{id:'t1',customerId:'c0',dealId:'d0',owner:st.customers[0].owner,title:'Hitta ny inköpare och boka avstämning',due:plusDays(today,-1),done:false,kind:'care',doneAt:''},{id:'t2',customerId:'c5',dealId:'d5',owner:st.customers[5].owner,title:'Följ upp offert på jackor',due:plusDays(today,-2),done:false,kind:'quote',doneAt:''},{id:'t3',customerId:'c3',dealId:'dw',owner:won.owner,title:'Följ upp första leveransen: passform och återköp',due:plusDays(today,3),done:false,kind:'delivery',doneAt:''}].map(task=>TaskSchema.parse(task));
 st.meetings=[MeetingSchema.parse({id:'m1',customerId:'c1',title:'Behovsmöte: höstens profilering',owner:st.customers[1].owner,date:plusDays(today,1),time:'10:00',duration:45,location:'Kundbesök',notes:'Exempelbokning. Ingen kalenderinbjudan har skickats.'})];
 st.events=[{id:'e1',customerId:'c0',dealId:'',text:'Exempelanteckning: tidigare kontaktperson har slutat. Följ upp vem som tar över inköpen.',at:new Date().toISOString(),kind:'note'}];return st;
}
// Older records receive empty workflow fields; no completed work is inferred.
export function normalizeState(st:State):State{
 st.articles=(st.articles||[]).map(a=>ArticleSchema.parse(a));st.notices=(st.notices||[]).map(n=>NoticeSchema.parse(n));st.leads=(st.leads||[]).map(l=>LeadSchema.parse(l));st.companyEvents=(st.companyEvents||[]).map(e=>CompanyEventSchema.parse(e));
 st.settings=SettingsSchema.parse(st.settings);st.tasks=(st.tasks||[]).map(task=>TaskSchema.parse(task));st.meetings=(st.meetings||[]).map(meeting=>MeetingSchema.parse(meeting));st.deals=st.deals.map(d=>DealSchema.parse(d));st.orders=st.orders.map(raw=>{const o=OrderSchema.parse(raw);if(!o.invoiceOwner&&o.invoiceValue!==null&&o.invoiceRef&&o.invoiceDate){o.invoiceOwner=o.owner;o.invoiceOwnerSource='legacy_fallback';}o.production=normalizeProduction(o.production);o.productionHistory=o.productionHistory.map(normalizeProduction);return o;});
 st.customers=st.customers.map(raw=>{const c=CustomerSchema.parse(raw);if(c.status==='onboarding'&&!c.onboarding.startedAt){const d=st.deals.filter(d=>d.customerId===c.id&&d.stage==='won').sort((a,b)=>a.wonAt.localeCompare(b.wonAt))[0];if(d)c.onboarding={...c.onboarding,owner:c.owner,dealId:d.id,startedAt:d.wonAt||d.createdAt};}return c;});validateSellerProfileReferences(st);validateCustomerResponsibilityReferences(st);validateCommercialResponsibilityReferences(st);validateTaskResponsibilityReferences(st);validateMeetingResponsibilityReferences(st);validateOnboardingResponsibilityReferences(st);validateIssueResponsibilityReferences(st);validateYearwheelResponsibilityReferences(st);return st;
}
export const onboardingProgress=(c:Customer)=>ONBOARDING_CHECKS.filter(x=>c.onboarding.checks[x.id]).length;
const need=(v:unknown,m:string)=>{if(!v)throw new RuleError(m)};
export function validateDeal(d:Deal,c:Customer){
 const n=d.stage==='won'?7:PIPELINE.findIndex(x=>x.id===d.stage);
 if(isOpen(d)||d.stage==='paused'){need(d.nextAction,'Skriv nästa aktivitet.');need(d.nextDate,'Välj datum för nästa aktivitet.');}
 if(n>=1)need(c.contact,'Lägg till kundens kontaktperson på kundkortet först.');
 if(n>=2){need(d.need,'Dokumentera behovet.');need(d.decisionMaker,'Ange vem som fattar beslut.');need(d.deliveryDate,'Ange önskad leveransdag.');}
 if(n>=3)need(d.solution,'Beskriv lösningen eller sortimentet.');
 if(n>=4){need(d.value!==null&&d.value>0,'Ange ett ordervärde större än noll.');need(d.cost!==null,'Fyll i kalkylerade direkta kostnader, även om de är noll.');}
 if(n>=4&&d.sourceDealId)need(d.priceChecked,'Kontrollera aktuella priser och leveranstid för återbeställningen.');
 if(d.proofDeadline&&d.orderDeadline)need(d.proofDeadline<=d.orderDeadline,'Korrekturet behöver godkännas senast på beställningsdagen.');
 if(d.orderDeadline&&d.deliveryDate)need(d.orderDeadline<=d.deliveryDate,'Beställningsdagen får inte ligga efter leveransen.');
 if(n>=5){need(d.quoteRef,'Ange offertreferens.');need(d.decisionDate,'Ange beslutsdatum.');}
 if(d.stage==='won')need(d.confirmed,'Bekräfta att kunden har accepterat ordern.');
 if(['lost','paused'].includes(d.stage))need(d.reason,'Ange orsak till förlorad eller pausad affär.');
}
export type Action={type:string;data:unknown};
export type Actor={id:string;memberId?:string;name:string;role:Role;owner:string};
// Stable commercial IDs and audit rows are server-owned. Older blank IDs stay
// blank until an explicit reviewed transfer; an ordinary edit is no migration.
function protectCommercialResponsibility(old:Deal|Order|undefined,next:Deal|Order,raw:unknown){
 const input=raw as Record<string,unknown>;
 for(const key of ['ownerProfileId','responsibilityTransfers'] as const){
  if(Object.prototype.hasOwnProperty.call(input,key))need(JSON.stringify(next[key])===JSON.stringify(old?.[key]??(key==='ownerProfileId'?'':[])),'Ansvarsprofil och ansvarshistorik ändras bara genom en granskad överföring.');
 }
 if(old){next.ownerProfileId=old.ownerProfileId;next.responsibilityTransfers=structuredClone(old.responsibilityTransfers);}
}
function assignNewResponsibleProfiles(previous:State,next:State,exactNewMeetingOwners?:ReadonlyMap<string,string>,exactNewOnboardingOwners?:ReadonlyMap<string,string>,exactNewNeedDealOwners?:ReadonlyMap<string,string>,exactNewNeedDealTaskOwners?:ReadonlyMap<string,string>,exactNewFollowUpOwners?:ReadonlyMap<string,{sourceTaskId:string;ownerProfileId:string}>){
 for(const name of ['customers','deals','orders'] as const){
  const existing=new Set(previous[name].map(row=>row.id));
  for(const row of next[name])if(!existing.has(row.id)){
   const profile=next.settings.sellerProfilesInitialized?sellerProfileForOwner(next.settings,row.owner):undefined;
   need(!next.settings.sellerProfilesInitialized||profile?.active&&next.settings.owners.includes(profile.legacyOwnerName),name==='customers'?'Välj en aktiv, granskad säljarprofil för den nya kundens ansvar.':'Välj en aktiv, granskad säljarprofil för nytt affärs- eller orderansvar.');
   if(name==='deals'&&exactNewNeedDealOwners?.has(row.id)){
    const exact=exactNewNeedDealOwners.get(row.id)!,yearNeed=next.customers.find(customer=>customer.id===(row as Deal).customerId)?.yearNeeds.find(need=>need.dealId===row.id);
    need(yearNeed&&yearNeed.owner===row.owner&&yearNeed.ownerProfileId===exact&&(exact===''||profile?.id===exact),'Den nya behovsaffären måste följa årshjulets exakta ansvarskoppling.');row.ownerProfileId=exact;
   }else row.ownerProfileId=profile?.id||'';row.responsibilityTransfers=[];
  }
 }
 validateCustomerResponsibilityReferences(next);validateCommercialResponsibilityReferences(next);validateMeetingResponsibilityReferences(next);validateOnboardingResponsibilityReferences(next);validateIssueResponsibilityReferences(next);validateYearwheelResponsibilityReferences(next);return assignTaskResponsibilities(previous,next,exactNewMeetingOwners,exactNewOnboardingOwners,exactNewNeedDealTaskOwners,exactNewFollowUpOwners);
}
export function applyAction(current:State,action:Action,actor?:Actor):State{
 const st=normalizeState(structuredClone(current)),now=new Date().toISOString(),today=day(),uid=()=>crypto.randomUUID(),exactNewMeetingOwners=new Map<string,string>(),exactNewOnboardingOwners=new Map<string,string>(),exactNewNeedDealOwners=new Map<string,string>(),exactNewNeedDealTaskOwners=new Map<string,string>(),exactNewFollowUpOwners=new Map<string,{sourceTaskId:string;ownerProfileId:string}>();
 // Capture only audited identities and operational keys from the normalized
 // original; raw legacy fields need defaults without a second full data clone.
 const previousResponsibilities=snapshotRetiredSellerResponsibilities(st),finish=(next:State)=>previousResponsibilities.profiles.length||next.settings.sellerProfiles.some(profile=>profile.retirementHistory.length)?protectRetiredSellerResponsibilities(previousResponsibilities,next):next;
 const customer=(i:string)=>{const c=st.customers.find(x=>x.id===i);need(c,'Kunden finns inte i denna arbetsyta.');return c!};
 const owner=(o:string)=>need(st.settings.owners.includes(o),'Välj en ansvarig från teamet.');
 const event=(customerId:string,text:string,dealId='',kind='change')=>st.events.unshift({id:uid(),customerId,dealId,text,at:now,kind});
 // Editing a shared plan must never take back a delegated existing activity,
 // including a new follow-up with its own empty audit and exact copied UUID.
 // A genuinely new canonical activity still starts with the customer owner.
 const customerTask=(c:Customer,title:string,due:string,kind:string,assigned=c.owner)=>{const t=st.tasks.find(t=>t.customerId===c.id&&t.kind===kind&&!t.done);if(t){const preserveOwner=t.responsibilityTransfers.length||st.settings.sellerProfilesInitialized&&['csm','csm_need','prospecting'].includes(kind);Object.assign(t,{title,due,owner:preserveOwner?t.owner:assigned});return t;}const next=TaskSchema.parse({id:uid(),customerId:c.id,dealId:'',owner:assigned,title,due,done:false,kind,doneAt:''});st.tasks.push(next);return next;};
 // Checklist work never moves an existing task after profile initialization,
 // including an unaudited task deliberately left out of a handover. Only a
 // server-created replacement copies the onboarding's exact recorded ID.
 const onboardingTask=(c:Customer,title:string,due:string)=>{const old=st.tasks.find(t=>t.customerId===c.id&&t.kind==='onboarding'&&!t.done),task=customerTask(c,title,due,'onboarding',old&&st.settings.sellerProfilesInitialized?old.owner:c.onboarding.owner);if(!current.tasks.some(t=>t.id===task.id))exactNewOnboardingOwners.set(task.id,c.onboarding.ownerProfileId);return task;};
 // Ordinary plan saves update the task action/date and preserve every existing
 // issue task's responsibility, including an unselected, unaudited task.
 const issueTask=(c:Customer,plan:Customer['plan'])=>{const old=st.tasks.find(t=>t.customerId===c.id&&t.kind==='csm_issue'&&!t.dealId&&!t.done);if(old){Object.assign(old,{title:plan.issueAction,due:plan.issueDue});return old;}const task=TaskSchema.parse({id:uid(),customerId:c.id,dealId:'',owner:plan.issueOwner,ownerProfileId:plan.issueOwnerProfileId,title:plan.issueAction,due:plan.issueDue,kind:'csm_issue'});st.tasks.push(task);return task;};
 // A normal need edit refreshes one canonical reminder's text/date while
 // preserving every existing task's owner, UUID and responsibility chain.
 const yearwheelTask=(c:Customer,yearNeed:Customer['yearNeeds'][number])=>{const kind='year:'+yearNeed.id,old=st.tasks.find(task=>task.customerId===c.id&&task.kind===kind&&!task.dealId&&!task.done);if(old){Object.assign(old,{title:'Planera '+yearNeed.title,due:plusDays(yearNeed.due,-yearNeed.leadDays)});return old;}const task=TaskSchema.parse({id:uid(),customerId:c.id,dealId:'',owner:yearNeed.owner,ownerProfileId:yearNeed.ownerProfileId,title:'Planera '+yearNeed.title,due:plusDays(yearNeed.due,-yearNeed.leadDays),kind});st.tasks.push(task);return task;};
 const closeYearwheelTasks=(c:Customer,needId:string)=>st.tasks.forEach(task=>{if(task.customerId===c.id&&task.kind==='year:'+needId&&!task.dealId&&!task.done){task.done=true;task.doneAt=now;}});
 const closeTasks=(c:Customer,kind:string)=>st.tasks.forEach(t=>{if(t.customerId===c.id&&t.kind===kind&&!t.done){t.done=true;t.doneAt=now;}});
 const follow=(c:Customer,d:Deal,title:string,due:string,kind:string,assigned=d.owner)=>{if(!st.tasks.some(t=>t.dealId===d.id&&t.kind===kind&&!t.done))st.tasks.push(TaskSchema.parse({id:uid(),customerId:c.id,dealId:d.id,owner:assigned,title,due,done:false,kind,doneAt:''}));};
 if(action.type==='yearwheel_responsibility_transfer'){
  need(actor,'Logga in för att ändra behovsansvar.');const input=YearwheelResponsibilityTransferSchema.parse(action.data);transferYearwheelResponsibility(st,input,actor!);recordTaskBundleTransfers(current,st,'yearwheel',st.customers.find(row=>row.id===input.customerId)!.yearNeeds.find(row=>row.id===input.needId)!.responsibilityTransfers.at(-1)!.id);validateYearwheelResponsibilityReferences(st);return finish(assignTaskResponsibilities(current,st));
 }
 if(action.type==='issue_responsibility_transfer'){
  need(actor,'Logga in för att ändra ärendeansvar.');const input=IssueResponsibilityTransferSchema.parse(action.data);transferIssueResponsibility(st,input,actor!);recordTaskBundleTransfers(current,st,'customer_issue',st.customers.find(row=>row.id===input.customerId)!.plan.issueResponsibilityTransfers.at(-1)!.id);validateIssueResponsibilityReferences(st);return finish(assignTaskResponsibilities(current,st));
 }
 if(action.type==='onboarding_responsibility_transfer'){
  need(actor,'Logga in för att ändra onboardingansvar.');const input=OnboardingResponsibilityTransferSchema.parse(action.data);transferOnboardingResponsibility(st,input,actor!);recordTaskBundleTransfers(current,st,'onboarding',st.customers.find(row=>row.id===input.customerId)!.onboarding.responsibilityTransfers.at(-1)!.id);validateOnboardingResponsibilityReferences(st);return finish(assignTaskResponsibilities(current,st));
 }
 if(action.type==='commercial_responsibility_transfer'){
  need(actor,'Logga in för att överföra affärs- eller orderansvar.');const input=CommercialResponsibilityTransferSchema.parse(action.data);transferCommercialResponsibility(st,input,actor!);const target=input.targetType==='deal'?st.deals.find(row=>row.id===input.targetId):st.orders.find(row=>row.id===input.targetId);recordTaskBundleTransfers(current,st,input.targetType,target!.responsibilityTransfers.at(-1)!.id);validateCommercialResponsibilityReferences(st);return finish(assignTaskResponsibilities(current,st));
 }
 if(action.type==='customer_responsibility_transfer'){
  need(actor,'Logga in för att överföra kundansvar.');const input=CustomerResponsibilityTransferSchema.parse(action.data);transferCustomerResponsibility(st,input,actor!);recordTaskBundleTransfers(current,st,'customer',st.customers.find(row=>row.id===input.customerId)!.responsibilityTransfers.at(-1)!.id);validateCustomerResponsibilityReferences(st);return finish(assignTaskResponsibilities(current,st));
 }
 if(action.type==='customer_reopen'){
  need(actor,'Logga in för att återöppna kundrelationen.');const input=CustomerReopenSchema.parse(action.data);reopenCustomer(st,input,actor!);validateCustomerResponsibilityReferences(st);return finish(assignTaskResponsibilities(current,st));
 }
 if(action.type==='task_responsibility_transfer'){
  need(actor,'Logga in för att ändra uppgiftsansvar.');transferTaskResponsibility(st,TaskResponsibilityTransferSchema.parse(action.data),actor!);return finish(st);
 }
 if(action.type==='meeting_responsibility_transfer'){
  need(actor,'Logga in för att ändra mötesansvar.');transferMeetingResponsibility(st,MeetingResponsibilityTransferSchema.parse(action.data),actor!);return finish(st);
 }
 if(action.type==='seller_profile_retire'){
  need(actor,'Logga in för att göra resultatprofilen historisk.');retireSellerProfile(st,SellerProfileRetireSchema.parse(action.data),actor!);return finish(st);
 }
 if(action.type==='seller_profiles_init'||action.type==='seller_profile'){
  need(actor?.role==='admin','Säljarprofiler hanteras av administratören.');
  if(action.type==='seller_profiles_init'){const p=SellerProfilesInitSchema.parse(action.data);need(p.expectedContext===sellerProfilesBasis(st),'Säljarunderlaget har ändrats. Läs in aktuella profiler och historiska ansvar innan du fortsätter.');initializeSellerProfiles(st,p.profiles,actor!);}
  else{const p=SellerProfileInputSchema.parse(action.data);need(p.expectedContext===sellerProfilesBasis(st),'Säljarunderlaget har ändrats. Läs in aktuella profiler innan du sparar.');saveSellerProfile(st,p,actor!);}
  validateTaskResponsibilityReferences(st);validateMeetingResponsibilityReferences(st);validateOnboardingResponsibilityReferences(st);validateIssueResponsibilityReferences(st);validateYearwheelResponsibilityReferences(st);return finish(st);
 }
 if(action.type==='customer'){
  const c=CustomerSchema.parse(action.data);owner(c.owner);const old=c.id?customer(c.id):undefined;const suppliedPlan=(action.data as {plan?:Record<string,unknown>}).plan;if(suppliedPlan&&Object.prototype.hasOwnProperty.call(suppliedPlan,'issueOwnerProfileId'))need(c.plan.issueOwnerProfileId===(old?.plan.issueOwnerProfileId||''),'Kundärendets ansvarsprofil ändras bara i kundplanens granskade flöde.');if(suppliedPlan&&Object.prototype.hasOwnProperty.call(suppliedPlan,'issueResponsibilityTransfers'))need(JSON.stringify(c.plan.issueResponsibilityTransfers)===JSON.stringify(old?.plan.issueResponsibilityTransfers||[]),'Kundärendets ansvarshistorik skapas av systemet och får inte ändras.');if(Object.prototype.hasOwnProperty.call(action.data,'ownerProfileId'))need(c.ownerProfileId===(old?.ownerProfileId||''),'Kundens ansvarsprofil ändras bara genom en granskad överföring.');c.ownerProfileId=old?.ownerProfileId||'';const historySupplied=Object.prototype.hasOwnProperty.call(action.data,'responsibilityTransfers');if(historySupplied)need(JSON.stringify(c.responsibilityTransfers)===JSON.stringify(old?.responsibilityTransfers||[]),'Ansvarshistoriken skapas av systemet vid överföring och får inte ändras.');if(old&&st.settings.sellerProfilesInitialized)need(c.owner===old.owner,'Använd Byt kundansvar för en granskad överföring av kund och valda öppna uppgifter.');c.responsibilityTransfers=old?.responsibilityTransfers||[];if(c.fortnoxNumber)need(!st.customers.some(x=>x.id!==c.id&&x.fortnoxNumber===c.fortnoxNumber),'Fortnox-kundnumret finns redan.');if(c.organizationNumber)need(!st.customers.some(x=>x.id!==c.id&&x.organizationNumber.replace(/\D/g,'')===c.organizationNumber.replace(/\D/g,'')),'Organisationsnumret finns redan i kundregistret.');if(!old){need(!st.customers.some(x=>x.name.toLowerCase()===c.name.toLowerCase()),'Det finns redan en kund med samma namn.');c.id=uid();c.createdAt=now;c.prospecting=ProspectSchema.parse({});c.onboarding=OnboardingSchema.parse({});c.plan=PlanSchema.parse({contacts:c.plan.contacts});c.yearNeeds=[];c.products=[];}else {c.createdAt=old.createdAt;c.prospecting=old.prospecting;c.onboarding=old.onboarding;c.plan={...old.plan,contacts:c.plan.contacts};c.yearNeeds=old.yearNeeds;c.products=old.products;if(old.onboarding.startedAt&&!old.onboarding.completedAt)need(!['active','growth'].includes(c.status),'Slutför onboardingchecklistan innan kunden aktiveras.');}
  if(c.status==='risk')need(c.riskReason,'Skriv varför kunden behöver extra omsorg.');
  st.customers=old?st.customers.map(x=>x.id===c.id?c:x):[...st.customers,c];event(c.id,old?'Kundkort uppdaterat'+(old.status!==c.status?' · '+label(RELATIONS,c.status):''):'Kund skapad');
 }else if(action.type==='deal'){
  const d=DealSchema.parse(action.data),c=customer(d.customerId);owner(d.owner);const old=st.deals.find(x=>x.id===d.id);protectCommercialResponsibility(old,d,action.data);if(old&&st.settings.sellerProfilesInitialized)need(d.owner===old.owner,'Använd Byt affärsansvar för en granskad överföring.');need(!d.id||old,'Affären finns inte.');if(old){need(old.customerId===d.customerId,'En affär kan inte flyttas till en annan kund.');need(old.stage!=='won','Vunnen affär är låst. Hantera leveransen eller skapa en ny affär.');}
  d.quotes=old?.quotes||[];d.sourceDealId=old?.sourceDealId||'';d.repeatRecipe=old?.repeatRecipe||null;if(d.lines.length){Object.assign(d,calculateQuote(d.lines));need(d.value!==null&&d.value<=1e9&&(d.cost===null||d.cost<=1e9),'Offerten överstiger högsta tillåtna belopp.');}
  d.priceCheckedAt=d.priceChecked?(old?.priceChecked&&JSON.stringify(old.lines)===JSON.stringify(d.lines)?old.priceCheckedAt:now):'';
  validateDeal(d,c);if(['quoted','decision','won'].includes(d.stage)){const snapshot={reference:d.quoteRef,lines:d.lines,value:d.value,cost:d.cost,deliveryDate:d.deliveryDate,proofDeadline:d.proofDeadline,orderDeadline:d.orderDeadline};const last=d.quotes.at(-1);if(!last||JSON.stringify({reference:last.reference,lines:last.lines,value:last.value,cost:last.cost,deliveryDate:last.deliveryDate,proofDeadline:last.proofDeadline,orderDeadline:last.orderDeadline})!==JSON.stringify(snapshot)){need(d.quotes.length<100,'Offerten har nått 100 versioner. Skapa en ny affär.');d.quotes.push({...snapshot,version:d.quotes.length+1,at:now});}}d.id=old?.id||uid();d.createdAt=old?.createdAt||now;d.stageAt=old?.stage===d.stage?old.stageAt:now;d.wonAt=d.stage==='won'?today:'';
  st.deals=old?st.deals.map(x=>x.id===d.id?d:x):[...st.deals,d];event(c.id,(old?'Affär uppdaterad':'Affär skapad')+' · '+d.title+' · '+label([...PIPELINE,...OUTCOMES],d.stage),d.id);
  for(const [kind,due,title] of [['proof_deadline',d.proofDeadline,'Säkra kundens korrekturgodkännande'],['order_deadline',d.orderDeadline,'Beställ hos leverantören']] as const){const tasks=st.tasks.filter(t=>t.dealId===d.id&&t.kind===kind&&!t.done);if(!due||['lost','paused'].includes(d.stage)){for(const t of tasks){t.done=true;t.doneAt=now;}}else if(tasks.length){Object.assign(tasks[0],{due,owner:!old||tasks[0].owner===old.owner?d.owner:tasks[0].owner,title:(title+': '+d.title).slice(0,240)})}else follow(c,d,(title+': '+d.title).slice(0,240),due,kind);}
  const activityKind=['quoted','decision'].includes(d.stage)?'quote':'discovery';
  const activityChanged=!old||old.nextDate!==d.nextDate||old.nextAction!==d.nextAction||old.stage!==d.stage;
  const activeTasks=st.tasks.filter(t=>t.dealId===d.id&&['quote','discovery'].includes(t.kind)&&!t.done);
  if(['won','lost'].includes(d.stage)){for(const t of activeTasks){t.done=true;t.doneAt=now;}}
  else {
   let activity=activeTasks.find(t=>t.kind===activityKind);
   for(const t of activeTasks)if(t!==activity){t.done=true;t.doneAt=now;}
   if(activity)Object.assign(activity,{title:d.nextAction.slice(0,240),due:d.nextDate,owner:!old||activity.owner===old.owner?d.owner:activity.owner});
   else if(activityChanged&&d.nextDate&&d.nextAction)follow(c,d,d.nextAction.slice(0,240),d.nextDate,activityKind);
  }
  if(d.stage==='won'){need(!st.orders.some(o=>o.dealId===d.id),'En order finns redan.');st.orders.push(OrderSchema.parse({id:uid(),customerId:c.id,dealId:d.id,owner:d.owner,stage:'handover',proofRequired:true,proofApproved:false,supplierConfirmed:false,deliveryDate:d.deliveryDate,deliveredDate:'',invoiceDate:'',invoiceRef:'',invoiceValue:null,actualCost:null,notes:''}));if(c.status==='prospect'&&!c.onboarding.startedAt){c.status='onboarding';c.onboarding=OnboardingSchema.parse({owner:c.owner,ownerProfileId:c.ownerProfileId,due:plusDays(d.deliveryDate,st.settings.followupDays),dealId:d.id,startedAt:now});closeTasks(c,'prospecting');onboardingTask(c,'Slutför onboarding: '+c.name,c.onboarding.due);event(c.id,'Onboarding startad efter första ordern',d.id);}else if(c.status==='dormant')c.status='active';follow(c,d,'Säkra orderunderlaget: '+d.title,today,'handover');}
 }else if(action.type==='order'){
  const o=OrderSchema.parse(action.data),old=st.orders.find(x=>x.id===o.id);need(old,'Ordern finns inte.');need(old!.customerId===o.customerId&&old!.dealId===o.dealId,'Orderkopplingen får inte ändras.');owner(o.owner);protectCommercialResponsibility(old,o,action.data);if(st.settings.sellerProfilesInitialized)need(o.owner===old!.owner,'Använd Byt orderansvar för en granskad överföring.');o.invoiceOwner=old!.invoiceOwner;o.invoiceOwnerId=old!.invoiceOwnerId;o.invoiceOwnerSource=old!.invoiceOwnerSource;
  if(!o.invoiceOwner&&o.invoiceValue!==null&&o.invoiceRef&&o.invoiceDate){const profile=sellerProfileForOwner(st.settings,o.owner);need(!st.settings.sellerProfilesInitialized||profile?.active,'Skapa en aktiv säljarprofil för orderns ansvariga innan fakturan registreras.');o.invoiceOwner=o.owner;o.invoiceOwnerId=st.settings.sellerProfilesInitialized?profile!.id:'';o.invoiceOwnerSource='recorded';}
  o.directShipments=old!.directShipments;o.production=old!.production;o.productionHistory=old!.productionHistory;o.commercialVersion=old!.commercialVersion;o.commercialValue=old!.commercialValue;o.pendingAmendment=old!.pendingAmendment;o.revisions=old!.revisions;if(o.production.status!=='draft'&&o.production.status!=='cancelled'){if(['submitted','printed'].includes(o.production.status))need(o.stage==='production'&&o.supplierConfirmed,'En aktiv tryckorder ska ligga i produktion med bekräftad leverantör. Avbryt arbetsordern innan detta ändras.');need(o.proofRequired===old!.proofRequired&&o.proofApproved===old!.proofApproved&&o.proofFileId===old!.proofFileId&&o.proofVersion===old!.proofVersion&&o.approvedBy===old!.approvedBy&&o.approvedDate===old!.approvedDate,'Korrekturet är låst i tryckordern. Avbryt tryckordern innan underlaget ändras.');need(o.deliveryDate===old!.deliveryDate,'Leveransdatumet är låst i tryckordern. Avbryt och skicka om underlaget vid ändring.');if(['shipping','delivered','followed'].includes(o.stage))need(o.production.status==='dispatched','Lagret behöver först bekräfta utleveransen.');if(o.production.status==='dispatched')need(['shipping','delivered','followed'].includes(o.stage),'Utlevererad order kan inte flyttas tillbaka till produktion.');if(o.invoiceValue!==null)need(o.production.status==='dispatched','Registrera fakturan efter att hela ordern har skickats.');}const c=customer(o.customerId),d=st.deals.find(x=>x.id===o.dealId)!;
  const invoiceChanged=o.invoiceValue!==old!.invoiceValue||o.invoiceRef!==old!.invoiceRef||o.invoiceDate!==old!.invoiceDate;
  const advancesDelivery=['shipping','delivered','followed'].includes(o.stage)&&o.stage!==old!.stage;
  if(advancesDelivery||(o.invoiceValue!==null&&invoiceChanged))need(!o.pendingAmendment,'Godkänn eller återta orderändringen innan ordern går vidare.');
  if(o.directShipments.length&&deliveryVerified(st,o))need(['shipping','delivered','followed'].includes(o.stage),'En utlevererad order kan inte flyttas tillbaka före avsändning.');
  if(advancesDelivery||(o.invoiceValue!==null&&invoiceChanged))need(deliveryVerified(st,o),'Registrera leveransunderlag för hela ordern före avslut eller slutfakturering. Äldre leveranser utan underlag behöver kompletteras.');
  if(o.production.issue&&(advancesDelivery||(o.invoiceValue!==null&&invoiceChanged)))need(false,'Lös orderns produktionshinder före avslut eller fakturering.');
  if(o.deliveredDate&&o.deliveredDate!==old!.deliveredDate){need(['delivered','followed'].includes(o.stage)&&deliveryVerified(st,o),'Bekräfta mottagandet först efter verifierad avsändning i rätt leveranssteg.');need(o.deliveredDate<=today,'Leveransdatum får inte ligga i framtiden.');need(o.receivedBy,'Ange vem eller vilket underlag som bekräftar kundens mottagande.');need(!latestDispatch(o)||o.deliveredDate>=latestDispatch(o),'Mottagandet kan inte ligga före den senaste utleveransen.');}
  if(o.directShipments.length)need(o.proofRequired===old!.proofRequired&&o.proofApproved===old!.proofApproved&&o.proofFileId===old!.proofFileId&&o.proofVersion===old!.proofVersion&&o.approvedBy===old!.approvedBy&&o.approvedDate===old!.approvedDate,'Korrekturunderlaget är låst efter direktleverans.');
  if(o.proofRequired&&o.proofApproved&&(!old!.proofApproved||old!.proofFileId!==o.proofFileId||old!.proofVersion!==o.proofVersion||old!.approvedBy!==o.approvedBy||old!.approvedDate!==o.approvedDate)){need(o.proofFileId&&o.proofVersion&&o.approvedBy&&o.approvedDate,'Välj korrekturfil och ange version, vem som godkände och datum.');need(o.approvedDate<=today,'Godkännandedatum får inte ligga i framtiden.');}
  const n=DELIVERY.findIndex(x=>x.id===o.stage);if(n>=2)need(!o.pendingAmendment,'Godkänn eller återta orderändringen innan ordern går vidare.');if(n>=2){need(!o.proofRequired||o.proofApproved,'Kundens korrektur måste godkännas, eller markeras som ej tillämpligt.');need(o.supplierConfirmed,'Bekräfta leverantörens order och leveransdag.');need(o.deliveryDate,'Välj leveransdag.');}if(n>=5)need(o.deliveredDate,'Ange faktiskt leveransdatum.');if(o.invoiceValue!==null){need(!o.pendingAmendment,'Godkänn eller återta orderändringen före fakturering.');need(['shipping','delivered','followed'].includes(o.stage),'Registrera faktureringen efter att ordern skickats. Förskottsfakturering ingår inte i detta flöde.');need(o.invoiceDate,'Välj fakturadatum.');need(o.invoiceRef,'Ange fakturareferens.');}
  for(const t of st.tasks){if(t.dealId===d.id&&!t.done&&((t.kind==='proof_deadline'&&(!o.proofRequired||o.proofApproved))||(t.kind==='order_deadline'&&o.supplierConfirmed))){t.done=true;t.doneAt=now;}}
  if(o.invoiceValue!==null&&o.invoiceDate&&o.invoiceRef)for(const t of st.tasks)if(t.dealId===o.dealId&&t.kind==='invoice_ready'&&!t.done){t.done=true;t.doneAt=now;}
  if(o.deliveredDate&&['delivered','followed'].includes(o.stage)){need(o.deliveredDate<=today,'Leveransdatum får inte ligga i framtiden.');o.deliveryIssue='';o.deliveryNextCheck='';for(const t of st.tasks)if(t.dealId===o.dealId&&t.kind==='receipt'){t.done=true;t.doneAt=now;}}
  st.orders=st.orders.map(x=>x.id===o.id?o:x);ensureReceiptTasks(st);event(c.id,'Leverans uppdaterad · '+d.title+' · '+label(DELIVERY,o.stage),d.id);
  if(n>=5&&DELIVERY.findIndex(x=>x.id===old!.stage)<5)follow(c,d,'Följ upp leverans och nästa behov: '+d.title,plusDays(o.deliveredDate,st.settings.followupDays),'delivery',c.owner);
  if(o.stage==='followed'&&old!.stage!=='followed'){c.lastContact=today;c.nextReview=plusDays(today,c.reviewDays);st.tasks.forEach(t=>{if(t.dealId===d.id&&['delivery','handover'].includes(t.kind)){t.done=true;t.doneAt=now;}});}
 }else if(action.type==='task'){
  const t=TaskSchema.parse(action.data);customer(t.customerId);if(t.dealId)need(st.deals.some(d=>d.id===t.dealId&&d.customerId===t.customerId),'Affären hör inte till kunden.');const old=st.tasks.find(x=>x.id===t.id);protectTaskResponsibility(old,t,action.data,st.settings);if(old){const audited=[...st.deals,...st.orders].some(row=>row.responsibilityTransfers.some(history=>history.selectedTaskIds.includes(old.id)));if(audited)need(t.customerId===old.customerId&&t.dealId===old.dealId,'En uppgift med kommersiell ansvarshistorik får inte flyttas till en annan kund eller affär.');if(st.settings.sellerProfilesInitialized&&old.dealId&&['discovery','quote','proof_deadline','order_deadline','handover','receipt','invoice_ready'].includes(old.kind)){need(t.owner===old.owner,'Byt affärs- eller orderansvar i den granskade överföringen.');need(t.kind===old.kind&&t.customerId===old.customerId&&t.dealId===old.dealId,'Ett nödvändigt affärs- eller orderåtagande får inte kopplas om eller göras till en annan uppgift.');}}if(old&&old.customerId!==t.customerId)need(!st.customers.some(c=>c.responsibilityTransfers.some(row=>row.selectedTaskIds.includes(old.id))),'En uppgift med ansvarshistorik kan inte flyttas till en annan kund.');if(old&&protectedFollowUp(old)){need(!t.done||old.done,'Avsluta ärendet, inköpsbehovet eller onboarding i dess arbetsflöde.');need(t.kind===old.kind&&t.customerId===old.customerId&&t.dealId===old.dealId,'Aktivitetens koppling får inte ändras.');}if(old&&['quote','discovery'].includes(old.kind)){need(t.kind===old.kind&&t.customerId===old.customerId&&t.dealId===old.dealId&&t.owner===old.owner&&t.title===old.title&&t.due===old.due,'Ändra nästa aktivitet, datum och ansvarig i affären.');}if(old?.kind==='receipt'){need(t.kind===old.kind&&t.customerId===old.customerId&&t.dealId===old.dealId,'Leveransbevakningens koppling får inte ändras.');need(!t.done||st.orders.some(o=>o.dealId===old.dealId&&o.deliveredDate&&['delivered','followed'].includes(o.stage)),'Bekräfta kundens mottagande på ordern för att avsluta bevakningen.');}need(!t.id||old,'Uppgiften finns inte.');t.id=old?.id||uid();t.doneAt=t.done?(old?.doneAt||now):'';st.tasks=old?st.tasks.map(x=>x.id===t.id?t:x):[...st.tasks,t];event(t.customerId,(t.done?'Uppgift klar: ':'Uppgift sparad: ')+t.title,t.dealId);
 }else if(action.type==='meeting'){
  const m=MeetingSchema.parse(action.data);customer(m.customerId);const old=st.meetings.find(x=>x.id===m.id);need(!m.id||old,'Mötet finns inte.');protectMeetingResponsibility(old,m,action.data,st.settings);m.id=old?.id||uid();if(m.status==='done'){need(m.date<=today,'Ett genomfört möte kan inte ligga i framtiden.');if(old?.status!=='done'){const task=TaskSchema.parse({id:uid(),customerId:m.customerId,owner:m.owner,ownerProfileId:m.ownerProfileId,responsibilityTransfers:[],title:('Följ upp mötet: '+m.title).slice(0,240),due:today,kind:'meeting_followup'});st.tasks.push(task);exactNewMeetingOwners.set(task.id,m.ownerProfileId);}}st.meetings=old?st.meetings.map(x=>x.id===m.id?m:x):[...st.meetings,m];event(m.customerId,'Möte '+(m.status==='cancelled'?'avbokat':m.status==='done'?'genomfört':'planerat i CRM')+': '+m.title);
 }else if(action.type==='follow_up'){
  const p=FollowUpSchema.parse(action.data),t=st.tasks.find(t=>t.id===p.taskId);need(t&&canFollowUp(t),'Den här aktiviteten behöver hanteras i sitt ordinarie arbetsflöde.');need(p.expectedContext===followupBasis(st,p.taskId),'Aktiviteten har ändrats. Läs in aktuellt nästa steg.');
  const task=t!,previousTitle=t!.title,c=customer(task.customerId),canonical=['quote','discovery'].includes(task.kind),d=canonical?st.deals.find(d=>d.id===task.dealId):undefined;
  need(p.occurredOn<=today,'Kontakten kan inte ligga i framtiden.');if(canonical)need(st.tasks.filter(x=>x.dealId===task.dealId&&['quote','discovery'].includes(x.kind)&&!x.done).length===1,'Öppna och spara offerten för att uppdatera dess aktiviteter.');if(canonical)need(d&&d.customerId===c.id&&!['won','lost'].includes(d.stage)&&d.owner===task.owner,'Affären har ändrats. Öppna aktuellt underlag.');
  const protectedWork=protectedFollowUp(task),ongoing=['csm','prospecting'].includes(task.kind);
  need(!protectedWork||!p.completed,'Kontakten kan sparas här. Avsluta ärendet, inköpsbehovet eller onboarding i dess arbetsflöde.');
  if(canonical||ongoing||protectedWork||p.outcome==='no_reply'||!p.completed)need(p.nextAction,'Ange nästa aktivitet.');
  if(p.nextAction){TaskSchema.parse({...task,title:p.nextAction,due:p.nextDate});need(p.nextDate>=today,'Nästa aktivitet ska vara idag eller senare.');}
  const addFollowUp=(kind=task.kind)=>{const next=TaskSchema.parse({...task,id:uid(),kind,responsibilityTransfers:[],title:p.nextAction,due:p.nextDate,done:false,doneAt:''});st.tasks.push(next);if(!task.dealId&&['csm','csm_need','prospecting'].includes(task.kind))exactNewFollowUpOwners.set(next.id,{sourceTaskId:task.id,ownerProfileId:task.ownerProfileId});};
  if(protectedWork&&task.kind!=='csm_issue')addFollowUp('manual');
  else if(p.completed){task.done=true;task.doneAt=now;if(p.nextAction)addFollowUp();}else Object.assign(task,{title:p.nextAction,due:p.nextDate});
  if(d){d.nextAction=p.nextAction;d.nextDate=p.nextDate;}
  if(task.kind==='prospecting'){need(c.status==='prospect'&&!c.prospecting.convertedDealId,'Fortsätt uppföljningen i kundens affär.');c.prospecting.nextAction=p.nextAction;c.prospecting.nextDate=p.nextDate;}
  if(task.kind==='csm_issue'){need(c.plan.issueStatus==='open','Kundärendet är redan avslutat.');c.plan.issueAction=p.nextAction;c.plan.issueDue=p.nextDate;}
  if(task.kind==='csm'){c.plan.nextAction=p.nextAction;c.plan.nextDate=p.nextDate;c.nextReview=p.nextDate;if(p.completed&&p.outcome==='contact')c.plan.lastReview=[c.plan.lastReview,p.occurredOn].sort().at(-1)!;}
  if(p.outcome==='contact')c.lastContact=[c.lastContact,p.occurredOn].sort().at(-1)!;
  st.events.unshift({id:uid(),customerId:c.id,dealId:task.dealId,at:now,kind:'customer_note',text:({contact:'Kundkontakt',no_reply:'Kontaktförsök utan svar',internal:'Arbete med aktivitet'}[p.outcome])+' · '+p.occurredOn+'\n\n'+p.note+(p.nextAction?'\n\nNästa steg: '+p.nextAction+' · '+p.nextDate:''),note:{title:'Uppföljning: '+previousTitle,meetingDate:p.occurredOn,sourceFiles:[]}});
 }else if(action.type==='customer_note'){
  const n=CustomerNoteSchema.parse(action.data),c=customer(n.customerId);if(n.nextAction){owner(n.owner);need(n.nextDate,'Välj datum för nästa aktivitet.');st.tasks.push(TaskSchema.parse({id:uid(),customerId:c.id,owner:n.owner,title:n.nextAction,due:n.nextDate,kind:'meeting_followup'}));}if(n.contact){need(!n.meetingDate||n.meetingDate<=today,'Kundkontakten kan inte ligga i framtiden.');c.lastContact=[c.lastContact,n.meetingDate||today].sort().at(-1)!;}st.events.unshift({id:uid(),customerId:n.customerId,dealId:'',text:n.text,at:now,kind:'customer_note',note:{title:n.title||'Mötesanteckning',meetingDate:n.meetingDate,sourceFiles:n.sourceFiles}});
 }else if(action.type==='note'){
  const n=z.object({customerId:required,text:required,contact:z.boolean(),nextReview:date.default('')}).parse(action.data);const c=customer(n.customerId);event(c.id,n.text,'',n.contact?'contact':'note');if(n.contact)c.lastContact=today;
 }else if(action.type==='prospecting'){
  const p=z.object({customerId:required,prospecting:ProspectSchema}).parse(action.data),c=customer(p.customerId),v=p.prospecting;
  need(c.status==='prospect','Bearbetning gäller prospekt. Hantera befintliga kunder i CSM.');need(!c.prospecting.convertedDealId,'Bearbetningen har redan blivit en affär. Fortsätt i affären.');
  need(v.reason,'Beskriv varför företaget är relevant.');
  if(v.stage!=='not_relevant'){need(v.nextAction,'Ange nästa aktivitet.');need(v.nextDate,'Ange nästa kontaktdatum.');}
  if(['contact','qualified'].includes(v.stage))need(c.contact,'Lägg till en relevant kontaktperson på kundkortet.');
  if(v.stage==='qualified'){need(v.need,'Beskriv det bekräftade behovet.');need(v.scope,'Ange ungefärlig omfattning.');need(v.timing,'Ange när behovet ska vara löst.');}
  if(['paused','not_relevant'].includes(v.stage))need(v.outcomeReason,'Ange varför bearbetningen pausas eller avslutas.');
  const firstQualification=!c.prospecting.qualifiedAt&&v.stage==='qualified',profile=firstQualification?sellerProfileForOwner(st.settings,c.owner):undefined;
  need(!firstQualification||!st.settings.sellerProfilesInitialized||profile?.active,'Skapa en aktiv säljarprofil för kundens ansvariga innan behovet kvalificeras.');
  v.convertedDealId=c.prospecting.convertedDealId;v.qualifiedAt=c.prospecting.qualifiedAt||(firstQualification?now:'');v.qualifiedOwner=c.prospecting.qualifiedOwner||(firstQualification?c.owner:'');v.qualifiedOwnerId=c.prospecting.qualifiedOwnerId||(firstQualification&&st.settings.sellerProfilesInitialized?profile!.id:'');c.prospecting=v;
  if(v.stage==='not_relevant')closeTasks(c,'prospecting');else customerTask(c,v.nextAction,v.nextDate,'prospecting');
  event(c.id,'Nykundsbearbetning · '+label(PROSPECT_STAGES,v.stage));
 }else if(action.type==='qualify'){
  const p=z.object({customerId:required}).parse(action.data),c=customer(p.customerId),v=c.prospecting;
  need(c.status==='prospect'&&v.stage==='qualified','Bekräfta behov, omfattning och tidpunkt innan affären skapas.');need(!v.convertedDealId,'En affär har redan skapats från bearbetningen.');need(c.contact&&v.need&&v.scope&&v.timing&&v.nextAction&&v.nextDate,'Komplettera kontakt, behov, omfattning, tidpunkt och nästa aktivitet.');
  const d=DealSchema.parse({id:uid(),customerId:c.id,owner:c.owner,title:v.need.slice(0,200),stage:'contact',type:'new',need:v.need+' · '+v.scope,deliveryDate:v.timing,decisionMaker:c.decisionMaker,nextAction:v.nextAction,nextDate:v.nextDate,createdAt:now,stageAt:now});
  validateDeal(d,c);st.deals.push(d);v.convertedDealId=d.id;c.need=v.need;closeTasks(c,'prospecting');follow(c,d,d.nextAction,d.nextDate,'discovery');event(c.id,'Bekräftat behov blev nykundsaffär: '+d.title,d.id);
 }else if(action.type==='onboarding'){
  const p=z.object({customerId:required,onboarding:OnboardingSchema,complete:z.boolean().default(false)}).parse(action.data),c=customer(p.customerId),v=p.onboarding,old=c.onboarding;
  need(old.startedAt&&old.dealId,'Onboarding startar vid första bekräftade ordern.');need(!old.completedAt,'Onboarding är redan avslutad. Fortsätt i kundplanen.');protectOnboardingResponsibility(old,v,(action.data as {onboarding:unknown}).onboarding,st.settings);need(v.due,'Ange när onboarding ska vara klar.');
  v.dealId=old.dealId;v.startedAt=old.startedAt;v.completedAt=old.completedAt;
  const o=st.orders.find(o=>o.dealId===old.dealId&&o.customerId===c.id);
  if(v.checks.experience)need(o&&['delivered','followed'].includes(o.stage),'Registrera den första leveransen som levererad innan kundupplevelsen följs upp.');
  if(p.complete){need(ONBOARDING_CHECKS.every(x=>v.checks[x.id]),'Slutför alla fem kontrollpunkter.');need(v.feedback,'Dokumentera kundens återkoppling på första leveransen.');need(v.nextNeed,'Dokumentera nästa behov, även om det behöver undersökas.');need(c.nextReview&&c.nextReview>=today,'Planera en kommande kundavstämning i kundplanen.');need(c.plan.nextAction,'Ange nästa aktivitet i kundplanen.');v.completedAt=now;if(c.status==='onboarding')c.status='active';c.lastContact=today;c.plan.lastReview=today;c.plan.nextNeed=c.plan.nextNeed||v.nextNeed;if(o){o.stage='followed';st.tasks.forEach(t=>{if(t.dealId===o.dealId&&['delivery','handover'].includes(t.kind)&&!t.done){t.done=true;t.doneAt=now;}});}closeTasks(c,'onboarding');customerTask(c,c.plan.nextAction,c.nextReview,'csm');event(c.id,'Onboarding avslutad · kundplanen tar vid',v.dealId);}
  else{c.onboarding=v;onboardingTask(c,'Slutför onboarding: '+c.name,v.due);event(c.id,'Onboardingchecklista uppdaterad',v.dealId);}
  c.onboarding=v;
 }else if(action.type==='plan'){
  const p=z.object({customerId:required,plan:PlanSchema,nextReview:date,expectedOrder:date,reviewDays:z.number().int().min(7).max(730),reviewed:z.boolean().default(false)}).parse(action.data),c=customer(p.customerId),v=p.plan;
  need(c.status!=='prospect','Kundplanen används efter första ordern.');need(p.nextReview,'Planera nästa kundavstämning.');need(v.nextAction,'Ange nästa aktivitet för kundrelationen.');
  if(v.nextNeedDate)need(v.nextNeed,'Beskriv det kommande inköpsbehovet.');
  protectIssueResponsibility(c.plan,v,(action.data as {plan:unknown}).plan,st.settings);
  if(v.issueStatus==='open'){need(v.issue,'Beskriv kundärendet.');need(v.issueAction,'Ange åtgärden för kundärendet.');need(v.issueOwner,'Välj ansvarig för kundärendet.');need(v.issueDue,'Ange datum för åtgärden.');issueTask(c,v);}else st.tasks.forEach(t=>{if(t.customerId===c.id&&t.kind==='csm_issue'&&!t.dealId&&!t.done){t.done=true;t.doneAt=now;}});
  v.nextDate=p.nextReview;v.lastReview=p.reviewed?today:c.plan.lastReview;if(p.reviewed)closeTasks(c,'csm');c.plan=v;c.nextReview=p.nextReview;c.expectedOrder=p.expectedOrder;c.reviewDays=p.reviewDays;if(p.reviewed)c.lastContact=today;
  customerTask(c,v.nextAction,p.nextReview,'csm');if(v.nextNeedDate)customerTask(c,'Stäm av kommande behov: '+v.nextNeed,plusDays(v.nextNeedDate,-14),'csm_need');else closeTasks(c,'csm_need');
  event(c.id,p.reviewed?'Kundavstämning genomförd · kundplan uppdaterad':'Kundplan uppdaterad');
 }else if(action.type==='year_need'){
  const p=z.object({customerId:required,need:NeedSchema,expectedContext:z.string().min(1).max(3000000).optional()}).parse(action.data),c=customer(p.customerId),v=p.need,old=c.yearNeeds.find(n=>n.id===v.id);need(!v.id||old,'Behovet finns inte.');if(old&&p.expectedContext)need(p.expectedContext===yearNeedEditBasis(st,c.id,old.id),'Inköpsbehovet har ändrats. Läs in och granska aktuellt underlag innan du sparar.');need(old||c.yearNeeds.length<100,'Högst 100 behov per kund.');protectYearwheelResponsibility(old,v,(action.data as {need:unknown}).need,st.settings);v.id=old?.id||uid();v.completedAt=old?.completedAt||'';v.dealId=old?.dealId||'';c.yearNeeds=old?c.yearNeeds.map(n=>n.id===v.id?v:n):[...c.yearNeeds,v];if(v.status==='planned')yearwheelTask(c,v);else closeYearwheelTasks(c,v.id);event(c.id,'Årshjul uppdaterat: '+v.title+' · leveransbehov '+v.due);
 }else if(action.type==='complete_need'){
  const p=z.object({customerId:required,id:required}).parse(action.data),c=customer(p.customerId),v=c.yearNeeds.find(n=>n.id===p.id);need(v&&v.status==='planned','Behovet är redan hanterat.');closeYearwheelTasks(c,v!.id);v!.completedAt=now;event(c.id,'Inköpsbehov hanterat: '+v!.title+' · '+v!.due);if(v!.intervalMonths){v!.due=addMonths(v!.due,v!.intervalMonths);v!.dealId='';yearwheelTask(c,v!);}else v!.status='done';
 }else if(action.type==='need_deal'){
  const p=z.object({customerId:required,id:required}).parse(action.data),c=customer(p.customerId),v=c.yearNeeds.find(n=>n.id===p.id);need(v&&v.status==='planned','Välj ett planerat behov.');need(!v!.dealId,'En affär är redan kopplad till detta behov.');const needProfile=yearwheelResponsibleProfile(st,v!);need(!st.settings.sellerProfilesInitialized||needProfile?.active&&st.settings.owners.includes(v!.owner),'Byt behovsansvar till en aktiv, granskad säljarprofil innan en ny affär skapas.');const d=DealSchema.parse({id:uid(),customerId:c.id,owner:v!.owner,title:v!.title,type:c.status==='prospect'?'new':'expansion',category:v!.category,need:v!.notes||v!.title,deliveryDate:v!.due,nextAction:'Bekräfta omfattning och leverans med kunden',nextDate:today,createdAt:now,stageAt:now});st.deals.push(d);v!.dealId=d.id;d.ownerProfileId=v!.ownerProfileId;exactNewNeedDealOwners.set(d.id,v!.ownerProfileId);follow(c,d,d.nextAction,d.nextDate,'discovery');const discovery=st.tasks.find(task=>task.dealId===d.id&&task.kind==='discovery'&&!task.done)!;exactNewNeedDealTaskOwners.set(discovery.id,v!.ownerProfileId);event(c.id,'Affär skapad från årshjulet: '+d.title,d.id);
 }else if(action.type==='products'){
  const p=z.object({customerId:required,products:z.array(ProductSchema).max(100)}).parse(action.data),c=customer(p.customerId);c.products=p.products.map(v=>({...v,id:v.id||uid()}));need(new Set(c.products.map(p=>p.id)).size===c.products.length,'Produkterna behöver ha unika id:n.');event(c.id,'Kundens återkommande sortiment uppdaterat');
 }else if(action.type==='repeat_order'){
  const p=z.object({dealId:required}).parse(action.data),old=st.deals.find(d=>d.id===p.dealId);need(old&&old.stage==='won','Återbeställning utgår från en vunnen affär.');const c=customer(old!.customerId);const sourceOrder=st.orders.find(o=>o.dealId===old!.id);const recipe=sourceOrder&&['printed','dispatched'].includes(sourceOrder.production.status)?{sourceOrderId:sourceOrder.id,sourceWorkId:sourceOrder.production.workId,instructions:sourceOrder.production.instructions,sketchFileId:sourceOrder.production.sketchFileId,sketchVersion:sourceOrder.production.sketchVersion}:null;const d=DealSchema.parse({...old,ownerProfileId:'',responsibilityTransfers:[],owner:c.owner,repeatRecipe:recipe,id:uid(),title:('Återköp: '+old!.title.replace(/^Återköp: /,'' )).slice(0,200),stage:'identified',type:'repeat',sourceDealId:old!.id,confirmed:false,priceChecked:false,priceCheckedAt:'',quotes:[],quoteRef:'',decisionDate:'',deliveryDate:'',proofDeadline:'',orderDeadline:'',reason:'',wonAt:'',nextAction:'Kontrollera antal, aktuellt pris och leveranstid',nextDate:today,createdAt:now,stageAt:now});st.deals.push(d);follow(c,d,d.nextAction,d.nextDate,'discovery');event(c.id,'Återbeställning skapad från '+old!.title,d.id);
 }else if(action.type==='import_customers'){
  const p=z.object({customers:z.array(CustomerSchema).min(1).max(200)}).parse(action.data);for(const raw of p.customers){need(!raw.id,'Importen får bara skapa nya kunder.');need(!raw.responsibilityTransfers.length,'Kundimport får inte skapa ansvarshistorik.');need(!raw.ownerProfileId,'Kundimport får inte ange en egen ansvarsprofil. Välj en granskad ansvarig.');need(!raw.plan.issueOwnerProfileId&&!raw.plan.issueResponsibilityTransfers.length,'Kundimport får inte skapa ärendeprofil eller ansvarshistorik.');owner(raw.owner);const org=raw.organizationNumber.replace(/\D/g,'');need(!st.customers.some(c=>(raw.fortnoxNumber&&c.fortnoxNumber===raw.fortnoxNumber)||(org&&c.organizationNumber.replace(/\D/g,'')===org)||c.name.toLocaleLowerCase('sv')===raw.name.toLocaleLowerCase('sv')),'Dubblett i importen: '+raw.name);const c=CustomerSchema.parse({...raw,id:uid(),createdAt:now,prospecting:{},onboarding:{},plan:{},yearNeeds:[],products:[]});if(['active','growth','risk'].includes(c.status)){c.nextReview=raw.nextReview||plusDays(today,7);c.plan.nextAction='Stäm av kundens behov och planera nästa kontakt';c.plan.nextDate=c.nextReview;customerTask(c,c.plan.nextAction,c.nextReview,'csm');}st.customers.push(c);event(c.id,'Kund importerad');}
 }else if(action.type==='settings'){
  const settings=SettingsSchema.parse(action.data);protectSellerSettings(st.settings,settings,action.data);need(new Set(settings.catalogSources.map(s=>s.id)).size===settings.catalogSources.length,'Artikelkällorna måste ha unika id:n.');for(const source of st.settings.catalogSources){if(!settings.catalogSources.some(s=>s.id===source.id))need(!st.articles.some(a=>a.sourceId===source.id)&&!st.deals.some(d=>d.lines.some(l=>l.sourceId===source.id)),'Inaktivera en använd artikelkälla i stället för att ta bort den.');}need(new Set(settings.owners).size===settings.owners.length,'Säljarnamn måste vara unika.');for(const o of st.settings.owners){if(!settings.owners.includes(o))need(!([...st.customers,...st.deals,...st.tasks,...st.orders,...st.meetings].some(x=>x.owner===o)||st.companyEvents.some(e=>e.owner===o||e.checklist.some(t=>t.owner===o))||st.customers.some(c=>c.onboarding.owner===o||c.plan.issueOwner===o||c.yearNeeds.some(n=>n.owner===o&&n.status==='planned'))),'Omfördela poster innan du tar bort en ansvarig.');}st.settings=settings;validateSellerProfileReferences(st);
 }else if(operations.has(action.type)){need(actor,'Logga in för att utföra åtgärden.');return finish(assignNewResponsibleProfiles(current,applyOperations(st,action,actor!)));}else throw new RuleError('Okänd åtgärd.');return finish(assignNewResponsibleProfiles(current,st,exactNewMeetingOwners,exactNewOnboardingOwners,exactNewNeedDealOwners,exactNewNeedDealTaskOwners,exactNewFollowUpOwners));
}
