import { z } from 'zod';
import { LineSchema,AddressSchema,validDate,VariantFields } from './business';
const text=z.string().trim().max(4000),required=text.min(1,'Fyll i obligatoriska uppgifter.'),date=validDate;
export const RoleSchema=z.enum(['admin','seller','reader','print','warehouse','production']);
export type Role=z.infer<typeof RoleSchema>;
export const safeUrl=z.string().trim().max(2000).refine(v=>{if(!v)return true;try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password}catch{return false}},'Ange en fullständig http- eller https-adress.');
export const ArticleSchema=z.object({id:text.default(''),sourceId:required,sku:required.max(200),name:required.max(300),variant:text.default(''),...VariantFields,url:safeUrl.default(''),price:z.number().finite().min(0).max(1e9).nullable().default(null),cost:z.number().finite().min(0).max(1e9).nullable().default(null),updatedAt:text.default(''),active:z.boolean().default(true)});
export type Article=z.infer<typeof ArticleSchema>;
export const SourceSchema=z.object({id:required,name:required,url:safeUrl,active:z.boolean().default(true)});
export const MovementEntrySchema=z.object({lineId:required,quantity:z.number().finite().positive().max(1e6)});
export const MovementSchema=z.object({id:required,kind:z.enum(['received','printed','dispatched','scrap_unprinted','scrap_printed']),entries:z.array(MovementEntrySchema).min(1).max(100),at:required,by:required,reason:text.default(''),tracking:text.max(500).default(''),recipient:text.max(200).default(''),address:AddressSchema.nullable().default(null),legacy:z.boolean().default(false)});
export const QuantityAdjustmentSchema=z.object({id:required,entries:z.array(MovementEntrySchema).min(1).max(100),reason:required,customerApprovedBy:required,customerApprovedOn:date.refine(Boolean),recordedBy:required,recordedAt:required});
export const ProductionSchema=z.object({assigneeId:text.default(''),assigneeName:text.default(''),assignedAt:text.default(''),assignmentRevision:z.number().int().nonnegative().default(0),quantityAdjustments:z.array(QuantityAdjustmentSchema).max(100).default([]),issueOwnerId:text.default(''),issueOwnerName:text.default(''),workId:text.default(''),quantityMode:z.enum(['legacy','lines']).default('legacy'),movements:z.array(MovementSchema).max(1000).default([]),status:z.enum(['draft','submitted','printed','dispatched','cancelled']).default('draft'),lines:z.array(LineSchema).max(100).default([]),instructions:text.default(''),sketchFileId:text.default(''),sketchVersion:text.default(''),printDeadline:date.default(''),dispatchDeadline:date.default(''),deliveryDate:date.default(''),deliveryAddress:AddressSchema.default({}),submittedAt:text.default(''),submittedBy:text.default(''),printedAt:text.default(''),printedBy:text.default(''),dispatchedAt:text.default(''),dispatchedBy:text.default(''),tracking:text.default(''),issue:text.default(''),issueAt:text.default(''),goodsReceived:z.boolean().default(false),goodsReceivedAt:text.default(''),goodsReceivedBy:text.default(''),acceptedAt:text.default(''),acceptedBy:text.default(''),cancellationReason:text.default('')});
export const NoticeSchema=z.object({id:required,customerId:text.default(''),orderId:text.default(''),title:required,body:text.default(''),audience:z.enum(['print','warehouse','seller','team']),owner:text.default(''),at:required,readBy:z.array(text).default([])});
export type Notice=z.infer<typeof NoticeSchema>;
export const LeadContactSchema=z.object({name:required,role:text.default(''),email:z.union([z.literal(''),z.string().email()]).default(''),phone:text.default(''),linkedin:safeUrl.default('')});
export const LeadSchema=z.object({id:text.default(''),name:required.max(200),organizationNumber:text.default(''),industry:text.default(''),employees:z.number().int().min(0).max(1e7).nullable().default(null),city:text.default(''),address:text.default(''),latitude:z.number().min(-90).max(90).nullable().default(null),longitude:z.number().min(-180).max(180).nullable().default(null),website:safeUrl.default(''),contacts:z.array(LeadContactSchema).max(30).default([]),source:required,sourceUrl:safeUrl.default(''),checkedAt:date.default(''),customerId:text.default('')});
export type Lead=z.infer<typeof LeadSchema>;
export const CompanyEventSchema=z.object({id:text.default(''),title:required.max(200),date:date.refine(Boolean,'Välj datum.'),endDate:date.default(''),owner:required,category:z.enum(['event','campaign','internal','holiday']).default('event'),notes:text.default(''),status:z.enum(['planned','done','cancelled']).default('planned'),checklist:z.array(z.object({id:required,title:required,owner:required,due:date.refine(Boolean),done:z.boolean().default(false)})).max(50).default([])});
export type CompanyEvent=z.infer<typeof CompanyEventSchema>;
export function distanceKm(a:number,b:number,c:number,d:number){const r=Math.PI/180,x=Math.sin((c-a)*r/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin((d-b)*r/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(Math.max(0,1-x)))}
export const operations=new Set(['production_claim','production_release','prepare_order','receipt_confirm','receipt_issue','article','article_import','catalog_order','production_submit','production_accept','production_received','production_printed','production_dispatched','production_scrap_unprinted','production_scrap_printed','production_issue','production_cancel','order_shortfall','order_amend','order_amend_accept','order_amend_discard','notice_read','lead_import','lead_convert','company_event']);
export const roleActions:Record<Role,Set<string>|null>={admin:null,seller:new Set(['prepare_order','receipt_confirm','receipt_issue','customer','deal','order','task','meeting','note','customer_note','follow_up','prospecting','qualify','onboarding','plan','year_need','complete_need','need_deal','products','repeat_order','catalog_order','production_submit','production_issue','production_cancel','order_shortfall','order_amend','order_amend_accept','order_amend_discard','notice_read','lead_convert','company_event']),reader:new Set(),production:new Set(['production_claim','production_release','production_accept','production_received','production_printed','production_dispatched','production_scrap_unprinted','production_scrap_printed','production_issue','notice_read']),print:new Set(['production_claim','production_release','production_accept','production_printed','production_scrap_printed','production_issue','notice_read']),warehouse:new Set(['production_claim','production_release','production_received','production_dispatched','production_scrap_unprinted','production_issue','notice_read'])};

export const isDepartmentRole=(role:string|undefined)=>['print','warehouse','production'].includes(role||'');
export const receivesNotice=(role:Role,audience:string,owner:string,noticeOwner:string)=>role==='admin'||audience==='team'||(role==='production'&&['print','warehouse'].includes(audience))||(role===audience&&(role!=='seller'||owner===noticeOwner));
