import {env} from 'cloudflare:workers';
import {CustomerSchema,type Customer,type Deal} from './crm';
import {OUTLOOK_SCOPES,OUTLOOK_REDIRECT,type OutlookItem} from './outlook-shared';
export class OutlookError extends Error{constructor(message:string,public status=400){super(message)}}
type Config={MS_TENANT_ID?:string;MS_CLIENT_ID?:string;MS_CLIENT_SECRET?:string;OUTLOOK_TOKEN_KEY?:string};
type Tokens={access_token:string;refresh_token:string;expires_at:number};
type Connection={user_id:string;microsoft_id:string;email:string;tokens:string;last_sync:string;status:string;sync_note:string;lock_until:number;revision:number};
type ItemRow={id:string;user_id:string;kind:'mail'|'meeting';data:string;customer_id:string;deal_id:string;shared:number;happened_at:string;seen_at:string};
export const db=()=>{if(!env.DB)throw new OutlookError('Databasen är inte tillgänglig.',503);return env.DB};
const cfg=()=>env as unknown as Config;
export function configuration(){const c=cfg();return ['MS_TENANT_ID','MS_CLIENT_ID','MS_CLIENT_SECRET','OUTLOOK_TOKEN_KEY'].filter(k=>!c[k as keyof Config])}
function config(){const c=cfg();if(configuration().length)throw new OutlookError('Outlook behöver aktiveras för företaget innan ett konto kan anslutas.',503);if(!/^[0-9a-f-]{36}$/i.test(c.MS_TENANT_ID!)||!/^[0-9a-f-]{36}$/i.test(c.MS_CLIENT_ID!))throw new OutlookError('Microsoft-konfigurationen behöver kontrolleras.',503);return c as Required<Config>}
export function identity(req:Request){const id=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');if(!id||!email)throw new OutlookError('Logga in för att hantera ditt Outlook-konto.',401);return{id,email}}
export function sameOrigin(req:Request){if(req.headers.get('origin')!==new URL(OUTLOOK_REDIRECT).origin)throw new OutlookError('Begäran måste göras från CRM:et.',403)}
const b64=(v:Uint8Array)=>btoa(String.fromCharCode(...v)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
const un64=(v:string)=>Uint8Array.from(atob(v.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
export const random=()=>b64(crypto.getRandomValues(new Uint8Array(32)));
export const hash=async(v:string)=>b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))));
async function key(){let bytes:ReturnType<typeof un64>;try{bytes=un64(config().OUTLOOK_TOKEN_KEY)}catch{throw new OutlookError('Krypteringsnyckeln behöver kontrolleras.',503)}if(bytes.length!==32)throw new OutlookError('Krypteringsnyckeln behöver kontrolleras.',503);return crypto.subtle.importKey('raw',bytes,{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function seal(data:unknown,user:string){const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(user)},await key(),new TextEncoder().encode(JSON.stringify(data)));return b64(iv)+'.'+b64(new Uint8Array(encrypted))}
export async function unseal<T>(value:string,user:string):Promise<T>{const [iv,body]=value.split('.');return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(iv),additionalData:new TextEncoder().encode(user)},await key(),un64(body))))}
const now=()=>Math.floor(Date.now()/1000);
async function tokenRequest(params:URLSearchParams):Promise<Tokens>{const c=config();params.set('client_id',c.MS_CLIENT_ID);params.set('client_secret',c.MS_CLIENT_SECRET);params.set('scope',OUTLOOK_SCOPES.join(' '));const r=await fetch(`https://login.microsoftonline.com/${c.MS_TENANT_ID}/oauth2/v2.0/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params,signal:AbortSignal.timeout(20000)});const t=await r.json() as any;if(!r.ok)throw new OutlookError(r.status===429?'Microsoft begränsar anropen. Försök senare.':'Microsoft kunde inte förnya anslutningen. Anslut kontot igen.',r.status===429?429:401);if(!t.access_token)throw new OutlookError('Microsoft lämnade inget åtkomstbevis.',502);return {access_token:t.access_token,refresh_token:t.refresh_token||params.get('refresh_token')||'',expires_at:now()+Number(t.expires_in||3600)}}
export async function startConsent(user:string){const c=config(),state=random(),verifier=random();await key();await db().batch([db().prepare('DELETE FROM outlook_oauth_states WHERE expires < ?').bind(now()),db().prepare('INSERT INTO outlook_oauth_states(hash,user_id,verifier,expires) VALUES(?,?,?,?)').bind(await hash(state),user,await seal(verifier,user),now()+600)]);const url=new URL(`https://login.microsoftonline.com/${c.MS_TENANT_ID}/oauth2/v2.0/authorize`);Object.entries({client_id:c.MS_CLIENT_ID,response_type:'code',response_mode:'query',redirect_uri:OUTLOOK_REDIRECT,scope:OUTLOOK_SCOPES.join(' '),state,code_challenge:await hash(verifier),code_challenge_method:'S256',prompt:'select_account'}).forEach(([k,v])=>url.searchParams.set(k,v));return{url:url.toString(),state}}
export async function graph(url:string,access:string){const u=new URL(url);if(u.origin!=='https://graph.microsoft.com'||!u.pathname.startsWith('/v1.0/')||u.username||u.password)throw new OutlookError('Ogiltigt svar från synktjänsten.',502);const r=await fetch(u,{headers:{Authorization:'Bearer '+access,Prefer:'outlook.body-content-type="text", IdType="ImmutableId", outlook.timezone="UTC"'},signal:AbortSignal.timeout(20000)});if(!r.ok){if(r.status===429)throw new OutlookError('Microsoft begränsar synkningen. Försök igen senare.',429);if([401,403].includes(r.status))throw new OutlookError('Outlook-åtkomsten behöver godkännas igen.',401);throw new OutlookError('Outlook gick inte att läsa just nu. Försök igen senare.',502)}return r.json() as Promise<any>}
export async function finishConsent(req:Request){const user=identity(req),u=new URL(req.url),state=u.searchParams.get('state'),code=u.searchParams.get('code');const cookie=req.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('__Host-outlook-state='))?.slice('__Host-outlook-state='.length);if(!state||state!==cookie)throw new OutlookError('Anslutningen kunde inte verifieras. Börja om från CRM:et.',403);const row=await db().prepare('DELETE FROM outlook_oauth_states WHERE hash=? AND user_id=? AND expires>=? RETURNING verifier').bind(await hash(state),user.id,now()).first<{verifier:string}>();if(!row)throw new OutlookError('Anslutningsförsöket har löpt ut. Börja om.',403);if(u.searchParams.has('error')||!code)throw new OutlookError('Microsoft-anslutningen avbröts eller saknar godkännande.');const verifier=await unseal<string>(row.verifier,user.id);const tokens=await tokenRequest(new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:OUTLOOK_REDIRECT,code_verifier:verifier}));if(!tokens.refresh_token)throw new OutlookError('Microsoft behöver godkänna fortsatt åtkomst.',400);const me=await graph('https://graph.microsoft.com/v1.0/me?$select=id,mail,userPrincipalName',tokens.access_token);if(!me.id)throw new OutlookError('Microsoft-kontot kunde inte identifieras.',502);const existing=await connection(user.id);if(existing&&existing.microsoft_id!==me.id)throw new OutlookError('Koppla från ditt tidigare Outlook-konto innan du byter konto.');if(existing&&existing.lock_until>now())throw new OutlookError('En synkning pågår. Vänta en stund innan du ansluter igen.',409);const other=await db().prepare('SELECT user_id FROM outlook_connections WHERE microsoft_id=? AND user_id<>?').bind(me.id,user.id).first();if(other)throw new OutlookError('Det Outlook-kontot är redan kopplat till en annan CRM-användare.',409);await db().prepare('INSERT INTO outlook_connections(user_id,microsoft_id,email,tokens) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET tokens=excluded.tokens,email=excluded.email,status=\'connected\',revision=outlook_connections.revision+1').bind(user.id,me.id,me.mail||me.userPrincipalName||'',await seal(tokens,user.id)).run()}
export async function connection(user:string){return db().prepare('SELECT * FROM outlook_connections WHERE user_id=?').bind(user).first<Connection>()}
export async function customers(){const rows=await db().prepare("SELECT data FROM crm_customers WHERE space='live'").all<{data:string}>();return rows.results.map(r=>CustomerSchema.parse(JSON.parse(r.data)))}
const email=(v:any)=>String(v?.emailAddress?.address||'').trim().toLowerCase();
export function matches(addresses:string[],cs:Customer[]){const set=new Set(addresses.map(s=>s.toLowerCase()));return cs.filter(c=>[c.email,...c.plan.contacts.map(p=>p.email)].some(e=>e&&set.has(e.trim().toLowerCase()))).map(c=>c.id)}
function utc(v:string){return /Z$|[+-]\d\d:\d\d$/.test(v)?v:v+'Z'}
export function fromGraph(raw:any,kind:'mail'|'meeting',cs:Customer[],mailbox:string):Omit<OutlookItem,'id'|'customerId'|'dealId'|'shared'|'mine'>|null{
 if(raw.sensitivity&&raw.sensitivity!=='normal')return null;
 const sender=email(kind==='mail'?raw.from:raw.organizer),recipients=(kind==='mail'?[...(raw.toRecipients||[]),...(raw.ccRecipients||[])]:raw.attendees||[]).map(email),candidateIds=matches([sender,...recipients].filter(e=>e&&e!==mailbox.toLowerCase()),cs);if(!candidateIds.length||!raw.id||raw.isDraft)return null;
 const at=kind==='mail'?(raw.receivedDateTime||raw.sentDateTime):raw.start?.dateTime;if(!at||Number.isNaN(Date.parse(utc(at))))return null;
 const body=raw.body?.contentType?.toLowerCase()==='text'?String(raw.body.content).slice(0,32000):String(raw.bodyPreview||'').slice(0,4000);
 let webLink='';try{const u=new URL(raw.webLink);if(u.protocol==='https:'&&['outlook.office.com','outlook.office365.com','outlook.live.com'].includes(u.hostname))webLink=u.toString()}catch{}
 return{kind,subject:String(raw.subject||'(Utan ämne)').slice(0,500),body,at:utc(at),end:raw.end?.dateTime?utc(raw.end.dateTime):'',sender,recipients,location:String(raw.location?.displayName||'').slice(0,500),webLink,conversationId:String(raw.conversationId||raw.iCalUId||''),cancelled:!!raw.isCancelled,removed:false,allDay:!!raw.isAllDay,candidateIds,mailbox,direction:kind==='meeting'?'meeting':sender===mailbox.toLowerCase()?'out':'in'};
}
export async function readState(req:Request){const u=identity(req),c=await connection(u.id),rows=await db().prepare('SELECT * FROM outlook_items WHERE user_id=? OR shared=1 ORDER BY happened_at DESC LIMIT 501').bind(u.id).all<ItemRow>();return{configured:configuration().length===0,missing:configuration(),signedIn:true,email:u.email,connection:c?{email:c.email,lastSync:c.last_sync,status:c.status,syncNote:c.sync_note}:null,items:rows.results.slice(0,500).map(r=>({...JSON.parse(r.data),id:r.id,customerId:r.customer_id,dealId:r.deal_id,shared:r.shared===1,mine:r.user_id===u.id})),limited:rows.results.length>500}}
export async function sync(user:string){config();let c=await connection(user);if(!c)throw new OutlookError('Anslut ditt Outlook-konto först.');const lock=await db().prepare('UPDATE outlook_connections SET lock_until=?,revision=revision+1 WHERE user_id=? AND lock_until<? RETURNING *').bind(now()+180,user,now()).first<Connection>();if(!lock)throw new OutlookError('En synkning pågår redan.',409);try{c=lock;let tokens=await unseal<Tokens>(c.tokens,user);if(tokens.expires_at<now()+120){tokens=await tokenRequest(new URLSearchParams({grant_type:'refresh_token',refresh_token:tokens.refresh_token}));await db().prepare('UPDATE outlook_connections SET tokens=? WHERE user_id=? AND revision=?').bind(await seal(tokens,user),user,lock.revision).run()}
 const existingRows=await db().prepare('SELECT id,customer_id,deal_id,shared FROM outlook_items WHERE user_id=?').bind(user).all<{id:string;customer_id:string;deal_id:string;shared:number}>();const existingItems=new Map(existingRows.results.map(r=>[r.id,r]));const cs=await customers(),start=new Date(Date.now()-30*86400000).toISOString(),end=new Date(Date.now()+90*86400000).toISOString(),seen=new Date().toISOString();let truncated=false,count=0;const eventIds=new Set<string>();
 const mailFields='id,subject,body,bodyPreview,from,toRecipients,ccRecipients,receivedDateTime,sentDateTime,webLink,conversationId,sensitivity,isDraft';
 const queries:[string,'mail'|'meeting'][]=[...['inbox','sentitems'].map(f=>['https://graph.microsoft.com/v1.0/me/mailFolders/'+f+'/messages?'+new URLSearchParams({'$select':mailFields,'$filter':(f==='sentitems'?'sentDateTime':'receivedDateTime')+' ge '+start,'$top':'50'}),'mail'] as [string,'mail']),['https://graph.microsoft.com/v1.0/me/calendarView?'+new URLSearchParams({startDateTime:start,endDateTime:end,'$top':'50','$select':'id,subject,body,bodyPreview,organizer,attendees,start,end,location,isCancelled,isAllDay,sensitivity,webLink,iCalUId'}),'meeting']];
 for(const [initial,kind] of queries){let url:string|undefined=initial,pages=0;while(url&&pages<10){const lease=await db().prepare('UPDATE outlook_connections SET lock_until=? WHERE user_id=? AND revision=? AND lock_until>? RETURNING user_id').bind(now()+180,user,lock.revision,now()).first();if(!lease)throw new OutlookError('Synkningen avbröts eftersom anslutningen ändrades.',409);const page=await graph(url,tokens.access_token);pages++;const statements=[];for(const raw of page.value||[]){const id=await hash(user+'|'+kind+'|'+raw.id);if(kind==='meeting')eventIds.add(id);const item=fromGraph(raw,kind,cs,c.email);if(!item){statements.push(db().prepare('DELETE FROM outlook_items WHERE id=? AND user_id=? AND EXISTS(SELECT 1 FROM outlook_connections WHERE user_id=? AND revision=?)').bind(id,user,user,lock.revision));continue;}const old=existingItems.get(id);const keep=old&&item.candidateIds.includes(old.customer_id);const customerId=keep?old.customer_id:item.candidateIds.length===1?item.candidateIds[0]:'';statements.push(db().prepare('INSERT INTO outlook_items(id,user_id,kind,data,customer_id,deal_id,shared,happened_at,seen_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM outlook_connections WHERE user_id=? AND revision=?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,customer_id=CASE WHEN outlook_items.customer_id=\'\' THEN excluded.customer_id ELSE outlook_items.customer_id END,deal_id=outlook_items.deal_id,shared=outlook_items.shared,happened_at=excluded.happened_at,seen_at=excluded.seen_at').bind(id,user,kind,JSON.stringify(item),customerId,keep?old.deal_id:'',keep?old.shared:0,item.at,seen,user,lock.revision));count++;}if(statements.length)await db().batch(statements);url=page['@odata.nextLink'];}if(url)truncated=true;
 if(kind==='meeting'&&!url){const old=await db().prepare("SELECT id,data FROM outlook_items WHERE user_id=? AND kind='meeting' AND happened_at>=? AND happened_at<=?").bind(user,start,end).all<{id:string;data:string}>();const updates=old.results.filter(r=>!eventIds.has(r.id)).map(r=>db().prepare('UPDATE outlook_items SET data=? WHERE id=? AND user_id=? AND EXISTS(SELECT 1 FROM outlook_connections WHERE user_id=? AND revision=?)').bind(JSON.stringify({...JSON.parse(r.data),removed:true}),r.id,user,user,lock.revision));if(updates.length)await db().batch(updates);}}
 await db().prepare("UPDATE outlook_connections SET last_sync=?,status='connected',sync_note=? WHERE user_id=? AND revision=?").bind(seen,truncated?'Delvis synkat: fler än 500 poster i en källa. Kontakta ansvarig för utökad historik.':count+' kundhändelser lästa. Inkorg och skickat: 30 dagar. Kalender: −30 till +90 dagar.',user,lock.revision).run();
 }catch(e){await db().prepare('UPDATE outlook_connections SET status=?,sync_note=? WHERE user_id=? AND revision=?').bind(e instanceof OutlookError&&e.status===401?'reconnect':'error',e instanceof OutlookError?e.message:'Synkningen avbröts. Försök igen senare.',user,lock.revision).run();throw e}finally{await db().prepare('UPDATE outlook_connections SET lock_until=0 WHERE user_id=? AND revision=?').bind(user,lock.revision).run()}}
export async function publishItem(user:string,id:string,customerId:string,dealId:string,share:boolean){const row=await db().prepare('SELECT * FROM outlook_items WHERE id=? AND user_id=?').bind(id,user).first<ItemRow>();if(!row)throw new OutlookError('Händelsen finns inte i ditt Outlook-konto.',404);const cs=await customers();if(!cs.some(c=>c.id===customerId))throw new OutlookError('Välj en kund i den egna arbetsytan.');if(dealId){const d=await db().prepare("SELECT data FROM crm_deals WHERE space='live' AND id=?").bind(dealId).first<{data:string}>();if(!d||(JSON.parse(d.data) as Deal).customerId!==customerId)throw new OutlookError('Affären tillhör inte vald kund.');}await db().prepare('UPDATE outlook_items SET customer_id=?,deal_id=?,shared=? WHERE id=? AND user_id=?').bind(customerId,dealId,share?1:0,id,user).run()}
export async function disconnect(user:string){const r=await db().batch([db().prepare('DELETE FROM outlook_connections WHERE user_id=? AND lock_until<=?').bind(user,now()),db().prepare('DELETE FROM outlook_oauth_states WHERE user_id=? AND NOT EXISTS(SELECT 1 FROM outlook_connections WHERE user_id=?)').bind(user,user),db().prepare('DELETE FROM outlook_items WHERE user_id=? AND shared=0 AND NOT EXISTS(SELECT 1 FROM outlook_connections WHERE user_id=?)').bind(user,user)]);if(await connection(user))throw new OutlookError('Vänta tills pågående synkning är klar.',409);}
