import { sqliteTable, text, integer, primaryKey, foreignKey, index } from 'drizzle-orm/sqlite-core';
export const spaces = sqliteTable('crm_spaces', { id: text('id').primaryKey(), version: integer('version').notNull().default(0), writeToken: text('write_token').notNull().default(''), settings: text('settings').notNull() });
export const customers = sqliteTable('crm_customers', { id: text('id').notNull(), space: text('space').notNull().references(()=>spaces.id), data: text('data').notNull() }, t=>[primaryKey({columns:[t.space,t.id]})]);
export const deals = sqliteTable('crm_deals', { id: text('id').notNull(), space: text('space').notNull(), customerId: text('customer_id').notNull(), data: text('data').notNull() },t=>[primaryKey({columns:[t.space,t.id]}), foreignKey({columns:[t.space,t.customerId],foreignColumns:[customers.space,customers.id]}),index('idx_deals_customer').on(t.space,t.customerId)]);
export const orders = sqliteTable('crm_orders', { id:text('id').notNull(),space:text('space').notNull(),customerId:text('customer_id').notNull(),dealId:text('deal_id').notNull(),data:text('data').notNull() },t=>[primaryKey({columns:[t.space,t.id]}),foreignKey({columns:[t.space,t.dealId],foreignColumns:[deals.space,deals.id]}),index('idx_orders_customer').on(t.space,t.customerId)]);
export const tasks = sqliteTable('crm_tasks',{id:text('id').notNull(),space:text('space').notNull(),customerId:text('customer_id').notNull(),data:text('data').notNull()},t=>[primaryKey({columns:[t.space,t.id]}),foreignKey({columns:[t.space,t.customerId],foreignColumns:[customers.space,customers.id]})]);
export const meetings = sqliteTable('crm_meetings',{id:text('id').notNull(),space:text('space').notNull(),customerId:text('customer_id').notNull(),data:text('data').notNull()},t=>[primaryKey({columns:[t.space,t.id]}),foreignKey({columns:[t.space,t.customerId],foreignColumns:[customers.space,customers.id]})]);
export const events = sqliteTable('crm_events',{id:text('id').notNull(),space:text('space').notNull(),customerId:text('customer_id').notNull(),data:text('data').notNull()},t=>[primaryKey({columns:[t.space,t.id]}),foreignKey({columns:[t.space,t.customerId],foreignColumns:[customers.space,customers.id]})]);
export const mutations = sqliteTable('crm_mutations',{space:text('space').notNull().references(()=>spaces.id),id:text('id').notNull(),resultJson:text('result_json'),userId:text('user_id').notNull().default(''),requestHash:text('request_hash').notNull().default('')},t=>[primaryKey({columns:[t.space,t.id]})]);

export const members = sqliteTable('crm_members', {id:text('id').primaryKey(),email:text('email').notNull().unique(),userId:text('user_id').unique(),name:text('name').notNull(),role:text('role').notNull(),owner:text('owner').notNull().default(''),active:integer('active').notNull().default(1)});
export const files = sqliteTable('crm_files', {id:text('id').primaryKey(),space:text('space').notNull(),customerId:text('customer_id').notNull(),objectKey:text('object_key').notNull().unique(),data:text('data').notNull()},t=>[foreignKey({columns:[t.space,t.customerId],foreignColumns:[customers.space,customers.id]}),index('idx_files_customer').on(t.space,t.customerId)]);

// Outlook consent is bound to the authenticated Site user, separate from CRM ownership labels.
export const outlookConnections = sqliteTable('outlook_connections', {
 userId:text('user_id').primaryKey(), microsoftId:text('microsoft_id').notNull().unique(), email:text('email').notNull(), tokens:text('tokens').notNull(), lastSync:text('last_sync').notNull().default(''), status:text('status').notNull().default('connected'), syncNote:text('sync_note').notNull().default(''), lockUntil:integer('lock_until').notNull().default(0), revision:integer('revision').notNull().default(0)
});
export const outlookStates = sqliteTable('outlook_oauth_states',{hash:text('hash').primaryKey(),userId:text('user_id').notNull(),verifier:text('verifier').notNull(),expires:integer('expires').notNull()});
export const outlookItems = sqliteTable('outlook_items',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),data:text('data').notNull(),customerId:text('customer_id').notNull().default(''),dealId:text('deal_id').notNull().default(''),shared:integer('shared').notNull().default(0),happenedAt:text('happened_at').notNull(),seenAt:text('seen_at').notNull()},t=>[index('idx_outlook_user').on(t.userId,t.happenedAt),index('idx_outlook_shared_customer').on(t.shared,t.customerId,t.happenedAt)]);

export const articles = sqliteTable('crm_articles',{id:text('id').notNull(),space:text('space').notNull().references(()=>spaces.id),data:text('data').notNull()},t=>[primaryKey({columns:[t.space,t.id]})]);
export const notices = sqliteTable('crm_notices',{id:text('id').notNull(),space:text('space').notNull().references(()=>spaces.id),data:text('data').notNull()},t=>[primaryKey({columns:[t.space,t.id]})]);
export const leads = sqliteTable('crm_leads',{id:text('id').notNull(),space:text('space').notNull().references(()=>spaces.id),data:text('data').notNull()},t=>[primaryKey({columns:[t.space,t.id]})]);
export const companyEvents = sqliteTable('crm_company_events',{id:text('id').notNull(),space:text('space').notNull().references(()=>spaces.id),data:text('data').notNull()},t=>[primaryKey({columns:[t.space,t.id]})]);

// Private, independently versioned work-in-progress; never part of team exports.
export const drafts = sqliteTable('crm_drafts',{space:text('space').notNull(),userId:text('user_id').notNull(),id:text('id').notNull(),kind:text('kind').notNull(),context:text('context').notNull().default(''),revision:integer('revision').notNull().default(0),requestId:text('request_id').notNull(),title:text('title').notNull(),data:text('data').notNull(),archived:integer('archived').notNull().default(0),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.space,t.userId,t.id]})]);
